src/chrome/content/rules/MaybankHeart.com.xml
=> [MaybankHeart.com] New ruleset

src/chrome/content/rules/Maybank2u.com.kh.xml
=> [Maybank2u.com.kh] New ruleset

src/chrome/content/rules/Kijijiblog.ca.xml
https://github.com/EFForg/https-everywhere/pull/14249
=> [Kijijiblog.ca] New ruleset

src/chrome/content/rules/automobile.fr.xml
https://github.com/EFForg/https-everywhere/pull/14243
=> [automobile.fr] New ruleset

src/chrome/content/rules/Marktplaatsjournaal.nl.xml
https://github.com/EFForg/https-everywhere/pull/14242
=> [Marktplaatsjournaal.nl] New ruleset

src/chrome/content/rules/Marktplaatsautojournaal.nl.xml
https://github.com/EFForg/https-everywhere/pull/14242
=> [Marktplaatsautojournaal.nl] New ruleset

src/chrome/content/rules/Stubhub.fr.xml
=> [Stubhub.fr] New ruleset

src/chrome/content/rules/Stubhub.ca.xml
=> [Stubhub.ca] New ruleset

src/chrome/content/rules/Zhaw.ch.xml
Create a ruleset for _Zurich University of Applied Sciences (ZHAW)_.
There are a few non-functional subdomains. Should I add a wildcard for all the subdomains with some exceptions instead of adding all those targets?
=> [Zhaw.ch] New ruleset for Zurich University of Applied Sciences

src/chrome/content/rules/tutti.ch.xml
This should fix the issue described in #13953.
=> Fix #13953

src/chrome/content/rules/FacebookCoreWWWi.onion.xml
=> [FacebookCoreWWWI.onion] Add test urls

src/chrome/content/rules/TheHouseOrgan.xyz.xml
=> TheHouseOrgan.xyz rule

src/chrome/content/rules/SoFun.tw.xml
Initial creation of a ruleset for SoFun.tw
=> Ruleset for SoFun.tw

make.sh, utils/merge-rulesets.sh
=>  Remove utils/merge-rulesets.sh 

utils/relaxng.xml
=> Forbid the creation of fallback rules

src/chrome/content/rules/Stubhub.mx.xml
=> [Stubhub.mx] New ruleset

src/chrome/content/rules/Stubhub.pt.xml
=> [Stubhub.pt] New ruleset

src/chrome/content/rules/RISI.xml, src/chrome/content/rules/Tutanota.de.xml, src/chrome/content/rules/YouTube.xml
Follow up of #14396 and #14473.
=> Clean up after hsts-prune

src/chrome/content/rules/hardware.fr.xml
=> [Hardware.fr] Add targets

src/chrome/content/rules/Aeinstein.org.xml
=> Add Aeinstein.org.xml

src/chrome/content/rules/Stack-Exchange.xml
=> [Stack-Exchange] Exclude problematic path

test/rules/src/https_everywhere_checker/rules.py
Make Travis to assert that each test url is covered by at least one target
=> Update https_everywhere_checker/rules.py, Fix #14290

src/chrome/content/rules/University-of-Waterloo.xml
some broken subdomains have been fixed
=> Update University-of-Waterloo.xml again

src/chrome/content/rules/Instructables.com.xml
=> [Instructables.com] Fix redirect loop and CORS issues

src/chrome/content/rules/CVS.com.xml
This pull request replaces pull request https://github.com/EFForg/https-everywhere/pull/6641.
=> Add CVS.com.xml

src/chrome/content/rules/Frida.re.xml
This pull request replaces pull request https://github.com/EFForg/https-everywhere/pull/14266.
=> Add Frida.re.xml

src/chrome/content/rules/EbayCommerceNetwork.com.xml
This pull request replaces pull request https://github.com/EFForg/https-everywhere/pull/14259.
=> Add EbayCommerceNetwork.com.xml

utils/issue-format-bot/.env.example, utils/issue-format-bot/docs/development.md, utils/issue-format-bot/package-lock.json, utils/issue-format-bot/package.json
=> Bump issue bot deps

src/chrome/content/rules/Nieuweautokopen.nl.xml
https://github.com/EFForg/https-everywhere/pull/14242
=> [Nieuweautokopen.nl] New ruleset

src/chrome/content/rules/Kijiji.it.xml
https://github.com/EFForg/https-everywhere/pull/14249
=> [Kijiji.it] New ruleset

src/chrome/content/rules/Disqus.xml
=> [Disqus] Fix duplicate test url

src/chrome/content/rules/Thompson_Hotels.com.xml
=> [Thompsonhotels.com] Default_off ruleset

src/chrome/content/rules/AmazonAWS.com.xml
This subdomain is causing CORS issues on wishtv.com. Fix #14655, fix #4510
=> [AmazonAWS.com] Add exclusion for anvato-api-config

src/chrome/content/rules/JW_Platform.com.xml
follow up of #14472 
fix #14464
=> [JWPlatform.com] Fix exclusion pattern regex

src/chrome/content/rules/StatusPage.io.xml
=> [StatusPage.io] Fix duplicated test url

src/chrome/content/rules/shields.io.xml
=> [Shields.io] Remove extra test url

src/chrome/content/rules/phptesting.org.xml
=> [PHPtesting.org] Simplify ruleset

src/chrome/content/rules/david-dm.org.xml
=> [David-DM.org] Remove extra test url

src/chrome/content/rules/RedBubble.xml
=> redbubble.com: Remove obsolete exclusions

src/chrome/content/rules/CIMBIslamic.com.xml
=> [cimbislamic.com] New ruleset

src/chrome/content/rules/CIMB-Cambodia.xml
=> [CIMB Cambodia] Re-enable ruleset

src/chrome/content/rules/Tcl.tk.xml
=> [Tcl.tk] Add target and simplify rule

src/chrome/content/rules/CIMB-Indonesia.xml
=> [CIMB Indonesia] Update domains

src/chrome/content/rules/IMDB.xml
=> [IMDb] Add targets

src/chrome/content/rules/ebay.com.sg.xml
=> [ebay.com.sg] New ruleset

src/chrome/content/rules/ebayrtm.com.xml
=> [ebayrtm.com] New ruleset

src/chrome/content/rules/CIMB-Thailand.xml
=> [CIMB Thailand] Re-enable ruleset

src/chrome/content/rules/iTradeCIMB.com.my.xml
=> [itradecimb.com.my] Move to a separate ruleset

src/chrome/content/rules/CIMBPreferred.com.xml
=> [cimbpreferred.com] Move to a separate ruleset

src/chrome/content/rules/CIMBClicks.com.my.xml
=> [cimbclicks.com.my] Add subdomains

src/chrome/content/rules/eIPOCIMB.com.xml
=> [eipocimb.com] Move to a separate ruleset

src/chrome/content/rules/CIMB-Principal.com.my.xml
=> [cimb-principal.com.my] Move to separate ruleset

src/chrome/content/rules/CIMBBank.com.my.xml
=> [cimbbank.com.my] Add subdomains

src/chrome/content/rules/Maybank2e.com.xml
=> [Maybank2e.com] New ruleset

src/chrome/content/rules/KETrade.com.sg.xml
=> [KETrade.com.sg] New ruleset

src/chrome/content/rules/Twitch.tv.xml
- Add clips.twitch.tv target
- Update non-functional hosts
=> Add target to Twitch.tv ruleset

src/chrome/content/rules/Nyx.cz.xml
=> [Nyx.cz] Remove duplicate test url

src/chrome/content/rules/Theses.cz.xml
(This removes this ruleset from the ruleset whitelist)
=> [Theses.cz] Update regex style

src/chrome/content/rules/CIMB.com.xml
Previously dangling https://github.com/EFForg/https-everywhere/pull/14035#issuecomment-355794716
=> [cimb.com] Insert back the references

src/chrome/content/rules/Etiqa.com.my.xml
=> [Etiqa.com.my] New ruleset

src/chrome/content/rules/Maybank-KE.co.th.xml
=> [Maybank-KE.co.th] New ruleset

src/chrome/content/rules/Ikea.com.xml
I'm not really interested in having a more thorough look at this ruleset at the moment. Just fixing https://trac.torproject.org/projects/tor/ticket/12911
=> [Ikea.com] Add target

src/chrome/content/rules/Allizom.org.xml
I know I didn't list all subdomains. Feel free to suggest some more if you find important ones but I am not aiming at being exhaustive in this PR.
=> [Allizom.org] Simplify and reactivate ruleset

src/chrome/content/rules/Les-Crises.fr.xml
=> Add Les-Crises.fr.xml

src/chrome/content/rules/GNU.org.xml
@J0WI It seems that I have mistakenly removed some hosts in the previous PR. 
Close #14891, Close #14890.
=> Add planet.gnu.org, Fix #14890, Re-open #14891

src/chrome/content/rules/Panasonic.com.xml
=> [Panasonic.com] Add targets

src/chrome/content/rules/Alaalam.org.xml
This pull request replaces pull request https://github.com/EFForg/https-everywhere/pull/13904.
=> Add Alaalam.org.xml

src/chrome/content/rules/Asrock.com.xml
Adds asrock.com, www.asrock.com and events.asrock.com, per request in #13374
=> Add ruleset for asrock.com

src/chrome/content/rules/JobCloud.ch.xml, src/chrome/content/rules/jobcloud.ch.xml, src/chrome/content/rules/jobs.ch.xml
remove the 'evil regex' in the code base...
=>  Update and rename jobs.ch.xml to JobCloud.ch.xml

src/chrome/content/rules/Maybank.co.id.xml
=> [Maybank.co.id] New ruleset

src/chrome/content/rules/Maybank.com.sg.xml
=> [Maybank.com.sg] New ruleset

src/chrome/content/rules/Ur.se.xml
=> add rule for Ur.se

src/chrome/content/rules/jsrdn.com.xml
I,s & v subdomain are used as well on the net. For example ZAM Network sites.
=> jsrdn.com: add more subdomains

src/chrome/content/rules/Enjin.xml
Primary Domain: enjin.com
Additional Domains:
- enjincoin.io
- enjinwallet.io
- enjinx.io
- efinity.io
=> Official Enjin Ruleset

src/chrome/content/rules/FMyLife.com.xml
=> [FMLife.com] Default_off ruleset

src/chrome/content/rules/stubhubstatic.com.xml
will update references in `Stubhub.com.xml` once https://github.com/EFForg/https-everywhere/pull/14269 is merged.
related: https://github.com/EFForg/https-everywhere/pull/15057 https://github.com/EFForg/https-everywhere/pull/15058
=> [stubhubstatic.com] Separate ruleset

src/chrome/content/rules/worldofplayers.de.xml
=> Add Worldofplayers.de

src/chrome/content/rules/Maybank-KE.com.xml
=> [Maybank-KE.com] New ruleset

chromium/background-scripts/background.js
Since I am unable to reproduce this issues, I _assumed_ this PR works. Any step/ URLs to reproduce this issue is welcomed.
* Preserve sameSite property on Chromium
* Preserve firstPartyDomain property on Firefox
Relate #15045 
/cc @Hainish
=> Update background.js, Fix #15045

src/chrome/content/rules/Maybank-IB.com.xml
=> [Maybank-IB.com] New ruleset

src/chrome/content/rules/Merlinux.xml
- Add hq5.merlinux.eu
- Split pypy.org entries into a new ruleset
=> Revise ruleset: Merlinux

src/chrome/content/rules/NVMExpress.org.xml
=> nvmexpress.org: Keep comment for www domain

chromium/pages/popup/index.html, chromium/pages/popup/style.css
/cc @Hainish IMHO, the checkbox can be better aligned...
=> Fix checkbox spacing in popup

src/chrome/content/rules/DSLReports.xml
=> dslreports.com: Add exclusion for Puma6 test page

src/chrome/content/rules/iDreamx.com.xml
=> Create ruleset: iDreamx.com

chromium/background-scripts/background.js, chromium/pages/popup/index.html, chromium/pages/popup/ux.js, src/chrome/locale/en/https-everywhere.dtd
ping @Hainish 
Steps:
1. Visit https://github.com/
2. Disable `Github`, refresh page to make sure that ruleset is disabled
3. Press "Reset to Defaults"; reload pages and observe that `Github` is enabled.
BTW, it looks like that Travis `selenium` tests fail frequently these days, e.g. https://travis-ci.org/EFForg/https-everywhere/jobs/378370329; not sure if #15396 helps, though...
=> Add "Reset to Defaults" Option in Popup UI, Fix #10004

src/chrome/content/rules/PPSSPP.org.xml
=> Create ruleset: PPSSPP.org

src/chrome/content/rules/CrazyHD.com.xml
=> Create ruleset: CrazyHD.com

src/chrome/content/rules/Unicorn-engine.org.xml
=> Create ruleset: Unicorn-engine.org

src/chrome/content/rules/ExtremeTacticalDynamics.com.xml
=> Create ruleset: ExtremeTacticalDynamics.com

src/chrome/content/rules/Soup.io.xml, src/chrome/content/rules/SoupCDN.com.xml, src/chrome/content/rules/Soup_CDN.com.xml
=> Update ruleset: SoupCDN.com

src/chrome/content/rules/DailyHive.com.xml
Not marking as `platform="mixedcontent"` because the only AMC script is [a tracker](http://tags.crwdcntrl.net/c/12218/cc_af.js).
=> Create ruleset: DailyHive.com

src/chrome/content/rules/TomsHardware.com.xml, src/chrome/content/rules/tomshardware.com.xml
=> [tomshardware.com] Add ruleset

src/chrome/content/rules/Distributed-Weakness-Filing.xml
- Fix broken test due to duplicated test URL
- Match file name and ruleset name
=> Update ruleset: Distributed Weakness Filing

src/chrome/content/rules/Radare.org.xml
=> Create ruleset: Radare.org

src/chrome/content/rules/Abdullah-ocalan.com.xml
google fonts gets blocked as a result but i think that's tolerable
=> Update Abdullah-ocalan.com.xml [mixedcontents audit]

src/chrome/content/rules/ResearcherID.com.xml
=> Create ruleset: ResearcherID.com

src/chrome/content/rules/Mint.com.xml, src/chrome/content/rules/Mint.xml
blog.mint.com credit.mint.com seem to be down
=> Update and rename Mint.xml to Mint.com.xml [mixedcontents audit]

chromium/pages/popup/style.css, chromium/pages/popup/ux.js, test/selenium/test_popup.py
=> Improve popup page performance and reduce memory usage

src/chrome/content/rules/Afterpay.com.au.xml
https://github.com/EFForg/https-everywhere/pull/15719
=> [Afterpay.com.au] New ruleset

src/chrome/content/rules/Afterpay.co.nz.xml
https://github.com/EFForg/https-everywhere/pull/15719
=> [Afterpay.co.nz] New ruleset

src/chrome/content/rules/FirstChoiceLiquor.com.au.xml
=> [FirstChoiceLiquor.com.au] New ruleset

src/chrome/content/rules/Liquorland.com.au.xml
=> [Liquorland.com.au] New ruleset

src/chrome/content/rules/VintageCellars.com.au.xml
=> [VintageCellars.com.au] New ruleset

src/chrome/content/rules/Mycoles.com.au.xml
=> [mycoles.com.au] New ruleset

src/chrome/content/rules/Amazon-Adsystem.com.xml
I added some subdomains.
These redirect from HTTP to HTTPS in root path.
=> Update ruleset Amazon-Adsystem.com.xml

src/chrome/content/rules/Kmart.com.au.xml
=> [Kmart.com.au] New ruleset

src/chrome/content/rules/ColesExpress.com.au.xml
=> [ColesExpress.com.au] New ruleset

src/chrome/content/rules/IBsrv.net.xml, src/chrome/content/rules/Internet_Brands.xml
fix #14577
fix brave/browser-laptop#7460
=> Move IBsrv.net to its own ruleset and fix broken redirects

test/selenium/test_options.py
it should migrate these failing:
https://travis-ci.org/EFForg/https-everywhere/jobs/388095434
https://travis-ci.org/EFForg/https-everywhere/jobs/388093906
https://travis-ci.org/EFForg/https-everywhere/jobs/388101456
=> wait for option page to load

src/chrome/content/rules/Avidemux.org.xml
=> Create ruleset: Avidemux.org

src/chrome/content/rules/KTAS.com.au.xml
=> [KTAS.com.au] New ruleset

src/chrome/content/rules/Lxqt.org.xml
=> Add Lxqt.org.xml

.build_exclusions, chromium/package-lock.json
[`package-lock.json`](https://docs.npmjs.com/files/package-lock.json) is an important security feature of `npm` which allows to check integrity of downloaded packages to protect against repository compromise or man-in-the-middle attacks.
=> Add chromium/package-lock.json

src/chrome/content/rules/VelocityFrequentFlyer.com.xml
https://github.com/EFForg/https-everywhere/pull/13210/
=> [VelocityFrequentFlyer.com] New ruleset

src/chrome/content/rules/STA-Travel.co.th.xml
=> [STA Travel.co.th] New ruleset

src/chrome/content/rules/STA-Travel.co.za.xml
=> [STA Travel.co.za] New ruleset

src/chrome/content/rules/STA-Travel.at.xml
=> [STA Travel.at] New ruleset

src/chrome/content/rules/STA-Travel.de.xml
=> [STA Travel.de] New ruleset

src/chrome/content/rules/Mxptint.net.xml
=> Mxptint.net:

src/chrome/content/rules/RadiumOne.xml
=> RadiumOne:

src/chrome/content/rules/Firefox.com.xml
https://github.com/EFForg/https-everywhere/pull/15714#issuecomment-399766165
=> Add screenshotscdn and fix captive portal detection

src/chrome/content/rules/STA-Travel.com.au.xml
=> [STA Travel.com.au] New ruleset

src/chrome/content/rules/Stubhub.com.xml
=> [Stubhub.com] Update reference

src/chrome/content/rules/News-Corporation-mismatches.xml
Just an attempt to clean up these old rulesets
=> Update ruleset: News Corporation mismatches

src/chrome/content/rules/Blogtrottr.com.xml
- Add custom rule for `li.blogtrottr.com`
=> Update ruleset: Blogtrottr.com

src/chrome/content/rules/Advertising.com.xml
- add adserver-us subdomain and more
=> Advertising.com:

src/chrome/content/rules/STA-Travel.com.sg.xml
=> [STA Travel.com.sg] New ruleset

src/chrome/content/rules/STA-Travel.co.nz.xml
=> [STA Travel.co.nz] New ruleset

utils/trivialize-cdn-rules/index.js, utils/trivialize-cdn-rules/package-lock.json, utils/trivialize-cdn-rules/package.json
@Hainish @Bisaloo I have addressed https://github.com/EFForg/https-everywhere/pull/16000#discussion_r203020768 in this PR. ~Do you think I should run the script to trivialize some CDN rewrites here as well?~ It is better to wait #16029 merged before running this script.
=> Add support for 112.2o7.net rewrites

src/chrome/content/rules/STA-Travel.co.jp.xml
=> [STA-Travel.co.jp] New ruleset

src/chrome/content/rules/Motley-Fool-Singapore.xml
=> [Fool.sg] New ruleset

src/chrome/content/rules/Motley-Fool-Germany.xml
=> [Fool.de] New ruleset

src/chrome/content/rules/Verisign.xml
=> [Verisign.com] Re-enable ruleset

src/chrome/content/rules/PayPal.co.uk.xml
https://github.com/EFForg/https-everywhere/pull/16291
=> [PayPal.co.uk] Add subdomains

src/chrome/content/rules/Fool-CDN.com.xml
=> [foolcdn.com] Separate ruleset

src/chrome/content/rules/Motley-Fool-Australia.xml
=> [Fool.com.au] Separate ruleset

src/chrome/content/rules/Motley-Fool-UK.xml
=> [Fool.co.uk] Separate ruleset

src/chrome/content/rules/Dollar.de.xml
https://github.com/EFForg/https-everywhere/pull/16328
=> [Dollar.de] New ruleset

src/chrome/content/rules/DollarCanada.ca.xml
https://github.com/EFForg/https-everywhere/pull/16328
=> [DollarCanada.ca] New ruleset

src/chrome/content/rules/Dollar.co.uk.xml
https://github.com/EFForg/https-everywhere/pull/16328
=> [Dollar.co.uk] New ruleset

src/chrome/content/rules/Verisign.fr.xml
=> [Verisign.fr] Separate ruleset

src/chrome/content/rules/Verisign.com.sg.xml
=> [Verisign.com.sg] Separate ruleset

src/chrome/content/rules/Verisign.com.hk.xml
=> [Verisign.com.hk] Separate ruleset

src/chrome/content/rules/Verisign.com.tw.xml
=> [Verisign.com.tw] Separate ruleset

src/chrome/content/rules/Verisign.com.au.xml
=> [Verisign.com.au] Separate ruleset

src/chrome/content/rules/Verisign.dk.xml
=> [Verisign.dk] Separate ruleset

src/chrome/content/rules/Verisign.com.br.xml
=> [Verisign.com.br] Separate ruleset

src/chrome/content/rules/ThriftySingapore.com.xml
=> [ThriftySingapore.com] New ruleset

src/chrome/content/rules/ThriftyCanada.ca.xml
=> [ThriftyCanada.ca] New ruleset

src/chrome/content/rules/Thrifty.no.xml
=> [Thrifty.no] New ruleset

src/chrome/content/rules/Thrifty.nl.xml
=> [Thrifty.nl] New ruleset

src/chrome/content/rules/Thrifty.ie.xml
=> [Thrifty.ie] New ruleset

src/chrome/content/rules/Thrifty.ma.xml
=> [Thrifty.ma] New ruleset

src/chrome/content/rules/Thrifty.de.xml
=> [Thrifty.de] New ruleset

src/chrome/content/rules/Thrifty.ch.xml
=> [Thrifty.ch] New ruleset

src/chrome/content/rules/Thrifty.be.xml
=> [Thrifty.be] New ruleset

src/chrome/content/rules/Thrifty.co.kr.xml
=> [Thrifty.co.kr] New ruleset

src/chrome/content/rules/Thrifty.co.nz.xml
=> [Thrifty.co.nz] New ruleset

src/chrome/content/rules/Thrifty.co.za.xml
=> [Thrifty.co.za] New ruleset

src/chrome/content/rules/Thrifty.com.br.xml
=> [Thrifty.com.br] New ruleset

src/chrome/content/rules/Thrifty.com.ph.xml
=> [Thrifty.com.ph] New ruleset

test/run_travis.sh, test/selenium/requirements.txt
http://blog.pytest.org/2016/whats-new-in-pytest-30/
https://twitter.com/hashtag/dropthedot
=> Use pytest instead of py.test per upstream recommendation, #dropthedot

src/chrome/content/rules/Budgetsuriname.com.xml
=> [Budgetsuriname.com] New ruleset

src/chrome/content/rules/Budget-Martinique.com.xml
=> [Budget-Martinique.com] New ruleset

src/chrome/content/rules/Budget-Belize.com.xml
=> [Budget-Belize.com] New ruleset

src/chrome/content/rules/Budget.se.xml
=> [Budget.se] New ruleset

src/chrome/content/rules/Budget.no.xml
=> [Budget.no] New ruleset

src/chrome/content/rules/Budget.nl.xml
=> [Budget.nl] New ruleset

src/chrome/content/rules/Budgetautonoleggio.it.xml
=> [Budgetautonoleggio.it] New ruleset

src/chrome/content/rules/Budget-Peru.com.xml
=> [Budget-Peru.com] New ruleset

src/chrome/content/rules/Budget-Panama.com.xml
=> [Budget-Panama.com] New ruleset

src/chrome/content/rules/PayPal-Gifts.com.xml
https://github.com/EFForg/https-everywhere/pull/16291
=> [PayPal-Gifts.com] New ruleset

src/chrome/content/rules/Budget.ma.xml
=> [Budget.ma] New ruleset

src/chrome/content/rules/Budget.com.fj.xml
=> [Budget.com.fj] New ruleset

src/chrome/content/rules/Budget.com.gt.xml
=> [Budget.com.gt] New ruleset

src/chrome/content/rules/Budget.com.do.xml
=> [Budget.com.do] New ruleset

src/chrome/content/rules/Budget.co.za.xml
=> [Budget.co.za] New ruleset

src/chrome/content/rules/Budget.lu.xml
=> [Budget.lu] New ruleset

src/chrome/content/rules/Budget.ee.xml
=> [Budget.ee] New ruleset

src/chrome/content/rules/Budget.ie.xml
=> [Budget.ie] New ruleset

src/chrome/content/rules/Budget.lv.xml
=> [Budget.lv] New ruleset

src/chrome/content/rules/Budget.com.sv.xml
=> [Budget.com.sv] New ruleset

src/chrome/content/rules/Budget.com.tr.xml
=> [Budget.com.tr] New ruleset

src/chrome/content/rules/Budget.com.mx.xml
=> [Budget.com.mx] New ruleset

src/chrome/content/rules/Budget.es.xml
=> [Budget.es] New ruleset

src/chrome/content/rules/Budget.bo.xml
=> [Budget.bo] New ruleset

src/chrome/content/rules/Budget.ba.xml
=> [Budget.ba] New ruleset

src/chrome/content/rules/Budget.co.uk.xml
=> [Budget.co.uk] New ruleset

src/chrome/content/rules/Budget.de.xml
=> [Budget.de] New ruleset

src/chrome/content/rules/Budget.fr.xml
=> [Budget.fr] New ruleset

src/chrome/content/rules/Budget.co.nz.xml
=> [Budget.co.nz] New ruleset

src/chrome/content/rules/Avissuriname.com.xml
=> [Avissuriname.com] New ruleset

src/chrome/content/rules/Avisautonoleggio.it.xml
=> [Avisautonoleggio.it] New ruleset

src/chrome/content/rules/Avis.tc.xml
=> [Avis.tc] New ruleset

src/chrome/content/rules/Avis.se.xml
=> [Avis.se] New ruleset

src/chrome/content/rules/Avis.no.xml
=> [Avis.no] New ruleset

src/chrome/content/rules/Avis.pl.xml
=> [Avis.pl] New ruleset

src/chrome/content/rules/Avis.nl.xml
=> [Avis.nl] New ruleset

src/chrome/content/rules/Avis.be.xml
=> [Avis.be] New ruleset

src/chrome/content/rules/Avis.at.xml
=> [Avis.at] New ruleset

src/chrome/content/rules/Avis.ie.xml
=> [Avis.ie] New ruleset

src/chrome/content/rules/Avis.fi.xml
=> [Avis.fi] New ruleset

src/chrome/content/rules/Avis.ma.xml
=> [Avis.ma] New ruleset

src/chrome/content/rules/Avis.ch.xml
=> [Avis.ch] New ruleset

src/chrome/content/rules/Avis.cl.xml
=> [Avis.cl] New ruleset

src/chrome/content/rules/Avis.ca.xml
=> [Avis.ca] New ruleset

src/chrome/content/rules/Avis.com.lb.xml
=> [Avis.com.lb] New ruleset

src/chrome/content/rules/Avis.com.pa.xml
=> [Avis.com.pa] New ruleset

src/chrome/content/rules/Avis.com.pk.xml
=> [Avis.com.pk] New ruleset

src/chrome/content/rules/Avis.com.do.xml
=> [Avis.com.do] New ruleset

src/chrome/content/rules/Avis.com.hr.xml
=> [Avis.com.hr] New ruleset

src/chrome/content/rules/Avis.com.hk.xml
=> [Avis.com.hk] New ruleset

src/chrome/content/rules/Avis.com.ar.xml
=> [Avis.com.ar] New ruleset

src/chrome/content/rules/Avis.com.br.xml
=> [Avis.com.br] New ruleset

src/chrome/content/rules/Avis.com.tr.xml
=> [Avis.com.tr] New ruleset

src/chrome/content/rules/Avis.co.il.xml
=> [Avis.co.il] New ruleset

src/chrome/content/rules/Avis.co.uk.xml
=> [Avis.co.uk] New ruleset

src/chrome/content/rules/Avis.com.co.xml
=> [Avis.com.co] New ruleset

src/chrome/content/rules/Avis.co.za.xml
=> [Avis.co.za] New ruleset

src/chrome/content/rules/Avis-Tahiti.com.xml
=> [Avis-Tahiti.com] New ruleset

src/chrome/content/rules/Avis-Japan.com.xml
=> [Avis-Japan.com] New ruleset

src/chrome/content/rules/Avis-Thailand.com.xml
=> [Avis-Thailand.com] New ruleset

src/chrome/content/rules/Avis-Taiwan.com.xml
=> [Avis-Taiwan.com] New ruleset

src/chrome/content/rules/Avis-sxm.com.xml
=> [Avis-sxm.com] New ruleset

src/chrome/content/rules/Verisign.se.xml
=> [Verisign.se] Separate ruleset

src/chrome/content/rules/Click4Wheels.com.xml
=> [Click4Wheels.com] New ruleset

src/chrome/content/rules/Click4Wheels.cn.xml
=> [Click4Wheels.cn] New ruleset

src/chrome/content/rules/Click4Wheels.jp.xml
=> [Click4Wheels.jp] New ruleset

src/chrome/content/rules/Click4Wheels.co.kr.xml
=> [Click4Wheels.co.kr] New ruleset

src/chrome/content/rules/Europcar.es.xml
=> [Europcar.es] New ruleset

src/chrome/content/rules/Europcar-Group.com.xml
=> [Europcar-Group.com] New ruleset

src/chrome/content/rules/Europcar.fr.xml
=> [Europcar.fr] New ruleset

src/chrome/content/rules/Europcar.com.au.xml
=> [Europcar.com.au] New ruleset

src/chrome/content/rules/Europcar.co.nz.xml
=> [Europcar.co.nz] New ruleset

src/chrome/content/rules/Motley-Fool.xml
=> Add reference to related rulesets

src/chrome/content/rules/PayPal.me.xml
https://github.com/EFForg/https-everywhere/pull/16291
=> [PayPal.me] New ruleset

src/chrome/content/rules/Graphviz.org.xml
=> Add Graphviz.org.xml

src/chrome/content/rules/Real_World_OCaml.org.xml
* Add targets
* Remove target www.realworldocaml.org which seems forever broken
=> Update ruleset: Real World OCaml.org

src/chrome/content/rules/Gtk.org.xml
=> Add Gtk.org.xml

src/chrome/content/rules/Comic-Con-Intl.xml
=> Update Ruleset for Comic Con

src/chrome/content/rules/Openjpeg.org.xml
=> Add Openjpeg.org.xml

src/chrome/content/rules/Libssh2.org.xml
=> Add Libssh2.org.xml

src/chrome/content/rules/Uclibc.org.xml
=> Add Uclibc.org.xml

src/chrome/content/rules/Speedtest.net.xml
close #16615, #1362 is more than 3 years ago and it is no longer reproducible on my side.
=> Update Speedtest.net, fix #16615

src/chrome/content/rules/Verisign.co.jp.xml
=> [Verisign.co.jp] Separate ruleset

src/chrome/content/rules/Avis.fr.xml
=> [Avis.fr] New ruleset

src/chrome/content/rules/Avis.es.xml
=> [Avis.es] New ruleset

src/chrome/content/rules/Verisign-Inc.com.xml
=> [Verisign-Inc.com] Separate ruleset

src/chrome/content/rules/Thrifty.co.uk.xml
=> [Thrifty.co.uk] New ruleset

src/chrome/content/rules/Budget.com.ar.xml
=> [Budget.com.ar] New ruleset

src/chrome/content/rules/Budget.com.br.xml
=> [Budget.com.br] New ruleset

src/chrome/content/rules/Nuitka.net.xml
=> Create Nuitka.net.xml, fix #16635

src/chrome/content/rules/Toppers.jp.xml
=> Create Toppers.jp.xml, fix #16636

src/chrome/content/rules/Budget.co.cr.xml
=> [Budget.co.cr] New ruleset

src/chrome/content/rules/nicchile.xml
We're issuing a 302 redirect from plain http since a couple of weeks.
=> Ruleset for www.nic.cl

src/chrome/content/rules/Tinc-vpn.org.xml
=> Add Tinc-vpn.org.xml

src/chrome/content/rules/QBE-Re.com.xml
https://github.com/EFForg/https-everywhere/pull/15785
=> [QBE Re.com] New ruleset

src/chrome/content/rules/Verisign-grs.com.xml
=> [Verisign-grs.com] Separate ruleset

src/chrome/content/rules/LibreOffice.org.xml
=> Add dev-www.libreoffice.org

src/chrome/content/rules/GovHK.xml, src/chrome/content/rules/info.gov.hk.xml
=> [info.gov.hk] New ruleset

src/chrome/content/rules/GovHK.xml, src/chrome/content/rules/rocars.gov.hk.xml
New ruleset for [Hong Kong Customs and Excise Department - Road Cargo System](http://www.rocars.gov.hk)
=> [rocars.gov.hk] New ruleset

src/chrome/content/rules/Synchronicer.dk.xml
Synchronicer.dk no longer has any mixed content problems.
=> Update Synchronicer.dk to enforce HTTPS

src/chrome/content/rules/GovHK.xml, src/chrome/content/rules/hydro.gov.hk.xml
New ruleset for [Hong Kong Hydrographic Office](http://www.hydro.gov.hk)
=> [hydro.gov.hk] New ruleset

src/chrome/content/rules/Thrifty.com.au.xml
=> [Thrifty.com.au] New ruleset

src/chrome/content/rules/GovHK.xml, src/chrome/content/rules/familycouncil.gov.hk.xml
New ruleset for [Hong Kong Family Council](http://www.familycouncil.gov.hk)
=> [familycouncil.gov.hk] New ruleset

src/chrome/content/rules/GovHK.xml, src/chrome/content/rules/hiking.gov.hk.xml
New ruleset for [Enjoy Hiking](http://www.hiking.gov.hk)
=> [hiking.gov.hk] New ruleset

src/chrome/content/rules/smokefree.hk.xml
New ruleset for [Hong Kong Council on Smoking and Health](http://www.smokefree.hk)
=> [smokefree.hk] New ruleset

src/chrome/content/rules/University-of-Exeter.xml
=> Update University-of-Exeter.xml, fix #16473

src/chrome/content/rules/Maybank2u.com.ph.xml
=> [Maybank2u.com.ph] New ruleset

src/chrome/content/rules/NordVPN.com.xml
Closes https://github.com/EFForg/https-everywhere/issues/17046
=> [NordVPN.com] Add subdomains

src/chrome/content/rules/QBE.com.au.xml
https://github.com/EFForg/https-everywhere/pull/15785
=> [QBE.com.au] New ruleset

src/chrome/content/rules/Marktplaatsperskamer.nl.xml
depends on https://github.com/EFForg/https-everywhere/pull/14242
=> [Marktplaatsperskamer.nl] Move to a separate ruleset

src/chrome/content/rules/Marktplaats.com.xml
depends on https://github.com/EFForg/https-everywhere/pull/14242
=> [Marktplaats.com] Update subdomains

src/chrome/content/rules/Budget.ca.xml
=> [Budget.ca] New ruleset

src/chrome/content/rules/Freelibrary.org.xml
=> Add Freelibrary.org.xml

src/chrome/content/rules/Net-metrix.ch.xml, src/chrome/content/rules/Wemfbox.ch.xml
`Wemfbox.ch.xml` is only tracking anyway.
See also: #14293
=> Add Net-metrix.ch.xml and update Wemfbox.ch.xml

src/chrome/content/rules/iPay88.com.xml
https://github.com/EFForg/https-everywhere/pull/15724
=> [iPay88.com] New ruleset

src/chrome/content/rules/Quassel-irc.org.xml
=> Add Quassel-irc.org.xml

src/chrome/content/rules/Colordiff.org.xml
=> Add Colordiff.org.xml

src/chrome/content/rules/Qemu.org.xml
=> Add Qemu.org.xml

src/chrome/content/rules/Cloudflare-ipfs.com.xml
Who said Cloudflare is a champion of complete HTTPS coverage?
=> [cloudflare-ipfs.com] New ruleset

src/chrome/content/rules/Spiegel.xml
=> add spiegel-de subdomain

src/chrome/content/rules/Europcar.de.xml
=> [Europcar.de] New ruleset

chromium/pages/popup/index.html, chromium/test/rules_test.js, src/chrome/locale/en/https-everywhere.dtd
- For better user clarity for when they request un-encrypted requests
- In reference to the conversation had in #16985
- New UX is under development from #16669, but this can be a quick fix for the release tomorrow
=> Change HTTP Block language

chromium/pages/popup/ux.js
=> Reload current tab when enabling EASE mode, fix #16870

chromium/.eslintrc.json, chromium/background-scripts/background.js, chromium/background-scripts/rules.js, chromium/background-scripts/store.js, chromium/background-scripts/update.js, chromium/background-scripts/util.js, chromium/pages/cancel/ux.js, chromium/pages/debugging-rulesets/ux.js, chromium/pages/options/ux.js, chromium/pages/popup/ux.js, chromium/test/update_test.js
=> Add eslint rules space-before-blocks and brace-style

src/chrome/content/rules/Github-Pages.xml
Fixed in https://github.com/katbailey/katbailey.github.io/commit/673b7c0319c732d9f043726d0e054858d63e1088
=> [GitHub.io] Remove outdated exclusion

src/chrome/content/rules/GitList.org.xml
Subdomain `i.gitlist.org` cannot resolve.
=> Create ruleset: GitList.org

src/chrome/content/rules/KOOORA.com.xml
Fixes: #17271 
kooora.com falls in redirect loop
http://kooora.com <=> http://www.kooora.com/default.aspx
=> Disable rule

src/chrome/content/rules/Avahi.org.xml
=> Add Avahi.org.xml

src/chrome/content/rules/X.org.xml
=> Add X.org.xml

src/chrome/content/rules/Net-dns.org.xml
=> Add Net-dns.org.xml

src/chrome/content/rules/Offlineimap.org.xml
=> Add Offlineimap.org.xml

src/chrome/content/rules/Rephial.org.xml
I have added a new ruleset for Rephial.org.
This is my first ruleset and opensource contribution so please let me know if I did anything wrong and you need something changing. Thank you
=>  Add Rephial.org.xml to ruleset

src/chrome/content/rules/Remmina.org.xml
=> Add Remmina.org.xml

src/chrome/content/rules/Libspf2.org.xml
=> Add Libspf2.org.xml

src/chrome/content/rules/Rsyslog.com.xml
=> Add Rsyslog.com.xml

src/chrome/content/rules/escortradarforum.com.xml
=> Created ruleset for escortradarforum.com

src/chrome/content/rules/Pgpool.net.xml
=> Add Pgpool.net.xml

src/chrome/content/rules/Libarchive.org.xml
=> Add Libarchive.org.xml

src/chrome/content/rules/UAB.edu.xml
=> Add ruleset: UAB.edu

src/chrome/content/rules/Privoxy.org.xml
=> Add Privoxy.org.xml

utils/labeller/README.md
Add context for token creation
=> Update Labeler doc

utils/hsts-prune/index.js
=> Reflect the change in HSTS preload rules.

CONTRIBUTING.md
=> Update HSTS preload max age

src/chrome/content/rules/Cheapshark.com.xml
Closes https://github.com/EFForg/https-everywhere/issues/17214
=> Added new ruleset - Cheapshark.com.xml

src/chrome/content/rules/risctraining.org.xml
=> Create risctraining.org.xml 

src/chrome/content/rules/FSF.xml
This does only address hosts mentioned in #15750
=> Add some nongnu.org hosts

src/chrome/content/rules/AhnLab.com.xml, src/chrome/content/rules/Ahnlab.com.xml
No evidence of mixed content issues.
=> Update and rename Ahnlab.com.xml to AhnLab.com.xml

src/chrome/content/rules/Gamer-network.net.xml, src/chrome/content/rules/Nintendolife.com.xml, src/chrome/content/rules/Pushsquare.com.xml
This fixes the remaining https://github.com/EFForg/https-everywhere/pull/17481#discussion_r264250890.
=> [Game Network rulesets] add missing targets and fix code style

src/chrome/content/rules/Nuttcp.net.xml
=> Add Nuttcp.net.xml

src/chrome/content/rules/Lxde.org.xml
=> Add Lxde.org.xml

install-dev-dependencies.sh
Noticed Geckodriver install is out of date, will likely be combing through script to see what else is out of date
=> Update Geckodriver in dependencies

utils/issue-format-bot/package-lock.json, utils/issue-format-bot/package.json
- Fixes: https://nvd.nist.gov/vuln/detail/CVE-2019-5413 for Morgan package
- Also updates numerous other outdated packages
=> Update NPM Dependencies in Issue Formating Bot

chromium/pages/popup/ux.js
=> Fix bug in Chromium that makes popup links always load in non-incognito mode

src/chrome/content/rules/YourWorldOfText.com.xml
=> Add YourWorldOfText.com.xml

chromium/background-scripts/rules.js
=> Avoid redundant statement branching in safeToSecureCookie()

src/chrome/content/rules/123domain.eu.xml
=> Add 123domain.eu.xml

src/chrome/content/rules/WebDiplomacy.net.xml
=> Add WebDiplomacy.net.xml

src/chrome/content/rules/FF7.fr.xml
=> Add FF7.fr.xml

src/chrome/content/rules/WorldOfPlayers.ru.xml
=> Add WorldOfPlayers.ru.xml

src/chrome/content/rules/BlamBot.com.xml
=> Add BlamBot.com.xml

src/chrome/content/rules/buaa.edu.cn.xml
Closes #17475.
Due to the nature of Chinese internet I want review from someone who is located in Mainland. @cschanaj I know you are located in HK, but can you run a VPS in Mainland? I don't know any VPS providers that work without ICP number.
=> Add buaa.edu.cn.xml

chromium/pages/popup/index.html, chromium/pages/popup/ux.js, src/chrome/locale/en/https-everywhere.dtd
Updating the rest of the changed language that occurred from the UX overhaul of state based strings
=> Update Translation Strings Properly

utils/hsts-prune/package-lock.json
=> Run npm audit fix on hsts-prune

test/selenium/test_popup.py
Putting the "test rule shown" unit test back in with amendments from the new UI
=> Amend test for stable rules

src/chrome/content/rules/JList.com.xml
#17912 note: contains some nsfw content
=> Re-activate and update JList.com.xml

src/chrome/content/rules/Florida_Today.xml
=> Trivialize and update Florida_Today.xml

src/chrome/content/rules/Uni.Lu.xml
=> Fix typo causing *.uni.lu unprotected

docs/en_US/rulesets.md
This can cause confusion for users, as shown in https://github.com/EFForg/https-everywhere/issues/17882#issuecomment-489828459
=> Update outdated paragraph about MCB and Tor

chromium/background-scripts/background.js, chromium/pages/cancel/ux.js
Please test before merging. This should work fine though.
=> Fix #17983 (some URL parameters dropped from EASE return links)

src/chrome/content/rules/Online.nl.xml
=> Fix missing target causes online.nl unprotected 

utils/sign-rulesets/async-request.sh, utils/sign-rulesets/standalone.sh
I haven't test this, but it should not break things too crazily.
=> Add git reference to OOB ruleset releases, close #17641

src/chrome/content/rules/AntennaPod.org.xml
=> Add AntennaPod.org (#18042)

utils/trivialize-rules/trivialize-targets.js
Feel free to partially merge/cherrypick if needed.
=> Minor style fixes to cschanaj script

chromium/pages/options/index.html, chromium/pages/options/style.css, chromium/pages/options/ux.js, src/chrome/locale/en/https-everywhere.dtd
This is how appearing effect looks like: https://raw.githubusercontent.com/pipboy96/https-everywhere/raw/tmp/fix-ruleset-editor.mp4
=> Fix ruleset editor

src/chrome/content/rules/Infradead.org.xml
=> Re-enable Infradead.org.xml

src/chrome/content/rules/University_of_Houston.xml
=> Trivialize and update University_of_Houston.xml

src/chrome/content/rules/Aqicn.org.xml
https://github.com/EFForg/https-everywhere/pull/17741
=> [Aqicn.org] New ruleset

src/chrome/content/rules/Waqi.info.xml
https://github.com/EFForg/https-everywhere/pull/17740
=> [Waqi.info] New ruleset

src/chrome/content/rules/LimeSurvey.org.xml
https://github.com/EFForg/https-everywhere/pull/15977
=> [LimeSurvey.org] Fix cert mismatch

src/chrome/content/rules/hzqx.com.xml
Add support for Hangzhou Weather Service Center(杭州市气象服务中心) website:
`http://www.hzqx.com/hztq/index.html` --> `https://www.hzqx.com/hztq/index.html`
=> Add hzqx.com.xml

src/chrome/content/rules/zufe.edu.cn.xml
Add a ruleset for Zhejiang University of Finance & Economics(浙江财经大学).
=> Add zufe.edu.cn.xml

src/chrome/content/rules/USTC.edu.cn.xml
Updated the ruleset`USTC.edu.cn.xml` for University of Science and Technology of China.
=> Updated USTC.edu.cn.xml

.gitmodules, chromium/.eslintrc.json, chromium/background-scripts/background.js, chromium/background-scripts/rules.js, chromium/background-scripts/wasm.js, chromium/manifest.json, chromium/test/rules_test.js, make.sh
functionality of `rules.js` into WASM for memory efficiency and
performance.
=> Adding https-everywhere-lib submodule, which moves much of the

src/chrome/content/rules/NoelShack.com.xml
=> Add NoelShack.com.xml

src/chrome/content/rules/Libevent.org.xml
=> Add Libevent.org.xml

src/chrome/content/rules/SkyscraperPage.com.xml
=> Add skyscraperpage.com

src/chrome/content/rules/World-Nuclear-News.org.xml
=> Add world-nuclear-news.org

chromium/pages/options/ux.js
Addresses errors found by LGTM
https://lgtm.com/projects/g/EFForg/https-everywhere/snapshot/239a0cfcadb7283c846700b084fa421d1e199587/files/chromium/pages/options/ux.js?sort=name&dir=ASC&mode=heatmap
=> Added semicolons to avoid auto semicolon insertion

src/chrome/content/rules/hko.gov.hk.xml
(This is a re-submission of #18147)
@cschanaj
=> Update hko.gov.hk.xml to include weather.gov.hk

src/chrome/content/rules/Spinroot.com.xml
=> Add Spinroot.com.xml

src/chrome/content/rules/BedfordshirePolice.xml
Working my way through the [List of UK police forces](https://www.police.uk/forces/) adding rules for each (many have already been added).
=> Add ruleset for Bedfordshire Police

src/chrome/content/rules/Aqicn.org.xml, src/chrome/content/rules/Waqi.info.xml
=> Add related rulesets

src/chrome/content/rules/Neis-One.org.xml, src/chrome/content/rules/Neis-One.org_mixedcontent.xml
=> Add Neis-One.org.xml

src/chrome/content/rules/NCRegister.com.xml
=> Add NCRegister.com.xml

src/chrome/content/rules/Digint.ch.xml
=> Add Digint.ch.xml

src/chrome/content/rules/FreeSWITCH.org.xml
=> Add files and lists to FreeSWITCH.org.xml

src/chrome/content/rules/Ghostscript.com.xml
=> Add Ghostscript.com.xml

src/chrome/content/rules/Schweikert.ch.xml
=> Add Schweikert.ch.xml

src/chrome/content/rules/Fark.xml
See https://trac.torproject.org/projects/tor/ticket/15763#comment:6
=> [Fark.com] Reactivate and simplify ruleset

src/chrome/content/rules/Java.net.xml
Still no full coverage but some enhancements.
=> Add more hosts to Java.net.xml

src/chrome/content/rules/UNICEF.fi.xml
(I do not wish to investigate other potential subdomains)
=> Re-enable UNICEF.fi.xml

src/chrome/content/rules/Criu.org.xml
=> Add Criu.org.xml

src/chrome/content/rules/make-trivial-rule
per invitation from @jeremyn at
https://github.com/EFForg/https-everywhere/pull/10875#issuecomment-362609979
=> Add note to ruleset creators

src/chrome/content/rules/Classpath.org.xml
=> Add Classpath.org.xml

src/chrome/content/rules/SystemSensor.ca.xml
=> Add SystemSensor.ca.xml

src/chrome/content/rules/E-Hentai-Forums.xml, src/chrome/content/rules/E-Hentai.org.xml
=> Add E-Hentai.org.xml

src/chrome/content/rules/WebMD.xml
=> Update WebMd.xml, related to #17965

src/chrome/content/rules/Vaultize.com.xml
Added a ruleset for a [site](https://vaultize.com "Vaultize").
=> Ruleset for vaultize.com

src/chrome/content/rules/WorldOfGothic.com.xml
=> Add WorldOfGothic.com.xml

src/chrome/content/rules/Randaris-Anime.net.xml
=> Add Randaris-Anime.net.xml

src/chrome/content/rules/SmartSource.xml
- smartsource.ca
- smartsource.com
=> Add ruleset: SmartSource

src/chrome/content/rules/Tpaste.us.xml
=> Add Tpaste.us.xml

src/chrome/content/rules/EHWiki.org.xml
=> Add EHWiki.org.xml

src/chrome/content/rules/Bues.ch.xml
=> Add Bues.ch.xml

src/chrome/content/rules/Ace-book.net.xml
=> Add Ace-book.net.xml

src/chrome/content/rules/airsoftclubnederland.nl.xml
=> Added ruleset airsoftclubnederland.nl.xml

src/chrome/content/rules/HentaiVerse.org.xml
=> Add HentaiVerse.org.xml

src/chrome/content/rules/learning.hccs.edu.xml
=> Add learning.hccs.edu.xml

src/chrome/content/rules/Memo.tv.xml
Related: https://github.com/EFForg/https-everywhere/issues/18157#issuecomment-510749635
=> Add Memo.tv.xml

src/chrome/content/rules/ADCBlog.org.xml, src/chrome/content/rules/AmericanDreamCoalition.org.xml
=> Add AmericanDreamCoalition.org.xml and ADCBlog.org.xml

src/chrome/content/rules/OpenSignal.com.xml
(I didn't check if there are other subdomains)
=> Re-enabling OpenSignal.com.xml

src/chrome/content/rules/PremierLiga.ru.xml
https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-510866960
=> Add PremierLiga.ru.xml

src/chrome/content/rules/ShoutWiki.com.xml
=> Add ShoutWiki.com.xml

src/chrome/content/rules/Otrs.com.xml, src/chrome/content/rules/Otrs.org.xml
=> Add Otrs rulesets

src/chrome/content/rules/Nagios.com.xml, src/chrome/content/rules/Nagios.org.xml
=> Add Nagios

src/chrome/content/rules/Uvnc.com.xml
https://github.com/EFForg/https-everywhere/issues/15777
=> Add new ruleset for www.uvnc.com

src/chrome/content/rules/KOLRanking.com.xml
=> Add KOLRanking.com.xml

src/chrome/content/rules/ArchiveTeam.org.xml
=> Add ArchiveTeam.org.xml

src/chrome/content/rules/TheClaroGroup.com.xml
=> Add TheClaroGroup.com.xml

utils/hsts-prune/index.js
This addresses a [recommendation from lgtm](https://lgtm.com/projects/g/EFForg/https-everywhere/snapshot/239a0cfcadb7283c846700b084fa421d1e199587/files/utils/hsts-prune/index.js?sort=name&dir=ASC&mode=heatmap)
=> Remove Unused Variable `pos`

src/chrome/content/rules/Nabble.com.xml
=> Add Nabble.com.xml

src/chrome/content/rules/Meteoalarm.eu.xml
=> Add Meteoalarm.eu.xml

src/chrome/content/rules/Tcpdump.org.xml
=> Add Tcpdump.org.xml

src/chrome/content/rules/Barnebys.com.xml, src/chrome/content/rules/Blogo.xml, src/chrome/content/rules/Janalta.com.xml, src/chrome/content/rules/Livefyre.xml, src/chrome/content/rules/NewsLook.xml, src/chrome/content/rules/Talking_Points_Memo.com.xml, src/chrome/content/rules/tori.net.xml
=> Run node utils/trivialize-cdn-rules/index.js

src/chrome/content/rules/litresp.ru.xml
=> Add litresp.ru.xml

src/chrome/content/rules/Clubic.com.xml
=> Add Clubic.com.xml

src/chrome/content/rules/welmers.net.xml
Added rules for domains running webservers that I own.
=> Add welmers.net.xml

src/chrome/content/rules/Eyny.com.xml
=> Create ruleset: Eyny.com

src/chrome/content/rules/GlobalConnect.dk.xml
Replaces #16120 due to Travis failure.
=> Globalconnect.dk

src/chrome/content/rules/Abbott-Laboratories.xml, src/chrome/content/rules/abbott.com.xml
I don't want to investigate the other subdomains
=> Re-enabling Abbott-Laboratories.xml

src/chrome/content/rules/RustFest.eu.xml, src/chrome/content/rules/rustfest.eu.xml
- some subdomains do not always redirect to https
=> Add rule for RustFest.eu

src/chrome/content/rules/Roblox-whitelist.xml, src/chrome/content/rules/Roblox.xml
- accountsettings.roblox.com supports HTTPS
- billing.roblox.com supports HTTPS
- developer.roblox.com supports HTTPS
- devforum.roblox.com supports HTTPS
- friends.roblox.com supports HTTPS
- games.roblox.com supports HTTPS
- groups.roblox.com supports HTTPS
- partners.roblox.com no longer exists
- points.roblox.com supports HTTPS
- wiki.roblox.com supports HTTPS
=> [Roblox] Update subdomains

install-dev-dependencies.sh
This pull request is basically the same as another I did a while back. Basically, all I did is remove what seemed like redundant colours in a script file, and also added a line to properly install `chromedriver` on Mac.
=> Properly install `chromedriver` on Mac.

.travis.yml
=> Temporarily downgrade LTS to Dubnium branch to fix node-webcrypto-ossl install error

src/chrome/content/rules/Elixir-Lang.org.xml
=> Add Elixir-Lang.org.xml

src/chrome/content/rules/Scrapy.org.xml
=> Add Scrapy.org.xml

src/chrome/content/rules/CPAN.org.xml
=> Add CPAN.org.xml

src/chrome/content/rules/ZX2C4.com.xml
=> Add ZX2C4.com.xml

src/chrome/content/rules/OpenCV.org.xml
=> Add OpenCV.org.xml

src/chrome/content/rules/HTTrack.com.xml
=> Add HTTrack.com.xml

src/chrome/content/rules/ZNC.in.xml
=> Add ZNC.in.xml

src/chrome/content/rules/LibGen.is.xml
=> Add LibGen.is.xml

src/chrome/content/rules/Biologo.ru.xml
=> Add Biologo.ru.xml

chromium/pages/popup/style.css
This PR fixes the UI distortion when the display language is not English
- #18482
=>  Fix styles when display language is not English, issue #18482 

chromium/pages/cancel/index.html, chromium/pages/cancel/style.css
ping @zoracon.
This PR fixes multiple issues with EASE cancel page. The most severe issue fixed by this PR is a layout issue shown below:
=> Fix multiple issues on EASE cancel page

src/chrome/content/rules/the-eye.eu.xml
=> Add the-eye.eu

chromium/pages/cancel/style.css, chromium/pages/cancel/ux.js
=> Hotfix: EASE interstitial Link Failing for some Locales

src/chrome/content/rules/Robert.ca.xml
=> Add Robert.ca.xml

src/chrome/content/rules/spacechase0.com.xml
=> Add spacechase0.com.xml

src/chrome/content/rules/AmamiyaSora.jp.xml
=> Add AmamiyaSora.jp.xml

src/chrome/content/rules/YogaDNS.com.xml
=> Add YogaDNS.com.xml

src/chrome/content/rules/tmp.ninja.xml
=> Add tmp.ninja.xml

chromium/background-scripts/background.js
=> Fix parseIP call

src/chrome/content/rules/SSLEnforcer.com.xml
=> Add SSLEnforcer.com.xml

src/chrome/content/rules/Proxifier.com.xml
=> Add Proxifier.com.xml

src/chrome/content/rules/LightningMaps.org.xml
=> Add targets to LightningMaps.org.xml

src/chrome/content/rules/HDME.eu.xml
=> Add HDME.eu.xml

src/chrome/content/rules/QuickSilverMail.net.xml
=> Add QuickSilverMail.net.xml

src/chrome/content/rules/AOMedia.org.xml
=> Add AOMedia.org.xml

src/chrome/content/rules/Azet.sk.xml
=> Aktuality.sk

src/chrome/content/rules/GameTechWiki.com.xml
Related issue: https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-576042333.
=> Add GameTechWiki.com.xml

src/chrome/content/rules/AwkwardZombie.com.xml
=> Add AwkwardZombie.com.xml

CONTRIBUTING.md
This will let the url redir to its localized one.
=> Chore: Remove en-US from link in CONTRIBUTING.md

src/chrome/content/rules/Dict.cn.xml
=> Add Rule for Dict.cn

src/chrome/content/rules/Canonical.xml
=> Add bazaar.canonical.com

src/chrome/content/rules/Netlib.org.xml
=> Add Netlib.org.xml

src/chrome/content/rules/Karlsruhe_Institute_of_Technology.xml
=> Add more targets to kit.edu ruleset

src/chrome/content/rules/Engadget.com.xml
=> [engadget.com] Update ruleset

src/chrome/content/rules/cdngc.net.xml
Fixes https://github.com/EFForg/https-everywhere/issues/18889
=> Remove upupgame from cdngc.net.xml

src/chrome/content/rules/Enlightenment.org.xml
=> Add ruleset for enlightenment.org

test/rules/disable-broken-rulesets.checker.config, test/rules/src/https_everywhere_checker/check_rules.py
In relation to #13829 and prep for the pending fetch test, I am updating the check rules code to have proper comments that differentiate if a ruleset was totally turned off or just had targets disabled
Also updated the disabled the check rules config to look for >=TLS1.2
=> Amend check rules python for Fetch Test

src/chrome/content/rules/voxmedia.com-resources.xml
Fixes https://github.com/EFForg/https-everywhere/issues/18897
=> voxmedia.com-resources.xml: Remove dup targets

src/chrome/content/rules/Linux-nfs.org.xml
=> Add Linux-nfs.org.xml

src/chrome/content/rules/Madison-Logic.xml
Fixes https://github.com/EFForg/https-everywhere/issues/18887
=> Madison-Logic.xml: Fix regex replacement group

src/chrome/content/rules/Ecosia.org.xml
Added wildcard to include subdomains and added "ecosia.co" shortlink as it is used periodically on their site.
=> update Ecosia.xml subdomains, short URL

test/rules/checker.config.sample, test/rules/coverage.checker.config, test/rules/http.checker.config, test/rules/manual.checker.config
- #18866 
See also https://wiki.mozilla.org/Release_Management/Calendar
=> Use Tor Browser user agent for fetch tests

src/chrome/content/rules/BBC.com.xml
=> Update BBC.com.xml, fix #19012

src/chrome/content/rules/PiStar.uk.xml
=> Add PiStar.uk.xml

src/chrome/content/rules/ImprovedTube.com.xml
=> Add ImprovedTube.com.xml

src/chrome/content/rules/Cephalofair.com.xml
=> Add Cephalofair.com.xml

src/chrome/content/rules/Devast.io.xml
Related: https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-604142532.
=> Add Devast.io.xml

src/chrome/content/rules/NCStateFair.org.xml
=> Add NCStateFair.org.xml

test/rules/src/https_everywhere_checker/check_rules.py, test/rules/src/https_everywhere_checker/rules.py
- https://github.com/EFForg/https-everywhere/issues/18985
- https://github.com/EFForg/https-everywhere/issues/18986
=> https_everywhere_checker syntax fixes

chromium/background-scripts/background.js
Related: https://github.com/EFForg/https-everywhere/issues/8242#issuecomment-610247779.
=> Exclude localhost subdomains from EASE redirection

src/chrome/content/rules/Panli.com.xml
Related: https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-616368201.
=> Add Panli.com.xml

src/chrome/content/rules/BSD.lv.xml
=> Add BSD.lv.xml

src/chrome/content/rules/SQLiteBrowser.org.xml
=> Add SQLiteBrowser.org.xml

src/chrome/content/rules/GeekGhost.net.xml
=> Add GeekGhost.net.xml

src/chrome/content/rules/Gwern.net.xml
=> Add Gwern.net.xml

src/chrome/content/rules/DeathGenerator.com.xml
=> Add DeathGenerator.com.xml

src/chrome/content/rules/Bepo.fr.xml
=> Add Bepo.fr.xml

src/chrome/content/rules/Telekom.sk.xml
Related issues:  #17965 #12297 
- From https://github.com/EFForg/https-everywhere/pull/18938
=> Telekom.sk.xml: Add missing host mail.telecom.sk

src/chrome/content/rules/PageAbode.com.xml
=> Add PageAbode.com.xml

src/chrome/content/rules/Mastodon.cloud.xml
=> Create mastodon.cloud ruleset

src/chrome/content/rules/RedditSearch.io.xml
=> Add RedditSearch.io.xml

src/chrome/content/rules/DogsbodyTechnologyLtd.xml, src/chrome/content/rules/Dogsbodytechnology.com.xml
=> Update file and contents for DogsbodyTechnology

src/chrome/content/rules/TetherReport.com.xml
=> Add TetherReport.com.xml

src/chrome/content/rules/Neil.brown.name.xml
=> Add Neil.brown.name.xml

src/chrome/content/rules/GloDLS.to.xml
=> Add GloDLS.to.xml

src/chrome/content/rules/tinyimg.io.xml
=> Add tinyimg.io.xml

src/chrome/content/rules/Beeimg.com.xml
Closes #19221
Signed-off-by: Atrate <Atrate@protonmail.com>
=> Create Beeimg.com.xml (closes #19221)

src/chrome/content/rules/Worldometers.info.xml
=> Re-enable Worldometers.info.xml and add more targets

src/chrome/content/rules/Ticketmaster.ae.xml, src/chrome/content/rules/Ticketmaster.at.xml, src/chrome/content/rules/Ticketmaster.be.xml, src/chrome/content/rules/Ticketmaster.ch.xml, src/chrome/content/rules/Ticketmaster.co.nz.xml, src/chrome/content/rules/Ticketmaster.co.uk.xml, src/chrome/content/rules/Ticketmaster.com.au.xml, src/chrome/content/rules/Ticketmaster.com.mx.xml, src/chrome/content/rules/Ticketmaster.cz.xml, src/chrome/content/rules/Ticketmaster.de.xml, src/chrome/content/rules/Ticketmaster.dk.xml, src/chrome/content/rules/Ticketmaster.es.xml, src/chrome/content/rules/Ticketmaster.eu.xml, src/chrome/content/rules/Ticketmaster.fi.xml, src/chrome/content/rules/Ticketmaster.fr.xml, src/chrome/content/rules/Ticketmaster.gr.xml, src/chrome/content/rules/Ticketmaster.ie.xml, src/chrome/content/rules/Ticketmaster.it.xml, src/chrome/content/rules/Ticketmaster.nl.xml, src/chrome/content/rules/Ticketmaster.no.xml, src/chrome/content/rules/Ticketmaster.pl.xml, src/chrome/content/rules/Ticketmaster.se.xml, src/chrome/content/rules/Ticketmaster.xml, src/chrome/content/rules/Ticketweb.co.uk.xml, src/chrome/content/rules/Ticketweb.com.xml
Domain list comes from `www.ticketmaster.dk`. I ran the follow script in the browser console to obtains the list conveniently. I am not very keen on adding all domains for this website though.
```javascript
let elements = document.querySelector(".sc-1qfebe8-0").querySelectorAll("a")
let output = ""
for (const el of elements) {
const href = el.getAttribute("href");
const url = new URL(href);
output = (output + "\n" + url.hostname.substring(4) + "\n" + url.hostname)
}
console.log(output)
```
- #11203
=> Update Ticketmaster related rulesets

src/chrome/content/rules/Oprah.com.xml
Signed-off-by: Atrate <Atrate@protonmail.com>
Closes #19077
=> Create Oprah.com.xml (closes #19077)

src/chrome/content/rules/Kb.se.xml
Closes #19022
Signed-off-by: Atrate <Atrate@protonmail.com>
=> Create Kb.se.xml (closes #19022)

test/tor-browser.sh
Please create a merge commit instead of squashing so acat gets credit for their commit
=> Acat https everywhere

src/chrome/content/rules/Csair.com.xml
Closes #18803
Signed-off-by: Atrate <Atrate@protonmail.com>
=> Create Csair.com.xml (closes #18803)

chromium/background-scripts/background.js
Related PR: #19125
Introduced a bug on EASE checks, patching function reference
=> Fix function reference

src/chrome/content/rules/Wix.xml
=> Add shoutout.wix.com to Wix.xml

src/chrome/content/rules/NFARL.org.xml
=> Add NFARL.org.xml

src/chrome/content/rules/GamerSky.com.xml
=> Add GamerSky.com.xml

src/chrome/content/rules/University_of_California_San_Francisco.xml
Add more subdomains of `ucsf.edu`
=>  Update University_of_California_San_Francisco.xml

src/chrome/content/rules/RC24.xyz.xml
=> Add RC24.xyz.xml

src/chrome/content/rules/technet-cz.xml
Adds redirect rule for technet.cz - one of the idnes.cz subsites
=> Add technet.cz

src/chrome/content/rules/VoDLocker.to.xml
=> Add VoDLocker.to.xml

src/chrome/content/rules/ModTheSims.info.xml
=> Add ModTheSims.info.xml

src/chrome/content/rules/Everything_Everywhere.xml
=> Add myaccount.ee.co.uk to Everything_Everywhere.xml

src/chrome/content/rules/Open.ac.uk.xml
=> Add exclusion to Open.ac.uk.xml

src/chrome/content/rules/Tim.it.xml
=> Add ruleset: Tim.it

src/chrome/content/rules/Asia-Pacific-Network-Information-Centre.xml
Also minor ruleset name change, original source on Wikipedia also updated
=> [apnic.net] Moved wq to active target, added new sub-domains

src/chrome/content/rules/CDTFA.ca.gov.xml
=> Add CDTFA.ca.gov.xml

src/chrome/content/rules/Rowetel.com.xml
=> Add Rowetel.com.xml

chromium/background-scripts/background.js, chromium/pages/popup/ux.js
- #19029, #18760
- fix #19291 
cc @zoracon let's revert the change for the moment.
=> Revert #19029 and #18760

src/chrome/content/rules/Anonymix.io.xml, src/chrome/content/rules/Bitcoin-laundry.com.xml, src/chrome/content/rules/Bitcoinmixer.org.xml, src/chrome/content/rules/Bitmix.biz.xml, src/chrome/content/rules/Blender.io.xml, src/chrome/content/rules/Chipmixer.com.xml, src/chrome/content/rules/Cryptomixer.io.xml, src/chrome/content/rules/Mixtum.io.xml, src/chrome/content/rules/Smartmix.io.xml, src/chrome/content/rules/Smartmixer.io.xml
Adds rules for the following bitcoin mixers:
https://cryptomixer.io
https://mixtum.io
https://smartmix.io
https://bitcoin-laundry.com
https://smartmixer.io
https://bitmix.biz
https://anonymix.io
https://bitcoinmixer.org
https://blender.io
https://chipmixer.com
=> Add 10 bitcoin mixers

src/chrome/content/rules/PhotoPea.com.xml
=> Add PhotoPea.com.xml

src/chrome/content/rules/silego.com.xml
This new ruleset adds rules for silego.com, the store for Dialog Semiconductor GreenPAK integrated circuits.
=> Create silego.com ruleset

chromium/pages/popup/style.css
Lowering mobile cutoff point for min-width at the request of Firefox team for Firefox Preview. This could also help: #19366
=> Hotfix firefox preview ux

src/chrome/content/rules/DartSearch.net.xml, src/chrome/content/rules/GoogleServices.xml
=> Add DartSearch.net.xml

utils/labeller/Dockerfile, utils/labeller/README.md, utils/labeller/index.js, utils/labeller/state_dir/.gitignore, utils/labeller/test.js, utils/labeller/utils.js
Fixing Docker Image for Alexa Labeller
- Fixes references in file
- Fixes issue with overwriting process global in Node
=> Hotfix Alexa Labeller

chromium/package-lock.json, chromium/package.json, utils/trivialize-cdn-rules/package-lock.json
Addresses vulnerabilities from moderate to higher severities
=> NPM Updates

src/chrome/content/rules/gitea.com.xml
=> Add rule for gitea.com

src/chrome/content/rules/tns-cs.net.xml
- Extracted from https://github.com/EFForg/https-everywhere/pull/18957
=> tns-cs.net.xml: Remove non-existent hosts

src/chrome/content/rules/Colocation_America.com.xml
- Extracted from https://github.com/EFForg/https-everywhere/pull/18980
=> Invalid hosts colocation america

src/chrome/content/rules/DMLP.org.xml
- Extracted from https://github.com/EFForg/https-everywhere/pull/18980
=> Too many redirects dmlp

src/chrome/content/rules/yuji.ne.jp.xml
This new ruleset adds rules for [yuji.ne.jp](https://yuji.ne.jp)
=> Create yuji.ne.jp ruleset

CONTRIBUTING.md, test/README.md
#17820
Adding more links & info to ruleset testing and updated Selenium testing language to reflect current UI more
=> README Docs Update: Testing

chromium/.eslintrc.json
See: https://travis-ci.org/github/EFForg/https-everywhere/jobs/722242042; https://travis-ci.org/github/EFForg/https-everywhere/jobs/722242042.
=> Bump ECMAScript version to ES2019 to make ESLint pass

src/chrome/content/rules/Soundcloud.xml
=> Hotfix: remove securecookie tag from Soundcloud.xml

src/chrome/content/rules/TaxChopper.ca.xml
=> Add TaxChopper.ca.xml

src/chrome/content/rules/WSPRnet.org.xml
=> Add WSPRnet.org.xml

src/chrome/content/rules/Tigertronics.com.xml
=> Add Tigertronics.com.xml

src/chrome/content/rules/DaemonPage.com.xml
=> Add DaemonPage.com.xml

src/chrome/content/rules/dof.gob.mx.xml
=> Add dof.gob.mx.xml

edge.sh
=> Hotfix: CRX Edge Script

src/chrome/content/rules/osuosl.org.xml
This was not originally part of #19536, but is related to the same set of PRs
=> Re-enabled nagios2.osuosl.org (works)

src/chrome/content/rules/VE7SCC.org.xml
=> Add VE7SCC.org.xml

src/chrome/content/rules/VPNGate.net.xml
=> Add VPNGate.net.xml

src/chrome/content/rules/VyprVPN.com.xml
=> Add VyprVPN.com.xml

src/chrome/content/rules/strasbourgfestival.com.xml
- pr link
- issue link
***May delete note after reading***
Thank you for contributing! If this is a new ruleset and your first time contributing, congratulations! There will be some tests ran through our continuous integration in Travis. For example, checking for duplicate hosts, problematic hosts, etc. in the ruleset file. You will see this testing begin when you open this pull request.
If this is not your first time and you have open PRs that have not been closed or merged, please revisit them by searching: `https://github.com/EFForg/https-everywhere/issues?q=is%3Aopen+assignee%3A[yourusernamehere]`. If there is something not being addressed by other maintainers or a project lead, link them to the PR with your question. Thank you for your patience. …
=> Add a ruleset for strasbourgfestival.com

src/chrome/content/rules/JanRain.xml, src/chrome/content/rules/JanRainCapture.com.xml
=> Update JanRain.xml related rulesets

src/chrome/content/rules/CityEmail.com.xml, src/chrome/content/rules/CityMail.com.xml, src/chrome/content/rules/Wizard-Internet-Services.xml
=> Rename and update CityEmail.com.xml

test/setup_travis.sh
Closes #19654 
ChromeDriver version needs to be updated:
Info: https://chromedriver.chromium.org/downloads
=> Hotfix: Update Chromedriver

src/chrome/content/rules/Sidibouras.xml
=> Remove Sidibouras.xml

chromium/background-scripts/background.js
Related: #18799, #18020
Persistent error caused by not setting enough checks for proper URL construction and waiting for tab to leave "pending" status.
=> Hotfix: Amend URL Construction Log Error

src/chrome/content/rules/Surfshark.com.xml, src/chrome/content/rules/Whoer.net.xml
- https://github.com/EFForg/https-everywhere/pull/18713
- https://github.com/EFForg/https-everywhere/pull/19550
- https://github.com/EFForg/https-everywhere/pull/19551
- https://github.com/EFForg/https-everywhere/issues/18059
=> Create Rulesets for issue #18059 (Whoer.net.xml & Surfshark.com.xml)

src/chrome/content/rules/9anime.to.xml
=> Add 9anime.to.xml

src/chrome/content/rules/Bitfun.co.xml
=> Add rules for Bitfun.co

src/chrome/content/rules/FireSmoke.ca.xml
=> Add FireSmoke.ca.xml

src/chrome/content/rules/VSIXGallery.com.xml
=> Add VSIXGallery.com.xml

src/chrome/content/rules/AwesomeStuffToBuy.com.xml
=> Add AwesomeStuffToBuy.com.xml

src/chrome/content/rules/InternetX.com.xml
=> Add InternetX.com.xml

src/chrome/content/rules/Nic.bc.ca.xml
=> Add Nic.bc.ca.xml

src/chrome/content/rules/CPlusPlus.com.xml
=> Add CPlusPlus.com.xml

src/chrome/content/rules/Asfar.org.uk, src/chrome/content/rules/Asfar.org.uk.xml
Randomly came across this site
Only the main page redirects http to https
=> Add rules for Asfar.org.uk

src/chrome/content/rules/artefact.org.xml
- pr link
- issue link
***May delete note after reading***
Thank you for contributing! If this is a new ruleset and your first time contributing, congratulations! There will be some tests ran through our continuous integration in Travis. For example, checking for duplicate hosts, problematic hosts, etc. in the ruleset file. You will see this testing begin when you open this pull request.
If this is not your first time and you have open PRs that have not been closed or merged, please revisit them by searching: `https://github.com/EFForg/https-everywhere/issues?q=is%3Aopen+assignee%3A[yourusernamehere]`. If there is something not being addressed by other maintainers or a project lead, link them to the PR with your question. Thank you for your patience. …
=> Add a ruleset for artefact.org

src/chrome/content/rules/molodoi.net.xml
- pr link
- issue link
***May delete note after reading***
Thank you for contributing! If this is a new ruleset and your first time contributing, congratulations! There will be some tests ran through our continuous integration in Travis. For example, checking for duplicate hosts, problematic hosts, etc. in the ruleset file. You will see this testing begin when you open this pull request.
If this is not your first time and you have open PRs that have not been closed or merged, please revisit them by searching: `https://github.com/EFForg/https-everywhere/issues?q=is%3Aopen+assignee%3A[yourusernamehere]`. If there is something not being addressed by other maintainers or a project lead, link them to the PR with your question. Thank you for your patience. …
=> Add a ruleset for molodoi.net

src/chrome/content/rules/Pkcell.com.xml
=> Add Pkcell.com.xml

src/chrome/content/rules/Open_Library.org.xml
=> Update rules for Open Library.org

src/chrome/content/rules/MarginalRevolution.com.xml
=> Add MarginalRevolution.com.xml

src/chrome/content/rules/modulus.com.xml
=> Add modulus.com.xml

src/chrome/content/rules/WilsonTimes.com.xml
=> Add WilsonTimes.com.xml

src/chrome/content/rules/0chan.one.xml
=> Add 0chan.one.xml

src/chrome/content/rules/IndianaCourts.us.xml
=> Add IndianaCourts.us.xml

src/chrome/content/rules/Indeed.co.uk.xml
=> Add Indeed.co.uk.xml

src/chrome/content/rules/cmpxchg8b.com.xml
=> Add cmpxchg8b.com.xml

src/chrome/content/rules/mpg123.org.xml
=> Add mpg123.org.xml

src/chrome/content/rules/SpaceLab.ie.xml
=> Add SpaceLab.ie.xml

src/chrome/content/rules/alsace-lait.com.xml
- pr link
- issue link
***May delete note after reading***
Thank you for contributing! If this is a new ruleset and your first time contributing, congratulations! There will be some tests ran through our continuous integration in Travis. For example, checking for duplicate hosts, problematic hosts, etc. in the ruleset file. You will see this testing begin when you open this pull request.
If this is not your first time and you have open PRs that have not been closed or merged, please revisit them by searching: `https://github.com/EFForg/https-everywhere/issues?q=is%3Aopen+assignee%3A[yourusernamehere]`. If there is something not being addressed by other maintainers or a project lead, link them to the PR with your question. Thank you for your patience. …
=> Add a ruleset for alsace-lait.com

src/chrome/content/rules/nzbget.net.xml
=> Add nzbget.net.xml

src/chrome/content/rules/SmallArmsReview.com.xml
=> Add SmallArmsReview.com.xml

src/chrome/content/rules/Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch.co.uk.xml
I guess this is the longest ruleset name
=> Add rules for Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch.co.uk

src/chrome/content/rules/ICMail.xml
Related to #18949
Website gone since [Dec 2014](https://web.archive.org/web/20141217224626/http://icmail.com/).
=> Remove ICMail.xml

src/chrome/content/rules/CafePharma.com.xml
=> Add CafePharma.com.xml

chromium/pages/popup/index.html, chromium/pages/popup/style.css
Closes #17885
"Reset to Defaults" wipes all local settings, want to make that clear in the UI
=> Move Global Setting for Defaults up in UI

src/chrome/content/rules/TikTok.xml
=> Add TikTok.com.xml

src/chrome/content/rules/HKUST-GZ.edu.cn.xml, src/chrome/content/rules/UST.hk.xml
=> Add HKUST-GZ.edu.cn.xml

src/chrome/content/rules/Cointelegraph.com.xml
=> Add rules for cointelegraph.com

src/chrome/content/rules/Dogpile.com.xml
=> Add Dogpile.com.xml

src/chrome/content/rules/Razzies.com.xml
doesn't automatically redirect
=> Add rules for Razzies.com

src/chrome/content/rules/onepace.net.xml
=> Add onepace.net.xml

src/chrome/content/rules/KYM-CDN.com.xml
Add s.kym-cdn.com and i.kym-cdn.com subdomains and add test urls for the others
=> Update rules for Kym-cdn.com

src/chrome/content/rules/goodweave.org.xml
=> Add goodweave.org

src/chrome/content/rules/banned.video.xml
=> Add banned.video.xml

src/chrome/content/rules/AdvocateAndDemocrat.com.xml
=> Add AdvocateAndDemocrat.com.xml

src/chrome/content/rules/co.cumberland.nc.us.xml
=> Add co.cumberland.nc.us.xml

src/chrome/content/rules/02ch.su.xml
=> Add 02ch.su.xml

src/chrome/content/rules/CounterMail.com.xml
=> Add CounterMail.com.xml

src/chrome/content/rules/msgsafe.io.xml
=> Add msgsafe.io.xml

src/chrome/content/rules/swissnode.ch.xml
=> Add swissnode.ch.xml

src/chrome/content/rules/soverin.net.xml
=> Add soverin.net.xml

src/chrome/content/rules/novo-ordo.com.xml
=> Add novo-ordo.com.xml

src/chrome/content/rules/Intertwingly.net.xml
=> Add rules for Intertwingly.net

chromium/pages/base.css, chromium/pages/options/index.html, chromium/pages/options/style.css
=> Options UI: Adding Responsiveness

chromium/manifest.json
=> Open option page in a new tab

chromium/pages/options/style.css
=> Adjust CSS for Better Alignment in Options UI

test/setup_travis.sh
=> Install the latest geckodriver for firefox

src/chrome/content/rules/gvt1.com.xml
=> Add gvt1.com.xml

src/chrome/content/rules/Fail2ban.org.xml
=> Fail2ban.org.xml: Add missing target

src/chrome/content/rules/skbbank.ru.xml
=> Add ruleset for skbbank.ru

src/chrome/content/rules/coin.space.xml
Enable by default coin.space.xml
=> Enable coin.space.xml

CONTRIBUTING.md
https://github.com/EFForg/https-everywhere/pull/19638
=> Use example.com

utils/trivialize-cdn-rules/index.js
=> Update regex in trivialize-cdn-rules

src/chrome/content/rules/CashTravel.info.xml
=> Add CashTravel.info.xml

utils/labeller/package-lock.json, utils/labeller/package.json
Security Level: High severity
https://github.com/advisories/GHSA-hxcc-f52p-wc94
Fixes #(issue)
=> Update NPM Dependency

src/chrome/content/rules/OMC.net.xml
=> Add OMC.net.xml

src/chrome/content/rules/Radentscheid-frankfurt.de.xml
=> Add radentscheid-frankfurt.de

src/chrome/content/rules/yiwutaro.com.xml
=> Add rules for Yiwutaro.com

src/chrome/content/rules/manning.com.xml
=> manning.com - add enews

src/chrome/content/rules/egl.lv.xml
=> Add egl.lv

src/chrome/content/rules/Idris-lang.org.xml
=> docs.idris-lang.org

src/chrome/content/rules/vizzion.com.xml
=> Add rule for vizzion.com

src/chrome/content/rules/Allegrolokalnie.pl.xml
=> Added rules for allegrolokalnie.pl

src/chrome/content/rules/wolfssl.com.xml
=> Added wolfssl.com

src/chrome/content/rules/thekelleys.org.uk.xml
=> Added thekelleys.org.uk

src/chrome/content/rules/daemonology.net.xml
=> Added daemonology.net

src/chrome/content/rules/softforge.de.xml
=> Added softforge.de

src/chrome/content/rules/dmalloc.com.xml
=> Added dmalloc.com

src/chrome/content/rules/draisberghof.de.xml
=> Added draisberghof.de

src/chrome/content/rules/digip.org.xml
=> Added digip.org

src/chrome/content/rules/French-National-Centre-for-Scientific-Research.xml
=> Added ftp.igh.cnrs.fr

src/chrome/content/rules/XS4ALL.xml
=> Added download.xs4all.nl

src/chrome/content/rules/Chalmers.se.xml
=> Chalmers.se update

src/chrome/content/rules/cyberbits.eu.xml
=> Added cyberbits.eu

src/chrome/content/rules/projectable.me.xml
=> Added projectable.me.xml

src/chrome/content/rules/lwfinger.com.xml
=> Added lwfinger.com

src/chrome/content/rules/openembedded.org.xml
=> Added openembedded.org

chromium/background-scripts/background.js
=> Add missing default values in background.js

src/chrome/content/rules/valgrind.org.xml
=> Added valgrind.org

src/chrome/content/rules/University-of-Strathclyde.xml
University-of-Strathclyde update
=> University-of-Strathclyde update

src/chrome/content/rules/Funet.fi.xml
=> Added more domains to funet.fi

src/chrome/content/rules/scons.org.xml
=> Added scons.org

src/chrome/content/rules/nvaccess.org.xml
=> Added nvaccess.org

src/chrome/content/rules/www.inet.no.xml
=> Added www.inet.no

src/chrome/content/rules/openwall.info.xml
=> Added openwall.info

src/chrome/content/rules/Infradead.org.xml
=> No longer different content on git.infradead.org

src/chrome/content/rules/candelatech.com.xml
=> Added candelatech.com

src/chrome/content/rules/rsbsrt.ru.xml
=> Added rsbsrt.ru

src/chrome/content/rules/RIT.edu.xml
=> Added mirrors.rit.edu

src/chrome/content/rules/S.to.xml
=> Add S.to.xml

src/chrome/content/rules/Naver_Corp.com.xml
=> Added more domains to NaverCorp

src/chrome/content/rules/jaist.ac.jp.xml
=> Added jaist.ac.jp

src/chrome/content/rules/conan.io.xml
https://github.com/conan-io/website/issues/35
=> Add https rule for conan.io

src/chrome/content/rules/SlovakGovernment.xml
=> Business Register SR

src/chrome/content/rules/paralus.co.xml, src/chrome/content/rules/pylos.co.xml
=> add paralus.co ruleset

src/chrome/content/rules/Umsmash.com.xml
=> Add rules for Umsmash.com

src/chrome/content/rules/www.tecgraf.puc-rio.br.xml
=> Added www.tecgraf.puc-rio.br

src/chrome/content/rules/cogentco.com.xml
=> Added cogentco.com

src/chrome/content/rules/Telefonica.xml
=> fix O2/Telefonica rules

src/chrome/content/rules/phys.org.xml
=> add physorg.com

src/chrome/content/rules/FreeBSoft.org.xml
=> Added devel.freebsoft.org and www.freebsoft.org

src/chrome/content/rules/SF.net.xml
=> Added git.code.sf.net and svn.code.sf.net

src/chrome/content/rules/Netfilter.org.xml
=> ipset.netfilter.org is no longer nonfunctional
