src/chrome/content/rules/mosoblgaz.ru.xml

mosoblgaz.ru

---

src/chrome/content/rules/coin.space.xml

coin.space

---

src/chrome/content/rules/bitcoinknots.org.xml

bitcoinknots.org

---

src/chrome/content/rules/bitcoinchain.com.xml

bitcoinchain.com

---

src/chrome/content/rules/refugee.ru.xml

refugee.ru

---

src/chrome/content/rules/republic.ru.xml

republic.ru

---

src/chrome/content/rules/112-akersloot.nl.xml
src/chrome/content/rules/112-uitgeest.nl.xml

Adding two local news sites to the list.
They use an Let's Encrypt SSL certficate.

Adding 112-uitgeest.nl and 112-akersloot.nl

---

src/chrome/content/rules/Marketwatch.com.xml

Update Marketwatch.com.xml, Fix #8123

---

src/chrome/content/rules/Icio.us.xml

Update icio.us with del.icio.us fix

---

src/chrome/content/rules/samaratoday.ru.xml

samaratoday.ru

---

src/chrome/content/rules/prokopievsk.ru.xml

prokopievsk.ru

---

src/chrome/content/rules/opensocietyfoundations.org.xml

opensocietyfoundations.org

---

src/chrome/content/rules/fitchratings.ru.xml

fitchratings.ru

---

src/chrome/content/rules/matchtv.ru.xml

matchtv.ru

---

src/chrome/content/rules/tnwcdn.com.xml

tnwcdn.com

---

src/chrome/content/rules/Google_App_Engine.xml

*.appspot.com not includes *.*.appspot.com

---

src/chrome/content/rules/gitignore.io.xml

gitignore.io

---

src/chrome/content/rules/gruntjs.com.xml

gruntjs.com

---

src/chrome/content/rules/Ooyala.xml

Add api.ooyala.com to Ooyala.xml

---

src/chrome/content/rules/Geany.org.xml

[Geany.org] Add subdomains and remove platform

---

src/chrome/content/rules/clahub.com.xml

clahub.com

---

src/chrome/content/rules/Reuters.com.xml
src/chrome/content/rules/Thomson-Reuters-mismatches.xml

- move s1-4 .reutersmedia.net to the working hosts

Reuters.com:

---

src/chrome/content/rules/Dotomi.xml

- add media.msg subdomain
- update coding style
- add comment about another broken subdomain
- remove squarespace redirect, account no longer active

Dotomi updates

---

src/chrome/content/rules/Sanoma.fi.xml

Sanoma.fi:

---

src/chrome/content/rules/360_Yield.xml

- remove wildcard
-  clean up the comments

360_Yield:

---

src/chrome/content/rules/Lavabit.xml

On inauguration day Lavabit came back to life.

re-enable Lavabit rule

---

src/chrome/content/rules/Nicovideo.jp.xml
src/chrome/content/rules/Nimg.jp.xml
src/chrome/content/rules/Simg.jp.xml

Added `nimg.jp` and `simg.jp`.

Update NicoVideo.jp related ruleset

---

src/chrome/content/rules/mycelium.com.xml

mycelium.com

---

src/chrome/content/rules/esnextb.in.xml

esnextb.in

---

src/chrome/content/rules/Tribecastudios.co.uk.xml

Just a local gym. I didn't notice any mixed-content warnings etc. when signing into my account, booking a session, and generally poking around the site.

Add Tribecastudios.co.uk.xml

---

src/chrome/content/rules/kommersant.ru.xml

kommersant.ru

---

src/chrome/content/rules/lkk-zkh.ru.xml

lkk-zkh.ru

---

utils/downgrade-whitelist.txt

clean up downgrade-whitelist.txt

---

src/chrome/content/rules/BlackArch.org.xml

Related: https://github.com/EFForg/https-everywhere/issues/3069#issue-111248804

Re-enable and Update BlackArch.org.xml

---

src/chrome/content/rules/lyngsat.com.xml

lyngsat.com

---

src/chrome/content/rules/admtyumen.ru.xml

admtyumen.ru

---

src/chrome/content/rules/inforos.ru.xml

inforos.ru

---

src/chrome/content/rules/idelreal.org.xml

idelreal.org

---

src/chrome/content/rules/mp3scene.info.xml

mp3scene.info

---

src/chrome/content/rules/arifmetika-dobra.ru.xml

arifmetika-dobra.ru

---

src/chrome/content/rules/leader-id.ru.xml

leader-id.ru

---

src/chrome/content/rules/infoculture.ru.xml

infoculture.ru

---

src/chrome/content/rules/clearspending.ru.xml

clearspending.ru

---

src/chrome/content/rules/ekovolga.com.xml

ekovolga.com

---

src/chrome/content/rules/moodys.com.xml

moodys.com

---

src/chrome/content/rules/therunet.com.xml

therunet.com

---

src/chrome/content/rules/novayagazeta.ru.xml

novayagazeta.ru

---

src/chrome/content/rules/razor1911.com.xml

razor1911.com

---

src/chrome/content/rules/rostrud.ru.xml

rostrud.ru

---

src/chrome/content/rules/defacto2.net.xml

defacto2.net

---

src/chrome/content/rules/karusel-tv.ru.xml

karusel-tv.ru

---

utils/labeller/index.js

new-ruleset labeller

---

src/chrome/content/rules/hkqf.gov.hk.xml

New ruleset for [Hong Kong Qualifications Framework (HKQF)](http://www.hkqf.gov.hk)

[hkqf.gov.hk] New ruleset

---

src/chrome/content/rules/civitas.ru.xml

civitas.ru

---

src/chrome/content/rules/smart-soft.ru.xml

smart-soft.ru

---

src/chrome/content/rules/imercer.com.xml

imercer.com

---

src/chrome/content/rules/bither.net.xml

bither.net

---

src/chrome/content/rules/airbitz.co.xml

airbitz.co

---

src/chrome/content/rules/xn--90aijkdmaud0d.xn--p1ai.xml

xn--90aijkdmaud0d.xn--p1ai

---

src/chrome/content/rules/Akamai.xml

eg http://www.ausopen.com/en_AU/video/index.html?tabName=highlights_videos

Akamai: fix video playback on ausopen.com

---

src/chrome/content/rules/Politico.xml
src/chrome/content/rules/Politico_Pro.com.xml

Hi, I'm an Developer at Politico and [jahnatpolitico](https://github.com/jahnatpolitico) is on vacation right now.
I've made the changes you requested in this PR: https://github.com/EFForg/https-everywhere/pull/9361

Change the default_off text to webmaster request

---

src/chrome/content/rules/Team_UNICEF.org.xml
src/chrome/content/rules/UNICEF.org.nz.xml
src/chrome/content/rules/UNICEF.org.xml

Create Team_UNICEF.org.xml and UNICEF.org.nz.xml

---

src/chrome/content/rules/rosminzdrav.ru.xml

rosminzdrav.ru

---

src/chrome/content/rules/genotek.ru.xml

genotek.ru

---

src/chrome/content/rules/civil-forum.ru.xml

civil-forum.ru

---

src/chrome/content/rules/premiagi.ru.xml

premiagi.ru

---

src/chrome/content/rules/parlamentri.ru.xml

parlamentri.ru

---

src/chrome/content/rules/konsumentverket.se.xml

This is the website for the Swedish government agency Konsumentverket.
It has forms where you submit personal information, among other things.

Add konsumentverket.se

---

src/chrome/content/rules/lgbtnet.org.xml

lgbtnet.org

---

src/chrome/content/rules/scnsrc.net.xml

scnsrc.net

---

src/chrome/content/rules/WWF.ch.xml
src/chrome/content/rules/WWF.or.jp.xml
src/chrome/content/rules/WWF.org.xml
src/chrome/content/rules/WorldWildlife.org.xml

This PR overwrite #9559, #9558, #9557 and is ready for review. thanks.

Update WorldWildlife.org related rulesets

---

src/chrome/content/rules/ABC_News.xml

Reported in https://github.com/EFForg/https-everywhere/issues/7659

ABC_News.xml default breaks site

---

src/chrome/content/rules/Sciencemag.org.xml

The cert chain has been fixed.
I know I could optimize those regexes but I am not sure what the style guide recommends in this case.
PS: sorry about the terrible commits names, I always click too fast...

Update and reactivate Sciencemag.org.xml

---

src/chrome/content/rules/volistob.ru.xml

volistob.ru

---

src/chrome/content/rules/Anonbox.net.xml

[Anonbox.net] Update subdomains and remove platform

---

src/chrome/content/rules/Cypouz.com.xml

[Cypouz.com] Update subdomains and remove platform

---

src/chrome/content/rules/Golf_Digest.xml

This is a re-open of #9527 because there was too many involuntary changes on many files. This close #9488 as well. thanks.
Remark: I did not perform a domain enumeration for `golfdigestinsiders.com` because my intention is to fix the aforementioned issue only.

Update Golf_Digest.xml, Re-open #9527, Fix #9488

---

src/chrome/content/rules/artvillage.club.xml

artvillage.club

---

src/chrome/content/rules/apus.agency.xml

apus.agency

---

src/chrome/content/rules/Live.xml

Remove ^login.live.com from Live.xml securecookie

---

src/chrome/content/rules/1823.gov.hk.xml

New ruleset for [1823 Online](http://www.1823.gov.hk)

[1823.gov.hk] New ruleset

---

src/chrome/content/rules/GovHK.xml
src/chrome/content/rules/HKGov-AFCD.xml
src/chrome/content/rules/HKGov-ArchSD.xml
src/chrome/content/rules/HKGov-HKMA.xml
src/chrome/content/rules/HKGov-HYD.xml
src/chrome/content/rules/HKGov-HousingAuth.xml
src/chrome/content/rules/HKGov-ITF.xml
src/chrome/content/rules/HKGov-LAD.xml
src/chrome/content/rules/HKGov-LCSD.xml
src/chrome/content/rules/HKGov-TID.xml
src/chrome/content/rules/data.gov.hk.xml
src/chrome/content/rules/heritage.gov.hk.xml
src/chrome/content/rules/hkpl.gov.hk.xml
src/chrome/content/rules/hkqf.gov.hk.xml
src/chrome/content/rules/hongkongpost.gov.hk.xml
src/chrome/content/rules/jobs.gov.hk.xml
src/chrome/content/rules/voterinfo.gov.hk.xml

HKSAR portal (GovHK) finally supports HTTPS 🇭🇰

[gov.hk] New ruleset

---

src/chrome/content/rules/148apps.com.xml

Create rule for 148apps

---

src/chrome/content/rules/Toolslib.net.xml

Add https://toolslib.net domains redirection.

Add ToolsLib rule

---

src/chrome/content/rules/hongkongairport.com.xml

New ruleset for [Hong Kong International Airport](https://www.hongkongairport.com)

[hongkongairport.com] New ruleset

---

src/chrome/content/rules/flypeach.com.xml

New ruleset for [Peach Aviation](https://www.flypeach.com)

[flypeach.com] New ruleset

---

src/chrome/content/rules/hkexpress.com.xml

New ruleset for [HK Express](https://www.hkexpress.com)

[hkexpress.com] New ruleset

---

src/chrome/content/rules/polymus.ru.xml

polymus.ru

---

src/chrome/content/rules/astrobl.ru.xml

astrobl.ru

---

src/chrome/content/rules/permkrai.ru.xml

permkrai.ru

---

src/chrome/content/rules/krasnodar.ru.xml

krasnodar.ru

---

src/chrome/content/rules/belregion.ru.xml

belregion.ru

---

src/chrome/content/rules/khabkrai.ru.xml

khabkrai.ru

---

src/chrome/content/rules/krskstate.ru.xml

krskstate.ru

---

src/chrome/content/rules/demozoo.org.xml

demozoo.org

---

src/chrome/content/rules/roysac.com.xml

roysac.com

---

src/chrome/content/rules/gov-murman.ru.xml

gov-murman.ru

---

src/chrome/content/rules/government-nnov.ru.xml

government-nnov.ru

---

src/chrome/content/rules/bit-hdtv.com.xml

bit-hdtv.com

---

src/chrome/content/rules/TIME.com.xml

Update Time.com.xml, Fix #8887

---

src/chrome/content/rules/Viu.com.xml

New ruleset for [Viu](https://www.viu.com)

[viu.com] New ruleset

---

src/chrome/content/rules/Videogamer.com.xml

Create rule for Videogamer

---

src/chrome/content/rules/Wza.us.xml

[Wza.us] Update subdomains and remove platform

---

src/chrome/content/rules/netams.com.xml

netams.com

---

src/chrome/content/rules/Testyourmight.com.xml

Create rule for Testyourmight

---

src/chrome/content/rules/Freshapps.com.xml

Create rule for freshapps

---

src/chrome/content/rules/keenetic.net.xml

keenetic.net

---

src/chrome/content/rules/Touchgen.net.xml

Create Touchgen.com.xml. Site contains MCB, used a test URL of the site's logo.

Create rule for Touchgen

---

src/chrome/content/rules/sciencedirect.com.xml

Major parts of the website have mixed content. I think this option is safer than exclusions.

[ScienceDirect.com] Update subdomains and add platform (fix #9689)

---

src/chrome/content/rules/Sci-hub.xml

I found test urls for subdomains previously listed under `No working URL known`.

[Sci-hub] Add subdomains

---

src/chrome/content/rules/Yabause.org.xml

Re-activate and Update Yabause.org.xml

---

src/chrome/content/rules/CrossWire.org.xml

Re-activate and Update CrossWire.org.xml

---

src/chrome/content/rules/GovHK.xml
src/chrome/content/rules/hee.gov.hk.xml

New ruleset for [Higher Education Employment Information e-Platform](https://www.hee.gov.hk)

[hee.gov.hk] New ruleset

---

src/chrome/content/rules/GovHK.xml
src/chrome/content/rules/HKGov-NEWS.xml

New ruleset for [news.gov.hk](https://www.news.gov.hk)

[news.gov.hk] New ruleset

---

src/chrome/content/rules/1823.gov.hk.xml
src/chrome/content/rules/GovHK.xml
src/chrome/content/rules/hkwetlandpark.xml

Add subdomain related to the [GovHK](https://www.gov.hk) portal

[gov.hk] Update ruleset

---

src/chrome/content/rules/GovHK.xml
src/chrome/content/rules/HKGov-DEVB.xml

New ruleset for [Development Bureau (HKSARG)](https://www.devb.gov.hk)

[devb.gov.hk] New ruleset

---

src/chrome/content/rules/C-Base.org.xml
src/chrome/content/rules/C-Base.xml

Rename and Update C-Base.org.xml

---

src/chrome/content/rules/Mersenne.org.xml

Re-activate and Update Mersenne.org.xml

---

src/chrome/content/rules/Calameo.com.xml
src/chrome/content/rules/Calameoassets.com.xml

Re-activate and Update Calameo.com.xml

---

src/chrome/content/rules/Necessary_and_Proportionate.org.xml

[NecessaryAndProportionate.net] Update and rename ruleset

---

src/chrome/content/rules/GratiSoft.us.xml

[GratiSoft.us] Update and reactivate ruleset

---

src/chrome/content/rules/dinglisch.net.xml

Update dinglisch.net.xml (cosmetic)

---

src/chrome/content/rules/Merkur.de.xml

This is a very minor change to complete #6525 .

Mark jobs.merkur.de as "Refused"

---

src/chrome/content/rules/SPU.ac.th.xml
src/chrome/content/rules/Spu.ac.th.xml

Re-activate and Update SPU.ac.th.xml

---

src/chrome/content/rules/JPGmag.xml

[JPGmag.com] Update and reactivate ruleset

---

src/chrome/content/rules/Imperial-College-London-Union.xml

Re-activate and Update Imperial-College-London-Union.xml

---

src/chrome/content/rules/Replicant.us.xml

[Replicant.us] Update and reactivate ruleset

---

src/chrome/content/rules/FAU.org.xml

[FAU.org] Update and reactivate ruleset

---

src/chrome/content/rules/Pocketgamer.co.uk.xml

Create rule for Pocketgamer

---

src/chrome/content/rules/Selectricity.xml

Re-activate and Update Selectricity.xml

---

src/chrome/content/rules/VDownloader.xml

[VDownloader.es] Update rewrite rule

---

src/chrome/content/rules/EFF.xml

Update list of EFF rulesets

---

src/chrome/content/rules/CoinJabber.com.xml

[CoinJabber.com] Reactivate ruleset

---

src/chrome/content/rules/Offog.org.xml

Re-activate and Update Offog.org.xml

---

src/chrome/content/rules/Geekzone.xml

Adding geekzone.co.nz subdomains cdn, images, avatar

Adding geekzone.co.nz CDN

---

src/chrome/content/rules/Theiphonemom.com.xml

Create rule for Iphonemom

---

src/chrome/content/rules/Iphoneblog.de.xml

Create rule for iphoneblog

---

src/chrome/content/rules/Appolicious.com.xml

Create rule for appolicious

---

src/chrome/content/rules/Bluesnews.com.xml

Create rule for Bluesnews

---

src/chrome/content/rules/Controllerpro.com.xml

Create Controllerpro.com.xml. The site does not seem to have any non-functional hosts.

Create rule for controllerpro

---

src/chrome/content/rules/hydra-billing.com.xml

hydra-billing.com

---

src/chrome/content/rules/GiNaC.de.xml

Related: #9842 Pending until #10046

Re-activate and Update GiNaC.de.xml

---

src/chrome/content/rules/stoloto.ru.xml

stoloto.ru

---

src/chrome/content/rules/Arma3.com.xml

Re-activate and Update Arma3.com.xml

---

src/chrome/content/rules/DevConf.cz.xml

Re-activate and Update DevConf.cz.xml

---

src/chrome/content/rules/Dark_Reading.com.xml

Re-activate and Update Dark_Reading.com.xml

---

src/chrome/content/rules/Atarnotes.com.xml

Suggested labels: `top-100k`, `new-ruleset`

Added rules for atarnotes.com.

---

src/chrome/content/rules/Shoryuken.com.xml

Create rule for Shoryuken

---

src/chrome/content/rules/Gamegeek-denter.de.xml

Create rule for gamegeek-denter

---

src/chrome/content/rules/Gameselectors.com.xml

Create Gameselectors.com.xml. No nonfunctional hosts for the time being.

Create rule for gameselectors

---

src/chrome/content/rules/Gamewithyourbrain.com.xml

Create Gamewithyourbrain.com.xml. No nonfunctional hosts.

Create rule for gamewithyourbrain

---

src/chrome/content/rules/Howinerd.com.xml

Create Howinerd.com.xml. No nonfunctional hosts.

Create rule for howinerd

---

src/chrome/content/rules/Macobserver.com.xml

Create rule for Macobserver

---

src/chrome/content/rules/Appadvice.com.xml

Create Appadvice.com.xml. Multiple targets handled, quite a few nonfunctional hosts. Tried to list as many as possible.

Create rule for Appadvice

---

src/chrome/content/rules/Cultofmac.com.xml

Create Cultofmac.com.xml. Multiple targets and nonfunctional hosts.

Create rule for Cultofmac

---

src/chrome/content/rules/Iphoneincanada.ca.xml

Create rule for Iphoneincanada

---

src/chrome/content/rules/Iphonelife.com.xml

Create rule for Iphonelife

---

src/chrome/content/rules/ReadCube.com.xml

Work in progress, I still need to go through all those `No working URL known` and see if I can find a valid test URL.

[ReadCube.com] Remove wildcard and increase coverage

---

src/chrome/content/rules/AdF.ly.xml

Re-activate and Update AdF.ly.xml

---

src/chrome/content/rules/Mpagano.com.xml

[Mpagano.com] Update and reactivate ruleset

---

src/chrome/content/rules/Diygadget.com.xml

[Diygadget.com] Reactivate ruleset

---

src/chrome/content/rules/receivesmsonline.net.xml

receivesmsonline.net

---

src/chrome/content/rules/smsreceiveonline.com.xml

smsreceiveonline.com

---

src/chrome/content/rules/receivefreesms.net.xml

receivefreesms.net

---

src/chrome/content/rules/ireceivesmsonline.com.xml

ireceivesmsonline.com

---

src/chrome/content/rules/justdelete.me.xml

justdelete.me

---

src/chrome/content/rules/receive-a-sms.com.xml

receive-a-sms.com

---

src/chrome/content/rules/proovl.com.xml

proovl.com

---

src/chrome/content/rules/sms-online.co.xml

sms-online.co

---

src/chrome/content/rules/HackLab.to.xml

[HackLab.to] Update and reactivate ruleset

---

src/chrome/content/rules/groovl.com.xml

groovl.com

---

src/chrome/content/rules/softline.ru.xml

softline.ru

---

src/chrome/content/rules/Ugly_Mugs.ie.xml

Re-activate and Update Ugly_Mugs.ie.xml

---

src/chrome/content/rules/North_Devon_Theatres.org.uk.xml

Re-activate and Update North_Devon_Theatres.org.uk.xml

---

src/chrome/content/rules/Axel_Simon.net.xml

Re-activate and Update Axel_Simon.net.xml

---

src/chrome/content/rules/RDot.org.xml

Re-activate and Update RDot.org.xml

---

src/chrome/content/rules/Pingability.com.xml

[Pingability.com] Update and reactivate ruleset

---

src/chrome/content/rules/Techmeme.com.xml

Re-activate and Update Techmeme.com.xml

---

src/chrome/content/rules/Cloudfront.xml

@J0WI do you mind help merging this? This close #10274 related to #9488 
P.S. Maybe this should be scheduled for the next release in #10186.

Update Cloudfront.xml, Fix #10274

---

src/chrome/content/rules/Dezeen.com.xml

Re-activate and Update Dezeen.com.xml

---

src/chrome/content/rules/viu.tv.xml

New ruleset for [ViuTV](https://www.viu.tv)

[viu.tv] New ruleset

---

src/chrome/content/rules/Sidux-ev.org.xml

[Sidux-ev.org] Reactivate ruleset

---

src/chrome/content/rules/ddos-guard.net.xml

ddos-guard.net

---

src/chrome/content/rules/Mirt.net.xml

Re-activate and Update Mirt.net.xml

---

src/chrome/content/rules/wyreforestdc.gov.uk.xml

Re-activate and Update wyreforestdc.gov.uk.xml

---

src/chrome/content/rules/Voice.fi.xml

Re-activate and Update Voice.fi.xml

---

src/chrome/content/rules/XE.com.xml

@jeremyn I added some coverage of working paths for `www` and `community` here. Are you still interested in reviewing this? #10160

Add complicated rule for 'www.xe.com' and 'community.xe.com'

---

src/chrome/content/rules/Leo.org.xml

`Sublist3r` finds more subdomains but I couldn't find any working url so I didn't include them.

[Leo.org] Remove wildcard

---

src/chrome/content/rules/Freesound.org.xml

I don't have a test url for https://test.freesound.org/ but it was already there so I am assuming it is working.

[Freesound.org] Add subdomains

---

src/chrome/content/rules/msu.edu.xml

#9906 Partial sub-domain enumeration is performed, which produce a 300+ line ruleset I would like to avoid. Only a relatively small portion of sub-domains are included.

Re-activate and Update msu.edu.xml

---

src/chrome/content/rules/Websterwood.com.xml

[Websterwood.com] Remove wildcard, platform and reactivate ruleset

---

src/chrome/content/rules/Rejseplanen.dk.xml

Re-activate and Update Rejseplanen.dk.xml

---

src/chrome/content/rules/CCA.edu.xml
src/chrome/content/rules/Vault.cca.edu.xml

#9842 California College of the Arts

Re-activate, Rename and Update CCA.edu.xml

---

src/chrome/content/rules/kirpich-ors.ru.xml

kirpich-ors.ru

---

src/chrome/content/rules/allepizza.ru.xml

allepizza.ru

---

src/chrome/content/rules/Visaplace.com.xml

Added a ruleset for VisaPlace.com

Created ruleset for VisaPlace.com

---

src/chrome/content/rules/Daft.ie.xml

Re-activate and Update Daft.ie.xml

---

src/chrome/content/rules/US_Cyber_Challenge.org.xml
src/chrome/content/rules/Us_Cyber_Challenge.xml

Re-activate, Rename and Update US_Cyber_Challenge.org.xml

---

src/chrome/content/rules/UrlQuery.xml
src/chrome/content/rules/urlQuery.net.xml

Re-activate, Rename and Update urlQuery.net.xml

---

src/chrome/content/rules/DayZ.com.xml

Re-activate and Update DayZ.com.xml

---

src/chrome/content/rules/Planet-Source-Code.com.xml

[Planet-Source-Code.com] Update and reactivate ruleset

---

src/chrome/content/rules/C9x.me.xml

Hi, I own the domain and wanted to add it to your ruleset.
Thanks!

Add c9x.me

---

src/chrome/content/rules/PCWorld.xml

Re-activate and Update PCWorld.xml

---

src/chrome/content/rules/Flinq.de.xml

Re-activate and Update Flinq.de.xml

---

src/chrome/content/rules/Nruns.com.xml

Re-activate, Rename and Update Nruns.com.xml

---

src/chrome/content/rules/HTC.com.xml
src/chrome/content/rules/HTC.xml

Re-activate, Rename and Update HTC.com.xml

---

src/chrome/content/rules/burgerking.ru.xml

burgerking.ru

---

src/chrome/content/rules/OkCDN.com.xml
src/chrome/content/rules/OkCupid.xml

Re-activate and Update OkCupid.xml and OkCDN.com.xml

---

src/chrome/content/rules/Now.com.xml

New ruleset for [Now.com](https://www.now.com)

[now.com] New ruleset

---

src/chrome/content/rules/WeChat.xml

Re-activate and Update WeChat.xml

---

src/chrome/content/rules/Mercatus-Center.xml

Re-activate and Update Mercatus-Center.xml

---

src/chrome/content/rules/StanDeyo.xml
src/chrome/content/rules/Stan_Deyo.com.xml

Update and rename StanDeyo.xml to Stan_Deyo.com.xml

---

src/chrome/content/rules/biglion.ru.xml

biglion.ru

---

src/chrome/content/rules/citilink.ru.xml

citilink.ru

---

src/chrome/content/rules/sportmaster.ru.xml

sportmaster.ru

---

docs/es/faq.md

Add FAQ fully translated to Spanish.
Issue: https://github.com/EFForg/https-everywhere/issues/9631

Translation of the FAQ to Spanish

---

src/chrome/content/rules/domofond.ru.xml

domofond.ru

---

src/chrome/content/rules/lifehacker.ru.xml

lifehacker.ru

---

src/chrome/content/rules/sevenforums.com.xml

sevenforums.com

---

src/chrome/content/rules/rsload.net.xml

rsload.net

---

src/chrome/content/rules/Avropa.se.xml

 	Re-activate and Update Avropa.se.xml 

---

src/chrome/content/rules/WordPress-blogs.xml

I will keep working on the split but I wanted to do that first to have a clearer view of what really needs to be updated.

[WordPress-blogs] Remove broken targets

---

src/chrome/content/rules/domainer.ru.xml

domainer.ru

---

src/chrome/content/rules/9gag.com.xml

Re-activate and Update 9gag.com.xml

---

src/chrome/content/rules/ust.hk.xml

Re-activate and Update ust.hk.xml

---

src/chrome/content/rules/free-torrents.org.xml

free-torrents.org

---

src/chrome/content/rules/cdnvideo.ru.xml

cdnvideo.ru

---

src/chrome/content/rules/chipdip.ru.xml

chipdip.ru

---

src/chrome/content/rules/radiokot.ru.xml

radiokot.ru

---

src/chrome/content/rules/PopAds.xml

Re-activate and Update PopAds.xml

---

src/chrome/content/rules/PayPal.xml

Re-activate and Update PayPal.xml

---

src/chrome/content/rules/YouTube.xml

I am assuming the time out is temporary and the subdomain is eventually going to be fixed.

[Youtube] Reactivate ruleset

---

src/chrome/content/rules/Twitch.tv.xml

Re-activate and Update Twitch.tv.xml, Fix #4916

---

src/chrome/content/rules/Crypton.io.xml

[Crypton.io] Update and reactivate ruleset

---

src/chrome/content/rules/Hao123.xml
src/chrome/content/rules/hao123.com-mixedcontent.xml

Reactivate hao123.com-mixedcontent.xml

---

src/chrome/content/rules/LinkedIn.xml

Reactivate LinkedIn.xml

---

src/chrome/content/rules/Live.xml

Reactivate Live.xml

---

src/chrome/content/rules/BBC.xml

Reactivate BBC.xml

---

src/chrome/content/rules/Mail.ru.xml

Reactivate Mail.ru.xml

---

src/chrome/content/rules/ThePirateBay.xml
src/chrome/content/rules/proxybay.pl.xml
src/chrome/content/rules/thepiratebay-proxylist.org.xml

Re-activate and Update ThePirateBay related rulesets

---

src/chrome/content/rules/westbyte.com.xml

westbyte.com

---

src/chrome/content/rules/dimonvideo.ru.xml

dimonvideo.ru

---

src/chrome/content/rules/mydigitallife.net.xml

mydigitallife.net

---

src/chrome/content/rules/allnokia.ru.xml

allnokia.ru

---

src/chrome/content/rules/Start.me.xml

Re-activate and Update Start.me.xml

---

src/chrome/content/rules/Smart-AdServer.xml

- add multiple new subdomains for smartadserver.com & sascdn.com

Smart-AdServer:

---

src/chrome/content/rules/Apple.com.xml

Re-activate and Update Apple.com.xml

---

src/chrome/content/rules/vasexperts.ru.xml

vasexperts.ru

---

src/chrome/content/rules/svyaznoy.ru.xml

svyaznoy.ru

---

src/chrome/content/rules/Adentifi.com.xml

 	Re-activate and Update Adentifi.com.xml 

---

src/chrome/content/rules/Alipay.com.xml

#10545 ~`cshall`, `my` and `openhome` WFM but failed on Travis for unknown reason. Possibly some targets are `only-available-in-china`.~
~P.S. I cannot confirm this because I am outside of the GFW.~

Re-activate and Update Alipay.com.xml

---

src/chrome/content/rules/Reuters.com.xml

Expand a Reuters.com ruleset

---

src/chrome/content/rules/ThomasCook.xml
src/chrome/content/rules/Thomas_Cook.com.xml

#9906 only some obvious sub-domains are covered.

Re-activate, Rename and Update Thomas_Cook.com.xml

---

src/chrome/content/rules/104.com.tw.xml

Reenable 104.com.tw.xml

---

src/chrome/content/rules/Instagram.xml

Re-activate and Update Instagram.xml

---

src/chrome/content/rules/South_China_Morning_Post.xml

Re-activate and Update South_China_Morning_Post.xml

---

src/chrome/content/rules/Vancity.xml

- Added targets for `myvisaapplication.com` and `myvisarewardsplus.com`.
- Sorted all targets alphabetically.

[Vancity] Add new targets

---

src/chrome/content/rules/Stack-Exchange.xml

[Stack-exchange] Simplify ruleset

---

src/chrome/content/rules/ASUS.xml

Reenable ASUS.xml

---

src/chrome/content/rules/CodePen.io.xml

Re-activate and Update CodePen.io.xml

---

src/chrome/content/rules/BuzzFeed.xml

#10782 sub-domain enumeration is not performed.

Re-activate and Update BuzzFeed.xml

---

src/chrome/content/rules/Exoclick.xml

Re-activate and Update Exoclick.xml

---

src/chrome/content/rules/Simply_Technology.net.xml

no sub-domain enumeration is performed

Update Simply_Technology.net.xml, Fix Problematic Rewrite

---

src/chrome/content/rules/Billy_Creative.xml

Re-activate and Update Billy_Creative.xml

---

src/chrome/content/rules/Nimg.jp.xml

Possibly #10536 since it is related to `nicovideo.jp` which is a `alexa-top-112.`

Update Nimg.jp.xml, Fix #10674

---

src/chrome/content/rules/Douban.com.xml

Re-activate and Update Douban.com.xml

---

src/chrome/content/rules/Doublepimp.xml

Re-activate and Update Doublepimp.xml

---

src/chrome/content/rules/Magento.xml
src/chrome/content/rules/Magento_Commerce.com.xml

Update Magento.com related rulesets

---

src/chrome/content/rules/Bbcshop.com.xml
src/chrome/content/rules/Deakin-University.xml
src/chrome/content/rules/Extreme_Digital.xml
src/chrome/content/rules/Perl-Foundation.xml
src/chrome/content/rules/PodOmatic.com.xml
src/chrome/content/rules/Securities.com.xml
src/chrome/content/rules/University_of_Georgia.xml
src/chrome/content/rules/beersofeurope.co.uk.xml
src/chrome/content/rules/videos.toypics.net.xml

Trivialize direct rewrite rules (platform)

---

src/chrome/content/rules/RoboForm.com.xml

[RoboForm.com] Add more subdomains

---

src/chrome/content/rules/MedicineNet.com.xml

Re-activate and Update MedicineNet.com.xml

---

src/chrome/content/rules/Viu.com.xml

[viu.com] Re-activate and update ruleset

---

src/chrome/content/rules/Reevoo.xml

- http://mark.reevoo.it
- http://mark.reevoo.es
are for sale
- http://mark.reevoo.nl
is unreachable

[Reevoo] Remove right and left wildcards

---

src/chrome/content/rules/GovHK.xml
src/chrome/content/rules/brandhk.gov.hk.xml

New ruleset for [Brand Hong Kong](http://www.brandhk.gov.hk)

[brandhk.gov.hk] New ruleset

---

README.md

Hello @EFForg, :smiley:
I edit the `README.md` file. :pencil:
*Cheers,*
[**Suriyaa**](https://github.com/SuriyaaKudoIsc)

Add title link in README.md

---

src/chrome/content/rules/Fundinfo.com-falsemixed.xml
src/chrome/content/rules/GameSpot.com-falsemixed.xml
src/chrome/content/rules/Intel.com-falsemixed.xml
src/chrome/content/rules/Npmawesome.com-falsemixed.xml
src/chrome/content/rules/SigFig.com-falsemixed.xml
src/chrome/content/rules/Thing.net-falsemixed.xml

Similar to #10872, by _linked_ I mean that the string `.xml` exist in the ruleset. 
https://github.com/cschanaj/covfefe/blob/master/src/TrivializeSimpleRules.go#L43
```golang
if strings.Contains(string(xmlFile), ".xml") == false {
continue
}
```
https://github.com/cschanaj/covfefe/blob/master/src/TrivializeSimpleRules.go#L52
```golang
if len(r.Default_off) > 0 || len(r.Platform) == 0 {
continue
}
```

Trivialize direct rewrite rules (linked, platform)

---

src/chrome/content/rules/Powervoip.com.xml

Added new https rule for powervoip.com

[Powervoip.com] Add new rule

---

src/chrome/content/rules/Pagely.xml

I may add `pagely.com` rules to this ruleset if I get the time.

[Page.ly] Simplify ruleset

---

src/chrome/content/rules/RPXCorp.com.xml

Fix https://github.com/EFForg/https-everywhere/pull/9441#issuecomment-314979829 @terrorist96 thanks!!

Update and rename RPXCrop.com.xml to RPXCorp.com.xml

---

src/chrome/content/rules/freenode.xml

[Freenode] Remove default_off

---

src/chrome/content/rules/Mozilla.xml

Ignore the preloaded test failure, it's caused by NPM.

Reenable Mozilla.xml

---

src/chrome/content/rules/EvolMed.com.xml

[EvolMed.com] Update and reactivate ruleset

---

src/chrome/content/rules/Linuxaria.com.xml

https://github.com/EFForg/https-everywhere/issues/10843

[Linuxaria.com] Simplify ruleset

---

src/chrome/content/rules/Kellycodetectors.com.xml

Force HTTPS (SSL) for, *.kellycodetectors.com

Add files via upload: Kellycodetectors.com Rule

---

src/chrome/content/rules/Deutsche-Rentenversicherung.de.xml

[Deutsche-Rentenversicherung.de] Simplify and reactivate ruleset

---

src/chrome/content/rules/Twimg.com.xml

#10545 #10888 because this is a CDN used by twitter and by itself is `alexa-top-180+`

Re-activate and Update Twimg.com.xml

---

src/chrome/content/rules/Reddit.xml

Note: this domain is now preloaded and should soon be included in all supported browsers.

[Reddit.com] Remove unnecessary rule

---

src/chrome/content/rules/Reddit_media.com.xml

thumbs.redditmedia.com is gone from DNS.

[Redditmedia.com] Remove outdated target and rule

---

src/chrome/content/rules/Racjonalista.pl.xml

Re-activate and Update Racjonalista.pl.xml

---

src/chrome/content/rules/Sebastian_Wick.net.xml

Re-activate and Update Sebastian_Wick.net.xml

---

src/chrome/content/rules/Oppo.com.xml

Re-activate and Update Oppo.com.xml

---

src/chrome/content/rules/newtimes.ru.xml

newtimes.ru

---

src/chrome/content/rules/delimobil.ru.xml

delimobil.ru

---

src/chrome/content/rules/Freecall.com.xml

Added new rule for freecall.com

[freecall.com] Added new rule for freecall.com

---

utils/duplicate-whitelist.txt

It won't be removed by the clean up script.

Remove duplicate entry

---

src/chrome/content/rules/fvz.io.xml

offers mirrors for a few sites

add rule for fvz.io

---

src/chrome/content/rules/Virus_Bulletin.xml

[VirusBulletin.com] Simplify and reactivate ruleset

---

src/chrome/content/rules/upbad.com.xml

Creating upbad.com and setting up https everywhere ruleset for upbad.com

Creating upbad.com

---

src/chrome/content/rules/KickNews.xml

Simplify KickNews.xml

---

src/chrome/content/rules/mikbill.ru.xml

mikbill.ru

---

src/chrome/content/rules/hkairportshop.com.xml

New ruleset for [HKairport Shop](http://www.hkairportshop.com)

[hkairportshop.com] New ruleset

---

src/chrome/content/rules/mobile-review.com.xml

mobile-review.com

---

src/chrome/content/rules/Wemfbox.ch.xml

- add more subdomains
- remove wildcard

Wemfbox.ch:

---

src/chrome/content/rules/Lowes.com.xml

Re-activate and Update Lowes.com.xml

---

src/chrome/content/rules/GlobalSign.xml

this remove the extremely complicated rewrites and the right-wildcard.  hopefully I did not miss any existing target. #11203

Simplify GlobalSign.xml

---

src/chrome/content/rules/Wald.Intevation.org.xml

Update Wald.Intevation.org.xml default_off reason

---

src/chrome/content/rules/Uakron.edu.xml

Simplify and Update Uakron.edu.xml

---

src/chrome/content/rules/Ortolo.eu.xml

[Ortolo.eu] Remove wildcard and platform

---

src/chrome/content/rules/The-New-Yorker.xml

Re-activate and Update The-New-Yorker.xml

---

chromium/background.js
chromium/popup.js
chromium/rules.js

A by-product for understanding the code of the project. This is a readability cleanup, although there may be no significant advantage and may need to QA test (I have do it).

Use for-of and Array.filter instead of general `for`

---

src/chrome/content/rules/Foresters.xml

Simplify Foresters.xml

---

src/chrome/content/rules/Planet-Work.xml

Simplify Planet-Work.xml

---

src/chrome/content/rules/SamKnows.xml

Simplify SamKnows.xml

---

src/chrome/content/rules/Attendesource.com.xml
src/chrome/content/rules/Attendesource.xml

#9906 there is only one sub-domain with working DNS record.

Re-activate and Update Attendesource.com.xml

---

src/chrome/content/rules/Sony_Entertainment_Network.xml

P.S. I prefer to keep to `rule` simple.

Re-activate and Update Sony_Entertainment_Network.xml

---

src/chrome/content/rules/LoveFilm.xml

Simplify LoveFilm.xml

---

src/chrome/content/rules/Caisse-Epargne.fr.xml

I didn't go through all subdomains listed by `Sublist3r`.
#10595

[Caisse-Epagne.fr] Update and reactivate ruleset

---

src/chrome/content/rules/STRATO.xml

Simplify STRATO.xml

---

src/chrome/content/rules/Nordea.xml

Simplify Nordea.xml

---

src/chrome/content/rules/respekt.cz.xml

Re-activate and Update respekt.cz.xml

---

src/chrome/content/rules/Komoona.com.xml

- remove wildcard
- cdn now serves a valid cert
- add some more subdomains

Komoona.com update

---

src/chrome/content/rules/invitro.ru.xml

invitro.ru

---

src/chrome/content/rules/dodopizza.ru.xml

dodopizza.ru

---

src/chrome/content/rules/technopark.ru.xml

technopark.ru

---

src/chrome/content/rules/luxorfilm.ru.xml

luxorfilm.ru

---

src/chrome/content/rules/bitrace.ru.xml

bitrace.ru

---

src/chrome/content/rules/caravan.ru.xml

caravan.ru

---

src/chrome/content/rules/kartoshka.com.xml

kartoshka.com

---

src/chrome/content/rules/rosreserv.ru.xml

rosreserv.ru

---

src/chrome/content/rules/pickpoint.ru.xml

pickpoint.ru

---

src/chrome/content/rules/ponyexpress.ru.xml

ponyexpress.ru

---

src/chrome/content/rules/litreev.com.xml

litreev.com

---

src/chrome/content/rules/redbtn.info.xml

redbtn.info

---

src/chrome/content/rules/OpenX.net.xml

OpenX.net:

---

src/chrome/content/rules/Jako-O.xml

Simplify Jako-O.xml

---

src/chrome/content/rules/SonyMobile.xml

Re-activate and Update SonyMobile.xml

---

src/chrome/content/rules/Nagano.cz.xml

update `default_off` reason and remove the incomprehensible complicated rule.

Update Nagano.cz.xml default_off reason

---

src/chrome/content/rules/Unblocked.xml

[Unblocked] Add domains and simplify ruleset

---

src/chrome/content/rules/All-Inkl.xml

https://github.com/EFForg/https-everywhere/issues/11203

[All-inkl] Remove right-wildcard and simplify ruleset

---

src/chrome/content/rules/viu.tv.xml

[viu.tv] Update ruleset

---

src/chrome/content/rules/jetstar.com.xml

New ruleset for [Jetstar Airways](https://www.jetstar.com)

[jetstar.com] New ruleset

---

src/chrome/content/rules/High-Gear-Media.xml

I'm not really interested in increasing the coverage here. I am simply removing a useless and breakage-prone rule. It would be great if it can be merged as is.

[High-Gear-Media] Simplify rule

---

src/chrome/content/rules/AK-Vorrat.de.xml

[AK-Vorrat.de] Reactivate ruleset and remove platform

---

src/chrome/content/rules/francetvinfo.fr.xml

Tested on a fresh profile and everything looks fine.

[Francetvinfo.fr] Fix redirect loop

---

src/chrome/content/rules/Cpunk.de.xml

#9582 this site looks like a private server.

Remove 'cacert' platform from Cpunk.de.xml

---

src/chrome/content/rules/Marmotte.net.xml

Remove 'cacert' platform from Marmotte.net.xml

---

src/chrome/content/rules/Dobrochan.xml

Remove 'cacert' platform from Dobrochan.xml

---

src/chrome/content/rules/Tagesanzeiger.ch.xml

Tagesanzeiger.ch:

---

src/chrome/content/rules/ponominalu.ru.xml

ponominalu.ru

---

src/chrome/content/rules/Highlands.edu.xml

Add Highlands.edu.xml

---

src/chrome/content/rules/akusherstvo.ru.xml

akusherstvo.ru

---

src/chrome/content/rules/Krisostomus.xml

https://github.com/EFForg/https-everywhere/issues/11203

[Kriso] Remove left- and right-wildcards

---

src/chrome/content/rules/medikom.ru.xml

medikom.ru

---

src/chrome/content/rules/expodat.com.xml

expodat.com

---

src/chrome/content/rules/diamedclinic.ru.xml

diamedclinic.ru

---

chromium/background.js
chromium/incognito-cache-clearing.js
chromium/manifest.json
chromium/popup.css
chromium/popup.js
chromium/storage.js

Core changes to WebExtension code to make it work with Firefox.  Reference the `done` column of https://github.com/EFForg/https-everywhere/projects/1

Firefox webextensions core

---

src/chrome/content/rules/Atgsvcs.com.xml
src/chrome/content/rules/Bank_of_Taipei.com.tw.xml
src/chrome/content/rules/Customersvc.com.xml
src/chrome/content/rules/Delft-University-of-Technology.xml
src/chrome/content/rules/EUKhost.xml
src/chrome/content/rules/Eis.de.xml
src/chrome/content/rules/Element14.com-Mixed.xml
src/chrome/content/rules/Employease.xml
src/chrome/content/rules/Flurry.xml
src/chrome/content/rules/Grenoble-INP.fr.xml
src/chrome/content/rules/MemberClicks.com.xml
src/chrome/content/rules/MeteoNews.xml
src/chrome/content/rules/MiniJuegos_gratis.com.xml
src/chrome/content/rules/Morningstar.xml
src/chrome/content/rules/Notebooksbilliger.xml
src/chrome/content/rules/Perfect_Market.com.xml
src/chrome/content/rules/PowerPay.biz.xml
src/chrome/content/rules/SDSC.edu.xml
src/chrome/content/rules/Schwab_CDN.com.xml
src/chrome/content/rules/Turtlebeach.xml
src/chrome/content/rules/United_Nations_Office_at_Vienna.xml

The following list of files needed to be updated manually in another PRs.
See [`trivialize-rules-list.txt`](https://github.com/cschanaj/https-everywhere-issues/blob/master/trivialize-rules-list.txt)

Trivialize capturing rewrites

---

src/chrome/content/rules/Export.gov.xml

@jeremyn 
#11510
I couldn't find more working subdomains

[Export.gov] Update top comment

---

src/chrome/content/rules/FbCDN.net.xml

Again, it's fine if you need to take some time to review this ruleset.

[FbCDN.net] Remove targets that are gone from DNS

---

src/chrome/content/rules/Buerger-CERT.xml

@cschanaj, it looks like this one managed to get through your automated comment removal.

[Buerge-CERT.de] Simplify ruleset

---

src/chrome/content/rules/BosslandGmbH.xml

BosslandGmbH:

---

src/chrome/content/rules/Rubicon-Project.xml

- add beadon-eu & fastlane  as target subdomains

Rubicon-Project:

---

src/chrome/content/rules/GoogleMaps.xml

I know this is important we don't break anything here so please take your time to review. I can also understand if you prefer to keep some more complicated rules for clarity.

[GoogleMaps] Simplify ruleset

---

src/chrome/content/rules/CBSNews.xml

add rule for CBSNews

---

src/chrome/content/rules/Ondarossa.info.xml

[Ondarossa.info] Reactivate ruleset and remove platform

---

src/chrome/content/rules/Directbox.xml

[Directbox] Remove right wildcard and reactivate ruleset

---

src/chrome/content/rules/TheAnarchistLibrary.org.xml

Added two new subdomains. Also added three other domains that provide the library in different languages, but are still part of the same project.

Updated theanarchistlibrary

---

src/chrome/content/rules/Federal_Trade_Commission.xml

Remove dead hostnames and re-enable.

[Federal_Trade_Commission] Reactivate ruleset.

---

src/chrome/content/rules/University_of_Tennessee_Knoxville.xml

Sub-domain enumeration is not performed. #9842

Re-activate and Update University_of_Tennessee_Knoxville.xml

---

src/chrome/content/rules/PrintFriendly.xml

Related: https://github.com/EFForg/https-everywhere/issues/2708

[PrintFriendly.com] Simplify ruleset

---

src/chrome/content/rules/Thumbshots.xml

[Thumbshots] Simplify ruleset

---

src/chrome/content/rules/bicotender.ru.xml

bicotender.ru

---

src/chrome/content/rules/meb-biz.ru.xml

meb-biz.ru

---

src/chrome/content/rules/stylershop.ru.xml

stylershop.ru

---

chromium/background.js
chromium/options.html
chromium/options.js
chromium/popup.js
chromium/translation.js

@Hainish Test and merge if everything's fine.

Show icon badge (without unrelated changes)

---

test/fetch.sh
test/rules/src/https_everywhere_checker/http_client.py
test/travis.sh

Requires https://github.com/EFForg/https-everywhere-docker-base/pull/2 to work.

Make fetch test work with .onion domains

---

src/chrome/content/rules/Webstaurant_Store.xml

The http redirect issues seem to have been resolved.

[Webstaurant_Store] Simplify ruleset.

---

src/chrome/content/rules/RSPB.xml

It's currently broken. I have gotten in touch, but there will naturally
be some lag in getting a fix.

Remove shopping.rsbp.org.uk

---

src/chrome/content/rules/UST.hk.xml

 	Rename and Update UST.hk.xml 

---

chromium/rules.js

@Hainish this will notably improve performance and memory usage, as suggested in https://github.com/EFForg/https-everywhere/issues/1775#issuecomment-151655897, whereas the performance is measured by https://jsperf.com/es6-map-vs-object-properties/42. 
~Why `Firefox` test always fails?~

Use Map instead of Object for RuleSets.targets

---

src/chrome/content/rules/Heroku.xml

Removing lines made obsolete after https://github.com/EFForg/https-everywhere/commit/8bda7ce0a40d208a7e752e4df56e32b403160071.

[Heroku] Remove outdated exclusion and rule (fix travis)

---

src/chrome/content/rules/theses.fr.xml

[Theses.fr] Add missing target

---

src/chrome/content/rules/Tmblr.co.xml

[Tmblr.co] Simplify rule

---

src/chrome/content/rules/PureFTPd.org.xml

[PureFTPd.org] Fix broken rule and add targets

---

src/chrome/content/rules/VectorMagic.com.xml

Ameliorating https://github.com/EFForg/https-everywhere/pull/11097

Create VectorMagic.com.xml (1 Merge = 2 PRs closed)

---

src/chrome/content/rules/Libsyn.xml

`libsynpro.com` will need its own ruleset

[Libsyn.com] Add left-wildcard and test urls

---

src/chrome/content/rules/Eyeviewads.com.xml

[Eyeviewads.com] Remove wildcard

---

src/chrome/content/rules/Parkerpen.com.xml

https://github.com/EFForg/https-everywhere/issues/10843

[Parkerpen.com] Simplify ruleset

---

src/chrome/content/rules/troid.ca.xml

Ameliorating https://github.com/EFForg/https-everywhere/pull/11099

Create troid.ca.xml (1 Merge = 2 PRs closed)

---

src/chrome/content/rules/LineageOS.org.xml

cherry-pick from #12278. Thanks to @jcoscia

add cve.lineageos.org

---

src/chrome/content/rules/cambridgeshire.gov.uk.xml

Simplify and Update cambridgeshire.gov.uk.xml

---

src/chrome/content/rules/JS.org.xml

Synchronized with the upstream list. Several issues were fixed in js-org/dns.js.org#1454.

[JS.org] Update ruleset.

---

src/chrome/content/rules/CoinPayments.net.xml
src/chrome/content/rules/coinpaymtstgtibr.onion.xml

Create CoinPayments.net rulesets (onion + clearnet)

---

src/chrome/content/rules/OPM.gov.xml

#11513 was asking to merge in the wrong branch and I have no idea how to fix it.

[OPM.gov] Update and reactivate ruleset

---

src/chrome/content/rules/Servage.net.xml

[Servage] Remove left and right wildcards

---

chromium/background.js

Update chromium/background.js, Fix #12449

---

chromium/.eslintrc.json
chromium/background.js
chromium/devtools-panel.js
chromium/devtools.js
chromium/incognito-cache-clearing.js
chromium/options.js
chromium/popup.js
chromium/rules.js
chromium/send-message.js
chromium/storage.js
chromium/switch-planner.js
chromium/util.js

No unused vars

---

src/chrome/content/rules/Tafsir.net.xml

Ameliorating https://github.com/EFForg/https-everywhere/pull/11102

Create Tafsir.net.xml (1 Merge = 2 PRs closed)

---

src/chrome/content/rules/Covered-California.xml

[Covered-California] Fix redirect loop and update ruleset.

---

src/chrome/content/rules/GoogleServices_Complex.xml

Removing exclusions that don't have a matching target

[GoogleServices_Complex] Remove broken exclusions

---

src/chrome/content/rules/3min.xml

Unsure if this is expired, or just has no working nameservers, but in any case it's very dead.

[3min] Delete expired domain.

---

src/chrome/content/rules/uniongang.tv.xml

uniongang.tv

---

src/chrome/content/rules/PostNord.se.xml

Re-activate and Update PostNord.se.xml

---

src/chrome/content/rules/AerLingus.xml
src/chrome/content/rules/Aer_Lingus.com.xml

#9906 sub-domain enumeration is not performed.

Re-activate, Rename and Update Aer_Lingus.com.xml

---

src/chrome/content/rules/active.domains.xml

active.domains

---

src/chrome/content/rules/domainshop.ru.xml

domainshop.ru

---

src/chrome/content/rules/shop-dent.ru.xml

shop-dent.ru

---

src/chrome/content/rules/Google.xml

[Google] Remove broken target

---

src/chrome/content/rules/MIT.xml

https://github.com/EFForg/https-everywhere/issues/12640

Fixing MIT.xml

---

src/chrome/content/rules/elgoog.im.xml

Create elgoog.im.xml, Close #12604

---

src/chrome/content/rules/Linux_Containers.org.xml

Re-activate and Update Linux_Containers.org.xml

---

src/chrome/content/rules/Bankuralsib.ru.xml

Re-activate and Update Bankuralsib.ru.xml

---

src/chrome/content/rules/Lookback.io.xml

Re-activate and Update Lookback.io.xml

---

src/chrome/content/rules/360_Yield.xml

Re-activate and Update 360_Yield.xml

---

src/chrome/content/rules/Software_Freedom_Conservancy.xml

Re-activate and Update Software_Freedom_Conservancy.xml

---

src/chrome/content/rules/Southend.gov.uk.xml

Re-activate and Update Southend.gov.uk.xml

---

src/chrome/content/rules/Aberdeenshire.gov.uk.xml

Re-activate and Update Aberdeenshire.gov.uk.xml

---

src/chrome/content/rules/GovHK.xml
src/chrome/content/rules/thechinfamily.hk.xml

New ruleset for [The Chin Family](https://www.thechinfamily.hk)

[thechinfamily.hk] New ruleset

---

src/chrome/content/rules/Politico.xml

Fix broken politico.com ruleset and add tests; fixes #9000

---

src/chrome/content/rules/CanvasHolidays.co.uk.xml
src/chrome/content/rules/Wyndham.xml

#11203 I will be spliting this ruleset slowly and ultimately remove all right wildcard from it (hopefully).

Split CanvasHolidays.co.uk from Wyndham.xml

---

src/chrome/content/rules/RCITravelStore.co.uk.xml
src/chrome/content/rules/Wyndham.xml

Split RCITravelStore.co.uk from Wyndham.xml

---

src/chrome/content/rules/Racked.com.xml

The CORS issue (#7383) seems to have been resolved.

[Racked.com] Update ruleset.

---

src/chrome/content/rules/NBN_Co.com.au.xml

[NBN_Co.com.au] Update and re-enable ruleset.

---

src/chrome/content/rules/PyWeek.org.xml

Supersedes https://github.com/EFForg/https-everywhere/pull/7400.

[PyWeek.org] Update and reactivate ruleset

---

src/chrome/content/rules/ahyasalam.com.xml

Ameliorating https://github.com/EFForg/https-everywhere/pull/11022

Create ahyasalam.com.xml (1 Merge = 2 PRs closed)

---

src/chrome/content/rules/IkhwanWiki.com.xml

Ameliorating https://github.com/EFForg/https-everywhere/pull/9879

Create IkhwanWiki.com.xml (1 Merge = 2 PRs closed)

---

src/chrome/content/rules/JamesVillas.co.uk.xml
src/chrome/content/rules/Wyndham.xml

Split JamesVillas.co.uk from Wyndham.xml

---

src/chrome/content/rules/Xiami.xml

Includes "xiami.com" and "xiami.net" domains.

Create Xiami ruleset

---

src/chrome/content/rules/Claws-Mail.org.xml

https://github.com/EFForg/https-everywhere/issues/12297

[Claws-Mail.org] Add targets and simplify rule

---

src/chrome/content/rules/SSL_Labs.xml

Rename SSLlabs.xml rule

---

src/chrome/content/rules/GovHK.xml
src/chrome/content/rules/wi-fi.hk.xml

New ruleset for [Wi-Fi.HK](https://www.wi-fi.hk)

[wi-fi.hk] New ruleset

---

src/chrome/content/rules/APAN.org.xml

Re-activate and Update APAN.org.xml

---

src/chrome/content/rules/simplyaccessible.com.xml

[simplyaccessible.com] Add ruleset.

---

src/chrome/content/rules/Hoseasons.co.uk.xml
src/chrome/content/rules/Wyndham.xml

Split Hoseasons.co.uk from Wyndham.xml

---

src/chrome/content/rules/Racket-lang.org.xml

[Racket-lang.org] Update ruleset.

---

src/chrome/content/rules/Ancud.de.xml
src/chrome/content/rules/Betanews.xml
src/chrome/content/rules/DENX.de.xml
src/chrome/content/rules/Drwho.virtadpt.net.xml
src/chrome/content/rules/EW-online.de.xml
src/chrome/content/rules/Echothrust.com.xml
src/chrome/content/rules/Engelschall.com.xml
src/chrome/content/rules/Goddard-Group.xml
src/chrome/content/rules/Huxo.co.uk.xml
src/chrome/content/rules/IED-Industrieanlagen-und-Engineering.xml
src/chrome/content/rules/IWM_Network.com.xml
src/chrome/content/rules/Infile.xml
src/chrome/content/rules/JGuitar.com.xml
src/chrome/content/rules/Jeja.pl.xml
src/chrome/content/rules/Kanshoo.xml
src/chrome/content/rules/Kosimak.com.xml
src/chrome/content/rules/Kovidgoyal.net.xml
src/chrome/content/rules/Krautchan.xml
src/chrome/content/rules/Linkomanija.xml
src/chrome/content/rules/Merca20.xml
src/chrome/content/rules/Milwaukee-Makerspace.xml
src/chrome/content/rules/Praegnanz.de.xml
src/chrome/content/rules/Premier_Tax_Free.xml
src/chrome/content/rules/SRA_OSS.xml
src/chrome/content/rules/Suburban-Records.xml
src/chrome/content/rules/Tweegy.nl.xml
src/chrome/content/rules/United_Computer_Wizards.xml
src/chrome/content/rules/Universe_2.us.xml
src/chrome/content/rules/Vehicle_Visuals.com.xml

This PR re-enables all the rulesets from #13091 which require either only minimal simplification or straight re-enabling.

Bulk re-enabling of default_off="self-signed" rulesets.

---

src/chrome/content/rules/Holtwick-IT-mismatches.xml
src/chrome/content/rules/Holtwick-IT.xml

[Holtwick-IT] Update ruleset.

---

src/chrome/content/rules/Creative_Virtual.com.xml

[Creative_Virtual.com] Update ruleset.

---

src/chrome/content/rules/PCS.com.xml

#13091
Mixed content issues seem to have been resolved.

[PCS.com] Update ruleset.

---

src/chrome/content/rules/Digital-Transactions.xml

[Digital-Transactions] Update ruleset.

---

src/chrome/content/rules/UNHCR.org.xml

Re-activate and Update UNHCR.org.xml

---

src/chrome/content/rules/NBC-News.xml

Re-activate and Update NBC-News.xml

---

src/chrome/content/rules/Channelx.biz.xml

[Channelx.biz] Update ruleset.

---

src/chrome/content/rules/DepartmentofImmigrationandBorderProtection.xml

[DepartmentofImmigrationandBorderProtection] Add ruleset.

---

chromium/rules.js
chromium/test/rules_test.js

This finishes #12577 by adding tests and rebasing. 
Thanks @cschanaj !

Rebase and test cschanaj's nullIterable PR 

---

src/chrome/content/rules/Truenudists.com.xml

[TrueNudists.com] Remove wildcard in the middle and reactivate

---

src/chrome/content/rules/Ze.tt.xml
src/chrome/content/rules/Zeit.de.xml

Youth magazine from Zeit Online

add rule for Ze.tt

---

src/chrome/content/rules/Ubuntu_Linux.jp.xml

Re-activate Ubuntu_Linux.jp.xml

---

src/chrome/content/rules/2K_Games.xml
src/chrome/content/rules/Avanza.se.xml
src/chrome/content/rules/Sesamstrasse.de.xml
src/chrome/content/rules/Spielfuerdeinland.de.xml
src/chrome/content/rules/TNS-Global.xml
src/chrome/content/rules/TunnelBear.com.xml
src/chrome/content/rules/TunnelBear.xml
src/chrome/content/rules/hkjc.com.xml
src/chrome/content/rules/technopark.ru.xml
utils/relaxng.xml

ping @J0WI @cowlicks @Hainish this fix #13036

Require lowercase targets as per #13036

---

src/chrome/content/rules/Canonical.xml

Re-activate Canonical.xml

---

src/chrome/content/rules/Chartbeat.xml

Re-activate Chartbeat.xml

---

src/chrome/content/rules/Bluehost-CDN.com.xml

Re-activate Bluehost-CDN.com.xml

---

src/chrome/content/rules/Kaspersky.com.xml

Re-activate Kaspersky.com.xml

---

src/chrome/content/rules/ShareIslam.com.xml

Re-activate ShareIslam.com.xml

---

src/chrome/content/rules/Mozilla_Webmaker.xml

Re-activate Mozilla_Webmaker.xml

---

src/chrome/content/rules/Mozilla.jp.xml

Re-activate Mozilla.jp.xml

---

src/chrome/content/rules/Offensive-Security.com.xml

Re-activate Offensive-Security.com.xml

---

src/chrome/content/rules/LinuxFoundation.xml

Re-activate LinuxFoundation.xml

---

src/chrome/content/rules/XenServer.org.xml

Re-activate XenServer.org.xml

---

src/chrome/content/rules/Slashdot_Media.xml

Re-activate Slashdot_Media.xml

---

src/chrome/content/rules/Icehost.is.xml

Re-activate Icehost.is.xml

---

src/chrome/content/rules/Disconnect.me.xml

Re-activate Disconnect.me.xml

---

src/chrome/content/rules/Do_Not_Track-doc.com.xml

Re-activate Do_Not_Track-doc.com.xml

---

src/chrome/content/rules/UbuntuUsers.de.xml

Re-activate UbuntuUsers.de.xml

---

src/chrome/content/rules/Bitcoin_Foundation.org.xml

Re-activate Bitcoin_Foundation.org.xml

---

src/chrome/content/rules/BitTorrent.xml

Re-activate BitTorrent.xml

---

src/chrome/content/rules/Elfa.se.xml

Re-activate Elfa.se.xml

---

src/chrome/content/rules/SiteScout.xml

Re-activate SiteScout.xml

---

src/chrome/content/rules/Sky.com.xml

Re-activate Sky.com.xml

---

src/chrome/content/rules/Effective-Measure.xml

Re-activate Effective-Measure.xml

---

src/chrome/content/rules/Brown_University.xml

Re-activate Brown_University.xml

---

src/chrome/content/rules/Youm7.com.xml

Re-activate Youm7.com.xml

---

src/chrome/content/rules/Blockchain.xml
src/chrome/content/rules/Blockchainbdgpzk.onion.xml
src/chrome/content/rules/blockchainbdgpzk.onion.xml

Update and rename Blockchainbdgpzk.onion.xml to Blockchain.xml

---

src/chrome/content/rules/Brennan_Novak.com.xml

Re-activate Brennan_Novak.com.xml

---

src/chrome/content/rules/Pro-market.net.xml

Re-activate Pro-market.net.xml

---

src/chrome/content/rules/eyeota.net.xml

Re-activate eyeota.net.xml

---

src/chrome/content/rules/RL_CDN.com.xml

Re-activate RL_CDN.com.xml

---

src/chrome/content/rules/Casale-Media.xml

Re-activate Casale-Media.xml

---

src/chrome/content/rules/Inria.fr.xml

Re-activate Inria.fr.xml

---

src/chrome/content/rules/active24.co.uk.xml

Re-activate active24.co.uk.xml

---

src/chrome/content/rules/active24.cz.xml

Re-activate active24.cz.xml

---

src/chrome/content/rules/active24.de.xml

Re-activate active24.de.xml

---

src/chrome/content/rules/active24.es.xml

Re-activate active24.es.xml

---

src/chrome/content/rules/active24.nl.xml

Re-activate active24.nl.xml

---

src/chrome/content/rules/ApacheCon.com.xml

[ApacheCon.com] Update ruleset.

---

src/chrome/content/rules/TechSupportAlert.com.xml
src/chrome/content/rules/Techsupportalert.xml

Mixed content issues seem to have been resolved.

[TechSupportAlert.com] Update ruleset.

---

src/chrome/content/rules/ToolbarBrowser.xml

[ToolbarBrowser] Re-enable ruleset.

---

src/chrome/content/rules/Tapad.xml

Re-activate Tapad.xml

---

src/chrome/content/rules/Cottages.com.xml
src/chrome/content/rules/Cottages4you.co.uk.xml
src/chrome/content/rules/Wyndham.xml

Included changes from #12657 and thus blocked by #12657. thanks!
P.S. I am not really sure if this help to avoid the merge conflict or not.

Split Cottages.com from Wyndham.xml

---

src/chrome/content/rules/Google.com_Subdomains.xml

Add targets:
* alerts
* safebrowsing
* photos

Update Google.com Subdomains ruleset

---

src/chrome/content/rules/Files.poulsander.com.xml
src/chrome/content/rules/poulsander.com.xml

[Files.poulsander.com] Update and rename ruleset.

---

src/chrome/content/rules/Traffic_Safety_Marketing.gov.xml

Re-activate Traffic_Safety_Marketing.gov.xml

---

src/chrome/content/rules/southribble.gov.uk.xml

Re-activate and Update southribble.gov.uk.xml

---

src/chrome/content/rules/Portugal.gov.pt.xml

Re-activate Portugal.gov.pt.xml

---

src/chrome/content/rules/AllJoyn.org.xml

Re-activate and Update AllJoyn.org.xml

---

src/chrome/content/rules/GovHK.xml
src/chrome/content/rules/police.gov.hk.xml

New ruleset for [Hong Kong Police Force](https://www.police.gov.hk)

[police.gov.hk] New ruleset

---

src/chrome/content/rules/Calculator.net.xml

I ran the tests, built the XPI, installed it (in Developer edition with legacy extensions enabled, can't figure out how to build the Firefox WebExtension I guess?), and tested. It's redirecting correctly. The site is fairly simple (but great), no assets fail to load.

Add Calculator.net.xml

---

src/chrome/content/rules/Dabplus.ch.xml
src/chrome/content/rules/Dabplus.de.xml

The two hosts are not related.

Add rules for dabplus

---

src/chrome/content/rules/How_to_Box.xml

[How_to_Box] Update ruleset.

---

src/chrome/content/rules/Wix.xml

This reverts a change in 8b29bdfed711d07939506a0a67f377324f3c3087, but I'm not sure if this will fix all issues.
Related:
#9429
#13200
#13347

revert securecookie change, may fix #13347

---

CONTRIBUTING.md

I use `CONTRIBUTING.md` *a lot* both for my own rulesets but also as a primer for new contributors. But I always have a hard time finding the exact part I am interested in. I added a table of contents for quick access to the relevant sections.

Add table of contents

---

utils/issue-format-bot/.env.example
utils/issue-format-bot/package-lock.json
utils/issue-format-bot/package.json

* Bump deps
* Squash a deprecation
Note that I upgraded to `probot@3` and only had time to do minimal testing. But I'm not too worried.

Bot housekeeping

---

chromium/background.js

Simplify code and consider xmlhttprequest and sub_frame active content, identical to current Chrome version.

---

src/chrome/content/rules/Yelp.xml

Seems to respond correctly now (though it redirects to some random page on yelp)

Remove help.yelp.com exclusion

---

src/chrome/content/rules/Lijit.com.xml

Lijit.com:

---

src/chrome/content/rules/Wolfram_CDN.com.xml

Update Wolfram_CDN.com.xml [adding 	<securecookie host=".+" name=".+" />]

---

src/chrome/content/rules/Telecommunications-Industry-Ombudsman-mixedcontent.xml
src/chrome/content/rules/Telecommunications-Industry-Ombudsman.xml

[Telecommunications-Industry-Ombudsman] Add ruleset.

---

src/chrome/content/rules/Twinings.xml

https://github.com/EFForg/https-everywhere/issues/12297

[Twinings.co.uk] Fix and update ruleset

---

src/chrome/content/rules/VideoHub.tv.xml

Videohub.tv:

---

src/chrome/content/rules/TubeMogul.com.xml

TubeMogul:

---

src/chrome/content/rules/Appledaily.xml

Adds a new ruleset for Appledaily.

Add Appledaily ruleset

---

src/chrome/content/rules/thepeak.com.hk.xml

New ruleset for [The Peak Hong Kong](https://www.thepeak.com.hk)

[thepeak.com.hk] New ruleset

---

src/chrome/content/rules/LMU-Muenchen-Library.xml
src/chrome/content/rules/LMU-Muenchen.xml

- added library page
- added comment to main file

Add LMU-Muenchen-Library.xml

---

src/chrome/content/rules/Eskimi.com.xml

Site contains some trivial mixed content issues.

Add Eskimi.com.xml

---

src/chrome/content/rules/Wyndham-mismatches.xml
src/chrome/content/rules/Wyndham.xml
src/chrome/content/rules/landalskilife.be.xml
src/chrome/content/rules/landalskilife.ch.xml
src/chrome/content/rules/landalskilife.com.xml
src/chrome/content/rules/landalskilife.cz.xml
src/chrome/content/rules/landalskilife.de.xml
src/chrome/content/rules/landalskilife.fr.xml
src/chrome/content/rules/landalskilife.nl.xml

cc @J0WI this is ready to be merged. please have a look when you have the time. thanks!!

Split landalskilife.* from Wyndham.xml

---

src/chrome/content/rules/Okdiario.com.xml

This replaces PR https://github.com/EFForg/https-everywhere/pull/7441.

Add Okdiario.com.xml

---

src/chrome/content/rules/Image-Line.com.xml

Add Image-Line.com.xml

---

src/chrome/content/rules/ITcafe.hu.xml

Add ITcafe.hu.xml

---

src/chrome/content/rules/GAMEPOD.hu.xml

Add GAMEPOD.hu.xml

---

src/chrome/content/rules/Iweps.be.xml

Add Iweps.be.xml

---

src/chrome/content/rules/Filehippo.com.xml

https://github.com/EFForg/https-everywhere/issues/13613

[Filehippo.com] New ruleset

---

src/chrome/content/rules/Wyndham.xml

Remove landalcampings.de from Wyndham.xml

---

src/chrome/content/rules/PayGarden.com.xml

https://github.com/EFForg/https-everywhere/issues/3069

[paygarden.com] New ruleset

---

src/chrome/content/rules/CQ_Roll_Call.xml

[CQ_Roll_Call] Update and re-enable ruleset.

---

src/chrome/content/rules/ebayimg.com.xml

[ebayimg.com] New ruleset

---

src/chrome/content/rules/Kiwix.org.xml

Add Kiwix.org.xml

---

src/chrome/content/rules/Galiciana.gal.xml

Add Galiciana.gal.xml

---

src/chrome/content/rules/amd-osx.com.xml

[amd-osx.com] New ruleset.

---

src/chrome/content/rules/Schibsted.io.xml

add rule for Schibsted.io

---

src/chrome/content/rules/Wyndham.xml

SSL errors for all subdomain enumerated

Remove landalparkshop.de from Wyndham.xml

---

src/chrome/content/rules/ebay.ch.xml

[ebay.ch] New ruleset

---

src/chrome/content/rules/ebay.at.xml

[ebay.at] New ruleset

---

src/chrome/content/rules/FiveThirtyEight.com.xml

[FiveThirtyEight.com] Fix redirect loop (#13873)

---

src/chrome/content/rules/Lymo.fr.xml

Added ruleset for lymo.fr
My previous PR https://github.com/EFForg/https-everywhere/pull/9401 seems unmodifiable because I deleted my previous fork. Hopefully this one works better

Added ruleset for lymo.fr

---

src/chrome/content/rules/Github-Pages.xml

[Github.io] Add exclusion

---

src/chrome/content/rules/Anaxago.com.xml

Added ruleset for anaxago.com
My previous PR https://github.com/EFForg/https-everywhere/pull/9310 seems unmodifiable because I deleted my previous fork. Hopefully this one works better

Added ruleset for anaxago.com

---

src/chrome/content/rules/Uni-Stuttgart.de.xml

Edit uni-stuttgart.de.xml

---

src/chrome/content/rules/ebay.ru.xml

[ebay.ru] New ruleset

---

src/chrome/content/rules/ebay.ph.xml

[ebay.ph] New ruleset

---

src/chrome/content/rules/ebay.pl.xml

[ebay.pl] New ruleset

---

src/chrome/content/rules/ebay.ie.xml

[ebay.ie] New ruleset

---

src/chrome/content/rules/ebay.in.xml

[ebay.in] New ruleset

---

src/chrome/content/rules/ebay.com.hk.xml

[ebay.com.hk] New ruleset

---

src/chrome/content/rules/Themertailor.com.xml
src/chrome/content/rules/themertailor.com.xml

add rule for mertailor

---

src/chrome/content/rules/ebay.nl.xml

[ebay.nl] New ruleset

---

src/chrome/content/rules/MyEtherWallet.com.xml

Surprised this one wasn't already in HTTPS Everywhere, considering the owner enjoys ranting about people falling for phishing attacks after failing to check for HTTPS.

[myetherwallet.com] New ruleset

---

src/chrome/content/rules/PublicBank.com.vn.xml

[publicbank.com.vn] New ruleset

---

src/chrome/content/rules/PublicIslamicBank.xml

[publicislamicbank.com.my] New ruleset

---

src/chrome/content/rules/PublicMutual.xml

[publicmutualonline.com.my] New ruleset

---

src/chrome/content/rules/WoolworthsPetrol.com.au.xml

[WoolworthsPetrol.com.au] New ruleset

---

src/chrome/content/rules/WoolworthsPay.com.au.xml

[WoolworthsPay.com.au] New ruleset

---

src/chrome/content/rules/LastStopShop.co.nz.xml

[LastStopShop.co.nz] New ruleset

---

src/chrome/content/rules/bigw.com.au.xml

[bigw.com.au] New ruleset

---

src/chrome/content/rules/Masters.com.au.xml

[masters.com.au] New ruleset

---

src/chrome/content/rules/bws.com.au.xml

[bws.com.au] New ruleset

---

src/chrome/content/rules/LastStopShop.com.au.xml

[LastStopShop.com.au] New ruleset

---

src/chrome/content/rules/Langtons.com.au.xml

[Langtons.com.au] New ruleset

---

src/chrome/content/rules/danmurphys.com.au.xml

[danmurphys.com.au] New ruleset

---

src/chrome/content/rules/Atlantic-Metro-Communications.xml

Some non-functional domains are omitted.

Remove Left-wildcard from Atlantic-Metro-Communications.xml

---

src/chrome/content/rules/PublicBank.com.hk.xml

[publicbank.com.hk] New ruleset

---

src/chrome/content/rules/PublicInvestBank.com.xml

[PublicInvestBank.com] New ruleset

---

src/chrome/content/rules/Cellarmasters.com.au.xml

[Cellarmasters.com.au] New ruleset

---

src/chrome/content/rules/Ptt.cc.xml

This pull request replaces pull request https://github.com/EFForg/https-everywhere/pull/8072.

Add Ptt.cc.xml

---

src/chrome/content/rules/Tripbaa.com.xml
src/chrome/content/rules/tripbaa.com.xml

I hope I remembered everything. I reviewed a bunch of already merged rulesets after I made this to try to make sure.

add tripbaa.com ruleset

---

src/chrome/content/rules/163.com.xml

Add `you.163.com` to 163.com ruleset.

[you.163.com] Add rule for 163.com

---

src/chrome/content/rules/SHAttered.io.xml

This pull request replaces pull request https://github.com/EFForg/https-everywhere/pull/8966.

Add SHAttered.io.xml

---

src/chrome/content/rules/WelcomeCottages.com.xml
src/chrome/content/rules/Wyndham.xml

`Access Denied` for all pages, seemingly no longer in use.

Split WelcomeCottages.com from Wyndham.xml

---

src/chrome/content/rules/X86.fr.xml

This pull request replaces pull request https://github.com/EFForg/https-everywhere/pull/9234.

Add X86.fr.xml

---

src/chrome/content/rules/ExamService.com.tw.xml

This pull request replaces pull request https://github.com/EFForg/https-everywhere/pull/8044.

Add ExamService.com.tw.xml

---

src/chrome/content/rules/Expedia.co.jp.xml

[Expedia.co.jp] New ruleset

---

src/chrome/content/rules/Expedia.ca.xml

[Expedia.ca] New ruleset

---

src/chrome/content/rules/Expedia.co.nz.xml

[Expedia.co.nz] New ruleset

---

src/chrome/content/rules/Expedia.co.in.xml

[Expedia.co.in] New ruleset

---

src/chrome/content/rules/Expedia.co.th.xml

[Expedia.co.th] New ruleset

---

src/chrome/content/rules/Expedia.co.kr.xml

[Expedia.co.kr] New ruleset

---

src/chrome/content/rules/Expedia.cn.xml

[Expedia.cn] New ruleset

---

src/chrome/content/rules/Expedia.ch.xml

[Expedia.ch] New ruleset

---

src/chrome/content/rules/Expedia.at.xml

[Expedia.at] New ruleset

---

src/chrome/content/rules/Expedia.com.au.xml

[Expedia.com.au] New ruleset

---

src/chrome/content/rules/Expedia.be.xml

[Expedia.be] New ruleset

---

src/chrome/content/rules/Expedia.co.id.xml

[Expedia.co.id] New ruleset

---

src/chrome/content/rules/Wyndham.xml

`timeout` for 2 consecutive `fetch-test` (b69a6d7a7ba and 9bf49cbeb46) and the problem still persist.

Remove Secureholidays.com from Wyndham.xml

---

src/chrome/content/rules/WoolworthsMobile.com.au.xml

[WoolworthsMobile.com.au] New ruleset

---

src/chrome/content/rules/Countdown.co.nz.xml

[Countdown.co.nz] New ruleset

---

src/chrome/content/rules/EziBuy.com.xml

[EziBuy.com] New ruleset

---

src/chrome/content/rules/Macquarie.com.au.xml

https://github.com/EFForg/https-everywhere/pull/13169

[Macquarie.com.au] New ruleset

---

src/chrome/content/rules/Expedia.com.sg.xml

[Expedia.com.sg] New ruleset

---

src/chrome/content/rules/Expedia.com.tw.xml

[Expedia.com.tw] New ruleset

---

src/chrome/content/rules/Expedia.com.vn.xml

[Expedia.com.vn] New ruleset

---

src/chrome/content/rules/Expedia.com.ph.xml

[Expedia.com.ph] New ruleset

---

src/chrome/content/rules/Gumtree.co.za.xml

https://github.com/EFForg/https-everywhere/pull/14109

[Gumtree.co.za] New ruleset

---

src/chrome/content/rules/Gumtree.pl.xml

https://github.com/EFForg/https-everywhere/pull/14109

[Gumtree.pl] New ruleset

---

src/chrome/content/rules/Gumtree.ie.xml

https://github.com/EFForg/https-everywhere/pull/14109

[Gumtree.ie] New ruleset

---

src/chrome/content/rules/Gumtree.sg.xml

https://github.com/EFForg/https-everywhere/pull/14109

[Gumtree.sg] New ruleset

---

src/chrome/content/rules/444.hu.xml
src/chrome/content/rules/4cdn.hu.xml

This pull request replaces pull request https://github.com/EFForg/https-everywhere/pull/12479.

Update 444.hu.xml and add 4cdn.hu.xml

---

src/chrome/content/rules/Expedia.com.my.xml

[Expedia.com.my] New ruleset

---

src/chrome/content/rules/Expedia.com.br.xml

[Expedia.com.br] New ruleset

---

src/chrome/content/rules/Expedia.com.hk.xml

[Expedia.com.hk] New ruleset

---

src/chrome/content/rules/Springserve.com.xml

Springserve.com:

---

src/chrome/content/rules/RARLab.xml
src/chrome/content/rules/WinRAR.xml

Create RARLab.xml and Update WinRAR.xml

---

src/chrome/content/rules/VisualDNA.com.xml

VisualDNA:

---

src/chrome/content/rules/ScorecardResearch.com.xml

ScorecardResearch.com:

---

src/chrome/content/rules/Casale-Media.xml

Casale-Media:

---

src/chrome/content/rules/FactCheck.org.xml

[FactCheck.org] Add targets and remove platform (fix #14157)

---

src/chrome/content/rules/Swiss-Federal-Railways.xml

* Add subdomains:
* stories.sbb.ch
* company.sbb.ch
* dima.sbb.ch
* analytics.sbb.ch
* Secure cookies for domain `.sbb.ch`
* Add "CDN" which is used by sbb.ch

[sbb.ch] Add subdomains and CDN

---

src/chrome/content/rules/Conde_Nast_Digital.com.xml

Conde_Nast_Digital.com:

---

src/chrome/content/rules/Ckgs.us.xml

I had some trouble running the automated tests due to setup issues on my machine -- I think this works regardless.

Add rule for Cox & Kings International.

---

src/chrome/content/rules/Wizards.com-problematic.xml
src/chrome/content/rules/Wizards.com.xml

Bug reported in https://trac.torproject.org/projects/tor/ticket/24746

[Wizards.com] Fix broken redirect

---

src/chrome/content/rules/Expedia.com.ar.xml

[Expedia.com.ar] New ruleset

---

src/chrome/content/rules/Abs.ch.xml

Add rules for Alternative Bank Switzerland (ABS)

[abs.ch] Add rule

---

src/chrome/content/rules/aylesburyvaledc.gov.uk.xml

domain enumeration is not performed.

Re-activate and Update aylesburyvaledc.gov.uk.xml

---

src/chrome/content/rules/Expedia.nl.xml

[Expedia.nl] New ruleset

---

src/chrome/content/rules/Expedia.se.xml

[Expedia.se] New ruleset

---

src/chrome/content/rules/Expedia.fi.xml

[Expedia.fi] New ruleset

---

src/chrome/content/rules/Expedia.dk.xml

[Expedia.dk] New ruleset

---

src/chrome/content/rules/Expedia.it.xml

[Expedia.it] New ruleset

---

src/chrome/content/rules/Expedia.es.xml

[Expedia.es] New ruleset

---

src/chrome/content/rules/Expedia.fr.xml

[Expedia.fr] New ruleset

---

src/chrome/content/rules/Expedia.no.xml

[Expedia.no] New ruleset

---

src/chrome/content/rules/Expedia.mx.xml

[Expedia.mx] New ruleset

---

src/chrome/content/rules/Expedia.de.xml

[Expedia.de] New ruleset

---

src/chrome/content/rules/Expedia.ie.xml

[Expedia.ie] New ruleset

---

src/chrome/content/rules/Fedora_Project.org.xml
src/chrome/content/rules/Fedorainfracloud.org.xml

Fedorainfracloud.org.xml

---

src/chrome/content/rules/CIMB-Singapore.xml

[CIMB Singapore] Update domains

---

src/chrome/content/rules/WoolworthsRewards.com.au.xml

[WoolworthsRewards.com.au] New ruleset

---

src/chrome/content/rules/EduId.ch.xml
src/chrome/content/rules/Switch.ch.xml

* Add a domain `eduid.ch` which belong to SWITCH
* Add more subdomains in switch.ch

[Switch.ch] Add rules for domains and subdomains

---

src/chrome/content/rules/Bilibili.com.xml

It had MCB issue previously. but now looks fine.
Remove 'planet2017' which could not be reached.

[bilibili.com] Add 'search' subdomain

---

src/chrome/content/rules/CIMBSecurities.com.xml

[cimbsecurities.com] New ruleset

---

src/chrome/content/rules/Admission.com.xml
src/chrome/content/rules/Ticketmaster.xml

[Ticketmaster] Move admission.com to its own ruleset

---

src/chrome/content/rules/ebay.com.my.xml

[ebay.com.my] New ruleset

---

src/chrome/content/rules/Expedia.co.uk.xml
src/chrome/content/rules/Expedia.com.xml

[Expedia.co.uk] Separate ruleset and add subdomains

---

src/chrome/content/rules/CSdata1.com.xml

Reverts EFForg/https-everywhere#14258.
@gloomy-ghost @Hainish @J0WI Can one of you please merge this? It's breaking Travis, sorry.

Revert "Delete CSdata1.com.xml"

---

src/chrome/content/rules/CrossRef.org.xml

[CrossRef.org] Add targets

---

src/chrome/content/rules/Maybank2u.com.my.xml

[Maybank2u.com.my] New ruleset

---

src/chrome/content/rules/Maybank2e.net.xml

[Maybank2e.net] New ruleset
