EFForg/https-everywhere

src/chrome/content/rules/spkrb.de.xml

This adds a rule for the Bank Sparkasse Rotenburg-Bremervörde

add www.spkrb.de

---

src/chrome/content/rules/MusicBrainz.xml

Add 'picard' subdomain as a target.

Add rule for picard.musicbrainz.org

---

src/chrome/content/rules/NixOS.org.xml

Add rule for NixOS.org

---

src/chrome/content/rules/OEIS.org.xml

Add OEIS.org rule

---

src/chrome/content/toolbar_button.js

TypeError: httpsEverywhere.toolbarbutton is undefined toolbar_button.js:344

fix httpsEverywhere.toolbarbutton is undefined

---

src/chrome/content/rules/Conseil_National_du_Numérique.xml

Hello,
Here is a rule for contribuez.cnnumerique.fr.
Regards,

Rule for contribuez.cnnumerique.fr

---

src/chrome/content/rules/Mentalhealth.asn.au.xml

MCB blocks google web fonts, no big deal.

Added Mentalhealth.asn.au.xml

---

src/chrome/content/code/ApplicableList.js
src/chrome/content/code/ChannelReplacement.js
src/chrome/content/code/Cookie.js
src/chrome/content/code/IOUtil.js
src/components/https-everywhere.js

- Use XPCOMUtils.generateQI instead of our own hand-rolled one.
- Stringify rule.id.
CC @cooperq for code review. @pde I plan on doing a release next Tuesday, but if you decide to do one before then, include this branch.

Improvements in response to feedback from AMO-editors.

---

src/chrome/content/fetch-source.js

Fixes #914 
cc @reedy @cooperq for review.

Change URL to view XML source for rules.

---

src/chrome/content/rules/ThePirateBay.xml

The Pirate Bay: removing nonfunctional domain rules

---

src/chrome/content/code/ChannelReplacement.js
src/chrome/content/code/Cookie.js
src/chrome/content/code/IOUtil.js
src/components/https-everywhere.js
src/components/ssl-observatory.js

Remove spurious INCLUDE(md5).
Restore accidentally-deleted INCLUDE line.
Import XPCCOMUtils where needed.

Fix up some errors.

---

src/chrome/content/rules/Blender.xml

Added blender.org

---

src/chrome/content/rules/OpenStreetMap.de.xml

Added josm.openstreetmap.de

---

src/chrome/content/rules/Forocoches.com.xml

They have fixed mixed content images and they are rolling the change to their production servers right now

Update Forocoches.com, no more mixed content

---

src/chrome/skin/https-everywhere.css

See also: https://trac.torproject.org/projects/tor/ticket/14309

changed green font colour to something darker to solve Tor ticket #14309

---

https-everywhere-tests/README.md

Document manual tests to run before release.

---

test-ruleset-coverage.sh

Account for deleted files in ruleset coverage test.

---

src/chrome/content/rules/Httpbin.org.xml

[httpbin] Added *.httpbin.org

---

src/chrome/content/rules/Cloudfront.xml

[Cloudfront] Updated to new style

---

.travis.yml
src/chrome/content/rules/Blender.org.xml
src/chrome/content/rules/Cloudfront.xml

I thought I had previous restored the coverage test, but I forgot to update .travis.yml.
cc @cooper: I'm submitting this TBR (To Be Reviewed) because it's a test fix.

Restore coverage testing

---

src/chrome/content/rules/Hoodline.com.xml

Add a rule for hoodline.com https://www.hoodline.com/

Add a rule for hoodline.com

---

src/chrome/content/rules/MySQL.xml

```
$ openssl s_client -connect labs.mysql.com:443
connect: Connection refused
connect:errno=111
```

Exclude labs.mysql.com as it is not HTTPS enabled

---

src/chrome/content/rules/XHamster.com.xml

Given it's a top100 site I want to let this fix stay in master a little bit before moving to stable.
The Github issue describes the fix. (exclusion on crossdomain.xml)
Fixes #970

Fix buggy xhamster integration (NSFW)

---

src/chrome/content/rules/Kiva.org.xml

(ie. Exclude /ajax/)
See GitHub Issue #1010 & https://trac.torproject.org/projects/tor/ticket/11645
Was preventing users from adding a loan to a basket.

[Kiva] Remove /ajax/ from being excluded from the exclusion.

---

test-ruleset-coverage.sh

Indicates which docs to read for improvements.
cc @cooperq for code review.

Improve error message for ruleset coverage checker.

---

chromium/popup.html

This change addresses #1119 in order to make the link more explicit.
I also changed the title of the screen displayed to match the link title.
/cc @reedy

Change "Add this site" for clarity.

---

src/chrome/content/rules/Bahn.de.xml
src/chrome/content/rules/Heidelberg.de.xml
src/chrome/content/rules/heidelberg.xml

Updates to bahn.de and heidelberg.de

---

src/chrome/content/rules/Github.xml

Fix #1117 by adding test coverage and reenabling rule

[Github] replace *.github.com and *.githubusercontent.com, use ^http: → https:

---

src/chrome/content/rules/ChemistWarehouse.xml

I plan to keep bugging them until they go full https.

[Chemist Warehouse] Added chemistwarehouse.com.au

---

src/chrome/content/rules/PirateParty.xml

No longer suffers from mixed content

[PirateParty] www.pirateparty.org.au

---

chromium/popup.css
chromium/popup.js
makecrx.sh

Also fix makecrx.sh
cc @cooperq for code review

Only show "Add a rule" on HTTPS sites.

---

src/chrome/content/code/HTTPSRules.js

Cookies are only eligible to be secured if a ruleset matches them using
potentiallyApplicableRulesets. Previously, cookie wildcard domains
(".example.com") happened to match target host wildcards ("<target
host=*.example.com />") through a quirk in the implementation of
potentiallyApplicableRulesets.
However, the new ruleset style guide recommends against including
target host wildcards unless all subdomains are actually rewritten
to HTTPS. Under the old quirky behavior, the cookie domain attribute
".example.com" does not match the target host "example.com".
This change clarifies the function of potentiallyApplicableRulesets and modifies
the cookie-related functions to strip a leading dot before calling
potentiallyApplicableRulesets. This restores cookie securing functionality for
cookies …

Fix cookie securing under new style guide.

---

src/chrome/content/rules/Wikimedia.xml

Add test URLs, remove some hosts that no longer exist.

Re-enable wikimedia rule

---

src/chrome/content/rules/Lanik.us.xml
src/chrome/content/rules/Tumblr.xml

Fix tumblr image CDN and a ruleset validation bug on stable branch

---

src/chrome/content/rules/YouTube.xml

My previous change prepared the ruleset to be re-enabled but didn't actually re-enable it.
Submitting TBR (to be reviewed), cc @cooperq for review.

Re-enable Youtube for real this time.

---

src/chrome/content/rules/Btp.police.uk.xml
src/chrome/content/rules/Cambs.police.uk.xml
src/chrome/content/rules/Essex.police.uk.xml
src/chrome/content/rules/Gwent.police.uk.xml
src/chrome/content/rules/Herts.police.uk.xml
src/chrome/content/rules/Staffordshire.police.uk.xml
src/chrome/content/rules/West-midlands.police.uk.xml

Adding a few UK police websites which support HTTPS (but don't force), as highlighted in this post: https://shkspr.mobi/blog/2014/08/secure-the-police/

Police websites

---

test.sh
utils/make-sqlite.py

Remove DB before changing.
Report version of sqlite3 during testing.
cc @cooperq for code review.

Fix deterministic builds.

---

src/chrome/content/rules/Filippo.io.xml

They're part of the Superfish test at https://filippo.io/Badfish/

Disable intentionally broken subdomains

---

src/chrome/content/rules/OpenStreetMap.xml

cc @diracdeltas for code review.

Disable OpenStreetMap

---

src/chrome/content/rules/NK_News.org.xml

Broken per https://github.com/EFForg/https-everywhere/issues/902

Disable NK News.

---

src/chrome/content/rules/StatusPage.io.xml

Breaks per https://github.com/EFForg/https-everywhere/issues/1224

Disable StatusPage rule.

---

src/chrome/content/rules/Slate.com.xml

Breaks fonts per https://github.com/EFForg/https-everywhere/issues/1228

Disable Slate.

---

src/chrome/content/rules/WatchMedier.xml
src/chrome/content/rules/Webtrekk.net.xml
src/chrome/content/rules/Zen-Internet.xml
src/chrome/content/rules/Zentyal.com.xml
src/chrome/content/rules/Zentyal.org.xml
src/chrome/content/rules/Zoological_Society_of_London.xml
src/chrome/content/rules/Zumzi.xml

This fixes a few rulesets caught in last week's checker decimation.
I didn't go to any effort to make the rulesets perfect or up-to-date, but I did fix the specific issues that the checker caught, so they're not *worse*. I hope.
(I didn't run the checker myself, either. I'm crossing my fingers.)

Fix several minor rulesets

---

src/chrome/content/rules/Adobe.xml

Per https://github.com/EFForg/https-everywhere/issues/1236
and https-everywhere-checker.

Disable Adobe.

---

src/chrome/content/rules/FAZ.xml

The name already mentions these are broken, so just disable them.

Disable the broken FAZ rules

---

src/chrome/content/rules/Slashdot.xml

Per https://github.com/EFForg/https-everywhere/issues/1252

Disable Slashdot

---

src/chrome/content/rules/Corsair.com.xml

Per https://github.com/EFForg/https-everywhere/issues/1233

Disable Corsair.

---

src/chrome/content/rules/DailyDot.xml

Fixes https://github.com/EFForg/https-everywhere/issues/1290

Set platform=mixed for DailyDot.

---

test-ruleset-coverage.sh

Update test-ruleset-coverage and checker version.

---

src/chrome/content/rules/Bit.ly_vanity_domains.xml

Disables bit.ly vanity domain ruleset.

---

src/chrome/content/rules/The_Iconic.com.au.xml

[The Iconic.com.au] Disabled due to breaking functionality

---

src/chrome/content/rules/OkCupid.xml

Fixes https://github.com/EFForg/https-everywhere/pull/1310
cc @Hainish @cooperq for code review.

Disable OkCupid.

---

src/chrome/content/rules/Adbrite.xml
src/chrome/content/rules/Aggregate_Knowledge.xml
src/chrome/content/rules/AllDebrid.com.xml
src/chrome/content/rules/DatacentrumGids.nl.xml
src/chrome/content/rules/Novell.xml
src/chrome/content/rules/Web-Reservations-International.xml
src/chrome/content/rules/Zeromq.xml

Fixes #1316.
cc @Hainish @cooperq for review.

Disable some rulesets that failed ruleset tests.

---

src/components/https-everywhere.js

cc @cooperq @Hainish for code review.

Fix a null reference in https-everywhere.js

---

docs/rulesets.html
src/chrome/content/rules/Federal-Communications-Commission.xml

Fix fcc ruleset

---

chromium/popup.js

Fix bug in rule cache removal (didn't work -- was undefined) and enable strict mode here, too.

[Chrome] Fix popup

---

src/chrome/content/rules/StatusPage.io.xml

Fix StatusPage.io and reenable by default

---

requirements.txt
ruleset-testing.md
src/chrome/content/rules/Center-for-American-Progress.xml
src/chrome/content/rules/Zillow.xml

Fixes https://github.com/EFForg/https-everywhere/issues/1353
Also update requirements.txt and ruleset-testing.md per contributor feedback.

Disable thinkprogress and zillow.

---

chromium/popup.html
chromium/popup.js

[Chrome] Add version to Chrome popup

---

chromium/_locales/de/messages.json
chromium/_locales/en/messages.json
chromium/_locales/es/messages.json
chromium/_locales/fi/messages.json
chromium/_locales/sv/messages.json
chromium/popup.html
src/chrome/content/rules/Bing.net.xml
src/chrome/content/rules/First_Amendment_Center.org.xml
src/chrome/content/rules/How_To_Geek.com.xml
src/chrome/content/rules/Ikea.com.xml
src/chrome/content/rules/Speedtest.net.xml
src/chrome/content/rules/Start.me.xml

Rules are disabled per user reports.
cc @cooperq for code review.

Disable rules and rename "HTTP Nowhere"

---

makexpi.sh
utils/create_xpi.py

AMO version doesn't include updateKey and updateURL.

Modify makexpi to build EFF and AMO versions.

---

src/chrome/content/rules/Scriptfodder.com.xml
src/chrome/content/rules/Scriptfodder.net.xml

* Moved Scriptfodder to the primary domain (scriptfodder.com)
* Added media.scriptfodder.com to the rules

Updated Scriptfodder

---

src/chrome/content/rules/animenewsnetwork.xml

This site has a working non-default HTTPS variant.

Ruleset for animenewsnetwork.com

---

src/chrome/content/rules/moncompteformation.gouv.fr.xml

Hello,
Here is a rule for moncompteformation.gouv.fr.
Regards,

Rule for moncompteformation.gouv.fr

---

src/chrome/content/rules/HBO.xml

HBO.xml: Mixed content breaks the page.

---

src/chrome/content/rules/Arbitrary.ch.xml

arbitrary.ch: initial addition

---

src/chrome/content/rules/Android.xml

Available over https on Google Sites.

add tools.android.com

---

src/chrome/content/rules/Norton.xml

The site apparently doesn't have mixed content any more. 
I've added some minor updates too.

Toggle norton.xml on

---

src/chrome/content/rules/GnuPG.org-problematic.xml
src/chrome/content/rules/GnuPG.org.xml

Moved bugs.gnupg.org to from problematic to main rule

---

src/chrome/content/rules/Allpoetry.xml

Disabled allpoetry.com

---

src/chrome/content/rules/MXToolBox.xml

Disabled MXToolBox.xml

---

src/chrome/content/rules/Disqus.com.xml

I've changed the unreliable ruleset with the wildcard into a partial ruleset. It seems to work for me at the moment, but since I don't have an account there I can't test things like the login process.

Update for disqus.com ruleset

---

makexpi.sh

- This will let the OS disk scheduler seek efficiently

[Nerdsniped] use significant parallelism for warmup IO

---

src/chrome/content/rules/Flickr.xml
src/install.rdf

Fix Flickr login.

---

src/chrome/content/rules/Phoronix.com.xml

Disabled phoronix.com

---

src/chrome/content/rules/donmai.us.xml

Apparently I've forgotten to secure "www.donmai.us" in my last pull...

Minor update to donmai.us ruleset

---

utils/make-sqlite.py

Print out all case insensitive filename conflicts

---

src/chrome/content/rules/UU.se.xml

Updated to the new ruleset style after the old rule had been disabled. Quite a few rules had to be disabled. On the other hand, those that work now also appear to work just fine with mixed content taken into account. (See also issue #1617.)

[UU.se] Revamped ruleset

---

src/chrome/content/rules/Greenpeace.de.xml

[Greenpeace.de] new ruleset

---

src/chrome/content/rules/Greenpeace-magazin.de.xml

[Greenpeace-magazin.de] new ruleset

---

src/chrome/content/rules/UrlQuery.xml

I tested the rule in my browser and didn't spot any issues.

Re-enable urlquery.net

---

src/chrome/content/rules/AlltubeDownload.xml

Hello,
Here is a rule for alltubedownload.net.
Regards,

Rule for alltubedownload.net

---

src/chrome/content/rules/Phillips_Academy_Andover.xml

Add ruleset for Phillips Academy Andover websites.

Add ruleset for Phillips Academy Andover

---

src/chrome/content/rules/Ibood.com.xml

Added a ruleset for ibood.com, a popular site with daily deals.

[Ibood.com] Add ruleset

---

src/chrome/content/rules/Ouvaton.xml

Hello,
Here is a ruleset for ouvaton.coop.
Regards,

Rule for Ouvaton

---

src/chrome/content/rules/Eclipse.xml

Includes tests for marketplace.eclipse.org

HTTPS for marketplace.eclipse.org and wiki.eclipse.org.

---

src/chrome/content/rules/Freifunk-Karlsruhe.de.xml

I've added a simple rule set for freifunk-karlsruhe.de and www.freifunk-karlsruhe.de

Added Freifunk-Karlsruhe.de.xml

---

src/chrome/content/rules/Foxitsoftware.xml

Deactivated rule for www.foxitsoftware.com

---

src/chrome/content/rules/TonyZTan.xml

Add rules for my websites. All of them are HTTPS only. Thanks!

[tonytan.io][tonytan.cn][ztan.tk] New ruleset

---

src/chrome/content/rules/LSI.com.xml

[LSI.com] Disabled ruleset; expired cert

---

src/chrome/content/rules/Bohoomil.com.xml

As stated in #1835, the certificate has expired, and the owner has no plans to have it signed again.

[Bohoomil.com] Disabled ruleset; fixes #1835

---

src/chrome/content/rules/University-of-Southampton.xml

It was probably down because of a fluke

Univerisity of southampton should be fine now

---

src/chrome/content/rules/SSL-Trust.com.xml

Add SSL-Trust.com

---

src/chrome/content/rules/GPUGRID.net.xml

Add GPUGRID.net rule

---

src/chrome/content/rules/Snoonet.xml

Made a ruleset for IRC website Snoonet.org. First ruleset I've submitted, put in a few tests so and it all works on my machine so should be fit for submission!

[Snoonet.org] New ruleset

---

src/chrome/content/rules/YTS.to.xml
src/chrome/content/rules/Yts.re.xml

https://yts.to/blog/important-new-domain-for-yts

Update YTS domain

---

src/chrome/content/rules/Bakabt.me.xml

Add ruleset for big anime download community.

[Bakabt.me] Add ruleset

---

src/chrome/content/rules/Xtremepapers.xml

Follows Ruleset Style Guidelines

New Ruleset Xtremepapers.com

---

src/chrome/content/rules/Ouvaton.xml

Hello,
I've found 2 new domains for the Ouvaton rule.
Regards,

Add new domains to Ouvaton rule

---

src/chrome/content/rules/StartCom.xml

Attempt to fix problem that caused the ruleset to be disabled.

[StartCom] Attempt to fix problem

---

src/chrome/content/rules/BIGO.xml
src/chrome/content/rules/Comingolstadt.xml
src/chrome/content/rules/Infra-Fürth.xml
src/chrome/content/rules/Komro.net.xml
src/chrome/content/rules/M-net.de.xml
src/chrome/content/rules/N-ERGIE.xml
src/chrome/content/rules/NetCologne.xml
src/chrome/content/rules/R-kom.xml
src/chrome/content/rules/REWAG.xml
src/chrome/content/rules/Stadtwerke-Bamberg.xml
src/chrome/content/rules/Stadtwerke-Ingolstadt.xml
src/chrome/content/rules/Sternkom.xml
src/chrome/content/rules/Swu.de.xml
src/chrome/content/rules/smart-DSL.xml

This PR has new and updated rules for small german ISPs and related energy companies

Energy&isp

---

src/chrome/content/rules/Hochschule-Esslingen.xml

hs-esslingen.de uses normal certificate.

---

src/chrome/content/rules/Vox.com.xml

[Vox.com] Disabled ruleset; fixes #1936

---

src/chrome/content/rules/Sanalmarket.xml

[Sanalmarket.com.tr] fixes first half of #847

---

chromium/_locales/de/messages.json
chromium/_locales/en/messages.json
chromium/popup.html

We at Avira want to start contributing to HTTPS-Everywhere (Chrome). Here is a first PR (low hanging fruit). More to come.

I18N support for popup.html. German and English.

---

chromium/background.js
chromium/devtools-panel.js
chromium/popup.js
chromium/rules.js

I have just be studying the internals of https-everywhere. While doing so I added code comments. Hope they help others starting to develop https-everywhere. Enjoy

Added code comments to js files (function headers)

---

src/chrome/content/rules/Dota_2.com.xml
src/chrome/content/rules/Steam.xml
src/chrome/content/rules/Steam_static.com.xml
src/chrome/content/rules/Steamgames.com.xml
src/chrome/content/rules/Valve.xml

Unil a fix for https://github.com/EFForg/https-everywhere/issues/1911 is
arranged.

Disable all steam rulesets

---

src/chrome/content/rules/AmazonAWS.xml
src/chrome/content/rules/League_of_Legends.com.xml

This pull request contains fixes for issue #1980 and #1927
Additionally I rewrote League_of_Legends.com.xml according to the style guidelines and tested it a bit for compatibility.

Fix issues #1980/#1927

---

src/chrome/content/rules/Google_App_Engine.xml

[Google_App_Engine] Exclude sbux-portal.appspot.com

---

src/chrome/content/rules/Wdr.de.xml

added a few more domains to the ruleset and test-urls as well

WDR rule extensions

---

src/chrome/content/rules/Threema.xml

Added domains:  gateway, myid
Added securecookie and styled ruleset

Rewrote threema ruleset

---

src/chrome/content/rules/DD-WRT.xml
src/chrome/content/rules/dd-wrt.com.xml

Cleanup to indicate partial rule and addition of self-signed rule.

dd-wrt.com

---

src/chrome/content/rules/US-government.xml
src/chrome/content/rules/WhiteHouse.gov.xml

I'm thinking of "decentralizing" the US-government.xml.
Federal websites should be in better shape (as in HTTPS support) by now judging by the recent [memorandum](https://www.whitehouse.gov/sites/default/files/omb/memoranda/2015/m-15-13.pdf).

Update US-government.xml (whitehouse.gov)

---

src/chrome/content/rules/Agar.io.xml

See #2056 and #2057.
Thank you.

Disable https for agar.io per #2056

---

src/chrome/content/rules/StarWars.com.xml

Fixes https://github.com/EFForg/https-everywhere/issues/2037

Disable StarWars.com.xml

---

src/chrome/content/rules/tagesschau.de.xml

Tidy up and fix #2074
Correct `altas` to `atlas`.

Update tagesschau.de.xml 

---

.travis.yml

Travis is pushing a Docker-based infra:
http://docs.travis-ci.com/user/migrating-from-legacy/
This PR will probably break ... let's see!

Switch to new Travis infra?

---

src/chrome/content/rules/Veuwer.xml

Fix https://github.com/EFForg/https-everywhere/issues/2114

[Veuwer.xml] New ruleset

---

src/chrome/content/rules/Marvel.com.xml

Excludes wiki due to MCB (https://github.com/EFForg/https-everywhere/issues/1963). Replace * with actual subdomains

[Marvel.com.xml] Update ruleset

---

src/chrome/content/rules/T-Mobile.xml

Seeking review, @reedy, @2d1, @fuglede?

[T-Mobile] Fix and re-enable.

---

src/chrome/content/rules/Twitter.xml

Fixes https://github.com/EFForg/https-everywhere/issues/2075

Add exceptions to Twitter rule.

---

src/chrome/content/rules/bplaced.xml

Fix https://github.com/EFForg/https-everywhere/issues/2091

[bplaced.net] New ruleset

---

src/chrome/content/rules/Hepo.fi.xml
src/chrome/content/rules/Kilometrikisa.fi.xml

Add trivial rules for a couple of Finnish cycling related websites.

Finnish cycling

---

src/chrome/content/rules/Cloudera.com.xml

[Cloudera.com] Disabled blog.cloudera.com and added tests

---

src/chrome/content/rules/Streamfarm.net.xml

Fix jumpradio.de livestream

---

src/chrome/content/rules/Atlassian.xml

Signed-off-by: David Black <dblack@atlassian.com>

Exclude swag.atlassian.com.

---

src/chrome/content/rules/Atlassian.xml

Signed-off-by: David Black <dblack@atlassian.com>

Exclude the new internal office.atlassian.com domain.

---

src/chrome/content/rules/Ecosia.org.xml

Add Ecosia.org rule

---

src/chrome/content/rules/LibreOffice.xml

Explicit subdomains which would exclude invalid subdomains.
Fixes #2271

[LibreOffice] Update ruleset

---

src/chrome/content/code/ApplicableList.js
src/chrome/content/toolbar_button.xul

To decrease confusion about it being an active menuitem.
cc @pde @cooperq for review.

Add disabled attribute to Enable/Disable rules.

---

src/chrome/content/rules/CodingTeam.net.xml

Certificate is no longer expired

Enable CodingTeam.xml

---

src/chrome/content/rules/vanguard.xml

Tested the ruleset via `test.sh` script and [https-everywhere-checker](https://github.com/hiviah/https-everywhere-checker) library. Everything looks good to merge.

Added initial Vanguard.com ruleset

---

src/chrome/content/rules/Maxmind.xml

[Maxmind.com] Update ruleset

---

src/chrome/content/rules/GoExplore.net.xml

[GoExplore.net] New ruleset

---

src/chrome/content/rules/KK.dk.xml

Small bits of mixed content here and there; some pictures of maps missing. Nothing serious (that I could find).

[KK.dk] New ruleset

---

src/chrome/content/rules/Jobfinder.dk.xml
src/chrome/content/rules/Userreport.com.xml

A bit of mixed content here and there but the entire site appears to work fine.

[Jobfinder.dk] New ruleset

---

src/chrome/content/rules/Google.xml

https://www.google.com/registry

Add Google Registry

---

src/chrome/content/rules/Codinghorror.com.xml

Manually tested in Firefox 39.0.3 with HTTPS Everywhere 5.0.7.

Add Coding Horror blog rules

---

src/chrome/content/rules/pr0gramm.com.xml

add more pr0gramm.com subdomains

---

src/chrome/locale/fr/https-everywhere.dtd

Update forgotten french locale in the addon main menu.

[Locale] Add French translation for showCounter

---

src/chrome/content/rules/Peertech.org.xml

false positive, host only response on 443

reenable Peertech.org.xml

---

src/chrome/content/rules/Ouvaton.xml

I have added a domain to the rule.

Update Ouvaton rule

---

src/chrome/content/rules/BR.xml

the bavarian broadcasting station extended TLS to their mainpage recently.

BR-add mainpage

---

src/chrome/content/rules/Bundesverfassungsgericht.xml

remove bverfg.de, add securecookie, simplify rules

[Bundesverfassungsgericht] fix and reenable

---

src/chrome/content/rules/Fastly.net.xml

[Fastly.net] fix Periscope.tv live streaming

---

src/chrome/content/rules/OPM.gov.xml

The infamous OPM.gov. some page has MCB (e.g. [this](https://apps.opm.gov/tax_calc/withhold_calc/index.cfm). not too bad, page is a bit off, but at least the function is still operational.

[OPM.gov] New ruleset

---

chromium/background.js
chromium/manifest.json
chromium/rule_list.js
chromium/util.js

For issue #1327 
Start to split out HTTPS listening from HTTP in Chrome, and some other minor tweaks.

Cleanups & prep for reducing HTTPS listeners

---

makecrx.sh

Create pkg dir before running make-sqlite, otherwise make-sqlite fails to write
output there.
Remove unused "today" build target.
Only run validation if make-sqlite succeeds.
cc @cooperq

Improve makecrx.

---

makexpi.sh

 Fix typo in copying over translations.

---

src/chrome/content/rules/Tilt.com.xml

Hey folks, I'm an engineer at Tilt, and we have a few more exclusions to add and a defunct subdomain to remove from test.

Added blog and ambassador to exclusions

---

src/chrome/content/rules/Exactly-About.info.xml
src/chrome/content/rules/GoNewSoft.com.xml

Delete Exactly-About.info.xml
Old Website
&
Create GoNewSoft.com.xml
New Website

Delete Exactly-About.info.xml & Create GoNewSoft.com.xml

---

https-everywhere-tests/test/test-httpse-installed.js

Reddit now redirect to HTTPS on its own, so is not a good test.

Use LibSSH.org as test URL.

---

src/chrome/content/code/HTTPSRules.js

Remove reference to gone git_commit table.

---

src/chrome/content/rules/Dotplex.de.xml

https://github.com/EFForg/https-everywhere/issues/2324

[dotplex.de] Renew rule

---

src/chrome/content/rules/MedicineNet.com.xml

See https://github.com/EFForg/https-everywhere/issues/2635#issuecomment-133699624 for more details.

[MedicineNet.com] Disable ruleset, comments added

---

src/chrome/content/rules/YouCaring.com.xml

[YouCaring.com] Add exception

---

src/chrome/content/rules/WyzerMe.xml

fixed WyzerMe.xml

---

src/chrome/content/rules/AllDebrid.fr.xml

- certificate chain has been fixed

reenable AllDebrid.fr.xml

---

src/chrome/content/rules/OpenID.xml

- certificate chain has been fixed

reenable OpenID.xml

---

README.md
test/chrome/README.md
test/chrome/script.py

@TheNavigat tiny PR fixes, FYI

Tiny Chrome test cleanups

---

src/chrome/content/rules/transip.de.xml

https://github.com/EFForg/https-everywhere/issues/2324

[transip.de] New ruleset

---

src/chrome/content/rules/Archive.is.xml

[Archive.is] Rename ruleset

---

src/chrome/content/rules/FlixBus.xml

Suggested by https://github.com/EFForg/https-everywhere/issues/2090#issuecomment-119907819

[FlixBus] New ruleset

---

src/chrome/content/rules/Woolworths-AU.xml

For other brands, please create separate ruleset.

[Woolworths Australia] New ruleset

---

src/chrome/content/rules/Wien-IT.xml

adds a rule to cover most of the domains administrated by the it department of the austrian capital city

add ruleset for Wien-IT

---

.travis.yml
install-dev-dependencies.sh
test.sh
test/chromium.sh
test/chromium/script.py
test/firefox.sh
test/rules.sh

Testing cleanups for PR 2731

---

src/chrome/content/rules/Mikaela.info.xml

I hope everything is OK with this, the test script didn't understand Arch (pacman) and my regexp isn't the best possible and I hope the \* matches everything like HSTS IncludeSubDomains.

rules: add Mikaela.info.xml

---

src/chrome/content/rules/HR-Skyen.dk.xml

Marked mixedcontent as one of the subpages has some issues. Devs behind it have been informed.

[HR-Skyen.dk] New ruleset

---

src/chrome/content/rules/jekyllrb.com.xml

Added jekyll, fixes #2621 
(now without this stupid thing https-everywhere-checker - great...)

[jekyllrb.com] New ruleset

---

src/chrome/content/rules/uibk.ac.at.xml

University of Innsbruck, Austria
LFU, OLAT, VPN should all be forced to HTTPS

Ruleset for uibk.ac.at

---

src/chrome/content/rules/Seedrs.xml

There is mixed content at learn.seedrs.com but even with MCB, the site seems fine.

[Seedrs.com] New ruleset

---

src/chrome/content/rules/Christelijke_Mutualiteit.xml

Changes to be committed:
new file:   src/chrome/content/rules/Christelijke_Mutualiteit.xml

New rule for Christelijke Mutualiteit - cm.be

---

src/chrome/content/rules/echo24.cz.xml

The rules were hand tested and the site work 99 % (only some
trackers/ads aren't loaded because of mixed content restrictions)

Add rules for echo24.cz and echomedia.cz domains

---

src/chrome/content/rules/Discourse.org.xml

[Discourse.org] Fix subdomain cdn and simplify ruleset

---

src/chrome/content/rules/Popehat.com.xml

[Popehat.com] Disabled: SSL error

---

src/chrome/content/rules/Habrahabr.ru.xml

The test wants a few more tests for the exclusion pattern. Not quite sure what they're supposed to be. Otherwise fixes #2620.

[Habrahabr.ru] Fix icons

---

src/chrome/content/rules/Datared.dk.xml

[Datared.dk] New ruleset

---

src/chrome/content/rules/QuiteRSS.org.xml

Reverts EFForg/https-everywhere#2835
(meant for master)

Revert "[QuiteRSS.org] Update to new standard"

---

src/chrome/content/rules/Jolla.com.xml

[Jolla.com] Update ruleset

---

src/chrome/content/rules/Dash-Player.com.xml

add rule for Dash-Player.com

---

src/chrome/content/rules/GuerrillaMail.com.xml
src/chrome/content/rules/crazespaces.pw.xml

New domain. also add secure cookie for grr.la since it's used for control panel page.

[Crazespaces.pw] New ruleset

---

src/chrome/content/rules/UPI.com.xml

Fixing UPI.com

---

src/chrome/content/rules/Strugee.net.xml

As a side note, it would be nice if the test framework let me disable tests if I know the website maintainer (me) will check this.

Rewrite subdomains for strugee.net

---

src/chrome/content/rules/Strugee.net.xml

Followup to #2890:
* Inconsistent quoting
* Typo in the comment header

Fix some minor problems with the strugee.net rules

---

ruleset-style.md

Add some minor style details

---

test/chromium/script.py

This implements the change discussed in #2901.

Always provide a default value for the chromedriver_path variable

---

test/chromium/script.py

Since #2903 was merged before I got around to add the change, there's a separate pull request for @TheNavigat's comment on removing some blank lines.

Remove blank lines from chromium test script

---

.gitmodules
.travis.yml
install-dev-dependencies.sh
test/rules.sh

Please don't merge this right away, I made this PR because I want to see how tolerant Travis CI would be before we can merge.

Moving https-everywhere-checker to test/rules

---

src/chrome/content/rules/BrandweerUitgeest.nl.xml

Added a ruleset for the website https://www.brandweeruitgeest.nl

Added a ruleset for website: www.brandweeruitgeest.nl

---

src/chrome/content/rules/Nugg.ad.xml

Used on https://www.dhl.de/de.html

[Nugg.ad] add bei.nuggad.net

---

src/chrome/content/rules/spkrb.de.xml

http://banking.spkrb.de/ works for me, this looks like a temporary error to me.

[spkrb.de] activate again

---

src/chrome/content/rules/AquilaClothing.co.uk.xml

Committing on behalf of a friend.
HTTPS fully supported on this newly set-up site.

Create new ruleset for AquilaClothing.co.uk

---

src/chrome/content/rules/selfhtml.org.xml

Some things of https://github.com/EFForg/https-everywhere/pull/2843 already changed, so I had to update this ruleset.
As more things may change, please do not merge this now.

[selfhtml.org.xml] Update

---

src/chrome/content/rules/Surfeasy.com.xml

[Surfeasy.com] Update ruleset

---

src/chrome/content/rules/Threema.xml

[Threema.xml] New subdomain

---

src/chrome/content/rules/TorrentShack.xml

Adding a ruleset for the TorrentShack private tracker.

[TorrentShack] New ruleset

---

src/chrome/content/rules/realfavicongenerator.net.xml

Tidy https://github.com/EFForg/https-everywhere/pull/3038 up

[RealFaviconGenerator.net] Cleanup spaces and stuff

---

src/chrome/content/rules/Getbootstrap.com.xml

[Getbootstrap.com] New ruleset

---

src/chrome/content/rules/Eset.xml

Added subdomain *help.eset.com* and *ela.eset.com* and more...

[ESET] Add subdomains

---

src/chrome/content/rules/Carezone.cz.xml

Added ruleset for webhosting Carezone.cz.

[Carezone.cz] New ruleset

---

src/chrome/content/rules/Carezone.cz.xml

Added subdomains roundcube and squirrel to ruleset Carezone.cz.

[Carezone.cz] Added subdomains roundcube and squirrel to ruleset

---

src/chrome/content/rules/Carezone.cz.xml
src/chrome/content/rules/tetadrogerie.cz.xml

Added ruleset for drugstore teta (tetadrogerie.cz).

[tetadrogerie.cz] Added ruleset

---

src/chrome/content/rules/rage4.com.xml
src/chrome/content/rules/royaldns.net.xml

Next try of https://github.com/EFForg/https-everywhere/pull/2490
https://github.com/EFForg/https-everywhere/issues/2324

[Rage4] New ruleset

---

src/chrome/content/rules/AmazonAWS.xml

[AmazonAWS] Add exception for Scratchpad

---

src/chrome/content/rules/Ruhr-Uni-Bochum.de-falsemixed.xml
src/chrome/content/rules/Ruhr-Uni-Bochum.de.xml
utils/duplicate-whitelist.txt

This fixes https://github.com/EFForg/https-everywhere/issues/3009

[Ruhr-Uni-Bochum.de] Add some exceptions

---

src/chrome/content/rules/Bebo.com.xml

Add rule for bebo.com

---

src/chrome/content/rules/Loverslab.com.xml

#3133
Contains unimportant mixed content on some single pages.

Add rule for loverslab.com

---

src/chrome/content/rules/Certificate-transparency.org.xml
src/chrome/content/rules/GoogleServices.xml

[Certificate-Transparency.org] New ruleset

---

src/chrome/content/rules/Ecosia.org.xml

[Ecosia.org.xml] Added subdomain

---

src/chrome/content/rules/Passwort-generator.com.xml

[Passwort-generator.com] New ruleset

---

src/chrome/content/rules/Lasallehs.net.xml

Updated HTTPS-enabled domains for lasallehs.net. I also tried to make the rules a bit more concise.

Lasallehs.net - Update ruleset

---

src/chrome/content/rules/Pastemarkdown.com.xml

[Pastemarkdown.com.xml] New ruleset

---

src/chrome/content/rules/Badssl.com.xml

Rewritten to:
* add test URLs
* exclude URLs which (potentially) manipulate tests
* convert to spaces

[Badssl.com] Rewrite ruleset

---

src/chrome/content/rules/DN.no.xml

add rule for DN.no

---

src/chrome/content/rules/Backblaze.com.xml

Simplify (no mismatch issue anymore) and add new subdomain.

[Backblaze.com] Update ruleset

---

src/chrome/content/rules/SKortekaas.nl.xml

Added the website www.skortekaas.nl to the ruleset. It has the new Let's Encrypt certificate.

Addes the website skortekaas.nl to the ruleset

---

src/chrome/content/rules/EduPage.xml

Added rule for school management system EduPage.

[EduPage] Added ruleset

---

src/chrome/content/rules/OTR.to.xml

This fixes https://github.com/EFForg/https-everywhere/issues/3236.

[OTR.to] New ruleset

---

src/chrome/content/rules/Idevelop.ro.xml

[Idevelop.to] New ruleset

---

src/chrome/content/rules/checkmyrota.xml

Cert isn't valid for www. and there are no server side rewrite rules.

Checkmyrota.com (Argos UK employee rota) rules

---

src/chrome/content/code/NSS.js

This is already declared in ssl-observatory.js
cc @cooperq for review
Fixes #3222 
Fixes #3223

Remove redeclaration of tcypes.

---

src/chrome/content/rules/Qt.io.xml

Added subdomains to qt.io

---

src/chrome/content/rules/Gutenberg.org.xml

Fixed typo Gutenburg --> Gutenberg

---

.travis.yml

Fixes https://github.com/EFForg/https-everywhere/issues/2244 :laughing: 
An easy fix... (hopefully)

Require at least FF 40.0

---

src/chrome/content/rules/CodeWeavers.xml

Remove obsolete domain (.fr), simplify ruleset.

[CodeWeavers.com] Update ruleset

---

src/chrome/content/rules/DataSavesLives.eu.xml

Some mixed content here and there; a Google font is blocked but the site works fine.

[DataSavesLives] New ruleset

---

src/chrome/content/rules/Codemirror.net.xml

a simple ruleset
[HTTPS config report](https://discuss.codemirror.net/t/https-config-improvable/565)

[Codemirror] New ruleset

---

src/chrome.manifest

update chrome manifest for new locales

---

test/firefox/test_profile_skeleton/prefs.js

disable signature checking requirement for new versions of firefox

---

src/chrome/content/rules/overpass-turbo.eu.xml

add overpass-turbo.eu

---

src/chrome/content/rules/Conde_Nast_Digital.com.xml

- add event, pixel & capture subdomains

CondeNast Digital:

---

src/chrome/content/rules/Threema.xml

[Threema] Add domain

---

src/chrome/content/rules/Copperhead.co.xml

[Copperhead.co] Added Cloudflare note

---

rewriter/.gitignore

Ignore node_modules folder in rewriter dir.

---

src/chrome/content/rules/Mega.xml

[Mega] Update ruleset

---

src/chrome/content/rules/CeskaPosta.cz.xml

[CeskaPosta.cz] Added ruleset

---

src/chrome/content/rules/KRAXNET.cz.xml

[KRAXNET.cz] Added ruleset

---

src/chrome/content/rules/Levny-hosting.cz.xml

[Levny-hosting.cz] Reenable ruleset (certificate is valid)

[Levny-hosting.cz] Reenable ruleset (certificate is valid)

---

src/chrome/content/rules/Symbolab.com.xml

[Symbolab.com] New ruleset

---

src/chrome/content/rules/DoesNotWork.eu.xml
src/chrome/content/rules/Nebezi.cz.xml

Added rulesets for Nebezi.cz and DoesNotWork.eu. This websites work only on IPv6.

[Nebezi.cz] Added ruleset

---

src/chrome/content/rules/vas-hosting.cz.xml

[vas-hosting.cz] Added ruleset

[vas-hosting.cz] Added ruleset

---

src/chrome/content/rules/FakaHeda.eu.xml

[Fakaheda.eu] Added ruleset

---

src/chrome/content/rules/Sdilej.cz.xml

[Sdilej.cz] Added ruleset

---

src/chrome/content/rules/KOSMAS.cz.xml

[KOSMAS.cz] Added ruleset

---

src/chrome/content/rules/bux.cz.xml

[bux.cz] Added ruleset

---

src/chrome/content/rules/tsbohemia.cz.xml

[tsbohemia.cz] Added ruleset

---

src/chrome/content/rules/skolaonline.cz.xml

[skolaonline.cz] Added ruleset

[skolaonline.cz] Added ruleset

---

src/chrome/content/rules/Dein.dk.xml
src/chrome/content/rules/Sigdet.nu.xml

This adds two related hosts whose certificates are signed by Let's Encrypt.

[Sigdet.nu] [Dein.dk] New rulesets

---

src/chrome/content/rules/lackname.org.xml

[lackname.org] New ruleset

---

src/chrome/content/rules/UPC.cz.xml

[UPC.cz] Added ruleset

---

src/chrome/content/rules/PPL.cz.xml

[PPL.cz] Added ruleset

---

src/chrome/content/rules/cesky-hosting.cz.xml

[cesky-hosting.cz] Added ruleset

[cesky-hosting.cz] Added ruleset

---

src/chrome/content/rules/Strava.cz.xml

[Strava.cz] Added ruleset

---

src/chrome/content/rules/BANAN.cz.xml

[BANAN.cz] Added ruleset

---

src/chrome/content/rules/Deutscher-radiopreis.de.xml
src/chrome/content/rules/Eurovision.de.xml
src/chrome/content/rules/Medienstiftung-hsh.de.xml
src/chrome/content/rules/N-JOY.de.xml
src/chrome/content/rules/Ndr.de.xml
src/chrome/content/rules/Pfefferkoerner.de.xml
src/chrome/content/rules/Sesamstrasse.de.xml
src/chrome/content/rules/Spielfuerdeinland.de.xml

I'd recommend testing them a bit.
As for the exclusion at Spielfuerdeinland.de.xml this maybe will not be
neccessary in the future. I'm in contact with a site admin there.

New rulesets from NDR sites

---

src/chrome/content/rules/Motorola.de.xml
src/chrome/content/rules/Motorola.xml

One could merge this rule into the existing "Motorola.xml" but I haven't done it because there are missing tests.

New rule for motorola.de

---

src/chrome/content/rules/Symantec.xml

I had to push using ```no-verify``` to get this through. It's a bit too much to refactor the whole thing while the fix is that simple.

Fixing #2880

---

src/chrome/content/rules/lebsanft.org.xml
src/chrome/content/rules/pandasoph.de.xml
src/chrome/content/rules/veggiekarte.de.xml

Added more domains to my private ruleset now that the let's encrypt certificate covers all of them

Add more domains to the cert now that let's encrypt is alive

---

src/chrome/content/rules/Billiongraves.com.xml
src/chrome/content/rules/Mhcache.com.xml
src/chrome/content/rules/Myheritage.xml
src/chrome/content/rules/Myheritageimages.com.xml

MyHeritage is disabled by default, because there are iframes whown on the site, which cause mixed content errors.
Billiongraves has some errors, but I am in contact with them so maybe they may be fixed in the near future.

[MyHeritage] (Billiongraves.com] New rulesets

---

src/chrome/content/rules/Nicereply.com.xml

Sorry, did not saw this error in https://github.com/EFForg/https-everywhere/pull/3191

[Nicereply.com] Fix securecookie

---

src/chrome/content/rules/Posteo.xml

New subdomain: autodiscover
Added securecookie (just as a fallback :smile:)
Cleanup: use 4 spaces indentation everywhere

[Posteo.de] Added subdomain & cleanup

---

src/chrome/content/rules/Lloydsbank.com.xml

The certificate doesn't support the bare domain.

Add www.lloydsbank.com

---

src/chrome/content/rules/Deb.li.xml
src/chrome/content/rules/Debian.xml

Forwarded from @pabs3:
https://lists.eff.org/pipermail/https-everywhere-rules/2015-November/002269.html

[Deb.li] New ruleset

---

src/chrome/content/rules/Debian.xml

Forwarded from @pabs3:
https://lists.eff.org/pipermail/https-everywhere-rules/2015-November/002270.html

[Debian] Add appstream.debian.org, jenkins.debian.org

---

src/chrome/content/rules/Apkmirror.com.xml

https://twitter.com/rugkme/status/678190574474797058

[Apkmirror.com.xml] New ruleset

---

src/chrome/content/rules/Codecademy.com.xml

The discussion about HTTPS for the other subdomains is here:
http://discuss.codecademy.com/t/suggestion-https-on-subdomains/7935

[Codeacademy.com] Activate and update/fix ruleset

---

src/chrome/content/rules/prntscr.com.xml

Prntscr.com

---

src/chrome/content/rules/NewYorkVocalCoaching.xml

Rule for NewYorkVocalCoaching.com and associated websites

add rule for NYVC

---

src/chrome/content/rules/Fefe.xml

full chain is sent, lets encrypt instead of cacert

reflect certificate changes on fefe.de

---

src/chrome/content/rules/Fefe.xml

to fix #3510 (instead of #3515)

updated Fefe.xml to reflect new certificates from Let's Encrypt

---

src/chrome/content/rules/Seznam.cz.xml

- Added other Seznam.cz rulesets
- Added domain lab.email.seznam.cz to ruleset
- Edit rules for domains

[Seznam.cz] Edited ruleset

---

src/chrome/content/rules/Web.de.xml

Web.de: convert to new style & add more subdomains

---

src/chrome/content/rules/Blackfire.io.xml
src/chrome/content/rules/Sensiolabs.com.xml
src/chrome/content/rules/Symfony.com.xml

Including:
* Sensiolabs.com
* Symfony.com
* Blackfire.io

Add SensioLabs rulesets

---

src/chrome/content/rules/Holarse-LinuxGaming.de.xml

We now have a proper certificate.

Holarse Linuxgaming now has a proper certificate

---

src/chrome/content/rules/Posteo.xml

Improving @posteo ruleset again...

[Posteo.de] Add subdomains

---

src/chrome/content/rules/Cloudfront.xml

acinitiates.com fails on http -> https redirects

acinitiates.com fix

---

src/chrome/content/rules/Live.xml

Fix non-standard wildcard in Live.xml

---

src/chrome/content/rules/Lotame.xml
src/chrome/content/rules/Maker.tv.xml
src/chrome/content/rules/Picload.xml
src/chrome/content/rules/Polar.me.xml
src/chrome/content/rules/Reuters.com.xml
src/chrome/content/rules/Springserve.com.xml
src/chrome/content/rules/Theadex.xml
src/chrome/content/rules/Wurfljs.com.xml
src/chrome/content/rules/Xplosion_interactive.xml
src/chrome/content/rules/Yieldbot.xml
src/chrome/content/rules/Yieldlab.net.xml
src/chrome/content/rules/ZQTK.net.xml
src/chrome/content/rules/declaredthoughtfulness.xml

todays batch of updates for external content that is embedded on websites.

12 2015 3dparty

---

src/chrome/content/rules/OpenStreetMap.org-falsemixed.xml
src/chrome/content/rules/OpenStreetMap.org.xml

www.openstreetmap.org no longer has the MCB issue:
https://github.com/openstreetmap/openstreetmap-website/commit/0d2e160

[OpenStreetMap.org] securecookie, remove MCB

---

src/chrome/content/rules/Dynatech.de.xml
src/chrome/content/rules/Dynavision.de.xml
src/chrome/content/rules/Scieneo.de.xml

Dynatech.de
Dynavision.de
Scieneo.de

Add rulesets for sites by Mirco Neubert

---

src/chrome/content/rules/GRML.org.xml

[RC4] Update GRML.org.xml

---

src/chrome/content/rules/EpochStats.com.xml

[RC4] Update EpochStats.com.xml

---

src/chrome/content/rules/Literature_and_Latte.com.xml

[RC4] Update Literature_and_Latte.com.xml

---

src/chrome/content/rules/Atagar.com.xml

[RC4] Update Atagar.com.xml

---

src/chrome/content/rules/Extreme_Tech.com.xml

[ExtremeTech] broken, disable

---

src/chrome/content/rules/Chris_Newland.com.xml

[RC4] Update Chris_Newland.com.xml

---

src/chrome/content/rules/Stpeter.im.xml

[RC4] Update Stpeter.im.xml

---

src/chrome/content/rules/NASA.gov.xml

[RC4] Update NASA.gov.xml

---

src/chrome/content/rules/ManageEngine.xml

[RC4] Update ManageEngine.xml

---

src/chrome/content/rules/Private-Layer.xml

Re-open https://github.com/EFForg/https-everywhere/pull/3579. Previous cert issue has been resolved.

[privatelayer.com] New ruleset

---

src/chrome/content/rules/GrandMargherita.com.xml
src/chrome/content/rules/RiversideMajestic.com.xml

Also include new ruleset for riversidemajestic.com

[grandmargherita.com] New ruleset

---

src/chrome/content/rules/freenode.xml

In particular, this takes care of #3766.

[Freenode] Add freenode.org

---

src/chrome/content/rules/Hvidovrekajakklub.dk.xml

Some mixed content here and there, but nothing that appears to break site function.

[Hvidovrekajakklub.dk] New ruleset

---

src/chrome/content/rules/SciPy.org.xml

This adds a working target host and updates the ruleset comment.

[SciPy.org] Update ruleset

---

src/chrome/content/rules/Blazeti.me.xml

[Blazeti.me] New ruleset

---

src/chrome/content/rules/Uneddit.xml

Per the request to split #3805 into separate PRs for each of the rulesets, here's the PR for adding a rule for uneddit.com.

Add rule for uneddit.com

---

src/chrome/content/rules/pro.hostingas.lt.xml

Per the request to split #3805 into separate PRs for each of the rulesets, here's the PR for adding a rule for pro.hostingas.lt.

Add rule for pro.hostingas.lt

---

src/chrome/content/rules/irc.lc.xml

Per the request to split #3805 into separate PRs for each of the rulesets, here's the PR for adding a rule for irc.lc.

Add rule for irc.lc

---

src/chrome/content/rules/Dizaineriai.lt.xml

Per the request to split #3805 into separate PRs for each of the rulesets, here's the PR for adding a rule for dizaineriai.lt.

Add rule for dizaineriai.lt

---

src/chrome/content/rules/Dedikuoti.lt.xml

Per the request to split #3805 into separate PRs for each of the rulesets, here's the PR for adding a rule for dedikuoti.lt.

Add rule for dedikuoti.lt

---

.travis.yml

See: https://docs.travis-ci.com/user/trusty-ci-environment/
Signed-off-by: Nick Semenkovich \<semenko@alum.mit.edu\>

Switch to Travis Trusty environment on GCE

---

src/chrome/content/rules/Nullday.de.xml

hello,
I've added my website.
I hope the ruleset is okay like this was struggling first.. but should be ok like this.

new ruleset

---

src/chrome/content/rules/Ipfs.io.xml

[Ipfs.io] New ruleset

---

src/chrome/content/about.xul

cc @J0WI @fuglede @semenko @reedy: I'm assuming you're fine being listed here. Let me know if you'd prefer otherwise. Thanks!

Update ruleset librarians section of about page.

---

src/chrome/content/rules/DailyKos.xml

Updates https://github.com/EFForg/https-everywhere/pull/3192

[DailyKos] Simplify ruleset.

---

src/chrome/content/rules/Ripe.net.xml

matches all (and future) RIPE meeting websites (ripe[nn].ripe.net)

[ripe.net] added ruleset

---

src/chrome/content/rules/FreeDesktop.xml

Fixed https://github.com/EFForg/https-everywhere/issues/3864

[FreeDesktop.org] Remove redundant rules, add exceptions.

---

src/chrome/content/rules/GoogleAPIs.xml

e.g. https://fonts.gstatic.com/s/roboto/v15/d-6IYplOFocCacKzxwXSOFtXRa8TVwTICgirnJhmVJw.woff2

[Google APIs] Add fonts.gstatic.com

---

src/chrome/content/rules/HealthTap.xml

Re-open https://github.com/EFForg/https-everywhere/pull/3841. Removed `blog` due to mixed content.

[healthtap.com] New ruleset

---

src/chrome/content/rules/Endchan.xyz.xml
src/chrome/content/rules/Infinow.net.xml

This commit adds HTTPS Everywhere rules for the [Endchan](https://infinow.net/) imageboard.

Add Endchan Rules

---

src/chrome/content/rules/Virgin_Media.com.xml

Tidied up and fixed rules for virginmedia.com

Updated Virgin Media rules

---

src/chrome/content/rules/Booking.com.xml
src/chrome/content/rules/Villas.com.xml

Hi, Booking.com dev here. Nowadays everything should take HTTPS properly, let's update the rules to match that!

Update Booking.com, add Villas.com (same company)

---

src/chrome/content/rules/Takeaway.com.xml
src/chrome/content/rules/Thuisbezorgd.nl.xml

Copied from Pizza.fr.xml which is also Takeaway.com

Add a rule for thuisbezorgd.nl

---

src/chrome/content/rules/HKEdCity.xml

Site does not support https on subdomains.

[hkedcity.net] new ruleset

---

src/chrome/content/rules/Plays.tv.xml

add rule for Plays.tv

---

src/chrome/content/rules/DN.dk.xml

Most references seem to be securable, but all content pages redirect to HTTP.

[DN.dk] New ruleset

---

.travis.yml
test/chromium/script.py

Now that Travis containers on GCE support sudo, let's try installing this package from apt.

Switch to apt chromedriver with latest Travis

---

src/chrome/content/rules/xkcd.xml

(And fix a typo (or sed-o) in a comment.)

[xkcd] Disable hosts with certificate chain issues

---

chromium/_locales/de/messages.json
chromium/_locales/en/messages.json
chromium/_locales/es/messages.json
chromium/_locales/fi/messages.json
chromium/_locales/fr/messages.json
chromium/_locales/sv/messages.json
chromium/popup.html

Fix Chrome keyboard accessibility

---

src/chrome/content/code/AndroidUI.jsm
src/chrome/content/code/ApplicableList.js
src/chrome/content/code/HTTPSRules.js
src/chrome/content/toolbar_button.js
src/chrome/skin/https-everywhere.css
utils/make-sqlite.py
utils/merge-rulesets.py
utils/relaxng.xml
utils/simple.py
utils/trivial-validate.py

This caused a regression: Rules that are active but not taking effect (formerly
moot rules) are simply not listed, when my intention was to list them (i.e.,
match the Chrome behavior).
Will roll forward again when I have a fix, but didn't want to leave things in a
broken state until then.
cc @semenko for review.

Revert #3883.

---

src/chrome/content/rules/nerdster.org.xml

New trivial rule for nerdster.org.

Add simple rule for nerdster.org domain.

---

src/chrome/content/rules/Radware.com.xml

Followup of https://github.com/EFForg/https-everywhere/pull/3183

[Radware.com] New ruleset

---

src/chrome/content/rules/www.browserscope.org.xml

Browserscope is available over HTTPS as of yesterday!

Add www.browserscope.org

---

src/chrome/content/rules/Git.io.xml

And removed unneccessary empty lines.

[Git.io] Activate ruleset

---

src/chrome/content/rules/AustralianAlpsNationalParks.xml

Covered by https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/WordPress.xml

[theaustralianalps.wordpress.com] Remove redundant rule

---

src/chrome/content/rules/GetFirebug.xml

As far as I see there is no mixed content anywhere.

[GetFirebug] Rewrite and activate

---

src/chrome/content/rules/Xdebug.org.xml

@xdebug seems to support HTTPS now thanks to Let's Encrypt.
/cc @derickr

[Xdebug.org] New ruleset

---

src/chrome/content/rules/RenderFarming.net.xml

Add burp.renderfarming.net rules

[BURP] New ruleset

---

src/chrome/content/rules/Nugg.ad.xml

We are serving for http and https versions for all our tracking subdomains. I've also added our main company site.

[nugg.ad] Fix subdomain handling for nuggad.net

---

src/chrome/content/rules/Cloudfront.xml
src/chrome/content/rules/LongTail.xml

Fix PBS video in Cloudfront rule

---

chromium/rules.js
ruleset-style.md

Expand use of trivial_cookie_name_c
Point ruleset-style wolframalpha link to HTTPS

Expand use of trivial_cookie_name_c

---

src/chrome/content/rules/WineHQ.xml

Update WineHQ rule to add "dl" and (now working) "wiki" subdomains.

[WineHQ] Update rule

---

chromium/popup.css
chromium/popup.html
chromium/popup.js

Hide rules if extension is disabled [Chrome]

---

src/chrome/content/rules/DNSCurve.xml

Trying broken PR https://github.com/EFForg/https-everywhere/pull/4015 again.

[DNSCurve] New ruleset

---

src/chrome/content/rules/Wj32.org.xml

Some notes for the web admin @wj32:
* Pretty bad SSL config (already submitted you some more information)
* On https://wj32.org/wp/ there is some mixed content. You can easily fix it as it as it is just on your own site.

[Wj32.org] New ruleset

---

src/chrome/content/rules/Stack-Exchange.xml

Excluded http://elections.stackexchange.com

---

src/chrome/content/rules/MPlayer.xml

Add new subdomains (bugzilla, ffmpeg, samples, trac) and remove comment.

[MPlayer] Update ruleset

---

.gitignore
install-dev-dependencies.sh

Added common vagrant files to the ignore list and added git to the of packages to install for debian based systems in case the dev system does not already have it.

Vagrant additions

---

src/chrome/content/rules/CreativeCommons.xml

[Creative Commons] Addded subdomains, secured cookies, improved cosmetics

---

src/chrome/content/rules/NVidia.xml

Untested change that should resolve https://github.com/EFForg/https-everywhere/issues/4028

[NVidia] Workaround Chrome bug

---

src/chrome/content/rules/Computerbase.de.xml

- add test-urls and more files
- remove stylesheets path, not used anymore
- remove wildcard
- fix forum editor

Computerbase.de:

---

src/chrome/content/rules/PrimeGrid.com.xml

[PrimeGrid] Add new rule

---

src/chrome/content/rules/NetCologne.xml

- enable mirror subdomain
- add debian subdomain

Netcologne: add mirror domains

---

src/chrome/content/rules/Syncthing.net.xml

FIX: discourse.syncthing.net has moved to forum.syncthing.net
ADD: docs.syncthing.net

Fix syncthing.net issue

---

chromium/popup.html
chromium/popup.js
src/chrome/locale/en/https-everywhere.dtd

Fixes lost translations & chrome.tabs.query bug.

Fix regressions in custom rule functions

---

src/chrome/locale/en/https-everywhere.dtd

Adding this initial English string so Transifex will pick it up and add it to the translations submodule for all other languages.

Add English string for 'Donate to EFF'

---

src/chrome/content/rules/Motley-Fool.xml

Eg: http://www.fool.com/investing/general/2013/10/12/facebooks-incredible-growth-story-in-6-charts.aspx

[Motley-fool] breaks images, disable

---

src/chrome/content/rules/simpel.nl.xml

Simple ruleset for simpel.nl (heh).

Simple.nl ruleset

---

src/chrome/content/rules/songkick.com.xml

Simple ruleset for songkick.com

Songkick ruleset

---

src/chrome/content/rules/songkick.com.xml

This adds a few subdomains as well as comments about broken ones.

[Songkick] Update ruleset

---

src/chrome/content/rules/LandscapePhotographyMagazine.com.xml
src/chrome/content/rules/WildPlanetPhotoMagazine.com.xml

https://wildplanetphotomagazine.com/
https://landscapephotographymagazine.com/
@J0WI trivial, no subdomains.

Add 2 digital magazine websites

---

src/chrome/content/rules/3sat.xml

disable 3sat for now

---

src/chrome/content/rules/Rkn.gov.ru.xml

- Add
- rkn.gov.ru
- www.rkn.gov.ru
- reestr-svyaz.rkn.gov.ru
- pd.rkn.gov.ru
- eng.rkn.gov.ru

rkn.gov.ru

---

src/chrome/content/rules/Play0ad.com.xml
src/chrome/content/rules/Wildfiregames.com.xml

They've updated the forum: https://wildfiregames.com/forum/index.php?/topic/20426-planned-forum-upgrade-downtime/&page=1

Add Play0ad.com and Wildfiregames.com rulesets

---

src/chrome/content/rules/Infogr.am.xml

This fixes https://github.com/EFForg/https-everywhere/issues/4182 (rather inelegantly).

[Infogr.am] Add exclusions

---

src/chrome/content/rules/Fullrate.xml

https://fullrate.dk = invalid cert

Redirect fullrate.dk to www.fullrate.dk

---

src/chrome/content/rules/Wild-West-Domains.xml

Same problem as #4299, #4300, #4301, #2980.

Fix invalid RegExp in Wild-West-Domains.xml

---

src/chrome/content/rules/infosactu.com.xml
src/chrome/content/rules/ultimedecathlon.com.xml

Rulesets for :  
* infosactu.com   
* ultimedecathlon.com

Create new rulesets for infosactu.com and ultimedecathlon.com

---

src/chrome/content/rules/GoogleAPIs.xml

GoogleAPIs: add imasdk subdomain

---

src/chrome/content/rules/TheReadingRoom.com.xml

[TheReadingRoom.com] Update ruleset

---

src/chrome/content/rules/LongTail.xml

Simply a quick review of all the domains in this rule to fix https://github.com/EFForg/https-everywhere/issues/4216 before next release.

[LongTail] Comment out invalid rules, closes #4216

---

src/chrome/content/rules/SparkLabs.com.xml

[SparkLabs.com] Added new targets

---

src/chrome/content/rules/0bin.net.xml

BTW the server is vulnerable to the [Logjam attack](https://weakdh.org/).
https://www.ssllabs.com/ssltest/analyze.html?d=0bin.net
@sametmax

[0bin.net] New ruleset

---

src/chrome/content/rules/Thecthulhu.com.xml

- Add `annefrank`, `cryptome`, `fbidhs`, `fop`, `hp`, `insurance`, `mirror`, `nasadrones`, `patreon` and `turkey`
- Disable `hacked` (temporary `NXDOMAIN`)
- Sort hosts
- Trim comments

[Thecthulhu.com] Update hosts, trim comments

---

src/chrome/content/rules/CTAN.org.xml

This closes https://github.com/EFForg/https-everywhere/issues/3975.

[CTAN] New ruleset

---

rewriter/rewriter.js

Also update it to always rewrite to HTTPS, rather than protocol-relative.
cc @Hainish for review.

Fix rewriter.js, which went out of date.

---

utils/duplicate-whitelist.txt
utils/trivialize-rules/.gitignore
utils/trivialize-rules/package.json
utils/trivialize-rules/trivialize-rules.js

This PR sources the script by @RReverser from #4311, adding it to utils/ and running it on the ruleset.
Since #4311 contained so many ruleset changes, we decided it would be best to audit the script to ensure proper behavior, and re-run it against the latest ruleset.  I have done so, and noticed no unusual behavior after manually checking dozens of ruleset changes.

Trivialize rules

---

src/chrome/content/rules/PopCash.net.xml

PopUnder Advertiser , nevertheless it should be secured.

add rule for PopCash.net

---

src/chrome/content/rules/FitBit.xml

[FitBit] Enable and update ruleset
@J0WI lay it on me :)

[FitBit] Enable and update ruleset

---

src/chrome/content/rules/EDP.pt.xml
src/chrome/content/rules/Mouseflow.xml
src/chrome/content/rules/Qt-project.org.xml
utils/trivial-validate.py

Ready for review @cooperq @jsha

Fix trivial validate

---

src/chrome/content/rules/Something-Awful.xml

SA has now deployed SSL on most parts of the site so here are the updated rules. Many thanks!

Updated rules for somethingawful.com

---

src/chrome/content/rules/D2jsp.org.xml

They recently implemented HTTPS, so I thought to make some basic rules and submit them.

Add d2jsp.org and subdomains

---

src/chrome/content/rules/umblr.com.xml

[umblr.com] Disable; only existing rule is broken

---

src/chrome/content/rules/ASP.NET.xml
src/chrome/content/rules/IIS.net.xml

- Add
- forums.iis.net
- blogs.iis.net
- www.asp.net
- asp.net
- get.asp.net
- docs.asp.net
- hosting.asp.net
- weblogs.asp.net
- forums.asp.net
- live.asp.net
- samples.asp.net
- quickstarts.asp.net
- ajax.asp.net
- Remove
- learn.iis.net

iis.net and asp.net

---

src/chrome/content/rules/bloomsky.com.xml

Mixed content issue is related to https://github.com/EFForg/https-everywhere/pull/4040.

[bloomsky.com] New ruleset

---

src/chrome/content/rules/Unizar.es.xml

Add portaltransparencia.unizar.es.

Update Unizar.es.xml (trivial addition)

---

src/chrome/content/rules/Udacity.com-mismatches.xml
src/chrome/content/rules/Udacity.com.xml

Udacity recently added some new subdomains. Patching them in.

Add new Udacity subdomains.

---

src/chrome/content/rules/Yuri-ism.com.xml
src/chrome/content/rules/Yuri-ism.net.xml
src/chrome/content/rules/Yuri-ism.xml

(Whoohoo [WordPress.com](https://en.blog.wordpress.com/2016/04/08/https-everywhere-encryption-for-all-wordpress-com-sites/)!)

Move Yuri-ism.net.xml to Yuri-ism.xml, add yuri-ism.com (NSFW)

---

src/chrome/content/rules/Archive.is.xml

* Add archive.li and www.archive.li (fixes #4556)
* Add blog.archive.li and blog.archive.today
* Change comments

[Archive.is] Add archive.li (fixes #4556) and other hosts

---

src/chrome/content/rules/HolidayExtras.com.xml
src/chrome/content/rules/Merlinbreaks.co.uk.xml
src/chrome/content/rules/legolandholidays.co.uk.xml

Mainly for legolandholidays.co.uk, other 2 rulesets are to secure mixed content of that website.

[legolandholidays.co.uk] New ruleset

---

src/chrome/content/rules/India.gov.in.xml

[New rule set] Adding a trivial ruleset for india.gov.in

[New rule set] Adding a trivial ruleset for india.gov.in

---

src/chrome/content/rules/ArXiv.xml

The entire site appears to work now. I've sent them a query regarding the possibility of re-enabling it by default.

[ArXiv] Update ruleset

---

src/chrome/content/rules/Red_Hat.xml

* fix jobs - no longer goes to third party url
* fix investors url

Fix rules for Red Hat

---

src/chrome/content/rules/Nanopool.xml

Following up on https://github.com/EFForg/https-everywhere/pull/4611#issuecomment-209902315, this adds a target subdomain and a few comments about broken subdomains.

[Nanopool] Update ruleset

---

src/chrome/content/rules/Infogr.am.xml

[Infogr.am] Add exclusion

---

src/chrome/content/rules/bmvi.de.xml

BTW for all German readers: [They were affected by Heartbleed until Thursday](http://www.heise.de/security/meldung/Ministerium-fuer-digitale-Infrastruktur-pfuscht-beim-eigenen-Web-Server-3186960.html).

[bmvi.de] New ruleset

---

.gitignore
src/chrome/content/rules/Letterboxd.com.xml

https officially supported since a few days ago according to their feedback thread http://feedback.letterboxd.com/forums/136771-general/suggestions/2505918-login-registration-over-https

new ruleset for letterboxd

---

src/chrome/content/rules/Memorial-University.xml

This fixes https://github.com/EFForg/https-everywhere/issues/4725.

[Memorial University] Exclude subdomain

---

src/chrome/content/rules/Egotastic.xml

https://github.com/EFForg/https-everywhere/pull/4723#issuecomment-218231919

Add Egotasticallstars.com to Egotastic.xml

---

src/chrome/content/rules/turnoff.xml

This supersedes https://github.com/EFForg/https-everywhere/pull/4415 which has not seen any action for a while.

[Turnoff.us] New ruleset based on previous PR

---

src/chrome/content/rules/Fairphone.com.xml

[Fairphone.com] Add code.fairphone.com

---

src/chrome/content/rules/Craigslist.ca.xml

[Craigslist.ca] Refer to Craigslist.org.xml

---

src/chrome/content/rules/Kalooga.com.xml

This adds the geo,img and publishing subdomain for kaloo.ga

Kalooga.com: add publishing.kaloo.ga

---

src/chrome/content/rules/cubecraft.xml
src/chrome/content/rules/marcoslater.xml

Added rules for cubecraft.net and marcoslater.com. :)

Added cubecraft.net and marcoslater.com.

---

test/tor-browser.sh

Ready for review @jsha @cooperq

Adding a tor browser test file (just standalone for now)

---

src/chrome/content/rules/MTurk.com.xml

This closes https://github.com/EFForg/https-everywhere/issues/4869. A bit scary that the checker lets that big a distance through.

[MTurk] Fix rule

---

src/chrome/content/rules/Root.cz.xml

Root.cz recently enabled HTTPS on their servers.

[Root.cz] New ruleset

---

src/chrome/content/rules/Threema.xml

[Threema.ch] New subdomain

---

src/chrome/content/rules/JW_Platform.com.xml

[JW_Platform.com.xml] fixed #4531

---

src/chrome/content/rules/Wikimedia.xml

https://status.wikimedia.org/ now works.
https://phabricator.wikimedia.org/T34796

[Wikimedia.xml] Remove exclusion for status.wm.org

---

src/components/https-everywhere.js

Remove obsolete event listeners.

---

src/chrome/content/rules/Visual_Studio.com.xml

Site serves `Strict-Transport-Security: max-age=31536000; includeSubDomains`

[Visual Studio] Add subdomain marketplace

---

src/chrome/content/rules/Collyers.xml

Ruleset containing comments. Tested on latest FF, Windows 10.

Added ruleset for <collyers.ac.uk>

---

src/chrome/content/rules/Atlassian.xml

Signed-off-by: David Black <dblack@atlassian.com>

Exclude non-default ports.

---

src/chrome/content/rules/FreeBSD.xml

Add some previously non-functional subdomains.

[freebsd.org] Update subdomains

---

src/chrome/content/rules/Swehack.org.xml

As requested by webmaster in https://github.com/EFForg/https-everywhere/issues/5609

[Swehack.org] Disable ruleset

---

src/chrome/content/rules/NemID.xml

https://nemid.nu currently times out

[NemID] Fix broken subdomain

---

src/chrome/content/rules/sibinfo.su.xml

sibinfo.su

---

src/chrome/content/rules/nordportal.ru.xml

nordportal.ru

---

src/chrome/content/rules/tyumedia.ru.xml

tyumedia.ru

---

src/chrome/content/rules/tverweek.com.xml

tverweek.com

---

src/chrome/content/rules/yarcube.ru.xml

yarcube.ru

---

src/chrome/content/rules/yaostrov.ru.xml

yaostrov.ru

---

src/chrome/content/rules/Autistici-Inventati.xml

No more self signed certificate.

Autistici switched to Let's Encrypt

---

src/chrome/content/rules/tribuna.pl.ua.xml

tribuna.pl.ua

---

src/chrome/content/rules/sedmitza.ru.xml

sedmitza.ru

---

src/chrome/content/rules/novostivoronezha.ru.xml

novostivoronezha.ru

---

src/chrome/content/rules/lenizdat.ru.xml

lenizdat.ru

---

src/chrome/content/rules/Technische_Aufklärung.xml

small mixed content warning about thirdparty stuff from google, but so far the player works, calendar works and i can't find anything that breaks.

add rule for Technische Aufklärung

---

src/chrome/content/rules/newkaliningrad.ru.xml

newkaliningrad.ru

---

src/chrome/content/rules/BME.hu.xml
src/chrome/content/rules/BME.hu_incomplete.xml
src/chrome/content/rules/BME.xml

Rules for using Budapest University of Technology and Economics sites over https.

New rules for BME university main sites.

---

src/chrome/content/rules/Gslug.org.xml

This closes https://github.com/EFForg/https-everywhere/issues/5330

[Gslug.org] New ruleset

---

src/chrome/content/rules/Cyberport.de.xml

This closes https://github.com/EFForg/https-everywhere/issues/5144.

[Cyberport.de] New ruleset

---

src/chrome/content/rules/VCD.org.xml

In particular, this fixes https://github.com/EFForg/https-everywhere/issues/5302

[VCD.org] Disable broken subdomain

---

src/chrome/skin/https-everywhere.css

fix size of https-everywhere-button icon

issue #5719: fix size of https-everywhere-button icon

---

src/chrome/content/rules/Sina.xml

Reverts EFForg/https-everywhere#4983

Revert "Update Sina.xml"

---

src/chrome/content/rules/iqiyi.com.xml

Reverts EFForg/https-everywhere#4803

Revert "Update iqiyi.com.xml"

---

src/chrome/content/rules/HangSengBank.xml

Add support for [Hang Seng Bank](https://www.hangseng.com)

[HangSeng.com] New ruleset

---

src/chrome/content/rules/stadium.ru.xml

stadium.ru

---

src/chrome/content/rules/voterinfo.gov.hk.xml

Add support for [voterinfo.gov.hk](https://www1.voterinfo.gov.hk/) (Online Voter Information Enquiry System)

[VoterInfo.gov.hk] New ruleset

---

src/chrome/content/rules/TV4Play.se.xml

- add img cdn subdomains
- re-enable the rule

TV4Play.se

---

src/chrome/content/rules/CloudTrax.com.xml

Added several doamins to Cloudtrax.

---

src/chrome/content/rules/Bitmask.net.xml
src/chrome/content/rules/Riseup.xml

Updates subdomains and now use the new rules style.

Update Riseup and Bitmask rules

---

src/chrome/content/rules/Mapillary.com.xml

The site has some passive mixed content from CF; not a huge deal. This closes https://github.com/EFForg/https-everywhere/issues/5780

[Mapillary.com] Add subdomain forum

---

src/chrome/content/rules/gmodmp.jp.xml

Found on http://shop.gnavi.co.jp/

Added gmodmp.jp

---

src/chrome/content/rules/searchteria.co.jp.xml

Added searchteria.co.jp

---

src/chrome/content/rules/lekumo.jp.xml

Found on http://help.gnavi.co.jp/

Added lekumo.jp

---

src/chrome/content/rules/gsspat.jp.xml

Found on http://premium.gnavi.co.jp/

Added gsspat.jp

---

src/chrome/content/rules/adlantis.jp.xml

@fuglede, @J0WI: please let me know if ``static.adlantis.jp`` should be added. I will rebase commits based on your suggestion.

Added adlantis.jp

---

.travis.yml
test/travis-ruleset-fetch.sh

Ruleset change tests (resolves #5844)

---

test/rules/src/https_everywhere_checker/http_client.py

This pull request resolves issue #5628.

Use different default ciphers when using NSS

---

test/rules/src/https_everywhere_checker/http_client.py

@Hainish This fixes the whitespace problems added by my pull request #6215.

Fix whitespace related to bb63838

---

src/chrome/content/rules/Expo2020.xml

**Edit:** Added missing `grant` subdomain and added comment explaining `www` redirect.

[Expo2020] Add ruleset

---

src/chrome/content/rules/Tutti.ch.xml

I accidentally opened two PRs for this host and both got merged. 
See #4634 and #6064

removed Tutti.ch.xml in favor or tutti.ch.xml

---

src/chrome/content/rules/Posten.se.xml

Disabled posten.se

---

src/chrome/content/rules/Parallels.xml

In particular, this fixes https://github.com/EFForg/https-everywhere/issues/6433

[Parallels] Disable broken subdomains

---

src/chrome/content/rules/Visa.xml

This should resolve issue #4671.

Add Visa.xml atmlocator exclusion (issue #4671)

---

src/chrome/content/rules/Taboola.xml

Updated taboola.com

---

src/chrome/content/rules/Bazaarbay.org.xml

Added bazaarbay.org

---

src/chrome/content/rules/Poo.solutions.xml

Added poo.solutions

---

src/chrome/content/rules/Iconical.com.xml

Added iconical.com

---

src/chrome/content/rules/Starship.xyz.xml

Added starship.xyz

---

src/chrome/content/rules/Clearista.com.xml

Added clearista.com

---

src/chrome/content/rules/Codetriage.com.xml

Added codetriage.com

---

src/chrome/content/rules/T0.com.xml

Added t0.com

---

src/chrome/content/rules/Quickleak.se.xml

Added quickleak.se

---

src/chrome/content/rules/Poopjournal.rocks.xml

Added poopjournal.rocks

---

utils/ruleset-coverage-whitelist-cleanup.sh

This should resolve issue #4975. Just to note, this updated script removes 227 lines from `ruleset-coverage-whitelist.txt` compared to the original script removing 90.

Update whitelist cleanup script (issue #4975)

---

src/chrome/content/rules/Infoseek.co.jp.xml

Added infoseek.co.jp

---

src/chrome/content/rules/Eyeboot.com.xml

Added eyeboot.com

---

src/chrome/content/rules/Rakuten.co.jp-mixed.xml
src/chrome/content/rules/Rakuten.co.jp.xml
src/chrome/content/rules/rakuten-static.com.xml

- Added information of nonfunctional domains, problematic domains, etc.
- Added domains linked from www.rakuten.co.jp/sitemap/
- Added domains on www.infoseek.co.jp
Closes #5824

Updated rakuten.co.jp

---

src/chrome/content/rules/linkline.ru.xml

linkline.ru

---

src/chrome/content/rules/continuousphp.com.xml

Just fixing another syntax failure (#6558)

fix unescaped dot

---

utils/labeller/.gitignore
utils/labeller/Dockerfile
utils/labeller/README.md
utils/labeller/config.json.example
utils/labeller/index.js
utils/labeller/package.json
utils/labeller/state_dir/.gitignore

@fuglede, you're familiar with node.js, right?  Mind reviewing?

Add labeller to utils (closes #6424)

---

utils/labeller/index.js

@J0WI you spotted it, you want to review this 1-character PR? :)

http -> https for Alexa top 1M

---

src/chrome/content/rules/porvoo.fi.xml

This fixes https://github.com/EFForg/https-everywhere/issues/6475

[Porvoo.fi] Disable ruleset

---

src/chrome/content/rules/Vodafone.ie.xml

Fixes https://github.com/brave/browser-laptop/issues/3240

Updated Vodafone.ie

---

src/chrome/content/rules/Gfx.ms.xml

This closes https://trac.torproject.org/projects/tor/ticket/17978

[Gfx.ms] Add subdomain mem

---

src/chrome/content/rules/GoogleAPIs.xml

This fixes https://trac.torproject.org/projects/tor/ticket/15154

[GoogleAPIs] Add exclusion

---

src/chrome/content/rules/University_at_Buffalo.xml

Ran a quick sweep with the checker; these are the errors it caught. This closes https://trac.torproject.org/projects/tor/ticket/16345.

[University at Buffalo] Disable several subdomains

---

src/chrome/content/rules/FreedomBoxFoundation.org.xml

I checked for other sub-domains, and was not able to find any. Check one off of #3069.

[FreedomBoxFoundation.org] New ruleset

---

src/chrome/content/rules/JD.com.xml

This should resolve issue #5266.

Add vip.jr.jd.com to JD.com.xml (issue #5266)

---

src/chrome/content/rules/iSideWith.com.xml

This pull request partially resolves issue #3069.

Add iSideWith.com.xml

---

src/chrome/content/rules/Juno.com.xml

This pull request partially resolves issue #3069.

Add Juno.com.xml

---

src/chrome/content/rules/Plenti.com.xml

Added plenti.com

---

src/chrome/content/rules/Eliomotors.com.xml

Added eliomotors.com

---

src/chrome/content/rules/Paranoidsecurity.nl.xml

add paranoidsecurity.nl

---

src/chrome/content/rules/Computerworld.ch.xml

This should resolve issue #5116.

Add Computerworld.ch.xml (issue #5116)

---

src/chrome/content/rules/Huxiu.com.xml

Create Huxiu ruleset

---

src/chrome/content/rules/saint-petersburg.ru.xml

saint-petersburg.ru

---

src/chrome/content/rules/usainteanne.xml

Removed old alu site from rules.
Added rules for new office365 login page.

Changed around our sites rules

---

src/chrome/content/rules/Ameba.xml
src/chrome/content/rules/spotlight-media.xml

Added spotlight-media.jp

---

src/chrome/content/rules/Swiss-Federal-Railways.xml

Remove mailing.sbb.ch from HTTPS list

---

src/chrome/content/rules/Dell.xml

This fixes https://github.com/EFForg/https-everywhere/issues/6737 and disables a number of broken subdomains.

[Dell] Update ruleset

---

src/chrome/content/rules/Zerowater.com.xml

Added zerowater.com

---

src/chrome/content/rules/Globevestor.com.xml

Added globevestor.com

---

src/chrome/content/rules/Winkdex.com.xml

Added winkdex.com

---

src/chrome/content/rules/Zdrojak.cz.xml

https://hstspreload.appspot.com/?domain=zdrojak.cz
Signed-off-by: Roman3349 <ondracek.roman@centrum.cz>

[Zdrojak.cz] Remove HSTS preloaded ruleset

---

src/chrome/content/rules/nsis.ro.xml
src/chrome/content/rules/safeornot.net.xml
src/chrome/content/rules/vpn.ac.xml

Add related domains. Add new domain to vpn.ac.xml.

[nsis.ro] New rule

---

src/chrome/content/rules/Norge.no.xml

Norway's National Digital Services Portal

Added norge.no

---

src/chrome/content/rules/PornHub.xml

Found a couple more subdomains while checking #6680

PornHub: add cdn-d-vid-public, ht & services subdomain

---

src/chrome/content/rules/WildStar-online.com.xml

Wildstar-Online:

---

src/components/ssl-observatory.js

Fixes issue: https://trac.torproject.org/projects/tor/ticket/19996

Fix obs tor check

---

src/chrome/content/rules/ImQuQu.com.xml

See: https://chromium.googlesource.com/chromium/src/net/+/master/http/transport_security_state_static.json#5229

Remove ImQuQu.com, since it is included in HSTS Preload list

---

src/chrome/content/rules/Zakonyprolidi.cz.xml

In Czech republic is this website one of the best source for law documents. I mean its important to keep privacy.

Add website https://www.zakonyprolidi.cz/

---

src/chrome/content/rules/IPv6-adresse.dk.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=3507), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#4926), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n5442)

rm IPv6-adresse.dk.xml

---

src/chrome/content/rules/Mikaela.info.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=3294), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#6537), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n7230)

rm Mikaela.info.xml

---

src/chrome/content/rules/Darkengine.io.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=2747), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#2376), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n2637)

rm Darkengine.io.xml

---

src/chrome/content/rules/Fteproxy.org.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=2772), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#3741), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n4132)

rm Fteproxy.org.xml

---

src/chrome/content/rules/tbspace.de.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=1856), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#9837), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n10876)

rm tbspace.de.xml

---

src/chrome/content/rules/Koen.io.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=2084), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#5567), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n6156)

rm Koen.io.xml

---

src/chrome/content/rules/Tim_Taubert.de.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=1540), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#10145), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n11222)

rm Tim_Taubert.de.xml

---

src/chrome/content/rules/Certible.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=1117), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#1694), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n1871)

rm Certible.xml

---

src/chrome/content/rules/Shaaaaaaaaaaaaa.com.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=1175), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#8990), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n9933)

rm Shaaaaaaaaaaaaa.com.xml

---

src/chrome/content/rules/Lobste.rs.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=1781), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#5980), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n6613)

rm Lobste.rs.xml

---

src/chrome/content/rules/Waze.com.xml

Reverts EFForg/https-everywhere#7112

Revert "rm Waze.com.xml"

---

src/chrome/content/rules/Blognone.com.xml

Reverts EFForg/https-everywhere#7121

Revert "rm Blognone.com.xml"

---

src/chrome/content/rules/With_Google.com.xml

Reverts EFForg/https-everywhere#6997

Revert "rm With_Google.com.xml"

---

src/chrome/content/rules/BitMEX.com.xml

Reverts EFForg/https-everywhere#7093

Revert "rm BitMEX.com.xml"

---

src/chrome/content/rules/Todoist.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=2327), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#10194), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n11282)

rm Todoist.xml

---

src/chrome/content/rules/Hdfcbank.com.xml

Trivial rule for HDFC Bank (banking website)

Added trivial rule for Hdfcbank.com

---

src/chrome/content/rules/Da.gd.xml

Signed-off-by: Ricky Elrod <ricky@elrod.me>

add rules for da.gd

---

src/chrome/content/rules/Nvcc.edu.xml

This pull request partially resolves issue #3069.

Add Nvcc.edu.xml

---

src/chrome/content/rules/KB_IT.dk.xml

Preloaded
[Chromium](https://chromium.googlesource.com/chromium/src.git/+/53.0.2785.143/net/http/transport_security_state_static.json#3051), [Firefox](https://dxr.mozilla.org/mozilla-release/source/security/manager/ssl/nsSTSPreloadList.inc#4661), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n5964)
HTTPS Header: Strict-Transport-Security: max-age=15768000; includeSubDomains; preload

rm KB_IT.dk.xml

---

src/chrome/content/rules/CJFE.org.xml

Per bad cert, plus request by site owner:
https://trac.torproject.org/projects/tor/ticket/20253#comment:3

Disable CJFE ruleset.

---

src/chrome/content/rules/Colorado_Secretary_of_State.xml

Update Colorado_Secretary_of_State.xml (#7327)

---

src/chrome/content/rules/E-activist.com.xml

This fixes https://github.com/EFForg/https-everywhere/issues/7319

[E-activist.com] Add exclusion

---

src/chrome/content/rules/OpenSSH.com.xml

Add OpenSSH.com.xml

---

src/chrome/content/rules/LibreSSL.org.xml

Add LibreSSL.org.xml

---

src/chrome/content/rules/KissAnime.to.xml

[Kissanime.to] Disable ruleset

---

src/chrome/content/rules/Icanhazip.com.xml

... as https://www.icanhazip.com currently serves a bad certificate.

[Icanhazip.com] Rewrite www to ^

---

src/chrome/content/rules/Questionablecontent.net.xml
src/chrome/content/rules/adsymptotic.com.xml

Also had to add an entry for an ad server they use, p.adsymptotic.com.
Issue #3069

Add questionablecontent.net

---

src/chrome/content/rules/Calacademy.org.xml

Also added:
* store.calacademy.org
* ticketing.calacademy.org

Calacademy.org make trivial rule.

---

src/chrome/content/rules/Rk37.ru.xml

This is a new version of pull request #5372 , submitted due to lack of recent progress on the older pull request.

Add Rk37.ru.xml

---

src/chrome/content/rules/heritage.gov.hk.xml

New ruleset for [Conserve and Revitalise Hong Kong Heritage](http://www.heritage.gov.hk)

[heritage.gov.hk] New ruleset

---

src/chrome/content/rules/DMoruzzi.com.xml

Rewrite HTTP to HTTPS for my website.

Rewrite for DMoruzzi.com

---

src/chrome/content/rules/danluu.com.xml

Added danluu.com

---

src/chrome/content/rules/KH.hu.xml

Created and tested as a netbank user.

New rules for KH Bank (Hungary)

---

src/chrome/content/rules/ul.se.xml

Added ul.se [UL.se]

---

src/chrome/content/rules/approach0.xyz.xml

Added approach0.xyz

---

src/chrome/content/rules/Refaktor.hu.xml

There's no nonfunctional domain in *.refaktor.hu

Add ruleset Refaktor.hu

---

src/chrome/content/rules/hkpl.gov.hk.xml

Add support for [Hong Kong Public Libraries](https://www.hkpl.gov.hk/)

[hkpl.gov.hk] New ruleset

---

src/chrome/content/code/Cookie.js
src/chrome/content/code/HTTPS.js
src/chrome/content/code/IOUtil.js

Replace non-standard for each statement with for

---

src/chrome/content/rules/predb.me.xml

Added rule for PreDB (predb.me).

Added rule for predb.me

---

src/chrome/content/rules/thegyllenhall.com.xml

thegyllenhall.com

---

src/chrome/content/rules/ITunes.com.xml

Fix ITunes.com.xml HTTPS Mismatch

---

src/chrome/content/rules/Ringinout.com.xml

Added a ruleset for a [site](https://www.ringinout.com/ "RingInOut").

ruleset added for ringinout.com

---

src/chrome/content/rules/entware.net.xml

entware.net

---

src/chrome/content/rules/Shabdkosh.com.xml

Added a ruleset for a [site](https://www.shabdkosh.com/ "Shabdkosh | शब्दकोश").

Ruleset for shabdkosh.com

---

src/chrome/content/rules/Daily-Express.xml

Daily-Express:

---

src/chrome/content/rules/JustPaste.it.xml

Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=14427), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#5288), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n5855)

rm JustPaste.it.xml

---

test/firefox/test/test-httpse-installed.js

Fix core tests

---

src/chrome/content/rules/Mozilla.xml

This pull request fixes issue #8225.

Add exception for symbols.mozilla.org to Mozilla.xml

---

src/chrome/content/rules/Pridewatch.tw.xml

Add a new rules for lightup.pridewatch.tw

Create a Pridewatch.tw.xml rules

---

ruleset-style.md
ruleset-testing.md

Update ruleset-style.md ruleset-testing.md

---

src/chrome/content/rules/Wdr.de.xml

rest of the hosts from the SAN of the main certificate are omitted for now
There are small mixed content warnings but as far as i can tell the site doesn't break with the missing css.
Videos seem to work fine too.

WDR: add wdr4 and www1 subdomains

---

src/chrome/content/rules/IndieWeb.xml

This closes duplicate, inactive pull request https://github.com/EFForg/https-everywhere/pull/4106 .

Add IndieWeb.xml

---

src/chrome/content/rules/phonekeeper.ru.xml

phonekeeper.ru

---

src/chrome/content/rules/bitcoinwatch.com.xml

bitcoinwatch.com

---

src/chrome/content/rules/bestchange.ru.xml

bestchange.ru

---

src/chrome/content/rules/unichange.me.xml

unichange.me

---

src/chrome/content/rules/changeinfo.ru.xml

changeinfo.ru

---

src/chrome/content/rules/okchanger.ru.xml

okchanger.ru

---

src/chrome/content/rules/kurs.expert.xml

kurs.expert

---

src/chrome/content/rules/247exchange.com.xml

247exchange.com

---

src/chrome/content/rules/AbuseIPDB.com.xml

New ruleset for AbuseIPDB.com

---

src/chrome/content/rules/bankcomat.com.xml

bankcomat.com

---

src/chrome/content/rules/Bits.media.xml

bits.media

---

src/chrome/content/rules/Electrum.org.xml

electrum.org

---

src/chrome/content/rules/Deezer.xml

Disable ruleset since the navigation bar is broken.

Update Deezer.xml (#4768)

---

src/chrome/content/rules/xchange.is.xml

xchange.is

---

src/chrome/content/rules/alfacashier.com.xml

alfacashier.com

---

src/chrome/content/rules/blockchain-status.com.xml

blockchain-status.com

---

src/chrome/content/rules/discoverhongkong.com.xml

New ruleset for [Discover Hong Kong](http://www.discoverhongkong.com)

[DiscoverHongKong.com] New ruleset

---

src/chrome/content/rules/ukrcash.com.xml

ukrcash.com

---

src/chrome/content/rules/matbea.com.xml

matbea.com

---

src/chrome/content/rules/baksman.com.xml

baksman.com

---

src/chrome/content/rules/24paybank.com.xml

24paybank.com

---

src/chrome/content/rules/xchange.cc.xml

xchange.cc

---

src/chrome/content/rules/Indacoin.com.xml

indacoin.com

---

src/chrome/content/rules/bitport.net.xml

bitport.net

---

src/chrome/content/rules/e-btc.com.ua.xml

e-btc.com.ua

---

src/chrome/content/rules/roseurosud.org.xml

roseurosud.org

---

src/chrome/content/rules/dissernet.org.xml

dissernet.org

---

src/chrome/content/rules/helptorrents.com.xml

helptorrents.com

---

src/chrome/content/rules/breadwallet.com.xml

breadwallet.com

---

src/chrome/content/rules/torrentdownloads.me.xml

torrentdownloads.me

---

src/chrome/content/rules/Octopuspop.com.xml

This is a follow-up to https://github.com/EFForg/https-everywhere/pull/6102 in which various parts of the site was covered, but in which some of them still had some issues. In the same pull request, the developer later notified us that those issues have now been fixed.

[Octopuspop.com] Add ruleset

---

src/chrome/content/rules/torrentz2.eu.xml

torrentz2.eu

---

src/chrome/content/rules/Extratorrent.com.xml
src/chrome/content/rules/extratorrent.one.xml

extratorrent.one

---

src/chrome/content/rules/Golem.de.xml

Golem.de: add more secured subdomains

---

src/chrome/content/rules/torrenthound.com.xml

torrenthound.com

---

src/chrome/content/rules/tapochek.net.xml

tapochek.net

---

src/chrome/content/rules/uniongang.net.xml

uniongang.net

---

src/chrome/content/rules/nodeny-plus.com.ua.xml

nodeny-plus.com.ua

---

src/chrome/content/rules/Logout.hu.xml

This is a new version of pull request #5794 , submitted due to lack of recent progress on the older pull request.

Add Logout.hu.xml

---

src/chrome/content/rules/Alexhaydock.co.uk.xml

I operate both sites so if there are any queries with the rules please let me know.
Thanks :)

Remove redundant personal site rule (HSTS Preloaded)

---

src/chrome/content/rules/Dpskolkata.com.xml

Added a ruleset for a [site](https://www.dpskolkata.com/ "Delhi Public School, Ruby Park").

Ruleset for dpskolkata.com

---

src/chrome/content/rules/zerogate.tk.xml

zerogate.tk

---

src/chrome/content/rules/otr-online.ru.xml

otr-online.ru

---

src/chrome/content/rules/zarunet.org.xml

zarunet.org

---

src/chrome/content/rules/eutelsatnetworks.ru.xml

eutelsatnetworks.ru

---

src/chrome/content/rules/ispserver.ru.xml

ispserver.ru

---

src/chrome/content/rules/expressjs.com.xml

expressjs.com

---

src/chrome/content/rules/bgbilling.ru.xml

bgbilling.ru

---

src/chrome/content/rules/megatel.ru.xml

megatel.ru

---

src/chrome/content/rules/andreapaiola.name.xml

andreapaiola.name

---

src/chrome/content/rules/peercloud.io.xml

peercloud.io

---

src/chrome/content/rules/sharedrop.io.xml

sharedrop.io

---

src/chrome/content/rules/btorrent.xyz.xml

btorrent.xyz

---

src/chrome/content/rules/fastcast.nz.xml

fastcast.nz

---

src/chrome/content/rules/keepkey.com.xml

keepkey.com

---

src/chrome/content/rules/lostfilm.tv.xml

lostfilm.tv

---

src/chrome/content/rules/file.pizza.xml

file.pizza

---

src/chrome/content/rules/Openload.xml
src/chrome/content/rules/openload.co.xml

Updated comments, added more host for `openload.co` to improve ruleset coverage, as well as for `*.oloadcdn.net`.

Update and rename openload.co.xml to Openload.xml

---

src/chrome/content/rules/lostfilm.info.xml

lostfilm.info

---

src/chrome/content/rules/e-scrooge.is.xml

e-scrooge.is

---

src/chrome/content/rules/rosyama.ru.xml

rosyama.ru

---

src/chrome/content/rules/leonidvolkov.ru.xml

leonidvolkov.ru

---

src/chrome/content/rules/uptimeinstitute.com.xml

uptimeinstitute.com

---

src/chrome/content/rules/poiskvps.ru.xml

poiskvps.ru

---

src/chrome/content/rules/openwebrtc.org.xml

openwebrtc.org

---

src/chrome/content/rules/simplewebrtc.com.xml

simplewebrtc.com

---

src/chrome/content/rules/teleguide.info.xml

teleguide.info

---

src/chrome/content/rules/tokenly.com.xml

tokenly.com

---

src/chrome/content/rules/openwebtorrent.com.xml

openwebtorrent.com

---

src/chrome/content/rules/rom1504.fr.xml

rom1504.fr

---

src/chrome/content/rules/limetorrents.com.xml

limetorrents.com

---

src/chrome/content/rules/torrentdownload.ch.xml

torrentdownload.ch

---

src/chrome/content/rules/backendless.com.xml

backendless.com

---

src/chrome/content/rules/ispsystem.ru.xml

ispsystem.ru

---

src/chrome/content/rules/ispsystem.com.xml

ispsystem.com

---

src/chrome/content/rules/torrentz.ht.xml

torrentz.ht

---

src/chrome/content/rules/ispserver.com.xml

ispserver.com

---

src/chrome/content/rules/torrentz.site.xml

torrentz.site

---

src/chrome/content/rules/torrents.me.xml
src/chrome/content/rules/torrents.to.xml

torrents.to

---

src/chrome/content/rules/torrentdownloads.me.xml
src/chrome/content/rules/torrentdownloads.net.xml

torrentdownloads.net

---

src/chrome/content/rules/irongeek.com.xml

Solves: https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-265714735

irongeek.com.xml

---

src/chrome/content/rules/ievaphone.com.xml

Solves: https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-263136274

ievaphone.com.xml

---

src/chrome/content/rules/ouedkniss.com.xml

Suggested in: https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-262264505

ouedkniss.com.xml

---

src/chrome/content/rules/tinkernut.com.xml

Suggested in: https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-262264505

tinkernut.com.xml

---

src/chrome/content/rules/teamup.com.xml

Suggested in: https://github.com/EFForg/https-everywhere/issues/3069#issuecomment-262264505

teamup.com.xml

---

src/chrome/content/rules/Ziplist.com.xml

the cert expired long time ago

remove Ziplist.com.xml

---

src/chrome/content/rules/Ulteo.com.xml

This is a new version of pull request #5242 , submitted due to lack of recent progress on the older pull request.

Add Ulteo.com.xml

---

src/chrome/content/rules/dynastyfdn.com.xml

dynastyfdn.com
