src/chrome/content/rules/MySQL.xml
The MySQL Bugs website now also has SSL:
https://bugs.mysql.com/bug.php?id=73457
But there is no http->https redirect and the http url is still used in
email notifications:
https://bugs.mysql.com/bug.php?id=75367
=> Don't exclude bugs.mysql.com

src/chrome/content/rules/Adobe.xml
Download URL for Flash player.
Also, combining www and wwwimages2 should make the pattern a little more efficient.
=> Secure aihdownload.adobe.com

src/components/https-everywhere.js
Unless I'm missing something, this function shouldn't appear twice. Checked both occurrences to be exactly the same(with diff). This removes one of them.
=> toggleHttpNowhere function appeared twice in code

src/chrome/content/rules/Disqus.com.xml
cc @mattrobenolt for review.
Fixes #900.
=> Turn on Disqus rule by default and remove unreliable flag.

src/components/ssl-observatory.js
=> Remove bogus INCLUDE(md5). Was replaced by calls to Firefox MD5 API.

src/chrome/content/rules/Disqus.com.xml
As it turns out, Tumblr shut is down for doing this. I had to revert what we did to get https in front of our blogs.
I just routed traffic through our load balancers, which was terminating SSL, then passing the traffic back along to them and it worked fine. They apparently didn't like that and our blogs started 404ing today. Their service requires validating that the DNS record is pointed to `domains.tumblr.com`, and if it's not, they apparently just turn it off.
Any help from Tumblr here would be cool if possible. Fortunately, we're moving this away from Tumblr probably this quarter.
:(
=> Revert "Update Disqus.com.xml"

src/components/https-everywhere.js
=> Remove tls.version.min setting now that it is incorporated in Firefox

src/chrome/content/rules/ZeroC.com.xml
New rule for ZeroC.com - There's an automatic redirect from plaintext to SSL/TLS across most of the site, but there's a few slips, including most prominently across the plaintext download link, which is still available. This just seals that gap.
=> zeroC.com.xml (new rule)

utils/merge-rulesets.sh
error happens while running `./makecrx.sh`
because `python` is python3 on some systems
and python 3 renamed the `unicode` type to `str`,
the old `str` type has been replaced by `bytes`.
```bash
Removing whitespaces and comments...
Traceback (most recent call last):
File "./utils/merge-rulesets.py", line 77, in <module>
for rfile in sorted(xml_ruleset_files):
File "./utils/merge-rulesets.py", line 25, in normalize
f = unicodedata.normalize('NFC', unicode(f, 'utf-8')).encode('utf-8')
NameError: name 'unicode' is not defined
```
=> fix "NameError: name 'unicode' is not defined"

src/chrome/content/rules/EFF.xml, utils/relaxng.xml
This allows us to start adding explicit test URLs to rulesets.
=> Add test tag to RELAX NG grammar.

.gitmodules, .travis.yml, test-ruleset-coverage.sh
This ensures that all new or changed rulesets from now on must have sufficient test URLs to cover all the rules in them.
Adds a submodule pointing to `coverage' branch of https-everywhere-checker.
Adds a script to automatically run the checker in coverage-only mode.
cc @cooperq @pde for review.
=> Add automated coverage testing.

.travis.yml
This avoids having to 'pip install' lxml, which takes a long time because it
compiles the package each time. Instead we install the precompiled version from
apt-get and tell virtualenv it's okay to use it. Note that this works for Python
2.7 only.
This brings test times from ~3 minutes to ~1 minute.
=> Use system python-lxml in Travis.

ruleset-style.md
Here's a proposed style guide for writing rulesets. It represents a significant departure from typical ruleset writing practice today, but makes it much easier to comply with the new test coverage rules, which in turn should make managing our ruleset library much easier.
cc @cooperq @pde @2d1
=> Ruleset style guide

install-dev-dependencies.sh, src/chrome/content/rules/Royal-Navy.xml, src/chrome/content/rules/Shaklee.xml, src/chrome/content/rules/Student_Benefits.ca.xml, src/chrome/content/rules/TDC.dk.xml, src/chrome/content/rules/ThePermitStore.com.xml, src/chrome/content/rules/University-of-Southern-California.xml, src/chrome/content/rules/Van_Lanschot.com.xml, src/chrome/content/rules/WHATWG.org.xml, test-ruleset-coverage.sh, utils/relaxng.xml
=> Fix coverage from a bunch of rules

src/chrome/content/rules/trakt.xml
I didn't run into any mixed content issues (for instance, trakt.us is automatically accessed over HTTPS by trakt.tv if browsing it with HTTPS) whilst browsing trakt.tv with this rule on in Firefox. I tried to adhere to the common patterns I saw in other rules, but forgive me if there's any oddities.
=> Added trakt.xml

test-ruleset-coverage.sh
Turns out --date=local means something different on VMs running on UTC.
The ideal thing would be to specify an explicit timezone, but this is easier and makes little difference in the long run.
cc @cooperq submitting as TBR.
=> Bump up earliest date for mandatory coverage rulesets.

src/chrome/content/rules/Qt.io.xml
Just broadens the Qt.io rule a bit to include the download link, which doesn't autoredirect to SSL/TLS, and the bug reporting link, which does.
=> qtio: broaden rule for downloads/bugreporting links

src/chrome/content/rules/JQuery.org.xml, src/chrome/content/rules/QUnit_JS.com.xml
events.jquery.org, brand.jquery.org now work.
Redirect www.qunitjs.com -> qunitjs.com as www is not supported.
=> events.jquery.org, brand.jquery.org, www.qunitjs.com

src/chrome/content/rules/National-Security-Agency.xml
Yes, "nsa.gov" really doesn't resolve. "www.nsa.gov" works.
By the way, I suspect the website no longer has the mixed-content issues it used to, but I can't say for certain and don't know how to test.
=> Fix ruleset National-Security-Agency.xml by removing non-resolving host

ruleset-testing.md
HTML in ruleset-style.md is escaped, but it's not in ruleset-testing.md, so it doesn't get displayed properly on Github:
https://github.com/EFForg/https-everywhere/blob/master/ruleset-testing.md
See:
https://github.com/mnordhoff/https-everywhere/blob/ruleset-testing-html/ruleset-testing.md
=> Escape HTML tags in ruleset-testing.md

src/chrome/content/rules/Tmblr.co.xml
It was redirecting to www.tumblEr.com instead of www.tumblr.com.
This wasn't too much of a privacy issue, since https://www.tumbler.com/ has a
mismatching cert, so a user would have to click through the warning to load it.
Besides, it's only Tumblr's URL shortener.
=> [Tmblr.co] Redirect to the right domain

install-dev-dependencies.sh
Fix: install-dev-dependencies.sh fails if run just after cloning due to missing https-everywhere-checker/requirements.txt. This file is created when the corresponding submodule is updated.
=> install-dev-dependencies.sh fails after cloning

src/chrome/content/rules/MySQL.xml, src/chrome/content/rules/Oracle-mismatches.xml
foo.mysql.com and similar test URLs failed the fetch test. Also there were more
exclusions than inclusions, so turned the rule into an explicit list of good
subdomains.
cc @cooperq for review
=> Fix MySQL rule.

src/chrome/content/rules/UPS.com.xml
=> [UPS.com] Reenabled Exceptions

src/chrome/content/rules/Dom.bg.xml
Dom.bg is a major Bulgarian domain registrar and hosting provider. The URLs on the site are host-independent, so the rewriting rule is pretty simple.
=> Add Dom.bg.xml.

src/chrome/content/rules/GNU.org.xml
remove GNU.org's default_off originating from #1117 (jsha/disable-uncovered-rulesets)
=> [GNU.org] replace *.gnu.org, use ^http: → https:

src/chrome/content/rules/DHL.de.xml
Already supports HSTS, but currently doesn't default to https.
The official account-page on paket.de for example links from https to http which prevents HSTS from working.
=> [dhl.de] Multiple subdomains + test coverage

chromium/rules.js
An undefined reference was preventing them from saving.
Also, addUserRule was not correctly checking active status on reload, meaning
that rules would not stay disabled across restarts.
Fixes #741
=> Fix user rules in Chromium.

src/chrome/content/rules/Linuxlovers.at.xml, src/chrome/content/rules/Shaklee.xml
wiki.linuxlovers.at was duplicated in Linuxlovers.at-falsemixed.xml,
so I removed the references in Linuxlovers.at.xml.
Shaklee still failed the ruleset coverage checker with:
Not enough tests (0 vs 1) for <Exclusion pattern '^http://member\.myshaklee\.com/\w\w/\w\w/article/'>
Not enough tests (1 vs 4) for <Exclusion pattern '^http://shaklee\.com/(?:/\w\w/\w\w/)?(?:$|\?)'>
cc @cooperq @2d1 for code review.
Merging as TBR (To Be Reviewed) since this fixes tests.
=> Fix tests.

src/chrome/content/rules/Stack-Exchange.xml
Removed meta.*.stackexchange.com as the certificate is not valid for this pattern
=> Updated Stack-Exchange.xml

src/chrome/content/code/HTTPSRules.js, src/chrome/content/rules/Google.xml, src/chrome/content/rules/GoogleVideos.xml, src/chrome/content/rules/YouTube.xml
Re-enable Youtube ruleset.
Remove broken rule within GoogleVideos ruleset, and disable the ruleset because it needs ruleset tests.
Remove /url from list of paths that fail on cctld and need to be redirected to .com.
cc @2d1 @reedy @StevenRoddis could one of you code review this? Cooper and Peter are unavailable for reviews currently. Thanks!
=> Fix some Google-related rulesets

ruleset-style.md
Using ```([\w-.]+)``` as prescribed caused the TravisCI build to fail because the dash made what's between the brackets look like a character range.
=> Fixed a reg-exp example in ruleset-style.md

src/chrome/content/code/HTTPS.js, src/install.rdf
Adds a simple detector for whether the channel URI has STS state. This will not work in Firefox <26 because of https://bugzilla.mozilla.org/show_bug.cgi?id=887052.
Fix #1219
=> Don't block HSTS requests in HTTP Nowhere mode

src/chrome/content/rules/Politiken.dk.xml
Per report in IRC, rule breaks streaming video.
Possible fix at https://github.com/EFForg/https-everywhere/pull/1170,
but not tested.
=> Disable Politiken.dk.

src/chrome/content/rules/PeerJ.xml
The backreference $2 has no corresponding capturing group, so gets appended to the URL as `$2`.
=> [PeerJ] Remove unmatched $2

docs/rulesets.html
- Specified at the beginning that HTTPS-Everywhere is not a Firefox
extension, but a "Firefox and Chrom*" extension.
- Corrected a typo (missing whitespace)
- Replaced ' with &apos; and " with &quot;
=> HTML cleanup and a couple modifications

src/chrome/content/toolbar_button.js
Add null checks to avoid various errors that occur when the
HTTPS Everywhere button is not on the toolbar. This also fixes:
Bug 13550: 'counterItem is null' if no HTTPS Everywhere button.
=> Bug 12218: toolbar_button.js should do more null checks.

chromium/background.js, chromium/rules.js
A few nits, including strict mode on background.js. (Can't add to rules.js given prototype usage.)
Also drops a random try/catch (that isn't catching any sane failures?) that breaks optimization. (see https://github.com/petkaantonov/bluebird/wiki/Optimization-killers -- chrome specifically complains about this function)
=> [Chrome] A few cleanup nits

src/chrome/content/rules/Webs-MixedContent.xml, src/chrome/content/rules/Webs.xml
Webs.com triggers a bunch of Mixed Content Blocker failures. Therefore, this patch series rewrites Webs.xml to use way less wildcards (which means test coverage \o/) and also adds Webs-MixedContent.xml to cover platforms that disable the MCB.
=> Fix Webs.com's rulesets

src/chrome/content/rules/Bit.ly_vanity_domains.xml
Remove sched.co and explain recurring problem with domains that don't point at
bit.ly anymore.
cc @cooperq @2d1 for code review.
=> Update bitly vanity domain comment.

src/chrome/content/code/HTTPSRules.js, src/chrome/content/rules/Demandware.edgesuite.net.xml, src/chrome/content/rules/ScienceDaily.com.xml
Disable sciencedaily and demandware, per reports of breakage.
cc @cooperq
=> Disable sciencedaily

makexpi.sh
cc @cooperq 
Submitting TBR as this is required to finish the release build.
=> Fix makexpi when used in build-a-release mode.

src/chrome/content/rules/Andrew-Munsell.xml
Adds `www.andrewmunsell.com` and `andrewmunsell.com` to HTTPS Everywhere. HSTS is also enabled for these two domains.
=> Add andrewmunsell.com Rules

src/chrome/content/rules/TVLine.com.xml
=> Disabled tvline.com, because it has no valid certificate

src/chrome/content/rules/Dota_2.com.xml
Fixes for #1455 
- excluded a few paths that can't be accessed over https
- added corresponding tests
=> #1455 - Fixes for dota2.com:

install-dev-dependencies.sh, src/chrome/content/rules/New-Relic.xml
get.newrelic.com is used for interacting with NewRelic's marketing emails (unsubscribing, etc). It doesn't respond to HTTPS.
=> Exclude get.newrelic.com

src/chrome/content/rules/Razer.xml
razerzone.com redirects https -> http, creating a redirect loop with the existing rule.
=> Disable Razer due to broken redirect

src/chrome/content/rules/Dreamwidth.xml
https now works on Dreamwidth for both www and journal pages
Work on Dreamwidth here. We've done a bunch of work on https support recently, and https now works with journal subdomains and for logged out users.
=> Enable Dreamwidth

src/chrome/content/rules/ThePlatform.xml
I found out the pdk subdomain of thePlatform was the culprit behind #1431. I've removed this subdomain and modernized the ruleset.
=> Update thePlatform to fix #1431

makexpi.sh
Somehow make was obtaining the return value from this cp command and erroring
on it.
This preserves makexpi's ability to build releases from 3.x stable onwards.  2.x is broken, though I'm not sure that matters.
=> Surpress make failure if the old build script didn't support AMO

makexpi.sh
- IO optimisations were useless when building tagged releases (since git
already did this), but we should keep them when building from the
git index.
- Various changes to the build scripts had meant that these were now in an
inappropriate place, so put them before all ruleset-processing build work,
and only run them if we're doing that work.
=> Re-add IO optimisations

src/chrome/content/rules/Git.xml
https://github.com/git/git-scm.com/issues/489
=> [Git] www.git-scm.com now has a certificate, drop git-scm.herokuapp.com

src/chrome/content/rules/Moverall.com.xml
This adds support for moverall.com which is a removal comparison website. It supports SSL but has no autoredirect. It also loads al its resources from SSL when accessed via SSL.
=> www.moverall.com

src/chrome/content/rules/Wikimedia.xml
The certificate is only valid for librenms.wikimedia.org
=> Exclude smokeping.wikimedia.org

src/chrome/content/rules/Dejure.org.xml
The site's owner confirmed that all pages are also available through https.
=> New rule for dejure.org

src/chrome/content/rules/T411.xml
T411 is present on both t411.me and t411.io.
Known subdomains: www., wiki., forum., there may be more.
Cookies are from forum.t411.io and .t411.io (and respectively .me).
t411.me is getting deprecated but still in use. t411.io is the new address.
=> Adding ruleset for T411

src/chrome/content/rules/Fotki.xml
fotki.com looks completely broken currently with HTTPS Everywhere. 
That's because the current rule redirects all static files to cachefly and Fotki does not use cachefly anymore. 
Since the rule was created, Fotki added support for https for most of subdomains and it's being constantly improved. So it's better to have a full redirect. (Tested, it seems to work).
=> Fix the rule that breaks fotki.com

src/chrome/content/rules/KernelOrg.xml
Uses www.kernel.org ssl cert
Fixes #1605
=> Exclude ftp.kernel.org

src/chrome/content/rules/Cdninstagram.com.xml, src/chrome/content/rules/Igcdn.com.xml
Two simple rulesets for passive (instagram) content I encountered on wired.com (the second one is just an alternate name).
=> Add rules for cdninstagram.com & igcdn.com

src/chrome/content/rules/TV2.dk-mixedcontent.xml, src/chrome/content/rules/TV2.dk.xml
Test found 4 domains which are now broken. These have been fixed. (Is disabling the entire rule, including all functional domains, fortunate?)
=> [tv2.dk update] Fixed a typo and removed domains which now force http redirects

src/chrome/content/rules/University-of-California-Berkeley.xml
This is a followup to #1336, where I attempted to add some rules for the UC Berkeley Open Computing Facility, but realized I'd first need to essentially rewrite the berkeley.edu rules (or write a hundred tests :-)).
The main changes I've made are to use more specific targets (and add a few tests where needed for the things that need a regex). Unfortunately berkeley.edu is a rather large domain with many subdomains that don't support HTTPS. I think the specific target approach is preferred over a blanket target and long regex.
This also includes a few changes and fixes to the berkeley.edu rules:
* Add rules for some new subdomains:
- {accounts{,-dev},mirrors,pma,rt,puppet,ssh,wiki,www}.ocf.b.e
- calcentral.b.e
- netreg.b.e
- bcourses.b.e
* Rewrite http://ocf.b.e/ -> https://www.ocf.b.e/
* …
=> Add Open Computing Facility rules, rewrite most of Berkeley.edu ruleset

src/chrome/content/rules/YourBittorrent.xml
The "www" subdomain doesn't seem to work on this domain. (See [this](https://www.ssllabs.com/ssltest/analyze.html?d=yourbittorrent.com))
=> Update YourBittorrent.xml: strip "www."

makexpi.sh
BSD's version of sed requires -i to specify a backup file extension. (`sed -i ''` is equivalent to not backing up the file, but then GNU sed thinks '' is the file name.) This line should work on both BSD and GNU sed.
=> Make sed -i work consistently on OSX and linux

src/chrome/content/rules/Alternativet.dk.xml
Alternativet.dk (just now, I believe) started pulling in content from tv.alternativet.dk, which is not covered by the ruleset as it serves https on a bad cert.
=> [Alternativet.dk] Deactivated: breaks video content

src/chrome/content/rules/pcgarage.ro.xml
The rule has been tested to work properly in a standalone Firefox profile
=> Added rule for pcgarage.ro

Makefile
For normal functioning, this change is 100% unnecessary. (makexpi.sh itself cleans them up before it starts building.) Nonetheless, as relatively large build artifacts (15 MB total), my sense of order in the universe wants `make clean` to handle them. :-P
=> Make 'make clean' clean up pkg/xpi-amo and pkg/xpi-eff

src/chrome/content/rules/Alternativet.dk.xml
After being made aware of the cert problem that caused the ruleset being deactivated (#1673), it looks like the devs made the site https-e friendly once again.
=> [Alternativet.dk] Reactivated: video streaming fixed

src/chrome/content/rules/Consumentenbond.nl.xml
Added a ruleset for consumentenbond.nl, a Dutch non-profit organization
dedicated to consumer protection and rights.
Some sensitive login forms where already automatically being redirected
to https urls, but the information pages weren't. That's why a dedicated
ruleset was needed.
=> [Consumentenbond.nl] Add ruleset

src/chrome/content/rules/GNUnet.xml
* The certificate is not valid for `www.gnunet.org`, redirect to `gnunet.org`
* Removed *.gnunet.org wildcard, as I haven't been able to find any relevant subdomains.
`http://de.gnunet.org` exists, but `https://de.gnunet.org` doesn't.  
However, `http://gnunet.org` 301s to `https://gnunet.org/`, which sends `Strict-Transport-Security: max-age=15768000 ; includeSubDomains`, so they break `de.gnunet.org` for everyone.
=> Updated ruleset for GNUnet.org

src/chrome/content/rules/ThePlatform.xml
This commit contains a trivial fix to the problem mentioned in #1816, simply disabling the problematic domains.
=> [ThePlatform] Disabled two subdomains; fixes #1816

src/chrome/content/rules/StatusNet.xml
All active rules in StatusNet.xml are problematic and have been removed, fixing #1838. This leaves a ruleset with no targets; perhaps this should be deleted/left with just the comment instead? Certainly the Travis test does not seem overly impressed.
=> Disabled status.net rules. Fixes #1838.

src/chrome/content/rules/UU.se.xml
After a site change, this rule no longer works; the webadmins have been notified and it will be added again if it gets fixed.
=> [UU.se] Removed www.physics.uu.se due to new (bad) cert

src/chrome/content/rules/Egedalkommune.dk.xml
The entire page is covered; the only problem I could find was [this page](https://www.egedalkommune.dk/service-sider/nyhedsbreve) which loads JS over a connection which can not be secured. Is it worth it to force an insecure connection on that one page?
=> [Egedalkommune.dk] New ruleset

src/chrome/content/rules/Jyllands-Posten.dk.xml
This fixes some problems with CORS content on politiken.dk to fix #1809. I'm curious, though, if there is something more fundamental going on with https-e and CORS(?)
=> [Jyllands-posten.dk] Added exclusion; fixes #1809

src/chrome/content/rules/Ed.ac.uk.xml
Our users were having problems because some branches of www.inf.ed.ac.uk require authentication when using HTTPS (eg to edit content), but the content is still publicly readable via HTTP.  So
I've removed www.inf.ed.ac.uk from the list of sites to automatically
redirect to HTTPS. neilb @ inf. ed. ac .uk
Excuse any newbie github faux pas, it's my first time!
Neil
=> Updated ed.ac.uk rules due to user problems.

src/chrome/content/rules/Pdfreaders.org.xml
Add ruleset for Pdfreaders.org, a site from FSFE recommending free
software PDF readers.
=> [Pdfreaders.org] Add ruleset

src/chrome/content/rules/AlltubeDownload.xml
Hello,
The app is now hosted on a Heroku free plan so HTTPS is not available on alltubedownload.net anymore, so I updated the rule.
Regards,
=> Update AllTube Download rule

src/chrome/content/rules/Demandware.edgesuite.net.xml
Remove rule for aabl_prod bucket. This path seems like it should be covered
correctly by the subsequent rule, and I couldn't find any examples to test.
@2d1 for review.
=> Re-enable Demandware.

src/chrome/content/rules/UbuntuUsers.de.xml
German Ubuntu community began to secure its websites today.
Here is a rule for it.
=> add rule for UbuntuUsers.de

src/chrome/content/rules/Pao-pao.net.xml
Note, that even though this page has mixed content, it 301-s to https,
so this rule shouldn't do any harm.
```
$ curl -I http://pao-pao.net/
HTTP/1.1 301 Moved Permanently
[...]
Location: https://pao-pao.net/
```
=> Add rule for pao-pao.net

src/chrome/content/rules/Leaflet_JS.com.xml
The rule in this ruleset pointed at a non-responding cloudfront subdomain. The subdomain cdn.leafletjs.com itself does serve https but on a bad certificate.
This fixes #1837 and #1938.
=> [Leafletjs.com] Disabled ruleset; fixes #1837 and #1938

src/chrome/content/rules/Cyon.ch.xml
The reported issue with secure cookie are resolved on the server side. The securecookie tag is obsolete.
All subdomain content is served over https. HSTS header is constructed to includeSubDomains.
=> [Cyon.ch] Resolved insecure cookie and include all subdomains

src/chrome/content/rules/Employeeexpress.gov.xml, src/chrome/content/rules/WTFismyIP.xml
The checker only failed because the subdomain is IPv6-only. It passes when run from a dual-stack system.
=> [Employeeexpress.gov][WTF is my IP.com] Reenable IPv6-only rulesets

src/chrome/content/rules/Spiegel.xml
Based on issue #1960 I fixed the broken flash videos per exclusion, added test urls and did some general fixes
img/ gets rewritten to pics/ by the site itself, so i corrected the rule
shop.spiegel.de and wissen.spiegel.de are not longer functional due to bad ssl domain
=> [Spiegel.de] fixing ruleset

src/chrome/content/rules/Tilt.com.xml
Tilt no longer uses CloudFlare so we can remove that part of the ruleset.  Also, two domains hosted on other services do not pass the correct cert over HTTPS, so I added excludes for those.
=> Adding two excludes for *.tilt.com

src/chrome/content/rules/Stack-Exchange.xml
I fixed the mixed content on the site (I'm a dev on the Careers.SO team). The downgrade rule breaks parts of the /employer section of the site, such as [employer login](https://careers.stackoverflow.com/employer/login), by causing redirect loops.
=> Remove exclusions for careers.stackoverflow.com

src/chrome/content/rules/StartCom.xml
Even though host startcom.org responds neither on 80 nor on 443, we should still protect users who type in "startcom.org" in their browsers from being exposed to a MitM attacker that keeps victims on http://startcom.org while pretending to be StartCom. This change redirects http://startcom.org to https://www.startcom.org.
=> [StartCom] Add startcom.org protection

src/chrome/content/rules/RTL.de.xml
This pull request aims to fix issue #1994 by providing a working replacement for https://a248.e.akamai.net/f/610/6737/8/bilder.akamai.net/ which fails with a 503 error (DNS failure).
Furthermore the ruleset is rewritten according to the style guidelines.
=> fix and rewrite RTL.de (#1994)

src/chrome/content/rules/Pol.dk.xml
As of today or yesterday, the existing rule would cause all images on https://politiken.dk not to be loaded. Devs are contacted, and hopefully it will be fixed soon enough.
As an aside: For PRs like these, fixing broken websites, do you want an companion issue submitted as well?
=> [Pol.dk] Disabled ruleset: connections are refused

src/chrome/content/rules/aircrack-ng.org.xml
Two minor changes: ruleset name to indicate mismatched and secure
cookies.
=> aircrack-ng.org

src/chrome/content/rules/Signal_Spam.xml
I deleted the invalid domain "signal-spam.fr" to resolve problems.
=> Deleting invalid subdomain for sigal-spam.fr

src/chrome/content/rules/Wickr.com.xml
Redirect mywickr.com to wickr.com (server's default behaviour).
=> Re-enable Wickr.com.xml

src/chrome/content/rules/Tilt.com.xml
I work at tilt.com, and we just added this new domain (hosted on a third party, so we cannot provide SSL).
=> Added policies.tilt.com to exclusion pattern

src/chrome/content/rules/Unhosted.xml
The site's SSL cert is only valid for unhosted.org and apps.unhosted.org, so *.unhosted.org is dropped. There is also redirect rule for www.unhosted.org because it presents self-signed cert.
=> Improve Unhosted.xml

src/chrome/content/rules/Open_Rights_Group.xml
Proposed edit to add northeast.openrightsgroup.org and scotland.openrightsgroup.org subdomains to preexisting ruleset.
=> Add northeast.* and scotland.* subdomains

src/chrome/content/rules/Podbean.com.xml
The site isn't displayed correctly due to content being blocked on browsers that block mixed-content content and on many other podcast sites (such as pagebreakpodcast.com) the podcast doesn't load with no indication that the cause is https everywhere.
=> Remove podbean mixcontent & subdomains

install-dev-dependencies.sh
On Debian, Chromium uses the package name `chromium` instead of `chromium-browser`, and a rebranded version of Firefox, Iceweasel, is shipped instead. (`/usr/bin/firefox` is a wrapper to `iceweasel`, so command line names don't need any changing afaik; only this.)
=> install-dev-dependencies: make packages installable on Debian

src/chrome/content/rules/PDF.yt.xml
We removed `www` last month because it didn't work; now it works again.
=> [PDF.yt] Add www again

src/chrome/content/rules/Wikimedia.xml
lists.wikimedia.org now supports HTTPS for the whole site, and it has enabled HSTS. e.g. https://lists.wikimedia.org/pipermail/commons-l/. See also https://www.ssllabs.com/ssltest/analyze.html?d=lists.wikimedia.org&latest.
=> [Wikimedia.xml] No need to exclude lists.wikimedia.org

src/chrome/content/rules/Wikimedia.xml
mediawiki.org and wikimediafoundation.org have subdomains other than www, and they all support HTTPS.
https://raw.githubusercontent.com/wikimedia/operations-dns/master/templates/wikimediafoundation.org
https://raw.githubusercontent.com/wikimedia/operations-dns/master/templates/mediawiki.org
=> [Wikimedia.xml] Include subdomains

src/chrome/content/rules/GMX.xml
Excludes gmx.com due to MCB #1895
Removes `*` and unnecessary `test url`. Update subdomain and TLD.
Excludes .ca .it .ru .se as they redirect to gmx.com
=> [GMX.xml] Update ruleset

src/chrome/content/rules/Politiken.dk.xml
This ruleset was initially disabled as a result of it breaking the various kinds of video streaming on the page. After being made aware of this, the site devs fixed the underlying mixed content issue, so this ruleset is "safe" once again.
The entire page still serves a large amount of passive mixed content, whose redirection relies on the currently disabled ruleset in Pol.dk.xml. To the best of my knowledge, devs are currently working on fixing that as well.
=> [Politiken.dk] Re-enabled; video streaming now fixed

src/chrome/content/rules/Wacken.com.xml
the travel planning widget for the Wacken festival does not work with https, I added an exclusion. The festival will take place from July 30 to August 1, 2015, so please merge this soon.
=> exclusion for wacken.com anfahrt-widget

src/chrome/content/rules/Threema.xml, src/chrome/content/rules/computerguard.xml
As a security forum we recently enabled HTTPS on [our website] (https://www.computerguard.de/).
Now we think it would be a good idea to include us in HTTPS-Everywhere.
Just a small note: As we allow including images from outer sources some users choose http:// image host and so mixed content errors can occur. However this is quite rarely and we always encourage our users to host the images on https sites or on our own forum to prevent this.
I've also described this in the comments of this rule.
But this is not really a problem as most of today's browsers does not block mixed content images anyway.
=> New rule computerguard.de

src/chrome/content/rules/YTS.to.xml
The domain, `s.ynet.io`, is a duplicate: someone else concurrently added it in `Ynet.io.xml` in fafaa2838c361a2e7a698ead200a14e3398286f6.
This reverts commit f0722e55a4f27f07fcb4585d6cdee09bf2c0970d.
=> [YTS.to] Revert "add new domain" (fixing the build!)

src/chrome/content/rules/PHP.xml
This fixes two problems:
* www.php.net cannot be used with HTTPS any more, as the domain name will redirect to a mirror that (almost certainly) doesn't have a valid HTTPS configuration.
* bugs.php.net now sends a secure PHPSESSID cookie, so that rule can be enabled.
=> php.net updates

src/chrome/content/rules/Paste2.org-falsemixed.xml, utils/trivial-validate.py
Also, expand trivial-validate to catch this case.
Fixes https://github.com/EFForg/https-everywhere/issues/2220
=> [Paste2.org] Fix bad regexp.

chromium/rules.js
This will help mitigate future bugs like
https://github.com/EFForg/https-everywhere/issues/2220, so an error processing a
single ruleset doesn't break the whole extension. cc @semenko for review.
=> Add a try/catch around ruleset processing.

src/chrome/content/rules/Heise.de.xml
unfortunately Heise redirects all news pages to plain now, after i began rewriting them.
To avoid a redirect infinite loop we need to remove them from the ruleset.
=> repair Heise.de

makexpi.sh, src/Changelog
This reduces `make` runtime ~40% on one of my (slow) systems.
(The compare page is showing four other commits from master as part of this branch, though it's not showing them in the diff. I... don't know why.)
=> makexpi.sh: Don't copy and delete rules a second time

src/chrome/content/rules/CoinWorker.xml
Certificate is no longer mismatched
=> Enable CoinWorker.xml

src/chrome/content/rules/Emply.net.xml, src/chrome/content/rules/Synchronicer.dk.xml
These two rules are useful on herlev.dk, which itself has a decent SSL implementation but probably too many bugs for use in HTTPS-E.
=> Rulesets for use on herlev.dk

src/chrome/content/code/ApplicableList.js, src/chrome/content/toolbar_button.xul
Per amo-validator advice, we should avoid setting oncommand attributes using
interpolated JS. Instead this puts one constant oncommand attribute in the XUL,
which pull the necessary rule id from a data attribute.
=> Use a data-id element for rule toggling.

src/chrome/content/rules/StartCom.xml
This rule should not be disabled. The checker encounters an error at https://auth.startssl.com/ because it requires a client certificate for the handshake to complete, but this does not mean that https-everywhere should not include this rule. Is there a way to override this error?
Thanks!
=> [StartCom] Should not be disabled

src/chrome/content/rules/www.tibia.com.xml
`http://www.test.tibia.com/*` can be redirected to `https://secure.test.tibia.com/*`.
=> Add www.test.tibia.com

src/chrome/content/rules/Whirlpool.xml
Whirlpool's now fully functional on HTTPS, so enable the ruleset and add tests.
=> Enable rules for whirlpool.net.au and add tests

src/chrome/content/code/NSS.js, src/components/ssl-observatory.js
Amo-validator alerts for every instance of the string `ctypes` in the code, even multiple times per line, totalling over 200 warnings. This obscures other, useful warnings, so we work around it by renaming the ctypes variable.
cc @cooperq for review
=> Alias ctypes to tcypes in code that uses it.

src/chrome/content/rules/Nugg.ad.xml, src/chrome/content/rules/Politiken.dk.xml
The nugg.ad ruleset test currently fails due to a lack of tests. I would add those but I am not sure what the intent of the original ruleset is (i.e. what <code>[\w-]+-s\.nuggad\.net/</code> is supposed to match).
=> Updates to Politiken.dk and its ad service nugg.ad

src/chrome/content/rules/iapc.utwente.nl.xml
The DNS policy at Twente University only allows us to use subdomains under iapc.nl and iapc.utwente.nl. The ruleset has been updated to reflect this policy and is enabled again.
A comment is added that shows the illegal rulesets and an explanation on why they are disabled, so that someone may enable them again when policy changes.
=> Repair disabled ruleset iapc.utwente.nl

src/chrome/content/rules/YouTube.xml
This pull request proposes a fix for third-party flash applications which make use of the embedded chromeless YouTube player via the deprecated AS3 API.
Most of those applications fail to load the player if we rewrite the URL to HTTPS because it is an unexpected behaviour. They expect a HTTP connection in the first place. (see this example implementation which is also broken: http://www.republicofcode.com/tutorials/flash/as3youtube/)
The connection then gets upgraded to HTTPS by YouTube itself via a HTTP 301 redirect, however if we do that by ourselves things break. This is a flaw (or security feature?) in those third-party applications or Flash itself but we can work around it by excluding the URL used for loading the player from rewrite.
Fixes #1598, #2228 and probably some other …
=> [YouTube.com] fix embedded videos

src/chrome/content/rules/Phillips_Academy_Andover.xml
Continuation of pull request #2023. Attempts to fix the mail.andover.edu rule and adds a new rule for the root domain.
Please note that https://mail.andover.edu/owa requires login credentials, and thus may cause the rule to fail checks by the automatic checker. This is similar to #2022, where the website requires authentication with a client certificate.
=> [Andover.edu] Fix mail.andover.edu rule

src/chrome/content/rules/Alphabet.xml
There are duplicate rules for abc.xyz and www.abc.xyz in the current master, causing ruleset validation to fail. This removes one of those rulesets containing these.
=> [Alphabet] Remove duplicate rule

https-everywhere-tests/test_profile_skeleton/extensions.json, makexpi.sh, src/install.rdf, test.sh, utils/make-sqlite.py
To get an automated signature from AMO for self-hosting, we need to have
a separate unlisted version of our extension. Because of a problem in AMO,
the unlisted version cannot have the same id as the listed version. So we're
renaming the self-hosted version to https-everywhere-eff@eff.org.
This also includes a change to make-sqlite.py to remove the git commit table.
The new release process will require an initial build, then a signature, then a
second build. Since that second build will be at a different git commit,
rulesets.sqlite would change and cause the signature to no longer match.
@cooperq for review.
=> Change id of extension for AMO signing.

makexpi.sh
I think there's a mistake in a `cp` in the recent changes to `makexpi.sh`, but I don't use that part of it, so I'm not certain.
`cp $SUBDIR/$XPI_NAME.xpi pkg` was changed to `cp $SUBDIR/${XPI_NAME}-eff.xpi $SUBDIR/${XPI_NAME}-amo pkg` -- shouldn't that be `${XPI_NAME}-amo.xpi`?
=> makexpi.sh: Fix cp (I think)

src/chrome/content/rules/Scriptfodder.com.xml
Re-enable the ruleset and handle `cdn.scriptfodder.com/` with special care, to prevent the 403 error, that caused https-everywhere-checker to disable the ruleset.
Provided an alternative test url, too.
=> Update rule for Scriptfodder.com

test.sh
Prior to this, Firefox would get the `--justrun` flag, which would prevent it from processing the next arg passed.
cc @cooperq for review
=> Fix justrun CLI params.

src/chrome/content/rules/CreativeCommons.xml
=> Updated creativecommons.org, now contains rule for subdomain search

src/chrome/content/rules/EDRi.org.xml
Site was default_off'ed due to dropped connections. Seems to work just fine though.
=> [EDRi.org] Reenable

src/chrome/content/rules/WePromise.EU.xml
Site seems to work just fine but it does serve an expired certificate (unless I'm being MITMed).
=> [WePromise.EU] Change default_off explanation

src/chrome/content/rules/Akamai.xml, utils/duplicate-whitelist.txt
http://imagesmtv-a.akamaihd.net/ needs to be excluded to avoid breaking all the images on <http://www.mtv.com/news/>.
Edit: Several paragraphs about testing removed. I was able to mint enough mediocre tests for the other rules in the ruleset to satisfy the scripts.
=> [Akamai] Exclude imagesmtv-a.akamaihd.net

src/chrome/content/rules/SaltStack.com.xml
The main site (saltstack.com) currently has mixed content warnings over HTTPS. I'm not sure if it's still ok to add to the ruleset or not (I don't think any functionality breaks, it looks like it's just some favicons?), so I would appreciate some guidance on that.
=> Add ruleset for docs.saltstack.com.

src/chrome/content/rules/YellowBot.xml
This service seems to really hate HTTPS-Everywhere. They dropped nearly every service on https now. Hopefully this fix will work for a bit longer.
=> fixed YellowBot.xml

makexpi.sh
Reduces runtime of an optimal `make` (rules unchanged, everything in fs cache) by 75% on one of my systems.
The locales are still by and large deleted and then copied again, but it's speedy and difficult to fix.
This *does* add `rsync` as a dependency of `make`. I'll note that 1.) rsync is lovely and everyone should install it, 2.) `test.sh` already depends on it. I could add back the slow path, too.
=> makexpi.sh: Replace `cp` with `rsync` to save copying & deleting rules

src/chrome/content/rules/Fastmail.xml
The server sends a different, non-EV, certificate if you go to https://fastmail.com rather than https://www.fastmail.com, even though you get redirected to www the non-EV certificate persists.
I let Fastmail know about this a few months ago but they haven't fixed it.
=> Fix Fastmail sending the wrong certificate

src/chrome/content/rules/THC.xml
Cert expired a month ago (01/08/15 15:29).
=> [THC.org] Disable ruleset due to expired cert

src/chrome/content/rules/Webjet.xml
Rule test might fail due to missing CA cert in `/etc/ssl/certs/ca-certificates.crt` (#1862)
Edit:
Travis CI build log,
```
+bash test-ruleset-coverage.sh
ERROR src/chrome/content/rules/LinkedIn.xml
```
Hmm....
=> New rule for Webjet

src/chrome/content/rules/mytalkdesk.com.xml
Customer can create customised subdomain, and HTTPS is still served.
=> [mytalkdesk.com] New ruleset

src/chrome/content/rules/DR.dk.xml
Radio links currently give rise to a https<->http redirect loop. Simply
excluding the relevant radio pages gives rise to CORS issues instead, and
after excluding the URLs giving rise to those, the Flash radio player still
needs to be fetched over HTTP for whatever reason.
=> [DR.dk] Fix radio streaming

src/chrome/content/rules/HsKA.xml
This commit adds www.hs-karlsruhe.de and qis.hs-karlsruhe.de to the ruleset
=> Add www.hs-karlsruhe.de and qis.hs-karlsruhe.de to ruleset

.travis.yml
Just caching pip only saves the downloads, but the most time is spent compiling.
=> Cache Travis's python packages

src/chrome/content/rules/Wikimedia.xml
The mixed content issue on https://stats.wikimedia.org/ has been fixed.[1] So remove the mixed content section in the comment.
[1] https://phabricator.wikimedia.org/T93702
=> [Wikimedia.xml] mixed content has been fixed

src/chrome/content/rules/Strava.com.xml
Both `strava.com` and `www.strava.com` have valid certificates.
=> Add trivial rule for Strava

src/chrome/content/rules/Sainsburys.co.uk.xml
This rule only supports `www` because the bare domain doesn't have a valid SSL certificate.
Some things (like login) are already using HTTPS, but this rule ensures that all pages use HTTPS and we don't end up with silly things like login forms on an HTTP page with an HTTPS action.
=> Add rule for www.sainsburys.co.uk

src/chrome/content/rules/Agar.io.xml
Fixes #2799.
The ruleset was previously disabled upon webmaster request, but the webmaster has now requested that it be reenabled (GH #2799).
=> [Agar.io] Reenable ruleset

src/chrome/content/rules/respekt.cz.xml
The rule is disabled by default so that user login form is not broken,
however it's still nice to have the rule around in order to be able to
opt-in for https (as everything else works).
On Tor Browser, the login form may even work with the rule enabled by
default (if it isn't also overriden by cross-origin blocker, see
https://github.com/EFForg/https-everywhere/issues/2695 for details).
=> Add rule for Respekt.cz

src/chrome/content/rules/PrintFriendly.xml
The rules are invalid currently and HTTPS for our main domain will not
work 100% since we embed third party content which may not be HTTPS
=> Disable PrintFriendly Rules

chromium/popup.css
On high DPI/Retina displays, Chrome uses a higher resolution image for the generic favicon. This can cause some odd layout placement on the popup page.
The fix is to just simply set the width and height of the ```<img>``` tag to 16.
=> Set the size of favicons to 16x16 on Chrome extension

src/chrome/content/rules/ReadTheDocs.xml
Fixes GH-2847
/cc @ericholscher
Both .com and .org are fully https with *.readthedocs.org and *.readthedocs.com certificates.
So I _think_ this change will just 100% redirect everything correctly? Not 100% sure how to test.
=> Fix ReadTheDocs rules

src/chrome/content/rules/T411.xml
Special server irc.t411.io (also accessible through irc.t411.me) doesn't
provide any secured channel. Trying to access the server with https will
fail. An exclusion rule has been added thus.
Also added a coverage test for the server api.t411.io (and its .me
counterpart).
Note: yes, the server includes a specific web server, in addition to the
IRC service. The IRC service can be accessed with SSL on a specific
port, the web service cannot. The web server at irc.t411.io is a
different one than www.t411.io.
Signed-off-by: Cilyan Olowen <gaknar@gmail.com>
=> Exclude irc.t411.io from rewrite

test/chromium.sh
```
+ ./utils/mktemp.sh
./utils/mktemp.sh: 9: ./utils/mktemp.sh: Syntax error: "(" unexpected
```
This is what happens when ```test/chromium.sh``` is run with the ```--justrun``` parameter. This PR fixes the error.
=> Fix mktemp crash

src/chrome/content/rules/Wikimedia.xml
https://cs.wikimedia.org/, https://cz.wikimedia.org/, https://download.wikimedia.org/, https://download.wikipedia.org/, https://sitemap.wikimedia.org/ no longer use invalid certificates, so these can be covered by the general http to https rewrite.
=> [Wikimedia.xml] Remove some redundant rules

src/chrome/content/rules/Exposure.co.xml
It runs on Tumblr and only supports HTTP.
=> Don't redirect gettingstarted.exposure.co to HTTPS

test/chromium/script.py
When running the test scripts (and thus pre-commit hook) on a Linux distribution which is neither Ubuntu or Debian, the `chromedriver_path` variable isn't set at all, and the script will then always fail with a error such as this:
```plain
Traceback (most recent call last):
File "test/chromium/script.py", line 51, in <module>
driver = webdriver.Chrome(chromedriver_path, chrome_options=chromeOps)
NameError: name 'chromedriver_path' is not defined
```
This fixes that by providing the fallback value of just "chromedriver" to other Linux distributions, which at least makes it work on my machine (running Arch Linux).
=> Provide a fallback chromedriver for other Linuxes as well

src/chrome/content/rules/Octoshape.xml
Ruleset test failures occur in unrelated rulesets.
=> [Octoshape] Reenable

test/firefox.sh
I've tested the OS X side of this fairly thoroughly. In theory it should also be tested on GNU/Linux, but the change is so simple, who cares. I'm sure it works.
=> Make ./test.sh --justrun work on OS X

src/chrome/content/rules/Yandex.net.xml
Kinopoisk.ru use amcharts to draw charts (for example, [here](http://www.kinopoisk.ru/votes/)). Some time ago charts were broken by extension.
=> Fix kinopoisk.ru charts

src/chrome/content/rules/TLDRLegal.com.xml
Website cert valid for `tldrlegal.com`, `community.tldrlegal.com`, `dev.tldrlegal.com`, but not for `www.tldrlegal.com`.
=> Fix tldrlegal.com

src/chrome/content/rules/Esolangs.org.xml
Notes:
* The cookie name regex can just be `.`; it just has to match, no need for it to capture the entire string. (In fact, you can do `new RegExp("")` with an empty string, but I don't know how this works under the hood so I used a dot just to be safe.)
* Non-capturing groups perform significantly better than capturing groups.
=> Add Esolangs.org

chromium/rules.js
`.attributes.default_off` returns `undefined` since `attributes` returned from `DOMParser` is array-like `NodeList` and not key-value object. Attribute access is correctly implemented via `getAttribute` in all the other places of the code, so this could be just an oversight.
Fixes #2959.
=> Fix access to default_off attribute in RuleSets lib.

src/chrome/content/rules/Spiegel.xml
This fixes this page for example:
http://www.spiegel.de/sport/fussball/bundesliga-live-ticker-tabelle-ergebnisse-spielplan-statistik-a-842988.html#contest=bl1
This page uses javascript and it fails to load the additional parts without this change.
=> [Spiegel.de] fix Fußball live

src/chrome/content/rules/Webs.xml
Current rewrite was either typo or something changed, anyway test URL below failed.
=> Fix static.websimages.com rewrite

src/chrome/content/rules/Riotgames.com.xml
Created a ruleset for engineering.riotgames.com. Other riotgames domains don't seem to support https.
=> Support for engineering.riotgames.com.

src/chrome/content/rules/Blendle.xml
This removes the exclusion for the UserVoice sub domain, because it's no longer available. It also extends the `securecookie` rule to include all sub domains.
=> Update Blendle ruleset

src/chrome/content/rules/An.de.xml
Note that it only covers pk.an.de. Should I possibly rename it to
`pk.an.de` because of this?
=> [An.de] New ruleset

src/chrome/content/rules/LegitScript.xml
We no longer use a separate hostname for ssl connections
=> Update LegitScript rule

src/chrome/content/rules/Dispenser.tf.xml
Both http://www.dispenser.tf and https://www.dispenser.tf serve 404 Bad requests; we update the ruleset to avoid the www part altogether.
This fixes https://github.com/EFForg/https-everywhere/issues/3119
=> [Dispenser.tf] Update ruleset

src/chrome/content/rules/Deutsches_Forschungsnetz.xml
Some content such as http://cdp.pca.dfn.de/uni-erlangen-nuernberg-ca/pub/cacert/cacert.pem can not currently be secured.
This fixes GitHub issue https://github.com/EFForg/https-everywhere/issues/3067
=> [Deutsches Forschungsnetz] Add exception

src/chrome/content/rules/GroupMe.com.xml
Domains ^, www, and dev already serve HSTS headers but some resources from i.groupme.com are not secured without this ruleset.
Fixes #2996
=> [GroupMe.com] New ruleset

src/chrome/content/rules/National_Grid.xml
All tested subdomains have issues. In particular, nationalgrid.com and www.nationalgrid.com redirect to www2.nationalgrid.com which does not accept SSL connections.
This fixes #2979.
=> [National Grid] Update ruleset; disable most of it

src/chrome/content/rules/Online2pdf.com.xml
No 301 redirect to HTTPS, but they have a button on their HTTP site (at
the right top) which links to the HTTPS version, so they explicitly
support HTTPS. This means everything should work without any problems.
=> [Online2pdf.com] New ruleset

src/chrome/content/code/IOUtil.js
Causes warnings in Firefox Nightly.
=> Remove non-standard expression closure from IOUtil

src/chrome/content/rules/BBVA-Bancomer.xml, src/chrome/content/rules/TerraMailMX.xml, src/chrome/content/rules/TerraUserCentralMX.xml
I would like to contribute three new rulesets. Two of them (BBVA-Bancomer.xml and TerraMailMX.xml) pass both the manual tests and ``fetch-test.sh``. The other rule (TerraUserCentralMX.xml), breaks the layout and manual login, so it is turned off by default.
The reason I include the disabled ruleset is that Terra Mail has a (somewhat buried) button that redirects logged users to Terra User Central, logging them automatically to the latter, thus, a cookie obtained through HTTPS is sent to a HTTP site. I could not figure out how to prevent it with ``securecookie``.
=> My new rules

src/chrome/content/rules/Codeplex.xml
To help fix some non-HTTPS downloads of CodePlex. See also https://veracrypt.codeplex.com/workitem/251
=> [Codeplex.com] Added (new?) download domain, small cleanup

src/chrome/content/rules/Hollywood-Reporter.xml
We moved The Hollywood Reporter from Akamai to Edgecast a year ago and it has fully SSL support.
=> Updated HTTPS rule for HollywoodReporter.com

src/chrome/content/rules/Denic.de.xml, src/chrome/content/rules/WebGo.xml, src/chrome/content/rules/WebGo24.de.xml
Fixes https://github.com/EFForg/https-everywhere/issues/2875, 301
redirects to HTTPS
As Denic.de was mentioned in WebGo24.de I wanted to change this. However
WebGo24.de was a very bad wildcard ruleset without test URLs and without
any use of the wildcard. So I had to rewrite this too.
=> [Denic.de] New ruleset; [WebGo24.de] Rewrite

src/chrome/content/rules/Service.gov.uk.xml
`service.gov.uk` is the subdomain which all government services and transactions in the UK will run on. It's really important to make sure they're secure.
An example is [the service to register to vote in elections](https://www.gov.uk/register-to-vote).
Generally services use subdomains of a `service.gov.uk` subdomain which I believe this rule will catch, for example:
- `www.registertovote.service.gov.uk`
- `assets.registertovote.service.gov.uk`
Here's [the guidance that the Government Digital Service provides to government departments who operate `service.gov.uk` subdomains](https://www.gov.uk/service-manual/operations/operating-servicegovuk-subdomains).
The relevant section is titled "Transport Layer Security":
> Many services will collect personal information from users. It’s very …
=> Secure all subdomains of `service.gov.uk`

src/chrome/content/rules/VC-Server.xml
This handles three `vc-server.de` domains and also `(www.)vc-kundencenter.de` plus `(www.)vc-kundenservice.de`.
=> Add rule for VC-Server

src/chrome/content/rules/jekyllrb.com.xml
This update adds Jekyll discussion forum page `(talk.jekyllrb.com)` to the ruleset.
A comment also removed because redirection from `www` subdomain to secure HTTPS works.
I have tested this ruleset in the browser.
=> Update Jekyll ruleset to include Jekyll Talk

src/chrome/content/rules/Gml.cz.xml, src/chrome/content/rules/Stremio.io.xml
Namely [stremio.io](https://stremio.io) and [www.gml.cz](https://www.gml.cz) .
Stremio is a young app for streaming video content from the internet & p2p networks.
GML is our school website.
Both have HTTPS, but the don't have it enabled by default.
=> Add two sites

src/chrome/content/rules/Bitmask.net.xml
https://deb.bitmask.net uses a self-signed cert which CN is not matching
the subdomain.
=> [bitmask.net] cover all but deb in *.bitmask.net

src/chrome/content/rules/Lets_Encrypt.org.xml, src/chrome/content/rules/Powerlineman.com.xml, src/chrome/content/rules/ProjectEuler.xml, src/chrome/content/rules/Threema.xml, src/chrome/content/rules/WebAssign.xml
AFAIK the cookie host is only saved as a domain (`example.com`). However some rulesets contained a following slash `/` which I removed as this would break the securecookie functionality.
=> Remove end / included in cookie host

src/chrome/content/rules/gimp.org.xml
We've recently added HTTPS support via Let's Encrypt, so the majority of gimp.org domains can now be accessed this way.
=> Ruleset for gimp.org domains

src/chrome/content/rules/Itpol.dk.xml
itpol.dk and www.itpol.dk now serve a LE-signed certificate and can be used. Note that wiki.itpol.dk still serves the incorrect content over HTTPS, even though itpol.dk itself serves a HSTS includeSubDomains header; this is clearly a misconfiguration and the devs have been informed.
=> [Itpol.dk] Update and enable ruleset

src/chrome/content/rules/Microsoft.xml
https://microsoft.com currently serves a bad certificate, its CN only covering *.microsoft.com. This fixes https://github.com/EFForg/https-everywhere/issues/3234.
=> [Microsoft] Redirect microsoft.com to www.microsoft.com

src/chrome/content/rules/MP3Skull.xml
Some of these already redirect to HTTPS but http://mp3skull.ninja does not.
=> [MP3Skull] New ruleset

src/chrome/content/rules/Idenyt.dk.xml
Some Emediate scripts (secured by us) are blocked as mixed content in Firefox/Chrome but this has no effect on site function.
=> [Idenyt.dk] New ruleset

src/chrome/content/rules/Wikimedia.xml
These services have recently been fixed and now use https.
The exceptions can be removed.
https://gerrit.wikimedia.org/r/#/c/256986/
https://gerrit.wikimedia.org/r/#/c/256969/
https://gerrit.wikimedia.org/r/#/c/255463/
https://gerrit.wikimedia.org/r/#/c/256879/
=> wikimedia: remove smokeping and torrus services

src/chrome/content/rules/Roblox.xml
At the moment only api.roblox.com supports HTTPS for all visitors, but other subdomains will probably support it in the future, so it will be possible to add them to the `Roblox.xml` ruleset.
=> Add ruleset for roblox.com

src/chrome/content/rules/Zendesk.com.xml
radar.zendesk.com is hosted with Github Pages therefore requires redirection to correct URL to fix SSL error
=> Fix radar.zendesk.com

src/chrome/content/rules/LinuxTV.org.xml
As mentioned in https://github.com/EFForg/https-everywhere/issues/3357, the site no longer serves an untrusted certificate.
=> [LinuxTV] Update and activate ruleset

src/chrome/content/rules/Favstar.fm.xml
Favstar has finally removed their HTTPS to HTTP redirects. See https://twitter.com/TimHaines/status/676986243822014464.
=> Update Favstar.fm rules

src/chrome/content/rules/Oculus_VR.xml
Re-open https://github.com/EFForg/https-everywhere/pull/3246. Addressed https://github.com/EFForg/https-everywhere/pull/3246#issuecomment-164446928
All subdomains should support HTTPS, according to HSTS policy.
=> [Oculus.com] Simplify ruleset and update domain.

src/chrome/content/rules/University_of_Wisconsin-Madison.xml
Add support for subdomains:
* cs.wisc.edu
* discovery.wisc.edu
* doit.wisc.edu
* go.wisc.edu
* housing.wisc.edu
* kb.wisc.edu
* library.wisc.edu
* math.wisc.edu
Updated rule documentation (old comments not valid for all domains). Further updated this documentation with new domains to explain why they are not yet supported (for example, mixed content warnings caused by Google site search).
=> [wisc.edu] Add multiple subdomains

utils/validate.sh
This achieves a couple of different things:
- Previously, when some rulesets contained errors, xmllint would be run twice when running it only once was sufficient. This thus saves a fair amount of time.
- Previously, the end of the script would never actually be executed since xmllint would break it. In particular, the obtained exit status might not have been the expected one.
- Echo errors to stderr instead of stdout.
- Most importantly: Give some additional output when validation failure is due to one of the two most common ruleset errors, where the existing error output was not particularly helpful.
=> Changes to ruleset validation output

src/chrome/content/rules/Wdr.de.xml
All content on www1.wdr.de appears to redirect to HTTP. Disabling it also fixes https://github.com/EFForg/https-everywhere/issues/3347.
=> [Wdr.de] Disable www1

src/chrome/content/rules/Avm.de.xml
This excludes most of the content on avm.de, adding the existing exclusions from en.avm.de to this main domain as well. This fixes a redirect loop on the front page and false mixed content blocking on several subpages (cf. the test URLs). In particular, this fixes https://github.com/EFForg/https-everywhere/issues/3346.
=> [Avm.de] Add exclusions

src/chrome/content/rules/SwitchVPN.xml
Re-open previous PR https://github.com/EFForg/https-everywhere/pull/3015, which I messed up.
Also addressed https://github.com/EFForg/https-everywhere/pull/3015#issuecomment-149020763 through line 21.
The blocked mixed content shouldn't be a concern as it doesn't affect the site functionality (tested).
=> [SwitchVPN.net] New ruleset

src/chrome/content/rules/Sussan.com.au.xml
Both sussan.com.au and www.sussan.com.au are misconfigured and shouldn't be used, even with platform="mixedcontent". However, assets.sussan.com.au can actually be redirected to cloudfront directly.
=> [Sussan.com.au] Update ruleset

src/chrome/content/rules/Scene7.xml
This fixes at least two different issues. One is GH issue #2430, in which the ruleset would cause embedded videos at
https://www.verizonwireless.com/wcms/overlays/tips-video.html
to not load.
Another is a flawed redirect for http://s7sps3.scene7.com/.
Note that at the moment, the www1 subdomain appears to serve nothing.
=> [Scene7] Update ruleset; disable wildcard rule

src/chrome/content/rules/Postdanmark.dk.xml
This fixes https://github.com/EFForg/https-everywhere/issues/3166
The page http://postdanmark.dk/da/Sider/Quick%20Finder/LocationFinder.aspx includes content from www2.postdanmark.dk which in turn would fetch (falsely) blocked mixed content from maps.google.com.
=> [Postdanmark.dk] Add exclusion

src/chrome/content/rules/Qrpedia.org.xml
Causes mixed content errors; disabled by default because of missing chain.
I've contacted the site authors - maybe they'll fix it: https://twitter.com/rugkme/status/664840438503899136
=> [QRpedia.org] New ruleset

src/chrome/content/rules/Koreatimes.co.kr.xml
The site currently provides an expired certificate. In particular, this fixes #3398. Webmasters have been notified.
=> [Koreatimes] Disable ruleset

src/chrome/content/rules/Amara.xml
Login only saved for non-www domain, therefore it is a pain to manually
add www to access logged version of pages.
=> Fix amara login

src/chrome/content/rules/El-Giganten.dk.xml, src/chrome/content/rules/Elgiganten.se.xml, src/chrome/content/rules/Elgiganten.xml
This merges the rules for elgiganten.dk and elgiganten.se into a single ruleset. It also excludes all product pages as these produce various (false) mixed content blocking related issues; in particular, this fixes https://github.com/EFForg/https-everywhere/issues/3245. Devs have been informed about those issues.
=> [Elgiganten] Various updates and fixes

src/chrome/content/rules/Nativo.net.xml, src/chrome/content/rules/Ntv.io.xml, src/chrome/content/rules/Postrelease.com.xml
Nativo has a new version of their JS library that's served through a new domain. While adding a rule file for that, I noticed that the other rule files covering them needed to be brought up to the new standards, so I did that as well.
=> Nativo additions and cleanup

src/chrome/content/code/ApplicableList.js
If I understand it correctly, the first menuitem in the dropdown menu has been coloured black so as to avoid it being gray with its disabled status. This doesn't work very well on dark-themed setups though:
Now, I don't know of a way to pick out the text colours of the other menuitems, but <code>-moz-MenuBarText</code> seems to almost do the trick. This probably requires a bit of testing on various systems/theme setups.
=> Suggestion: Change style of heading menuitem

src/chrome/content/rules/Phpdoc.org.xml
disabled because expired cert; [I've asked](https://twitter.com/rugkme/status/664158508808581121) what PhpDoc wants to do about this.
=> [New ruleset] PHPDoc

src/chrome/content/rules/Wikimedia.xml
The removed domains have been included in Chrome's HSTS-preloaded list for quite a long time. So no need to include them in HTTPS Everywhere. Wikimedia.org is not currently HSTS-enabled, so it remains here.
=> [Wikimedia.xml] Remove already preloaded domains

src/chrome/content/rules/Trulia-cdn.com.xml
Use https trulia-cdn.com instead. Fixes #2233 and #3175
=> fix: Don't use broken akamai for Trulia

src/chrome/content/rules/Openresty.org.xml
No 301 redirect, but the whole website only seems to exist of a few sites.
**Attention:** Do not merge right now. Currently https://qa.openresty.org/ has a TLS error. Hopefully [this will be fixed](https://github.com/openresty/openresty.org/issues/16) soon.
=> [Openresty.org.xml] New ruleset

src/chrome/content/rules/Transport_for_London.xml
TfL has got a lot better since this rule was written in September 2012. Almost everything supports HTTPS and there are just a few subdomains which don't. The certificate is a wildcard cert now.
=> Update Transport for London

src/chrome/content/rules/Podnapisi.xml
podnapisi.net is a subtitle website that supports HTTPS, but sadly does not redirect to it, making you connect via unencrypted HTTP whenever you forget to include the 'S' in HTTPS. An HTTPS Everywhere rule would partially remedy this.
=> Add rule for podnapisi.net

src/chrome/content/rules/Teo.xml
teo.lt is the website of a Lithuanian ISP that has the same problem as the one described in #3502.
=> Add rule for teo.lt

src/chrome/content/rules/DreamHost.xml
I modified the exclusion line with the two existing inclusions to include transferapproval.dreamhost.com
Modified the spacing on the header since this new domain is longer and threw off the tabbing
=> Dreamhost subdomain transferapproval.dreamhost.com does not work over https

src/chrome/content/rules/Thecthulhu.com.xml
The rule for thecthulhu.com is missing a few subdomains, some of which do not redirect to HTTPS and therefore are in need of an HTTPS Everywhere rule.
This would also rename the rule to "Thecthulhu.com", since the space that is there is unnecessary.
=> Improve the rule for thecthulhu.com

src/chrome/content/rules/Laravel.com.xml
`laravel.com` and `www.laravel.com` do not support HTTPS ([source](https://twitter.com/taylorotwell/status/678975762154676224)). This ruleset is listed as "stable" which is kind of annoying.
`forge.laravel.com` does use HTTPS.
=> Fix Laravel rules

src/chrome/content/rules/Fefe.xml
On stable, instead of master.
We should really clean up our mess of branches & tags, and make this a bit clearer for new contributors.
Reverts EFForg/https-everywhere#3581
=> Revert "reflect certificate changes on fefe.de"

src/chrome/content/rules/GoExplore.net.xml
HTTPS connections are now redirected to HTTP... Unfortunately.
=> [GoExplore.net] Disable ruleset

src/chrome/content/rules/Tickets.gwr.com.xml
tickets.gwr.com uses http (despite seemingly supporting https with no issues) whilst all other subdomains of gwr.com use https.
=> Add rule for tickets.gwr.com

src/chrome/content/rules/NVidia.xml
- remove shield subdomain from the akamai redirect list
- remove shield test urls
=> fix Nvidia shield subdomain

src/chrome/content/rules/Suddeutsche_Zeitung.xml
- add global & jetzt subdmain
- clean up & extend testurls
- clean up exlusions patterns
- simplified rule for the immobilienmarkt-subdomain
- replaced exclusion patterns with proper rules
=> Sueddeutsche.de:

src/chrome/content/rules/Tisarana.ca.xml
Site has new content that causes this ruleset to trigger active mixed content blocking, which breaks parts of the site. Changing to `platform=mixedcontent` to fix it.
=> [Tisarana.ca] Change to Mixedcontent

src/chrome/content/rules/Fosscon.us.xml
Some Google fonts are blocked as mixed content, but the site works fine without them.
=> [Fosscon.us] New ruleset

src/chrome/content/rules/make-trivial-rule
The description of what the script does no longer reflected what it actually does.
=> Update make-trivial-rule description

test/chromium.sh
Fixes `bash test/chromium.sh --justrun` on Debian systems, where the chromium package is named differently than on Ubuntu.
The package name logic is copied from the existing `install-dev-dependencies.sh` script: https://github.com/EFForg/https-everywhere/blob/5effa1541a5a8dd9299a9a7820cec2a6a8052655/install-dev-dependencies.sh#L8
=> Fix standalone chromium profile runner in Debian

README.md
This updates the main README test-running instructions to match the current directory structure, with all of the tests in the tests/ directory
=> Update test running instructions for new test/ dir

src/chrome/content/rules/La_Naya_Chocolate.xml, src/chrome/content/rules/TorrentButler.xml, src/chrome/content/rules/Zimperium.xml
zimperium.com is a website that supports but fails to redirect to HTTPS and therefore is in need of an HTTPS Everywhere rule.
=> Add a few rules

src/chrome/content/rules/Jodel-app.com.xml
Per the request to split #3805 into separate PRs for each of the rulesets, here's the PR for disabling [Jodel-app.com.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Jodel-app.com.xml) because its certificate has expired.
=> Disable Jodel-app.com.xml

src/chrome/content/rules/Serveriai.lt.xml
Per the request to split #3805 into separate PRs for each of the rulesets, here's the PR for tweaking [Serveriai.lt.xml](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Serveriai.lt.xml) (removing the unnecessary wildcard).
=> Tweak Serveriai.lt.xml

src/chrome/content/rules/Filepicker.io.xml
Filepicker has been re-branded to Filestack. Rename ruleset but not filename (to retain history).
=> [Filepicker.io] Rename ruleset, add new domains.

.travis.yml, test/firefox.sh, test/firefox/test_profile_skeleton/extensions.json
This also adds an option to override the path to Firefox when running tests (e.g. to run a developer version), and updates the extensions.json to the latest schema, without which the test won't run.
cc @cooperq @pde for review.
=> Make Firefox run on the latest version in Travis.

src/chrome/content/rules/Earwolf_Podcast_Network.xml
The certificate for earwolf.com is *long* expired.
=> Disable rule for earwolf.com (expired cert)

src/chrome/content/rules/OpenMPT.xml
Neither openmpt.org nor any of its subdomains redirect to HTTPS, despite supporting it.
This fixes #3900.
=> Add rule for openmpt.org. Fixes #3900

src/chrome/skin/https-everywhere.css
It's unnecessary and incongruous with other modern addons.
cc @SwartzCr @cooperq for review.
Fixes #1697
=> Remove dropdown triangle from toolbar button.

src/chrome/content/rules/Piquadro.xml
[Piquadro.com](https://piquadro.com) fails to redirect to HTTPS despite supporting it.
=> Add rule for piquadro.com

src/chrome/content/about.xul, src/chrome/locale/en/https-everywhere.dtd
This changes a few hardcoded strings so as to allow for localisation. ~~Obviously the way this is done is not ideal, though, as translations are handled through a torproject.org based git submodule. The corresponding changes to this, which in turn is based on Transifex in a way that I do not remember, would be of the same form as those in https://github.com/fuglede/torproject_translation/commit/67875f8bf227798d8b46b77a4f6557e70cd365c3 which contains the changes to the English and Danish language strings. Cc @jsha for review/lesson on what I should have actually done ...~~
Scratch that; I remembered the logic.
=> Add a few strings for localisation in the 'about' window

src/chrome/content/rules/Vimeo.xml
Vimeo now supports HSTS (including subdomains). Still no secure cookie though.
=> [vimeo.com] Re-enable ruleset

chromium/rules.js
(For #1775 & inspired by @blockoperation's awesome work in https://github.com/blockoperation/https-everywhere/tree/chromium-memory-usage-v2 )
Don't create rule arrays when unneeded.
=> Memory usage improvements

src/chrome/content/rules/Nodes.dk.xml
The site specifies a HSTS header but does not redirect to HTTPS on its own.
=> [Nodes.dk] New ruleset

src/chrome/content/rules/Ubisoft-Entertainment.xml
and use additional https urls.
=> ubi.com updates

chromium/background.js, chromium/rules.js
I found this fun bug while expanding "use strict" for some ES6 features:
Because of the IIFE (immediately-invoked function expression) surrounding `localPlatformRegexp`, it's never worked. `this.userAgent` is undefined during execution, and the else is always taken, resulting in `chromium` being the platform -- always.
Let's just rip this out, since it hasn't worked and `mixedcontent` support has been dead for a while in Chrome (and FF 23+, and Opera 23+).
In the future, we should consider allowing Chrome users to enable `mixedcontent` rules, similar to the FF behavior.
Signed-off-by: Nick Semenkovich \<semenko@alum.mit.edu\>
=> Expand "use strict" use & drop (broken) old Opera mixedcontent support

chromium/background.js, chromium/popup.html, chromium/popup.js
Allow users to enable/disable HTTPSe from the extension popup itself -- otherwise it's hard to temporarily suspend the extension.
Two notes:
- On Chrome restart, the extension is always enabled
- I tried allowing users to disable HTTPSe per-tab [see commits], but that's a mess — pre-rendered tabs randomly replace current tabs, cookie rules don't understand the concept of a tab, etc.
This looks like:
Closes #760
Signed-off-by: Nick Semenkovich \<semenko@alum.mit.edu\>
=> Add an on/off switch for Chrome

src/chrome/content/rules/Virgin_Media.com.xml
national.virginmedia.com and identity.virginmedia.com now support proper cipher suites and no longer support RC4 (see links below), so they should be uncommented in Virgin Media's ruleset.
https://www.ssllabs.com/ssltest/analyze.html?d=identity.virginmedia.com
https://www.ssllabs.com/ssltest/analyze.html?d=national.virginmedia.com
=> Uncomment formerly rc4-only viginmedia.com subdomains

chromium/background.js, chromium/rules.js
Replace blacklists and potentiallyApplicableRulesets with actual Set()s, trying to clean up the Chrome code.
Compatible with FF 38 ESR and above per https://kangax.github.io/compat-table/es6/
=> Expand use of Set()

chromium/background.js, chromium/rules.js
Performance & memory usage improvements (for #1775), inspired in part by @blockoperation's suggestions.
- For trivial rules (`^http: -> https:`), set the Rules values equal to null (and handle null as a trivial rule), instead of creating a new, silly RegExp for every single one
- For trivial cookie names (~50% of cookie names are `.*` or `.+`), do the same
=> Regexp reduction for trivial rules + cookie names

src/chrome/content/toolbar_button.js
The first time the browser is started after installing
https-everywhere, a notification bar is shown, informing of
the fact that some https enforcement is active and pointing to the
toolbar button for options.
What is bad about that is that when the notification is dismissed, the
browser is forced to open https://www.eff.org/https-everywhere/faq
This is a privacy breach, as it informs the authors (and user's ISP)
that there is a new installation of https-everywhere.
This change adds a dedicated button to the notification bar.
Pressing that button loads the FAQ page as before, and just dismissing
the notification bar does nothing. In other words, it makes the user
*request* the FAQ before loading it.
Fixes #769.
=> load FAQ after install only if requested

src/chrome/content/rules/GoogleAPIs.xml
Current ruleset doesn't `target` the subdomain, despite having a `test url`.
e.g. http://storage.googleapis.com/bloomsky-video/eaB1rJytnZSmm6q3_-8_2015-11-09.mp4
Noticed this issue while testing for https://github.com/EFForg/https-everywhere/pull/4051.
=> [Google APIs] Add storage.googleapis.com

src/chrome/content/rules/WorldCommunityGrid.xml
Stop redirecting worldcommunitygrid.org requests to
secure.worldcommunitygrid.org. The former now supports HTTPS.
Closes https://github.com/EFForg/https-everywhere/issues/3963
=> [WorldCommunityGrid] Don't redirect to "secure" subdomain

src/chrome/content/rules/Virgin_Media.com.xml
The target tags for identity.virginmedia.com and national.virginmedia.com were uncommented in   #3998, but the comment in the ruleset wasn't changed to reflect that.
This fixes #4024.
=> Fix comment in Virgin_media.com.xml

chromium/incognito-cache-clearing.js, chromium/manifest.json
Fixes:
- Stops us from ~doubling memory usage on incognito (by instantiating again)
- Rule preferences & custom rules are shared in incognito
This is a little verbose, since:
- There's no easy way to see when incognito sessions are destroyed, and we
don't want to maintain additional state about window IDs.
- We need to clear caches when incognito sessions are destroyed, like Chrome
does for about:net-internals/#dns, for example.
Closes #4034
=> Switch to spanning incognito

.travis.yml, install-dev-dependencies.sh, test/chromium.sh, test/firefox.sh
I'm not sure if this is categorically useful.  There may be instances where you actually want to have the ability to interact with the webdriver browser.  We could also add this as an option, like `--headless` if desired.
=> Make tests headless with the help of xvfb

src/chrome/content/code/ApplicableList.js
JSON.stringify was transforming custom rule ids:
From: custom_0
To: "custom_0"
(quotes included in the string)
This was breaking the ability to disable custom rules.  This fixes it by making sure rules fit a certain regex for validation, but removing the JSON.stringify.
=> Fix: custom rules should be disableable

src/chrome/content/rules/Bit.ly_vanity_domains.xml
I went through the instructions in #4097 so the target domains all have valid https endpoints. It looks like all the rules are snapping redirects, other than the few very particular mzl.la path redirects. Some of those were simply mimicking server redirects that no longer exist, others were very specific paths that are still redirecting. Either way, https://mzl.la and all paths behind it redirect to https endpoints it looks like, so this should no longer be needed.
I also removed the exclusion patterns, as they seem brittle to me. Why should we only redirect bit.ly patterns that we've observed as valid instead of them all? What if they change this pattern? Better to just redirect them all.
I'm not completely sure if I've done everything right here and would appreciate any feedback you …
=> Bitly vanity domains: direct http to https redirect (resolves #4097)

src/chrome/content/code/ApplicableList.js
This avoids "uri.host is explosive" errors in the logs on URIs like
about:startpage. This check already happens in https-everywhere.js before
calling replaceChannel, but this other path into rewrittenURI wasn't checked
previously.
=> Check scheme before attempting to rewrite.

makexpi.sh, src/chrome/content/code/HTTPSRules.js, src/components/https-everywhere.js, utils/make-sqlite.py, utils/validate.sh
This loads much faster, and avoids reads from disk after startup.
Previously, loading all targets from SQLite took about 268ms. Now it takes about
60ms, including reading the file from disk and parsing JSON.
This replaces #3852 by removing SQLite support altogether.
=> Switch to using JSON to store rulesets.

utils/android-push.sh
script will error out with: `error: device offline`.   This fixes the
issue by grepping out offline devices from `adb devices` first.
=> Fix: If an android device is connected but offline, the android-push.sh

src/chrome/content/rules/Codecademy.com.xml
As [said in the forum](https://discuss.codecademy.com/t/suggestion-https-on-subdomains/7935/10?u=rugk) the discuss subdomain now also supports HTTPS.
The discuss-cdn subdomain does not seem to be used anymore.
=> [Codecademy.com] Add subdomain

src/chrome/content/rules/EinsteinAtHome.org.xml, src/chrome/content/rules/University-of-Wisconsin-Milwaukee.xml
Adds rules for einstein@home's alternative .org domain and securecookie
entry for its uwm.edu domain.
=> [Einstein@Home] Add .org rule

utils/downgrade-whitelist.txt
Downgrade rule has been removed from following rules (with corresponding commit):
Gigya (partial) ea881c383e819900bc8a2499243f540ba65c5443
GO.com (partial) 3f534ac0474c2de417082402d69d71331a166e74
Jabber.ru (partial) c97d1fda0a8329b3648ad998479a226918dbb451
Phoronix.com (partial) 666c4112fb8a723243203fcee9d37ec0bd737694
xxxbunker.com (partial) 96c87f3158c860f6752c67fdcaa83c4abac87b4e
=> [downgrade-whitelist] Remove ruleset that no longer have downgrade.

src/chrome/content/rules/Custhelp.com.xml
Fixes #4060 reported by Konomi.
https://motorola-global-community.custhelp.com/ mismatches with forums.motorola.com.
http://motorola-global-community.custhelp.com/ redirects to https://forums.motorola.com/ anyway.
=> [Custhelp.com] Work around mismatch on motorola-global-community.custhelp.com

src/chrome/content/rules/AdRiver.xml, src/chrome/content/rules/Mail.ru.xml, src/chrome/content/rules/Yandex.net.xml
I reverted "Fix kp charts" commit e000988a399cc00fe39ef61fd955c8d7f7fad865 in favour of more specific kinopoisk charts fix that does not unencrypt whole `st.kp.yandex.net` domain. Revert commit also include similar fix for rutube.ru.
=> yandex.ru and rutube.ru crossdomain.xml

.travis.yml
Too spammy: With the old config I'd get notifications of others' build failures.
=> Remove special travis notifications section.

src/chrome/content/rules/AvonandSomersetConstabulary.xml, src/chrome/content/rules/CambridgeshireConstabulary.xml, src/chrome/content/rules/CityofLondonPolice.xml, src/chrome/content/rules/ClevelandPolice.xml, src/chrome/content/rules/CumbriaConstabulary.xml, src/chrome/content/rules/DevonandCornwallPolice.xml, src/chrome/content/rules/DurhamConstabulary.xml, src/chrome/content/rules/EssexPolice.xml, src/chrome/content/rules/GloucestershireConstabulary.xml, src/chrome/content/rules/HertfordshireConstabulary.xml, src/chrome/content/rules/LeicestershirePolice.xml, src/chrome/content/rules/PoliceUK.xml, src/chrome/content/rules/StaffordshirePolice.xml, src/chrome/content/rules/WarwickshirePolice.xml, src/chrome/content/rules/WestMerciaPolice.xml, src/chrome/content/rules/WestMidlandsPolice.xml
**Renamed rules for the following UK Police Forces:**
- [Cambridgeshire Constabulary](https://www.cambs.police.uk/)
- [Essex Police](https://www.essex.police.uk/)
- [Hertfordshire Constabulary](https://www.herts.police.uk/)
- [Staffordshire Police](https://www.staffordshire.police.uk/)
- [West Midlands Police](https://www.west-midlands.police.uk/)
to match official names: [https://www.police.uk/forces/](https://www.police.uk/forces/)
**Added rules for the following UK Police Forces:**
- [Avon and Somerset Constabulary](https://www.avonandsomerset.police.uk/)
- [City of London Police](https://www.cityoflondon.police.uk/)
- [Cleveland Police](https://www.cleveland.police.uk/)
- [Cumbria Constabulary](https://www.cumbria.police.uk/)
- [Devon and Cornwall …
=> Add and update UK Police Forces

src/chrome/content/toolbar_button.js, src/chrome/content/toolbar_button.xul, src/components/ssl-observatory.js
1. Refactor js one-liner to allow ssl observatory component to load
2. HTTPSEverywhere object can no longer be refernced directly from
toolbar xul
=> Fixes for Firefox Developer Edition (resolves #4195)

src/chrome/content/rules/GoogleAPIs.xml
The 404s in the folder roots look a bit different over HTTP and HTTPS, but according to https://tools.ietf.org/html/rfc6962#section-4, all CT logs are to be served over HTTPS, so as far as the actual logs are concerned, this should be alright.
=> [GoogleAPIs] Add ct.googleapis.com

src/chrome/content/rules/Phpdoc.org.xml
Continuing https://github.com/EFForg/https-everywhere/pull/3184
Preparing ruleset for the change of phpdoc to @letsencrypt [they announced](https://twitter.com/phpDocumentor/status/677591475354476544). You can merge this once they have switched.
=> [Phpdoc] Activate ruleset [DNM]

src/chrome/content/rules/Deepin.xml
Including "*.deepin.com", "*.deepin.org" and "*.linuxdeepin.com" domains.
=> Recreate Deepin related ruleset.

src/chrome/content/rules/Virus_Bulletin.xml
Resolves https://github.com/EFForg/https-everywhere/issues/4273
=> [VirusBulletin] Add new domain

src/chrome/content/rules/Waffles.fm.xml
Same problem as #4299, #4300, #2980.
Also simplifies the rule to trivial one.
=> Fix invalid RegExp in Waffles.fm.xml

src/chrome/content/rules/yell.com.xml
@loveithateit: The ruleset check was not broken, but was finding a real problem
with the ruleset: URLs like "http://marketing.yell.com///" don't get rewritten
by the rule you were adding tests to, because they get caught by the exclusion.
I've fixed the rule to only apply to the root URL, but please double check that
this matches your intention.
cc @cooperq for code review.
=> Fix failing ruleset tests.

src/chrome/content/rules/portsmouth.gov.uk.xml
Same problem as #4302, #4301, #4300,  #4299, #2980.
=> Fix invalid RegExp in portsmouth.gov.uk.xml

src/chrome/content/rules/Bothar.xml
Using lookahead with substitution causes `$1` to appear in the end URL:
```javascript
> 'http://bothar.ie/'.replace(new RegExp('^http://(?:www\.)?bothar\.ie/'), "https://$1bothar.ie/")
"https://$1bothar.ie/"
```
Same problem as older #2980.
=> Remove Bothar.xml

chromium/rules.js
I'm running `addUserRule` in Node.js which fails due to `INFO` not being defined, and I noticed that other methods use various log types as well, so decided to fix altogether.
=> Stub all log types to execute other methods in Node.js

src/chrome/content/rules/Viacom.xml
api.mtvnn.com prevented videos from loading here:
http://www.mtv.de/charts/5-hitlist-germany-top-100
This site might be geoblocked in other countries, just like the US version is geoblocked for me, so I can't check this. Apart from that I simplified the rewrites.
=> simplified and fixed Viacom.xml

src/chrome/content/rules/Booking.com.xml
This explicitly excludes the subdomain blog.booking.com, which currently times out. In particular, this fixes https://github.com/EFForg/https-everywhere/issues/4350.
=> [Booking.com] Exclude broken subdomain

src/chrome/content/rules/OFTC.net.xml, src/chrome/content/rules/webchat.oftc.net.xml
* Rename **webchat.oftc.net** ruleset to **OFTC.net**.
* Add `oftc.net` and `www.oftc.net`.
* `https://oftc.net/` has a mismatched certificate for `www.oftc.net`, but serves an HTTP redirect to `www.oftc.net` anyway.
=> Rename webchat.oftc.net to OFTC.net and add new hosts

src/chrome/content/rules/Volksverschluesselung.xml
HSTS header is set for the domain , so preloading it might also be worth a shot.
=> add rule for Volksverschlüsselung

src/chrome/content/rules/Wilders-Security-Forums.xml
No longer uses a self signed cert.
@J0WI trivial, no subdomains.
=> [Wilders] Update and enable

src/chrome/content/rules/Transport_for_London.xml
This fixes https://github.com/EFForg/https-everywhere/issues/4390
=> [Transport for London] Exclude subdomain content

src/chrome/content/rules/Apple.xml
Creates an exclusion for /apple-events/ which is currently broken
(constant reload loop).
Partially resolves https://github.com/EFForg/https-everywhere/issues/4432
This is technically already too late for the Apple event which was today.
=> [Apple] Add exclusion

src/chrome/content/rules/OpenBlox.xml
HTTPS is supported on all subdomains.
=> [openblox.org] New ruleset

src/chrome/content/rules/PJ_Media.xml
Following up on https://github.com/EFForg/https-everywhere/issues/4558, this updates and disables the ruleset.
=> [PJ Media] Disable ruleset

src/chrome/content/rules/Mbl.is.xml
The entirety of the "fasteignir" subpage would appear to serve redirects to HTTP, so we exclude that to avoid some loops. In some (but apparently not quite all) cases, this would also break the search form on http://www.mbl.is/fasteignir/.
=> [Mbl.is] Add exclusion to fix redirect loop and breakage

src/chrome/content/rules/OFTC.net.xml
This change is effectively a no-op, since https://oftc.net/ just redirects to www.oftc.net, which is what we did anyway. Still, this simplifies the ruleset.
=> [OFTC.net] oftc.net cert mismatch is fixed

src/chrome/content/rules/ScummVM.org.xml
[scummvm.org](https://www.scummvm.org/) has recently switched on HTTPS.
It has many subdomains in use, but those don't have HTTPS yet. I will submit updates once those are in place.
=> [ScummVM.org] New ruleset

src/chrome/content/rules/Wikimedia.xml
It has a `<rule>` for `wikimedia.cz`, but no `<target>`.
I assume it was inadvertently omitted.
I also removed a redundant `<test>` that will be taken care of automatically.
=> [Wikimedia] Fix missing <target> for wikimedia.cz

src/chrome/content/rules/Speedrun.com.xml
Simple trivial rule for a new domain.  This domain has SSL support already and everything appears to work fine.
=> Added trivial rule for speedrun.com domain.

src/chrome/content/rules/Automattic.xml
Recreate `Automattic.xml`.
It was removed in 143128b3f9b647c3a07aa3063239e42f6a3e055f (2012), then independently recreated by @youdly in #3983 (January), then independently recreated again by me in #4585 (today).
This combines the best of all 3, reverting 143128b3f9b647c3a07aa3063239e42f6a3e055f, merging #3983, and rewriting #4585.
=> Recreate Automattic.xml

src/chrome/content/rules/GnuCash.xml
As mixed content goes, the page https://svn.gnucash.org/ has an image that is embedded via the URL http://www.ihtfp.com/Ihtfp.gif From what one understands, the default setting for Firefox is to load images (but not scripts) that are fetched via HTTP but embedded in an HTTPS page. As such, the functionality of the page should not be affected.
=> New ruleset for GnuCash

.travis.yml
(from https://github.com/EFForg/https-everywhere/issues/4645#issuecomment-214907617)
The problem seems to be not that we're using an outdated version of `curl` and `libcurl`, but that the version of `pycurl` that is installed by default in the travis build system uses `gnutls`, which apparently as @mnordhoff states does not support ECDSA keys.
I found that running the fetch test on https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Archive.is.xml on my local instance of Ubuntu 14.04 did not result in an error.  Thinking it curious, I noticed that the errors that we encounter are referencing `gnutls`, but that my own pycurl uses `openssl`.  I had both libraries installed, but it seems that pycurl prefers `openssl` when it is available, unless explicitly told …
=> Reinstall pycurl, making sure it uses OpenSSL instead of GnuTLS

src/chrome/content/rules/growerscup.coffee.xml
The site _does_ have HSTS enabled, but it isn't preloaded and there's no HTTP -> HTTPS redirect, so one still has to explicitly type https:// to get to the site securely the first time.
=> Add ruleset for growerscup.coffee

src/chrome/content/rules/Linode.xml
(It's still StatusPage.io.)
This is low priority, since the old redirect to https://linode.statuspage.io/ still works (for now, at least). But this is nicer. :smile:
Edit: On Travis, the firefox-latest tests succeeded, and firefox-esr-latest failed. Probably due to cached DNS. I'll rerun it later. I suppose it shouldn't be merged for ~24 hours until old DNS caches have expired anyway.
Edit: Travis is green now.
=> [Linode] https://status.linode.com/ has a proper certificate now.

src/chrome/content/rules/Minecraft.xml
Both ^ and www now work. This also adds a comment about a broken subdomain.
This closes https://github.com/EFForg/https-everywhere/issues/4703
=> [Minecraft] Update ruleset

src/chrome/content/rules/Princeton.edu.xml
The domain serves an invalid certificate; this in particular fixes https://github.com/EFForg/https-everywhere/issues/4665
=> [Princeton.edu] Remove subdomain tigernet

src/chrome/content/rules/Egotastic.xml
Mixed content warning for some advertising scripts. Is that a problem? Seems to me like security shouldn't be compromised for ads. What's the rule of thumb here?
Edit: Would it be better to add a platform="mixedcontent"?
=> Add Egotastic.com

src/chrome/content/rules/OpenBSD.org.xml
* Enable
* Add `^`, `lists` & `www`
* Remove `https` (no longer resolves)
Reported by someone on IRC.
They also mentioned that `cvsweb` may or may not be coming soon, but in any case it isn't here yet.
=> [OpenBSD.org] Enable, add ^ lists www, remove https.

src/chrome/content/rules/Minecraft-falsemixed.xml, src/chrome/content/rules/Minecraft.xml
As a follow-up on https://github.com/EFForg/https-everywhere/pull/4706#issuecomment-217903213, this adds several subdomains as targets, adds comments on broken ones, and adds a separate ruleset for a subdomain subject to false mixed content blocking.
=> [Minecraft] Add subdomains

src/chrome/content/rules/localphone.com.xml
Add rule for missing sub-domain:
- https://m.localphone.com/
Add rules for other Localphone-owned sites:
- https://www.0800buster.co.uk/
- https://www.freecallscanada.co.uk/
- https://www.freecallstosingapore.co.uk/
- https://www.freecallstousa.co.uk/
=> [localphone.com] Add sites owned by Localphone Ltd.

src/chrome/content/rules/News_Limited.xml
The previous change introduced a broken catch-all rule on accident. Removing it fixes #4561.
=> [News Limited] Remove wildcard rule

Makefile, makecrx.sh, makexpi.sh
* `make clean` now deletes the old `rulesets.unvalidated.sqlite` and `rulesets.sqlite` files
* `makecrx.sh` and `makexpi.sh` now delete the old `rulesets.sqlite` file and super-old `default.rulesets` file. (I'm pedantic.)
* (A `makecrx.sh` comment that referred to SQLite has been updated.)
I think it's important for `make clean` to continue to remove the old files, for people who forget to clean before pulling or switching between branches. (Ahem.)
I also think it's useful for `makecrx.sh` and `makexpi.sh` to do it, but that might be more controversial. (And maybe should have been a separate pull request.)
I don't know about you folks, but i build HTTPS Everywhere from a dirty directory, and i was unwittingly building double-size XPIs with `default.rulesets` for *months* after the switch …
=> Delete old ruleset databases in 'make' and 'make clean'

src/chrome/content/rules/Craigslist.org.xml, utils/downgrade-whitelist.txt
- Fixes #3997 by downgrading and excluding geo.craigslist.org
- Adds securecookie
- Simplifies the subdomain rule pattern, as per the [Ruleset Style Guide](https://github.com/EFForg/https-everywhere/blob/master/ruleset-style.md)
=> [Craigslist.org] Downgrade geo.craigslist.org

src/chrome/content/rules/Mozilla.xml
https://releases.mozilla.org/ now works.
=> [Mozilla.xml] releases.mozilla.org now supports HTTPS

src/chrome/content/rules/Lisonfan.com.xml
The site ships with a 301 redirect to HTTPS as well as the preload token but is not yet on any of the vendor preload lists. This closes https://github.com/EFForg/https-everywhere/issues/4804.
=> [Lisonfan.com] Add ruleset

src/chrome/content/rules/Teltarif.xml
According to
www.teltarif.de/https-verschluesselung-sicherheit/news/63626.html
did the website introduce TLS for both mobile and desktop version of their site
=> add rule for Teltarif.de

src/chrome/content/rules/CJS-CDKeys.com-mixed.xml, src/chrome/content/rules/CJS-CDKeys.com.xml
This modifies <code>trivial-validate.py</code> to no longer include the test for unescaped dots in the exclusion patterns; this test was introduced by @jsha in fb2d2bfd8ad0ca9ae169d3de283b58d0a3a1838e, which makes me think that it is probably there for a reason, though (no reason is given in the commit message specifically, but the same commit fixes up two patterns where wildcards were used (erroneously in one case)).
In this case, I ended up scratching my head for a good while because of it, as I used wildcards in an exclusion in order to fix #4498.
Edit: This no longer changes the test but only fixes the ruleset; see below.
=> [CJS-CDKeys.com] Splits ruleset due to false MCB; fixes #4498

src/components/ssl-observatory.js
This fixes a few separate but related issues with how we test proxy settings for the SSL observatory.
Commit https://github.com/EFForg/https-everywhere/commit/6de406768a56ad5dabda4b6f614c786d1a0805a1 resolves the edge case in https://github.com/EFForg/https-everywhere/issues/2719#issuecomment-219892166 where a user who has set a custom proxy will be making outbound requests to `check.torproject.org`.
The second issue, discovered while researching the first, is explained here: https://github.com/EFForg/https-everywhere/issues/2719#issuecomment-220182600.  Within the Tor Browser, we attempt to discover if the user can make outbound requests over Tor before the circuit is actually established.  This is technically a race condition, but since it will always take longer for the circuit to be …
=> Tor observatory integration (resolves #2719)

src/chrome/content/rules/SolarMovie.xml
The .is domain still exists and redirects to .ph so I just kept it.
=> Solarmovie.is to SolarMovie.ph

src/chrome/content/rules/Leakedsource.com.xml
Trivial ruleset; the site itself 301s to https; this closes https://github.com/EFForg/https-everywhere/issues/4870
=> [Leakedsource.com] Add ruleset

src/chrome/content/rules/Copenhagenmarathon.dk-falsemixed.xml, src/chrome/content/rules/Copenhagenmarathon.dk.xml
Unfortunately, the main Wordpress page provides a fair bit of false mixed content blocking, but this captures a good deal of the securable part of the site.
=> [Copenhagenmarathon.dk] New rulesets

src/chrome/content/rules/Ziplist.com.xml
Certificate expired in December 2015
=> Disable ziplist.com

src/chrome/content/rules/Cloudfront.xml
Broken trailer (video) on http://www.rottentomatoes.com/m/the_revenant_2015/
The source `d3biamo577v4eu.cloudfront.net` seems to support HTTPS just fine but I believe rotten tomatos is trying to force it over HTTP (I couldn't locate the actual source), so I'm excluding this rule in an attempt to resolve it.
Did a search and this was actually reported last year: https://github.com/EFForg/https-everywhere/issues/2742
=> [Cloudfront] Attempt to fix rotten tomatoes video playback

test/rules/coverage.checker.config, test/rules/disable-broken-rulesets.checker.config, test/rules/http.checker.config, test/rules/manual.checker.config
This doubles the length of the timeout restrictions for all current https-everywhere-checker configs in an attempt to fix https://github.com/EFForg/https-everywhere/issues/4810.
Arguably, since Travis is the one causing that particular issue, it could suffice to change only http.checker.config, but increasing all of them is probably safer for database-wide runs anyway.
=> Increase ruleset testing timeout limits

src/chrome/content/rules/Cisco.xml
This subdomain seems to have been removed and can no longer be resolved in DNS.
* http://csc-stage.cisco.com/
* https://csc-stage.cisco.com/
=> Remove csc-stage.cisco.com from Cisco rules.

test/travis-ruleset-fetch.sh
Immediately display the output of the travis fetch test - don't wait till it has completed
=> immediate fetch output

chromium/background.js, chromium/manifest.json, chromium/popup.html, chromium/popup.js, chromium/storage.js, src/chrome/locale/en/https-everywhere.dtd
Some minor code changes required for WebExtensions compatibility for Firefox.
These changes can be safely merged without affecting any functionality in Chrome.
To test the functionality in Firefox, apply the following patch:
```
diff --git a/makecrx.sh b/makecrx.sh
index 6cc852d..2758a28 100755
--- a/makecrx.sh
+++ b/makecrx.sh
@@ -76,11 +76,20 @@ sed -i -e "s/VERSION/$VERSION/g" pkg/crx/manifest.json
if [ -n "$BRANCH" ] ; then
crx="pkg/https-everywhere-$VERSION.crx"
+  xpi="pkg/https-everywhere-$VERSION.xpi"
key=../dummy-chromium.pem
else
crx="pkg/https-everywhere-$VERSION~pre.crx"
+  xpi="pkg/https-everywhere-$VERSION~pre.xpi"
key=dummy-chromium.pem
fi
+
+# Package the Firefox WebExtensions XPI format
+cd pkg/crx
+zip -r httpse.zip .
+cd ../..
+mv pkg/crx/httpse.zip $xpi
+
if ! [ -f …
```
=> Webextensions

src/chrome/content/rules/Golem.de.xml
This fixes https://github.com/EFForg/https-everywhere/issues/4770. It would be nice of course to disable only part of the domain, but I couldn't find an easier way out of this one. In particular, the following attempts did not solve the problem:
* Exclude all js/swf/xml on the domain but leave the rest intact.
* Exclude everything but the "files/" subfolder (which contains
the relevant videos).
=> [Golem.de] Disable subdomain video

src/chrome/content/rules/VEVO.xml
https://img.cache.vevo.com/ has a mismatched certificate (a248.e.akamai.net).
Therefore, http://img.cache.vevo.com/ is rewritten to https://scache.vevo.com/.
However, https://www.vevo.com/ uses a lot of "//img.cache.vevo.com/" protocol-relative images, which wind up going to https://img.cache.vevo.com/ and failing.
So, let's rewrite https://img.cache.vevo.com/ to https://scache.vevo.com/ too.
This change also rewrites https://cache.vevo.com/. I don't know if it's necessary -- i haven't looked hard -- but i decided it was simpler not to add a second rule.
* Remove special rule for vevo.com; it's not problematic. (It has a valid cert and redirects to www.vevo.com.)
* Modernize the style.
The ruleset could probably use other changes -- new subdomains, for example -- but this fixes the status …
=> [VEVO] Rewrite https URLs used in protocol-relative links; update style

src/chrome/content/rules/Le-Monde-diplomatique.de.xml
I have got one question before this pull request is merged. Regarding `securecookie`, the following is stated in *docs/rulesets.html*:
> A cookie whose domain attribute starts with a "." (the default, if not specified by Javascript) will be matched as if it was sent from a host name made by stripping the leading dot.
Does that mean that cookies like the following will be matched by `<securecookie host="^monde-diplomatique\.de$" name=".+" />`?
=> Add rules for German Le Monde diplomatique

src/chrome/content/rules/Netflix.com-problematic.xml, src/chrome/content/rules/Netflix.xml
Netflix has enabled TLS on most of their websites so i think it is time to re-enable the ruleset.
Sites without valid cert & timeouts still are off by default.
=> Netflix update

src/chrome/content/rules/Dota2lounge.com.xml
This sets `platform="mixedcontent"` for the ruleset which otherwise has its style sheets blocked. This follows up on https://github.com/EFForg/https-everywhere/pull/5131 and partially reverts https://github.com/EFForg/https-everywhere/pull/4835
=> [Dota2lounge.com] Avoid false mixed content blocking

src/chrome/content/rules/Idenyt.dk.xml
All functioning target hosts are now serving bad certificates.
=> [Idenyt.dk] Disable ruleset

src/chrome/content/rules/Uv.es.xml
This pull request fixes the rules for www.uv.es, an Spanish university, and most of its subdomains.
Namely:
- The name of the ruleset has been escaped. For some reason, the grave prevented HTTPS Everywhere from loading the file.
- Adds a special rule for uv.es, redirecting to https://www.uv.es/
- The subdomains of blogs.uv.es have been replaced by a single wildcard target. This can be done because the server has a wildcard certificate for *.blogs.uv.es.
=> [uv.es] Fixed ruleset

src/chrome/content/rules/Computerbase.de.xml
As of today CB has enabled TLS on the whole site for all users, not just those that have a paid subscription.
=> ComputerBase remove rewrite Restrictions

ruleset-style.md
Wrap some code snippets in backticks for readability e.g. `foo`.
The styleguide says to prefer tabs over spaces, so this commit
converts the correct ruleset example at the bottom to use tabs instead
of spaces.
=> Format ruleset-style.md

ruleset-testing.md
The ruleset target was using `example.com` but the rule was using
`dezeen.com`.
=> Fix example rule in `ruleset-testing.md`.

src/chrome/content/rules/PostNord.se.xml
The GitHub issue https://github.com/EFForg/https-everywhere/issues/5353 points out that the current ruleset causes a redirect loop; this fixes the issue by simply disabling the ruleset.
=> [PostNord] Turn off ruleset by default

src/chrome/content/code/HTTPS.js, src/chrome/content/toolbar_button.xul, src/chrome/locale/en/https-everywhere.dtd
This excludes .onion hostnames from the main HTTP Nowhere request block. It also updates the HTTP Nowhere label to reflect the change (but perhaps a better wording exists?).
The change is tested in Tor Browser 5.5.3 in which it does what is intended.
This fixes https://github.com/EFForg/https-everywhere/issues/4118
Note: Since this changes the name of a i18n string, a pull of the PR needs to be synced with the translations submodule.
=> Allow requests to hidden services with HTTP Nowhere

src/chrome/content/rules/xkcd.xml, utils/downgrade-whitelist.txt
https://xkcd.com/ now includes a protocol-relative link to `//c.xkcd.com/random/comic/`; since https://c.xkcd.com/ has a [problematic certificate chain (among other issues)](https://www.ssllabs.com/ssltest/analyze.html?d=c.xkcd.com), it needs to be downgraded.
=> [xkcd] Downgrade https://c.xkcd.com/ to http

src/chrome/content/rules/UserScape.xml
Currently, userscape.com serves 404s on all HTTPS requests. This takes care of the issue by redirecting all traffic to www.
=> [UserScape] Redirect ^ to www

chromium/popup.html, src/chrome/content/rules/Thecthulhu.com.xml
* Add `akp.thecthulhu.com` and `time.thecthulhu.com`
* Remove `annefrank.thecthulhu.com` and `hp.thecthulhu.com`; they no longer resolve
=> [Thecthulhu.com] Add akp and time, remove annefrank and hp

src/chrome/content/rules/Hummingbird.me.xml
Adds support for [hummingbird.me](https://hummingbird.me).
**Edit:** Added `www` subdomain (redirect) and secured cookies.
=> [Hummingbird.me] Add ruleset

test/rules/src/https_everywhere_checker/check_rules.py
When a fetch error occurs, try the URL once more before reporting an error
=> test fetch error twice

src/chrome/content/code/HTTPSRules.js, src/components/https-everywhere.js, src/install.rdf
In order to make https-everywhere a SystemAddon, it cannot have unpack true
flag in install.rdf. The flag was there, so ruleset.json can be references
with FileUtils API.
This PR, introduce alternative way of loading rulesets that are exposed as chrome resources. In this way an extension can be marked as unpack=false
=> Fetch rulset via chrome url

src/chrome/content/rules/Yahoo_Japan.xml
- Removed chiebukuro from search subdomains because http://chiebukuro.search.yahoo.co.jp is redirected to http://chiebukuro.yahoo.co.jp
- Added chiebukuro.yahoo.co.jp
- Added detail.chiebukuro.yahoo.co.jp
=> Updated Yahoo_Japan.xml

src/chrome/content/rules/Archive.is.xml
After having had a couple of different issues with this ruleset, cf. in particular https://github.com/EFForg/https-everywhere/issues/5805 and https://github.com/EFForg/https-everywhere/issues/4075.
I prompted the webmaster for what would be a proper solution moving forwards. On their request, this avoids redirecting anything to https://archive.is/ but ensures that the relevant connections are still upgrading by using archive.fo instead. Indeed, they considered disabling the option to use secure connections to archive.is but were happy with still providing the option in this slightly round-about fashion.
This closes #5805.
=> [Archive.is] Update ruleset

src/chrome/content/rules/hosts-file.net.xml
Recently hpHosts announced they started supporting HTTPS.  However, automatic redirect of the main domain (with and without www) got disabled due to issues with certain third-party applications.
Since redirecting on interactive web browsers should be safe, I am proposing the addition of hosts-file.net and www.hosts-file.net to HTTPS Everywhere.
=> Add hosts-file.net

src/chrome/content/rules/filecrypt.cc.xml
After the .html there always is a `?` followed by a string of number. Like this: `?1469099854883`
I don't know if the added exclusion pattern covers that, nor am I able to test it.
=> filecrypt.cc: restore click'n'load functionality #5727

install-dev-dependencies.sh, test/chromium/README.md, test/chromium/script.py
I've been working on a development environment for HTTPS-Everywhere running with Vagrant. I'm on a Windows 10 host and setting up a [Fedora 24 Cloud](https://atlas.hashicorp.com/fedora/boxes/24-cloud-base) guest. Why not Ubuntu 16.04? Because the ubuntu/xenial64 box [has problems](https://bugs.launchpad.net/cloud-images/+bug/1565985). Why not Ubuntu 14.04? Because I need SMB support and that seems to require a [more recent kernel](https://github.com/mitchellh/vagrant/issues/6188#issuecomment-171396607).
My working environment is Git (Bash) for Windows 2.9.0.
This pull request fixes some documentation and adds missing dnf dependencies.
Here are various other issues I encountered that should be documented somewhere. I can write the documentation if you can tell me where to put it.
The …
=> Fixes and documentation for development on Vagrant with Windows 10 host/Fedora 24 Cloud guest

src/chrome/content/rules/OPM.gov.xml
https://www.leadership.opm.gov/ no longer uses mismatched certificate, and it can successfully redirect to https://leadership.opm.gov/ by the server.
[1] https://www.ssllabs.com/ssltest/analyze.html?d=www.leadership.opm.gov&hideResults=on
=> [OPM.gov.xml] remove a redundant rule

src/install.rdf, test/firefox/test_profile_skeleton/extensions.json
This closes https://github.com/EFForg/https-everywhere/issues/6066. Test failure is unrelated (#6079).
=> Remove some dashes

src/chrome/content/rules/sankakucomplex.com.xml
Also added a outcommented exclusion rule for charts.sankakucomplex.com to point out that not all subdomains have https.
charts.sankakucomplex.com/niconico can be reached from the Videos menu in the navbar at the main page.
=> Added Sankaku Complex image boards

src/chrome/content/rules/24-ways.xml
Add `24ways.org` and `www.24ways.org`. No longer partial.
Rewrite `cloud.24ways.org` and `media.24ways.org` to themselves instead of their former AWS buckets.
=> [24 ways] Add hosts; no longer partial; update rewrites

src/chrome/content/rules/Foolz.us.xml
No target hosts function. This closes https://github.com/EFForg/https-everywhere/issues/6171.
=> [Foolz.us] Update and disable ruleset

src/chrome/content/rules/prntscr.com.xml
`prntsrc.com` redirects all requests to HTTP, causing redirect loops. `prnt.sc` on the other hand, requires active mixed content from `prntsrc.com`. This closes https://github.com/EFForg/https-everywhere/issues/6074.
=> [prntscr.com] Disable ruleset

src/chrome/content/rules/WhatPulse.org.xml
Adds support for [whatpulse.org](https://whatpulse.org).
**Edit:** I'm not sure why the build failed, [developer.whatpulse.org](https://developer.whatpulse.org) appears to work just fine on my end.
**Edit 2:** Added `www` subdomain, added notes for `amcdn` and `direct` mismatched subdomains, secured cookies.
=> [WhatPulse.org] Add ruleset

src/chrome/content/rules/Megabus.com.xml
The megabusgold.com sites fail fetch-test.sh, probably because of a missing CA certificate in the development environment. I've reported that in issue #6275. This should be okay to go live though.
=> Add Megabus.com.xml

src/chrome/content/rules/1fichier.xml
Example link: `https://alterupload.com/?dkqfao9flj`
One of their domains (dfichiers.com) wasn't configured correctly (SSL_ERROR_BAD_CERT_DOMAIN) so I left it out.
=> Add 1fichier.com and mirrors

src/chrome/content/rules/UrlQuery.xml
This fixes https://github.com/EFForg/https-everywhere/issues/6560
=> [UrlQuery] Disable ruleset

src/chrome/content/rules/Particle.io.xml
Particle uses quite a few subdomains and most appear to support HTTPS.
`community` in particular, needs a redirect rule as it does not
redirect to HTTPS automatically.
=> Make trivial rule for particle.io

src/chrome/content/rules/Mozilla.xml
This fixes https://github.com/EFForg/https-everywhere/issues/6613.
=> [Mozilla] Add exclusion for subdomain symbolapi

src/chrome/content/rules/Flexyourrights.org.xml
This ruleset is trivial; the site itself 301 redirects to HTTPS on connections to the included targets.
This closes https://trac.torproject.org/projects/tor/ticket/17614.
=> [Flexyourrights.org] New ruleset

rewriter/package.json, rewriter/rewriter.js
From `npm`:
npm WARN deprecated URIjs@1.11.2: package renamed to "urijs" (lower-case), please update accordingly
=> [https-everywhere-rewriter] Rename URIjs to urijs

test/rules/http.checker.config
The purpose of this commit is to avoid having Travis hit whitelisted rulesets in `test/fetch.sh` which caused some unexpected behaviour in #6684 (and possibly other places?)
I suppose one should really ask oneself why the skiplist is not already in there, and what the expected behaviour actually should be, but when I [put in the config](https://github.com/jsha/https-everywhere-checker/pull/4/commits/05d7c201f857a1fdfcd50ce85f626fbbd9f7b0df) last year, I think I just omitted it by mistake. At least, I can't really come with any reason for doing it on purpose.
For testing, I added the contents of this PR to #6684 after which all tests were green.
=> Add skiplist to http.checker.config

src/chrome/content/rules/Kvasir.no.xml
New rule for [Kvasir.no](https://kvasir.no/), a Norwegian search engine (Google front-end). Currently the 250th most visited website in Norway, [according to Alexa](https://www.alexa.com/topsites/countries/NO).
Everything works over HTTPS except for this their map service – kart.kvasir.no – which is not included in this patch as that subdomain isn’t available over HTTPS.
=> Added Kvasir.no

src/chrome/content/rules/Nyaa.eu.xml, src/chrome/content/rules/Nyaa.se.xml
- [nyaa.se](https://www.nyaa.se) now supports https on all its subdomains
- nyaa.eu now redirects to nyaa.se
**Edit:** Added main domain, secured all cookies.
=> [Nyaa] Update rulesets

src/chrome/content/observatory-popup.xul
Fixes #6078
@fuglede how does this look?
In order to test, apply the following patch:
```patch
diff --git a/test/firefox/test_profile_skeleton/prefs.js b/test/firefox/test_profile_skeleton/prefs.js
index 42b3f0a..7ff28e9 100644
--- a/test/firefox/test_profile_skeleton/prefs.js
+++ b/test/firefox/test_profile_skeleton/prefs.js
@@ -1,7 +1,7 @@
// Submit SSL Observatory reports.
-user_pref("extensions.https_everywhere._observatory.enabled", true);
+//user_pref("extensions.https_everywhere._observatory.enabled", true);
// Don't show any popups that might get in the way of testing.
-user_pref("extensions.https_everywhere._observatory.popup_shown", true);
+//user_pref("extensions.https_everywhere._observatory.popup_shown", true);
user_pref("extensions.https_everywhere.toolbar_hint_shown", …
```
=> Expand popup window (fixes #6078)

src/chrome/content/rules/BusinessInsider.xml
This should fix issue #5014 regarding broken video on businessinsider.com (example [here](http://www.businessinsider.com/how-plucking-nose-hairs-can-cause-lethal-infections-2016-6)). Commits 9ea45fbf452bbc49e6f97810e2b2631c9f353ff0 and 1e0802e635d9038d51320bd5b63d8b5725a0c48f fix these errors I get with `fetch-test.sh`:
```
ERROR rules/BusinessInsider.xml: Fetch error: http://www.businessinsider.com/account => https://www.businessinsider.com/account: Too many redirects while fetching 'https://www.businessinsider.com/account'
ERROR rules/BusinessInsider.xml: Fetch error: http://www.businessinsider.com/register => https://www.businessinsider.com/register: Too many redirects while fetching 'https://www.businessinsider.com/register'
ERROR rules/BusinessInsider.xml: Fetch error: …
```
=> Fix BusinessInsider.xml video

src/chrome/content/rules/Getbootstrap.com.xml
Fix https://trac.torproject.org/projects/tor/ticket/19396
=> getbootstrap.com

src/chrome/content/rules/Everydayfeminism.com.xml
I wasn't able to run the tests as the depedency installing script doesn't understand Arch Linux or pacman package manager, but this rule seems to work without breaking anything when added to Firefox custom rule directory. I use some other extensions though (PrivacyBadger could affect the tests), but I hope everything is done properly and your tests will raise the issues if there are any before any harm happens.
=> add rule for Everydayfeminism.com

src/chrome/content/rules/Github-Pages.xml
This should fix issue #2507.
I'm also open to a general exclusion on `googletrends.github.io` if whoever reviews this prefers that approach instead.
=> Add exclusion to Github-Pages.xml (issue #2507)

src/chrome/content/rules/Skatteverket.se.xml
The Swedish National Tax Agency website is one of the only two ways to do tax-deceleration (the other way is by post). This website has a national rank of 87 and I find it very surprising that it has not yet been included given the sites nature.
=> Added Swedish Tax Agency [skatteverket.se]

ruleset-style.md
This closes https://github.com/EFForg/https-everywhere/issues/2907.
The commit also includes a few other minor changes, such as syntax coloring and the fix of a typo.
=> Elaborate on securecookie usage in ruleset style

src/chrome/content/rules/Modernpgp.org.xml
Both included target hosts serve bad certificates. This closes https://trac.torproject.org/projects/tor/ticket/20126.
=> [Modernpgp] Disable ruleset

src/chrome/content/rules/444.hu.xml
444.hu has a wildcard certificate. It tries to fetch social media sharing statistics via cimlap.444.hu which uses an old, expired wildcard certificate, which is why I've marked this ruleset as mixedcontent.
=> [444.hu] Create mixedcontent ruleset

src/chrome/content/rules/Demonsaw.com.xml
Updated wiki.demonsaw.com (obsolete) to docs.demonsaw.com (current).
=> Updated link

src/chrome/content/rules/Videa.hu.xml
This should fix a problem introduced by pull request #6860 .
@fuglede @Hainish @J0WI This is breaking Travis, see [here](https://travis-ci.org/EFForg/https-everywhere/jobs/160021213).
=> Remove trailing slashes from Videa.hu.xml rule

src/chrome/content/rules/Sprawl.xml
Fixes https://github.com/EFForg/https-everywhere/issues/6892
=> Disabled ruleset due to expired certificate (thesprawl.org)

test/rules/src/https_everywhere_checker/http_client.py
This fixes the test problem identified in pull request #6871 , where [this code](https://github.com/EFForg/https-everywhere/blob/a37a897b014360893646a8699715bc5e58c011d0/test/rules/src/https_everywhere_checker/http_client.py#L382-L389) apparently (?) never finds the `Location` header, for example:
```
(Pdb) self._headerRe
regex.Regex('(?P<name>\\S+?): (?P<value>.*?)\\r\\n', flags=regex.V0)
(Pdb) headerStr
'HTTP/1.1 301 Moved Permanently\nServer: Apache\nDate: Tue Jun  1 12:48:03 PDT 1999 PDT\nReferer: http://itunes.com/\nLocation: http://www.apple.com/itunes/?cid=OAS-US-DOMAINS-itunes.com\nContent-type: text/html\nContent-length: 311\n\n'
(Pdb) headers = self._headerRe.findall(headerStr)
(Pdb) headers
[]
(Pdb)
```
Note that if in fact `location` has been incorrectly `False`-y for a while, …
=> Fix how 'Location' is parsed from header text

src/chrome/content/rules/Uservoice.xml
It points to Mailgun, and needs to be excluded just like `email.uservoice.com`.
(The error has also changed from a certificate mismatch to a timeout.)
=> [UserVoice] Exclude email.feedback-poweredby.uservoice.com

src/chrome/content/rules/Archive.org_Way_Back_Machine.xml
https://wayback.archive.org has a valid *.archive.org cert.
https://waybackmachine.org fails by presenting the same cert, hence the
redirection.
=> [Archive.org_Way_Back_Machine] Add 2 synonymous domains

src/chrome/content/rules/Energinet.dk.xml
The existing ruleset caused a redirect loop due to the inclusion on the following script on all content containing pages:
```html
<script type="text/javascript">
{
var url=location.href;
if(url.indexOf("https://") > -1)
{
var newurl=url.replace("https://","http://");
location.href=newurl;
}
}
</script>
```
This fixes that by exclusion of those pages.
Moreover, clicking the "English"/"Danish" link, you'd end up on a page for editing the webpage contents, which is great in itself.
=> [Energinet.dk] Fix various issues

src/chrome/content/rules/BME.hu.xml
vik.wiki is an alias for wiki.sch.bme.hu, which has an SSL certificate.
This change redirects all vik.wiki requests to wiki.sch.bme.hu (vik.wiki itself doesn't support HTTPS due to cert mismatch)
=> BME.hu: redirect vik.wiki alias to wiki.sch.bme.hu

src/chrome/content/rules/Infogr.am.xml
This particular subdomain has caused issues a number of places, and the most recent ones do not suggest an easy fix. This closes https://github.com/EFForg/https-everywhere/issues/6791.
=> [Infogr.am] Disable subdomain e.infogr.am

src/chrome/content/rules/bot.brew.sh.xml
Simple ruleset to force redirection from `bot.brew.sh` to `https://bot.brew.sh`.
=> bot.brew.sh: add ruleset

src/chrome/content/rules/US-government.xml
Preloaded
[Chromium](https://cs.chromium.org/chromium/src/net/http/transport_security_state_static.json?amp&sq=package:chromium&l=1864), [Firefox](https://dxr.mozilla.org/mozilla-aurora/source/security/manager/ssl/nsSTSPreloadList.inc#10630), [Tor](https://gitweb.torproject.org/tor-browser.git/tree/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-45.4.0esr-6.5-1#n11412)
=> Remove uspsoig.gov

src/chrome/content/rules/BitBucket.xml, src/chrome/content/rules/Bitbucket-mismatches.xml, src/chrome/content/rules/Bitbucket.xml
* `status.bitbucket.org`'s certificate is no longer mismatched; remove workaround
* Change the `<ruleset name>` from "BitBucket.org (partial)" to "Bitbucket.org (partial)". I didn't rename the files.
=> [Bitbucket.org] status's certificate is good now; fix name capitalization

src/chrome/content/rules/Woolyss.com.xml
**Note:** HTTPS works on this page (https://tools.woolyss.com/html5-audio-video-tester/) but redirects to a 403 when accessing https://tools.woolyss.com
=> [Woolyss.com] Add ruleset

src/chrome/content/rules/Monterey_Bay_Aquarium.xml
The cert is only valid for www., so exclude the bare host.
=> Enable for www.montereybayaquarium.org

src/chrome/content/rules/OpenBSD.org.xml
* Add `ftp.openbsd.org`.
* `openbsd.org` isn't problematic anymore.
Credit to @massoc.
=> [OpenBSD.org] Add ftp.openbsd.org. openbsd.org isn't problematic anymore.

src/chrome/content/rules/make-trivial-rule
improve make-trivial-rule duplicate heuristic
add comment block for nonfunctional hosts
=> improve make-trivial-rule

src/chrome/content/rules/Twitter.xml
=> Exclude click.e.twitter.com from the ruleset.

src/chrome/content/rules/Proxy.org.xml
Seems to pass ruleset test, and works in Firefox locally.
Partial #3069
=> Remove default_off for Proxy.org rule

src/chrome/content/rules/Strikingly.com.xml
In particular, this fixes https://github.com/EFForg/https-everywhere/issues/6865. Note that, unfortunately, a login is required to reproduce the issues.
=> [Strikingly.com] Add several exclusions to fix login and dashboard

src/chrome/content/rules/ACLU-of-New-Mexico.xml
In the ruleset, it is mentioned that `^aclu-nm.org` doesn't redirect properly. More specifically, `https://aclu-nm.org/` redirects to `https://www.aclu-nm.org`, which works. At the same time, other URLs do not redirect properly. For example, `https://aclu-nm.org/about/` redirects to `https://www.aclu-nm.orgabout` and `https://aclu-nm.org/resources/know-your-rights/` redirects to `https://www.aclu-nm.orgresources/know-your-rights/`. The redirect from `^http://aclu-nm\.org/` to `https://www.aclu-nm.org/` is intended as a workaround for this issue.
=> [ACLU of New Mexico] New ruleset

chromium/background.js, src/chrome/content/code/HTTPS.js
This applies to both main frame resources and subresource loads, though in
practice only image subresources get a chance to be rewritten, due to mixed
content blocking.
Loop detection still works, so pages that redirect back to HTTP will get caught
by that and eventually get the "cancelled by extension" message.
Fixes #2115
=> In HTTP Nowhere mode, attempt HTTPS before block.

src/chrome/content/rules/HUP.hu.xml
Hup.hu turned on https support today. Their certificate only contains hup.hu and www.hup.hu currently.
=> New ruleset HUP.hu

src/chrome/content/rules/NYTimes.xml, utils/downgrade-whitelist.txt
Per NYTimes engineer, this is now causing breakage as they migrate to fully
support HTTPS.
=> Remove NYTimes downgrade rule.

docs/faq.md
* The New York Times recently [added HTTPS support](https://open.blogs.nytimes.com/2017/01/10/https-on-nytimes-com/?_r=0). Replace it with Example.com.
* Short-term certs from LE aren't practical for everyone. Add a (paid) long-term cert provider.
=> faq: replace NYTimes

src/chrome/content/code/HTTPSRules.js
This fixes #4220 and https://bugzilla.mozilla.org/show_bug.cgi?id=1250770 (breakage with buttons on embedded http YouTube videos).
We could also do something fancy like testing `newurl` (the string) to see if it starts with "https" vs. "http", and choosing the default port we pass based on that. However, since we are HTTPS Everywhere, we should be pretty sure that the new URI will be HTTPS, so using 443 as our default port seems like a pretty good bet.
=> Init new URLs with default-port of 443, not 80

src/chrome/content/rules/Norwegian.com.xml
In the last 3 years, the HTTPS version of the site got better.
Also simplify rule, restrict cookies, and add comment of bad subdomains.
=> Unmark norwegian.com as mixedcontent

src/chrome/content/rules/tibia.com.xml, src/chrome/content/rules/www.tibia.com.xml
`http://forum.tibia.com/forum/*` is now available over HTTPS through `https://secure.tibia.com/forum/*`.
=> Force HTTPS for Tibia forums

src/chrome/content/rules/ProtonMail.com.xml, src/chrome/content/rules/ProtoniRockerXow.onion.xml, src/chrome/content/rules/Protonirockerxow.onion.xml
ProtonMail just launched a Tor hidden service that requires HTTPS.
https://protonmail.com/blog/tor-encrypted-email/
https://techcrunch.com/2017/01/19/protonmail-adds-tor-onion-site-to-fight-risk-of-state-censorship/
http://www.theregister.co.uk/2017/01/19/protonmail_launches_tor_hidden_service/
=> [ProtonMail Hidden Service] New ruleset

src/chrome/content/rules/Squarespace.xml
See https://github.com/EFForg/https-everywhere/issues/8251.
I disabled the chrome selenium test since selenium wasn't playing nicely on my fedora dev environment, but I tested the exclusion rule locally by building a crx, in addition to running the unit tests.
=> [#8251] Exclusion rule for sg-links.squarespace.com

src/chrome/content/rules/ACLU-of-Arizona.xml, src/chrome/content/rules/ACLU.xml
Note: There is another site, [Changing MCSO](http://www.changingmcso.org/), that is described as "An ACLU of Arizona site" but which does not support HTTPS. As of now, this site is not mentioned or included in the ruleset.
=> [ACLU of Arizona] New ruleset

src/chrome/content/rules/HUP.hu.xml
The wiki.hup.hu domain got a working https certificate.
=> Update ruleset HUP.hu.xml

src/chrome/content/rules/Racked.com.xml
- Default off (CORS issues). #7381.
- `racked.com` is no longer problematic.
So it's good news and bad news. But mostly bad news.
As i wrote in #7381, it would be possible to add an exclusion instead of turning off the ruleset entirely, but it would make the ruleset entirely useless (at least on some pages).
=> [Racked.com] Default off (CORS issues). racked.com isn't problematic.

src/chrome/content/rules/PersecutionOfAhmadis.org.xml
The mixed content blocking hides a YouTube link at the bottom of https://www.persecutionofahmadis.org, however the site itself redirects HTTP to HTTPS so at least we are not making things worse.
=> Add PersecutionOfAhmadis.org.xml

src/chrome/content/rules/VigLink.xml
Example: `https://redirect.viglink.com/?u=http%3A%2F%2Fhyperboleandahalf.blogspot.com%2F2010%2F12%2Fyear-kenny-loggins-ruined-christmas.html&key=cfdfcf52dffd0a702a61bad27507376d`
=> Additional subdomain in VigLink.xml

src/chrome/content/rules/cubecraft.xml
Remove special case for status.cubecraft.net as its SSL cert is now valid.
Also should be HSTS preloaded in some web browsers by now, and could potentially be removed from HTTPS Everywhere. Up to you guys. - cc @jeremyn
=> status.cubecraft.net fix.

src/chrome/content/rules/Pleasuredome.xml
This ruleset covers the Pleasuredome Tracker and its associated forums.
=> Initial commit of Pleasuredome.xml

src/chrome/content/rules/Wellcome-Trust-Sanger-Institute.xml
The Sanger institute web site is broken in various ways (the most obvious being that all icons are broken and represented by placeholder boxes) when using https everywhere.
=> sets default_off for Sanger Institute

src/chrome/content/rules/Stack-Exchange.xml
This host should not be downgraded to http, since it's a hop
to enable websockets. Close #3884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/efforg/https-everywhere/7518)
=> Excluded qa.sockets.stackexchange.com from Stack Exchange ruleset

src/chrome/content/rules/KrebsOnSecurity.com.xml
MCB issues were resolved some time ago when the site moved  to a different DDoS mitigation provider.
This commit also changes the `<securecookie>` tag to be conformant with the style guide.
=> Remove platform="mixedcontent" for KrebsOnSecurity

src/chrome/content/code/HTTPS.js
Updated `cookieManager` calls to match the updated API.
Tested and fixes #5791 on Mac 10.12 / Firefox ESR (45), current release (49), and dev edition (51).
=> Update nsICookieManager calls (#5791)

src/chrome/content/rules/KProxy.xml
Examples: https://server1.kproxy.com/ https://server2.kproxy.com/ https://server3.kproxy.com/ https://server4.kproxy.com/ https://server5.kproxy.com/ https://server6.kproxy.com/ https://server7.kproxy.com/ https://server8.kproxy.com/ https://server9.kproxy.com/
=> Adding support for sub-domains for KProxy.com

src/chrome/content/rules/Vancity.xml
See discussion at #7580.
There are invalid certificates at `https://vancityinsurance.com/` and `https://myreloadable.ca/`. But we should still redirect from `http://` to `https://www.` because the `www.` subdomains do have valid certs.
cc @J0WI
=> [Vancity] Add new rules due to invalid certs

test/travis.sh
It seems that when master get ahead HEAD before build is started it can't found common commit.
@Hainish
=> Fix for common base commit

src/chrome/content/rules/Enigmail.net.xml
The subdomain `test.enigmail.net` seems to work over https but I am not aware of it being used anywhere yet.
=> [Enigmail.net] Simplify rewrite rule

src/chrome/content/rules/Stack-Exchange.xml
The `meta.*.stackexchange.com` domains have moved to `*.meta.stackexchange.com` to for HTTPS support via a wildcard. This now does the appropriate redirects to the new homes. Child `blog.*.stackexchange.com` sites (actually only gaming) are unchanged and will not move...they continue to downgrade.
Long-term, we can narrow this entire rule set down to the blogs, all other domains are getting HTTPS support and HSTS headers.
This is an urgent issue since users of HTTPS Everywhere are currently getting redirect loops from us rolling out HTTPS support here. It's also my first time modifying these rulesets, if I'm doing something completely incorrectly please let me know and I'll fix it ASAP, or feel free to do so on your end, whatever fixes redirects for our combined user base faster. Thanks! …
=> Urgent: fix redirect loops for meta.*.stackexchange.com

src/chrome/content/rules/Dict.cc.xml, src/chrome/content/rules/xkcd.xml, utils/downgrade-whitelist.txt
After testing, they are no longer needed.
=> Remove downgrades for xkcd and dict.cc.

src/chrome/content/rules/Indapass.hu.xml
Indapass.hu is a single sign on provider of the index.hu page group. They have working SSL, but don't use it by default. (Not even for logins.)
=> Create ruleset Indapass.hu.xml (login provider)

src/chrome/content/rules/crossorigin.me.xml
The subdomain no longer exists, so including it in the file doesn't really make sense. (Source: I maintain [crossorigin.me](https://github.com/technoboy10/crossorigin.me))
=> Remove donate.crossorigin.me mismatch

src/chrome/content/rules/Amnesty.fr.xml
Some subdomains still are not functional over `https` but given that the main subdomain can now be reached over `https`, I think it is reasonable to remove the `(partial)`
=> [Amnesty.fr] Add subdomains

src/chrome/content/rules/Roblox.xml
The subdomains blog.roblox.com and corp.roblox.com support HTTPS, as do a few other subdomains.
=> [Roblox] Add some subdomains

src/chrome/content/rules/Pastebin.com.xml
Pastebin has apparently gone through an update (not sure when...) and:
- https is now enabled by default
- Tor users are not blocked by cloudflare anymore
=> [Pastebin.com] Update ruleset after site update

src/chrome/content/rules/wired.co.uk.xml
I have no idea whether the subdomain `cdni.wired.co.uk` is still used. I couldn't find it in the website source.
=> [Wired.co.uk] Add subdomains

src/chrome/content/rules/Yale_University.xml
**This is not a complete update of the `Yale.edu` ruleset. I simply noticed a subdomain that can and therefore should be secured.**
=> [Yale.edu] Add e360.yale.edu

src/chrome/content/rules/Mailinator.com.xml
I left the wildcard on purpose because I would argue that in this case, it is adequate.
- The website is secured by a wildcard certificate `*.mailinator.com`
- It looks like the website is configured so that any subdomain is a valid mirror of https://www.mailinator.com. For example, I tried https://idk.mailinator.com/ and https://thatsaninterestingbehaviour.mailinator.com/ and they work fine.
=> [Mailinator.com] Update rewrite rules

src/chrome/content/rules/Mastodon.social.xml
Site serves HSTS header with 1 year `max-age` and `includeSubdomains`, but no `preload`.
=> [Mastodon.social] New ruleset

src/chrome/content/rules/Cypherpunks.ca.xml, src/chrome/content/rules/Off-the-Record_Messaging.xml
Although I do not know any working URL for 
- `cypherpunks.ca`
- `www.cypherpunks.ca`
- `lists.cypherpunks.ca`
I left them here because https works fine and they were previously included in the ruleset so I am assuming the previous contributor knew they were working.
=> [Cypherpunks.ca] Update and merge rulesets

src/chrome/content/rules/DaButtonFactory.com.xml
[DaButtonFactory.com](https://DaButtonFactory.com) is an online button maker. It offers a simple REST API for button images generation, where an image is returned in response to an HTTP GET request. (The button settings, such as the text, size, and colors, are included in the requested URL query string.)
This API/hotlinking facility is used on thousands of sites around the web.
The use of HTTPS is recommended, and the site and its API are fully available over HTTPS. 
However, since Da Button Factory uses a shared SSL certificate (provided by Cloudflare), we do not redirect HTTP requests to HTTPS, to not mess with old browsers not supporting SNI.
Since the HTTPS everywhere plugin is only available for browsers supporting SNI, it is OK to add a ruleset here.
=> Add DaButtonFactory.com

src/chrome/content/rules/Goip.de.xml
This site is a dns provider, so all subdomains should not be included.
Even though there are a lot.
=> Add support for goip.de

src/chrome/content/rules/Gametracker.com.xml
A variety of TLS issues on gametracker.com have been fixed, and all endpoints now support https:// .  The old image.www.gametracker.com URL no longer exists.
=> Reenable gametracker.com rules

src/chrome/content/rules/IMDB.xml
Subdomain used to deliver trailers on movies pages.
=> [Media-IMDB] Add target

src/chrome/content/rules/CNN.com.xml, src/chrome/content/rules/CNN.net.xml
=> Update CNN.com related ruleset

src/chrome/content/rules/Wire.com.xml
Changes:
- Prior to this PR, the `<rule>` tags only redirected a few hosts to https, despite the wildcard target. They didn't cover Wire's main web app at `app.wire.com`. The new `<rule>` redirects everything to https.
- Added a target for Wire's Piwik analytics domain, `wire.innocraft.cloud`.
- Added test URLs for all subdomains I could find.
- Wildcard securecookie tag.
- Ruleset is no longer "partial".
=> [Wire.com] Update ruleset

src/chrome/content/rules/Malwarebytes.com.xml
Add rules for Malwarebytes domains.
Another PR to fix [malwarebytes.org legacy rules](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Malwarebytes.xml) will follow.
=> Malwarebytes.com

src/chrome/content/rules/Harvard-University-expired.xml, src/chrome/content/rules/Harvard-University.xml
Remove obsolete comment, enable working `target`. Re-open: #9866 Related: #9842, #9836, #9906 
P.S. This is a huge rule involves complex `regex`... it is so difficult to maintain...
=> Re-activate and Update Harvard.edu related rulesets

src/chrome/content/rules/BioInfo.pl.xml, src/chrome/content/rules/BioInfoBank.com.xml, src/chrome/content/rules/PicoStocks.com.xml
=> Re-activate and Update BioInfoBank.com related rulesets

src/chrome/content/rules/1time.aero.xml
#9906 
Remark: Still none of its sub-domains support HTTPS correctly.
=> Rename and Update 1time.aero.xml (cosmetic)

simplemachines.xml
=> add simplemachines.org

src/chrome/content/rules/Americas_Longest_War.xml
It's probably safer to wait until #9906 is settled before merging. I can update the `default_off` reason to `invalid-certificate` if needed.
=> [AmericasLongestWar.com] Update default_off reason

src/chrome/content/rules/AlterNet.xml
As I wrote in the top comment, this is a difficult case because the website is broken:
- many subdomains have a broken redirect rule server-side. It keeps adding `www.` even when it's already there, which creates an infinite redirect loop.
- it links to https version for subdomains where https is not correctly configured
=> [AlterNet.org] Remove wildcard and update subdomains

src/chrome/content/rules/make-trivial-rule
22,000 files was too many to handle as a glob when checking whether an existing rule matches a new one. This addresses the issue by using `find -exec` instead of a glob.
Manually tested on macOS Sierra. I'm assuming the syntax will likely be the same, but not aware of the cross platform requirements of this project enough to make a call.
=> Fix Argument list too long error

src/chrome/content/rules/Siliconera.com.xml
Create Siliconera.com.xml. The media subdomain contains mixed content blocking, so mixedcontent platform is added. Test url to check the main website image logo loads on HTTPS version.
=> Create rule for siliconera

src/chrome/content/rules/MetaEbene.xml
small passive mixed-content warning because audio-files are loaded from the meta-subdomain that has no valid cert, but that is minor.
=> Add MetaEbene.me 

src/chrome/content/rules/IDownloadBlog.xml
All assets from *media.idownloadblog.com* (CSS, JS, images) are broken with the existing ruleset (#9412).
*idownloadblog.plssl.com* doesn't seem to exist any more, but HTTPS now works on *media.idownloadblog.com*.
=> Fix media.idownloadblog.com rule

src/chrome/content/rules/MSNBC.com.xml
This "fixes" https://github.com/EFForg/https-everywhere/issues/10099 by disabling the ruleset.
=> Disable MSNBC.com.xml

src/chrome/content/rules/Australian-Koala-Foundation.xml
=> [SaveTheKoala.com] Update and reactivate ruleset

src/chrome/content/rules/CNN.com.xml
Despite `markets.money` works perfectly on `platform="mixedcontent"`, I would like to avoid writing a `mixedcontent` rule because of https://github.com/EFForg/https-everywhere/issues/9971#issuecomment-304081854, which mentioned that 
> The platform="mixedcontent" attribute was always intended as a short-term solution, see https://bugzilla.mozilla.org/show_bug.cgi?id=878890#c20.
=> Update CNN.com.xml, Fix #9964

src/chrome/content/code/HTTPS.js, utils/relaxng.xml, utils/simple.py, utils/single_rule_response.py, utils/trivial-validate.py
Downgrades to HTTP are detected and rejected in trivial-validate.py. We
used to have a handful of exemptions, but the list of exemptions has
become empty, so we are removing this function forever.
Relates to #1327.
/cc @ivysrono @semenko @Hainish
=> Remove support for downgrade rules.

src/chrome/content/rules/LMU-Muenchen.xml
Attempt at fixing #10161.
I purposely did not add any new subdomain but simply kept the previous coverage after fixing the securecookie.
=> [Uni-Muenchen.de] Remove wildcard (fix #10161)

src/chrome/content/rules/Gitorious.xml, src/chrome/content/rules/WordPress-blogs.xml
Gitorious.org shut down. All other subdomains are gone from DNS.
=> [Gitorious.org] Update ruleset

src/chrome/content/rules/WordPress-blogs.xml, src/chrome/content/rules/Zamzar.com.xml
It looks like all pages are actually redirecting to http on (www\.)zamzar.com. Fix #4147.
=> [Zamzar.com] Move blog.zamzar.com from WordPress-blogs.xml to Zamzar.com.xml (fix #4147)

src/chrome/content/rules/Tocco.ch.xml
The content has been generated directly from the DNS zone file
using #7706. Host names used for non-HTTP purposes, proxying, etc.
I left out intentionally.
=> update rules for tocco.ch

src/chrome/content/rules/Ruby-doc.org.xml, src/chrome/content/rules/Ruby-lang.org.xml
~~Also renamed `Ruby-lang.org.xml` → `Ruby-lang.xml`.~~
~~I hope it’s OK to include both domains in the same file, even though their WHOIS records show different contacts.~~
Update: see [my comment below](https://github.com/EFForg/https-everywhere/pull/10386#issuecomment-309361754), ruby-doc.org got its own rules file, rules for ruby-lang.org got updated.
=> Add rules for ruby-doc.org, update rules for ruby-lang.org

makecrx.sh
An attempt to handle a couple of issues with this script when using macOS, stumbled across in https://github.com/EFForg/https-everywhere/pull/10072#issuecomment-305370157.
It's written in such a way that it shouldn't mess with anything on the Linux side of development but I will spin up a VM a little later today to triple check that.
Locally after this change:
```
~> PYTHONPATH="/private/tmp/https-venv/lib/python2.7/site-packages" makecrx.sh
Building chrome version 2017.6.5
Generating ruleset DB
Validation of included rulesets completed.
Validation of rulesets against relaxng.xml succeeded.
Creating ruleset library...
Removing whitespaces and comments...
chrome/content/rules/default.rulesets passed XML validity test.
Unsigned package has sha1sum: 2386676cfd3157dcb3592697748439866238e909 …
```
=> makecrx.sh: improve support for macOS

src/chrome/content/rules/Phaser.io.xml
After manually forcing my browser to treat Phaser.io as a HSTS preloaded site, and testing all the previously affected URLs, and just wandering around the site generally, all the issues seem to be resolved. Closes #6907 (an old ticket that presumably caused the exceptions to be created, but hasn't been closed).
=> Remove old exceptions from Phaser.io.xml.

src/chrome/content/rules/Pro-Linux.de.xml
The mixed-content is just a bad google inclusion. The website doesn't break.
Therefore we should remove this platform and enable the rule by default
=> Pro-Linux.de

src/chrome/content/rules/Lemde.fr.xml
I have been thinking about it and it doesn't make sense to mark this ruleset as mixedcontent. It's related to `Le_Monde.fr.xml` which triggers MCB but this ruleset itself shouldn't.
=> [Lemde.fr] Add test urls and remove platform

src/chrome/content/rules/Yahoo_Japan.xml
This is ready for review now. thanks.
=>  	Re-activate and Update Yahoo_Japan.xml 

src/chrome/content/rules/ICIJ.xml
`4r7hcmz0uv8fsq5a6zp9cozerpu80vf.icij.org` is dead.
=> [ICIJ] Cleanup and reactivate.

src/chrome/content/rules/Irccloud.com.xml
=> [Irccloud.com] Cleanup and reactivate.

src/chrome/content/rules/Sofort.com.xml
`documents.sofort.com` is dead.
=> [Sofort.com] Remove dead target and reactivate.

src/chrome/content/rules/CANNEX.xml, src/chrome/content/rules/CCEDK.com.xml, src/chrome/content/rules/CHIP-Digital.de.xml, src/chrome/content/rules/CIO.com.au.xml, src/chrome/content/rules/C_F_Mueller.de.xml, src/chrome/content/rules/California-Department-of-Motor-Vehicles.xml, src/chrome/content/rules/Canadian-Lung-Assoc.xml, src/chrome/content/rules/Cbb.dk.xml, src/chrome/content/rules/Celiac-Foundation.xml, src/chrome/content/rules/Champions_of_Regnum.com.xml, src/chrome/content/rules/ChangeIP.com.xml, src/chrome/content/rules/Changemakers.xml, src/chrome/content/rules/Chase_Paymentech.com.xml, src/chrome/content/rules/ClouDNS.net.xml, src/chrome/content/rules/Colorado-No-Call-List.xml, src/chrome/content/rules/ConSecur.xml, src/chrome/content/rules/CoolCart.Net.xml, src/chrome/content/rules/Corbin_Fisher.xml, src/chrome/content/rules/Cricket_Wireless.com.xml, src/chrome/content/rules/Cts-strasbourg.eu.xml, src/chrome/content/rules/CuidadoDeSalud.gov.xml
No ruleset needed to be excluded.
=> Trivialize snapping redirects (^C, experimental)

src/chrome/content/rules/1177.se.xml, src/chrome/content/rules/17track.net.xml, src/chrome/content/rules/39dollarglasses.com.xml, src/chrome/content/rules/500ish.com.xml, src/chrome/content/rules/511tactical.com.xml
=> Trivializing Snapping Rewrite (^0 -> ^9)

src/chrome/content/rules/Lemde.fr.xml
Related: https://github.com/EFForg/https-everywhere/pull/10876 and https://github.com/EFForg/https-everywhere/issues/10962.
Another option would have been to remove the broken subdomain `s1.lemde.fr` but we would need to remove `s2.lemde.fr` as well because it looks like they are used as mirrors.
Also, because lemonde.fr has broken protocol-relative URL in many places in its source code, I would rather not take any chances.
=> [Lemde.fr] Default_off ruleset (fix #10962)

src/chrome/content/rules/Parkrun.com.xml
parkrun.org.uk is fetching one tiny image from parkrun.com which is causing mixed-content warnings, so this commit fixes that.
parkrun.com has a valid certificate for parkrun.com and *.parkrun.com.
=> Add ruleset for parkrun.com and subdomains

src/chrome/content/rules/Stallman.org.xml
#10843 
Content now differs between `ww.stallman.org` and `www.stallman.org`:
```sh
curl -s -L https://www.stallman.org/ | sha256sum
76d0ccca480bdc1e37482d3c2da299b98776228e17599219f2d4f39ef436f6f2
```
```sh
curl -s -L -k https://ww.stallman.org/ | sha256sum 
69c7a2ea3ed62a710b54ffb574168411cb948e0cb38fb3609dddecd1b28b41c6
```
=> [Stallman.org] Simplify ruleset

src/chrome/content/rules/Minijob-zentrale.de.xml
#10843
I could not find any valid reason for the `https` -> `https` rewrite.
=> [Minijob-zentrale.de] Simplify rewrite rule

src/chrome/content/rules/Mutterschaftsgeld.de.xml
#10843 
I could not find any reason for the `https` -> `https` rewrite.
=> [Mutterschaftsgeld.de] Remove https rewrite and update default_off

src/chrome/content/rules/US_Geological_Survey.xml
Related: #10965 however, it turns out only 1 such ruleset passing Travis.
Following ruleset failed Travis build (4):
- Bigmir.net-falsemixed.xml
- Element14.com-Mixed.xml
- Tinypass.com-falsemixed.xml
- Vungle.com-falsemixed.xml
=>  Trivialize capturing direct rewrite rules (linked, platform)

src/chrome/content/rules/World_of_Warships.xml
Note: I don't have an account and may have not able been to test all functionalities on this website.
I couldn't reproduce https://github.com/EFForg/https-everywhere/issues/5650 and `forum.wordofwarships.*` now redirects to `https` on its own so I am guessing it has been fixed.
Related: #11203
=> [WordOfWarships] Remove right-wildcard and add targets

src/chrome/content/rules/Ruhr-Uni-Bochum.de.xml
The system uses the `fn2.flexnow.ruhr-uni-bochum.de` domain after logging in.
=> Add additional Flexnow rule for ruhr-uni-bochum.de

src/chrome/content/rules/Maker.tv.xml
#9906 It seems that this is created with `default_off`, but `^` redirect to another domain and `www` seem to be obsolete (URLs on google all `4xx` even on HTTP) so I guess it is fine to re-activate/ remove this.
=> Re-activate and Update Maker.tv.xml

src/chrome/content/rules/Fr33tux.org.xml
Delete `Fr33tux.org.xml` since it is currently preloaded, for completion of #9582. See https://hstspreload.org/?domain=fr33tux.org Related: #10056
=>  	Update Fr33tux.org.xml 

src/chrome/content/rules/Nokia.xml
#11203 Only `*nokia.com` works over HTTPS.
```
account.nokia.com
advertising.nokia.com
analytics.developer.nokia.com
projects.developer.nokia.com
sso.developer.nokia.com
discussions.europe.nokia.com
i.nokia.com
map.nokia.com
www.map.nokia.com
api.maps.nokia.com
maps.nlp.nokia.com
0.maps.nlp.nokia.com
1.maps.nlp.nokia.com
2.maps.nlp.nokia.com
3.maps.nlp.nokia.com
4.maps.nlp.nokia.com
5.maps.nlp.nokia.com
6.maps.nlp.nokia.com
7.maps.nlp.nokia.com
8.maps.nlp.nokia.com
9.maps.nlp.nokia.com
primeplace.nokia.com
qt.nokia.com
blog.qt.nokia.com
developer.qt.nokia.com
doc.qt.nokia.com
labs.qt.nokia.com
```
See https://gist.github.com/cschanaj/9ad8c01eaecc5f575150aad949d26f0f
=> Re-activate and Update Nokia.xml

src/chrome/content/rules/DreamHost.xml
Under the `objects.dreamhost.com` domain, there are a number of subdomains. A few relevant URLs are listed below. Accessing these subdomains via HTTPS gives a certificate expired error. I am not aware of any subdomains under `objects.dreamhost.com` that support HTTPS at this time.
- http://netbadi.objects.dreamhost.com/%5BNetBadi.in%5D_EAMCET_2013_AM.pdf
- http://logstash.objects.dreamhost.com/presentations/logstash-puppetconf-2013/index.html
- http://remipresentations.objects.dreamhost.com/2012_Miscellaneous_Topics/Small_Business_Jobs_and_Tax_Relief_Act.pdf
- http://offer.objects.dreamhost.com/best-quality-aldo-ladson-lowest-price.html
- http://clarion.objects.dreamhost.com/documents/HRButlerNewHireForm.pdf
- http://www1.objects.dreamhost.com/nike-ohio-state-buckeyes-12in-laptop-backpack. …
=> [DreamHost] Enable ruleset, expanded/adjusted coverage, adjusted comments & test URL

src/chrome/content/rules/Parkrun.org.uk.xml
`images.parkrun.org.uk` has no DNS, so remove it completely.
=> [Parkrun.org.uk] Fix and re-enable

src/chrome/content/rules/Simply-Hired-clients.xml
- jobs.businessinsider.com gone from DNS
- nodejs.org: different content
=> [Simply-Hired-clients.xml] Remove broken targets

src/chrome/content/rules/tgstation13.org.xml
So, about the only question that I have is how this might apply to different ports. we have a webapp that communicates over ajax to :1337, but the end point for that is http only for legacy reasons, Would I need to exempt that, or would this by default not apply to that case.
(This is actually the reason we don't use htst or htst preload)
=> Add tgstation13.org rule

src/chrome/content/rules/basekit.com.xml
I'm not entirely sure what to do here. I usually wouldn't use https-everywhere to fix broken websites but it was already here so...
=> [BaseKit.com] Remove broken targets

src/chrome/content/rules/amazon.de.xml
smile.amazon.de is a domain for contributing for charity. It supports HTTPs.
=> Add smile.amazon.de

src/chrome/content/rules/Twimg.com.xml
Because the rewrite to `*.cloudfront.net` is somewhat dangerous, I am not comfortable with leaving it without a test url.
=> [Twimg.com] Add test urls

src/chrome/content/rules/Kettering.gov.uk.xml
https://github.com/EFForg/https-everywhere/issues/10843
I couldn't find protocol relative links on `secure.kettering.gov.uk`
=> [Kettering.gov.uk] Remove https->https rule

src/chrome/content/rules/AOL.xml
With this pull request, a number of problematical targets (and rules specifically related to those targets) have been removed from the ruleset. However, it is not clear as to how, and whether, these targets should be documented in the ruleset's comments about nonfunctional domains and problematic hosts. In particular, the difference between "nonfunctional" and "problematic" is not totally clear. In addition, if a domain does not work for both HTTP and HTTPS, should it be listed in the ruleset comments at all? (Or, are the ruleset comments about nonfunctional and problematic domains specifically intended for domains that work with HTTP but which have issues only with HTTPS?)
The behavior of the removed targets is as follows:
* `autos.aol.com` - http://autos.aol.com/ generates a redirect to …
=> [AOL] Enable ruleset, remove nonfunctional domains, slightly expand coverage

src/chrome/content/rules/Avadirect.com.xml, src/chrome/content/rules/Lester_Chan.net.xml, src/chrome/content/rules/Soundcloud.xml
All targets are already secured in `Netdna-ssl.com.xml`
=> Remove netdna-ssl.com targets duplicated across rulesets

src/chrome/content/rules/SWISS-Virtual.com.xml, src/chrome/content/rules/Swiss.xml
SWISS Virtual is **NOT** affiliated to Swiss International Air Lines Ltd.
Please refer to the disclaimer at the bottom of https://www.swiss-virtual.com/en/
P.S. I know that `Swiss.xml` is still `default_off`, but it should be works of a separate PR.
=> Split SWISS-Virtual.com from Swiss.xml

src/chrome/content/rules/CNBC.com.xml
`http://cnbc.com`  now redirect (301) to `http://www.cnbc.com` which work over HTTPS correctly.
=> Remove unnecessary exclusion from CNBC.com.xml

src/chrome/content/rules/Connect.me.xml
The previous ruleset was pointing to another domain that was
generating a 404. It now simply replaces http with https. Also,
it now only handles www.connect.me.
=> Update connect.me.xml ruleset

src/chrome/content/rules/Red_Bull.xml
#11203 It seems that only `*redbull.com` support HTTPS properly and other ccTLD simply redirect to `redbull.com`, see [`Red_Bull.xml (old)`](https://gist.github.com/cschanaj/0ac81bf991af720efec4959f59c836f4). 
P.S. All domains are extracted from the existing rule manually, so I might have missed some of them.
List of domains covered in the existing rulesets
```
redbull.com
api.redbull.com
athletewidget.redbull.com
balconyshot-game.redbull.com
cache-workbench.redbull.com
confluence.redbull.com
connect.redbull.com
create.redbull.com
creativearchive.redbull.com
creativearchive-staging.redbull.com
creativearchive-test.redbull.com
editorial.redbull.com
energydrink.redbull.com
energydrink-at.redbull.com
energydrink-de.redbull.com
energydrink-fr.redbull.com
energydrink-it.redbull.com …
```
=> Re-activate and Update Red_Bull.xml

src/chrome/content/rules/Indymedia.xml
- Remove broken hosts which caused the ruleset to be disabled
- Keep some of the hosts which are working once again.
=> Restore indymedia ruleset, with broken hosts removed

src/chrome/content/rules/MyUS.com.xml
this domain serves HSTS now, removed unnecessary complicated rules.  In particular, `http://myus.com` redirect (301) to `https://www.myus.com`, so all user will be exposed to the HSTS headers. No subdomains enumeration is performed.
```bash
$ curl -I https://www.myus.com
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
X-AspNetMvc-Version: 4.0
Content-Length: 25218
X-Frame-Option: DENY
Cache-Control: private, max-age=38277
Expires: Thu, 03 Aug 2017 01:00:20 GMT
Date: Wed, 02 Aug 2017 14:22:23 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
```
=> Simplify MyUS.com.xml

test/rules/coverage.checker.config, test/rules/requirements.txt, test/rules/src/https_everywhere_checker/check_rules.py, test/rules/src/https_everywhere_checker/rules.py
~Blocked by [`Xxxbunker.com.xml#L44`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Xxxbunker.com.xml#L44)~. See also #11185 Fix #10877. 
Hopefully before #11240 since we have a huge number of PR these days.
P.S. It is assumed that `target` matched the regex in  [`relaxng.xml#L36`](https://github.com/EFForg/https-everywhere/blob/master/utils/relaxng.xml#L36)
=> Update https_everywhere_checker/check_rules.py, Fix #10877

src/chrome/content/rules/Color-Of-Change.xml
The Color Of Change ruleset previously contained a number of subdomains (`orig`, `secure`, `stories`, and `vote`) that no longer appear to be functional. When I last checked, these subdomains gave errors related to Cloudflare when accessed.
http://orig.colorofchange.org/ref/hud_2.html
http://secure.colorofchange.org/
http://stories.colorofchange.org/
http://vote.colorofchange.org/
In addition, this pull request may be relevant with regard to issue #11114.
=> [Color Of Change] Enable ruleset, remove unsupported subdomains

src/chrome/content/rules/F-Droid.xml
Domain preloaded: https://hstspreload.org/?domain=f-droid.org
It should be removed in the next `HSTS-prune` iteration.
=> [F-droid.org] Add targets

src/chrome/content/rules/Ruhr-Uni-Bochum.de.xml
The entire ruleset was disabled due to the broken www.rz.ruhr-uni-bochum.de in 9bf49cbeb4696cdea76df23f685da1d11031f693
=> re-enable Ruhr-Uni-Bochum.de / remove www.rz.ruhr-uni-bochum.de

chromium/background.js, chromium/rules.js, utils/merge-rulesets.py
ping @Hainish 
~P.S. please do not feel obligated to merge before the next release.~
=> Use JSON for default.rulesets instead of XML

src/chrome/content/rules/01.org.xml
=> [01.org] Update ruleset.

chromium/background.js
1. From chrome://extensions, open the "Inspect views" for HTTPS Everywhere in a new session.
2. In the console, type `redirectCounter`. the console should output something like
```
Object {} // Empty Object
```
3. Visit https://www.nytimes.com/
4. Repeat Step 2, observe 
```
Object {440: 1, 444, 1}
```
5. Repeat Step 3-4, observe `redirectCounter` keep growing without sign of removing previous items
```
Object {440: 1, 444: 1, 598: 1, 601: 1, 632: 1, 635: 1}
```
This affect long lasting browsing sessions. 
**UPDATE** On Mixed Content pages, HTTP request are blocked by MCB from the browser. It is necessary to listen on both HTTP & HTTPS connection to resolve the memory leak (Assuming no "Block all unencrypted requests"). thanks.
P.S. I expected browser to handle redirect loops …
=> Use Map instead of Object for redirectCounter and Fix Memory Leak

test/chromium.sh
Instead of checking for a distro to determine if we want `chromium-browser` or `chromium` we just check if `which chromium-browser` works, if not we use `chromium`.
=> Make chromium.sh work for non-debian distros

src/chrome/content/rules/GoogleServices_Complex.xml
- preloaded
- broken rule (there is no target for it)
=> Remove preloaded domain goo.gl

src/chrome/content/rules/GoogleAPIs.xml, src/chrome/content/rules/YouTube.xml
Already covered by the wildcard in [YouTube.xml](https://github.com/EFForg/https-everywhere/blob/release/src/chrome/content/rules/YouTube.xml).
=> Remove duplicated target gdata.youtube.com

src/chrome/content/rules/Google.com_Subdomains.xml, src/chrome/content/rules/GoogleVideos.xml
It looks like many rules in `GoogleVideos.xml` are outdated because of the [end of Google Videos](https://en.wikipedia.org/wiki/Google_Video).
=> Move videos.google.com to Google.com_Subdomains.xml

src/chrome/content/rules/Google.com_Subdomains.xml
This ruleset doesn't handle ccTLDs so the securecookie regex is unnecessarily complex.
=> [Google.com_Subdomains] Fix securecookie regex

chromium/background.js, chromium/incognito.js, chromium/manifest.json, chromium/rules.js, chromium/util.js
Fixes some issues from #12586 with some work from #12556 by @RReverser 
Lets rules.js use `enableMixedRulesets` and `domainBlacklist` by moving them into rules.js from background.js.
Stubs out `util.*` so they work normally in the browser again, this was broken in #12556.
=> re-work #12556

src/chrome/content/rules/JanDan.net.xml
Still `default_off` but is up-to-date and ready to enable as soon as the certificate chains issues are resolved.
=> [JanDan.net] Update ruleset.

src/chrome/content/rules/LinuxTag.org.xml
=> Update LinuxTag.org.xml (cacert)

src/chrome/content/rules/WebAssign.xml
After logging in, the redirection from www.webassign.net to webassign.net breaks the site. Leaving the www in place fixes this.
=> Unbreak WebAssign

src/chrome/content/rules/BiblioCommons.com.xml
BiblioCommons runs the online catalogs for over a hundred public [libraries](https://www.bibliocommons.com/about/libraries/united-states) throughout the US, Canada, Australia and New Zealand.
The catalog subdomains all serve the HSTS header with `max-age=0`.
=> [BiblioCommons.com] New ruleset

src/chrome/content/rules/Ask.fm.xml
Note: Now it does have an HSTS header set to 15768000 but it isn't preloaded thus it's safe to re-activate the ruleset.
=> Re-activating Ask.fm.xml

chromium/.eslintrc.json, chromium/background.js, chromium/bootstrap.js, chromium/incognito.js, chromium/manifest.json, chromium/rules.js, chromium/store.js, chromium/util.js
NB: This is blocked until #12859 is merged, since that removes the `background` dependency in `store.js`.
This PR adds a "`require`" function. This is nice because:
* We have no more mystery globals floating around.
* We can import files like `rules.js` using node, this lets us unittest them our code without  a browser.
=> Add a require function

.gitignore, .travis.yml, README.md, chromium/package.json, chromium/rules.js, chromium/test/.eslintrc, chromium/test/rules_test.js, chromium/test/testing_utils.js, run_travis.sh, setup_travis.sh
NB: this depends on #12938 
This lays out the basics for adding unittests for code in `chromium/`.
To run them, cd into the `chromium/`. Run `npm install`. Then run `npm test`.
Todo: put tests in a better place. Hook in to travis.
=> Add unit tests

chromium/background.js, chromium/incognito.js, chromium/manifest.json, chromium/test/incognito_test.js
This  makes background.js depend on incognito.js, instead of incognito.js depending on background.js. This lets us test incognito.js, and it makes more sense for background.js to orchestrate imports.
This also adds unit tests that cover incognito.js 100%.
=> Add 100% unit test coverage for incognito.js

chromium/background.js
46bc17f fixes the icon text so it now say `HTTPS Everywhere`, `HTTPS Everywhere (blocking)`, or `HTTPS Everywhere (disabled)`. 
720fd78 ensures we only set the badge background color on the correct tab, this isn't really a bug since we only use one color anyway.
869b31f fixes the an error on start up
=> Fixes for small bugs and annoyances

chromium/background.js, chromium/rules.js, chromium/test/rules_test.js, rewriter/rewriter.js
cc @RReverser 
I looked at `rewriter.js`. It was broken :( It happened when the packaged rulesets switched from xml to json in #12273.
I updated `rewriter.js` and did a quick test on a file that just contained `<a href="http://freerangekitten.com/">foo</a>` and it rewrote it as expected.
I also added tests for the API's that rewriter js uses: `addFromJson` (previously `addFromXml`) and `rewriteURI`.
=> Fix rewriter.js and test the API it uses.

utils/issue-format-bot/lib/issueedit.js, utils/issue-format-bot/test/issueedit-handler-test.js, utils/issue-format-bot/test/mocks/context.js
Note: this does the *bare minimum* to make tests pass. This change has no real test coverage, but this bug is causing real pain and I _did_ test it manually in production so it'll have to do for now. At some point I'll send a followup PR adding the missing coverage.
Fixes #12855
=> Fix the bot commenting on edits more than once

chromium/background.js, chromium/debugging-rulesets.css, chromium/debugging-rulesets.html, chromium/debugging-rulesets.js, chromium/options.js, chromium/rules.js
Depends on https://github.com/EFForg/https-everywhere/pull/12859
Adds a special page where ruleset testers can enter debugging rulesets into a textarea.
When multiple rulesets are added, these have to all be wrapped `<root>` and `</root>` opening and closing tag in order to be valid XML.
To access this page, navigate to the extension options UI, then click "General Settings" and type `Ctrl-Z`.  This should open a new tab to enter debugging rules into.
When you click `Save`, these rulesets should immediately take effect.
The UX is pretty rough, but since this is only to be used by testers I figure that's alright.  The reason this page is so hidden away is that I'd rather have users enter custom rulesets in the standard way, through the popup.
=> Debugging rulesets

chromium/rules.js, chromium/test/rules_test.js
@cowlicks @Hainish currently, `potentiallyApplicableRulesets("")` returns `nullIterable`. I guess we can safely introduce this requirement.
=> Update potentiallyApplicableRulesets and add unittest

docs/en_US/development.md
Now that OFTC supports a webchat interface, it would be nice to mention it in the help documentation when pointing people to the IRC channel.
=> Suggest webchat link for IRC

src/chrome/content/rules/CAE.edu.au.xml
I get a strange error (`need more than 1 value to unpack`) on two of the hosts in this PR, but they are both internal use things that we probably don't need to mess with anyway.
=> [CAE.edu.au] Add ruleset.

chromium/background.js
this simply normalize the URL before further processing.
=> Update chromium/background.js , Fix #13568

.build_exclusions
`.eslintignore` is added to the packaged extension (see [here](https://github.com/EFForg/https-everywhere/pull/13693/files#diff-ac9aed2a391263bbc3c8236f8e674155R3)). It was added to `build_exclusions` in #13560 but it looks like the path was wrong.
@Hainish @jeremyn
=> Fix path to .eslintignore in build exclusions

src/chrome/content/rules/NetCologne.xml
- check subdomains and re-enable the ruleset
Webtv is called nettv now so we can enable the ruleset again
=> NetCologne:

CONTRIBUTING.md
=> CONTRIBUTING.md - Use double quotes (`"`, not `'`)

src/chrome/content/rules/CarterCenter.org-mismatches.xml
`blog` is no longer mismatched, but instead redirects to HTTP. This is noted in [CarterCenter.org.xml](https://github.com/EFForg/https-everywhere/blob/7e4193f45aeb4633e79cdfa56abe1178bf746b39/src/chrome/content/rules/CarterCenter.org.xml#L4) already.
=> [CarterCenter.org-mismatches] Delete ruleset.

test/rules/setup.py, test/rules/src/https_everywhere_checker/check_rules.py, test/rules/src/https_everywhere_checker/http_client.py, test/selenium/test_options.py, utils/check_certs.py, utils/create_xpi.py, utils/merge-rulesets.py, utils/single_rule_response.py, utils/test-generator.py, utils/trivial-response.py
Found by using pyflakes (https://launchpad.net/pyflakes)
Run `pyflakes .` in project root
@Hainish 
The new [Github security alerts](https://github.com/blog/2470-introducing-security-alerts-on-github) may be really useful to ensure optimal security while using external dependencies but we need to make sure that the list is up-to-date.
(Note that Github can't track python libraries yet but they make it sound like it's in the works.)
=> Remove unused python libraries

src/chrome/content/rules/VirtusOnline.org.xml
These guys have had working HTTPS for a long time but for some reason don't redirect their visitors to use it.
=> Add rules for VirtusOnline.org

src/chrome/content/rules/Pops.co.xml
If I understood well, the site has no HSTS so it makes sense to make a ruleset for it despite the HTTP to HTTPS redirect
=> Added ruleset for pops.co

src/chrome/content/rules/Magictail.net.xml, src/chrome/content/rules/Magictail.xml
Probably low priority but it's better if it exists ;)
Page has very good HTTPS support (green lock so no 3rd party content is loaded via HTTP).
=> add rule for Magictail

src/chrome/content/rules/headline24.de.xml
@J0WI 
A new PR
I renamed the ruleset to there  company name "Headline24 GmbH", because headline24.de is only the domain for the company with no content / valid certificate.
=> Add mannheim24.de, heidelberg24.de, ludwigshafen24.de

src/chrome/content/rules/Wyndham.xml
Both `^` and `www` timeout over HTTP and HTTPS.
=> Remove mijnlandal.nl from Wyndham.xml

test/travis.sh, utils/remove-obsolete-references.sh
Failing Travis is expected, blocked by #13657. This will help to keep the ruleset references up-to-date when we have some bulk ruleset updates, e.g. when running `hsts-prune` etc. The effort required by contributors should be minimal in each PR as they are only responsible for ruleset they have changed.
ping @Hainish @cowlicks @J0WI @jeremyn for opinions and reviews. Thanks!!
EDIT: ~It seem that when the script is ran in debug mode, the output doesn't fit Travis console....~
Where to `chmod +x` ???
=>  Add Travis test for obsolete ruleset references 

src/chrome/content/rules/Wyndham.xml
`^` and `www` refused over HTTPS and `301` redirect to https://www.jamesvillas.co.uk/?individual-villas. I assume that this domain is no longer in use.
=> Remove individual-villas.co.uk from Wyndham.xml

src/chrome/content/rules/OSNews.com.xml, src/chrome/content/rules/osnews.com.xml
This pull request replaces https://github.com/EFForg/https-everywhere/pull/12162 .
About `platform="mixedcontent"`: as @da2x reported in https://github.com/EFForg/https-everywhere/pull/12162#issue-253379415 :
> Preview button doesn’t work, so can’t progress to submission. Form works when loaded over HTTP.
It looks like some pages try and fail to load http://www.osnews.com/js/corejs.20091020.js , which seems responsible for both previewing submissions and other site behavior too. So it is safest to just mark the entire ruleset with `mixedcontent`.
=> Update and rename osnews.com.xml to OSNews.com.xml

src/chrome/content/rules/NYTimes.xml, src/chrome/content/rules/nyttips4bmquxfzw.onion.xml
Updated the .xml files to indicate that The New York Times has a new SecureDrop URL. This can be verified on [https://nytimes.com/tips](https://nytimes.com/tips). The old URL is serving a static page over HTTP.
=> The New York Times has a new SecureDrop URL

src/chrome/content/rules/Ubuntu.xml
=> [Ubuntu.com] Exclude keyserver.ubuntu.com:11371 (fix #14185)

src/chrome/content/rules/ORF.at.xml
Work in Progress,
some "subfolders" of the websites that relink to plain can be secured.
Needs a few more exceptions therefore
=> add rule for ORF.at

src/chrome/content/rules/DuckDuckGo.xml
Many certificates have been fixed. Also Include `favicons.` and `icons.` with the correct exclusion rule and tests.
`va-l1.duckduckgo.com` doesn't seem to exist anymore.
=> [DuckDuckGo] Update targets

src/chrome/content/rules/Hollywood-Reporter.xml
There's been some trouble with this rule previously (most recently with a redirect to HTTP documented in #10663) but it looks like things are working a little better now.
=> [Hollywood-Reporter] reactived rule for bare and www domains

src/chrome/content/rules/AerisWeather.com.xml
wildcard `securecookie` can be applied since non-functional subdomains either redirect to functional's (e.g. `hosted`→`wx`) or unnecessary to the function of the website (e.g. `status`).
=> [AerisWeather.com] New ruleset

.travis.yml
When https://github.com/EFForg/https-everywhere/pull/14364/files is rebased on top of this, it should fix the ipv6 issues.  This is a temporary measure - after extensive testing with solutions listed and linked from [here](https://github.com/travis-ci/travis-ci/issues/8891), I wasn't able to resolve the ipv6 issue with the latest trusty build.
=> Add deprecated image to .travis.yml

.editorconfig
Many contributors will have this set as their default text editor config but it isn't the case on GitHub. Because GitHub natively works with editorconfig, trailing whitespaces will be trimmed even with the online editor.
=> Automatically remove trailing whitespaces

CONTRIBUTING.md
This adds a "Contributing Documentation" section to `CONTRIBUTING.md` as discussed in PR https://github.com/EFForg/https-everywhere/issues/14467.
Ping @Hainish .
=> Add documentation section to CONTRIBUTING.md

test/run_travis.sh
#14586 should not pass the fetch-test. IMHO, we should assume all tests are running from `${toplevel}` and use relative path everywhere.
cc @Hainish @jeremyn @J0WI `preload` and `fetch-test` is not running.
=> Update test/run_travis.sh, Fix Travis fetch-test

docs/README.md, docs/en_US/development.md, docs/en_US/faq.md, docs/en_US/rulesets.md, docs/es/faq.md
per tradition. More importantly, this gives improved accessibility for
contributors with small screens or large fonts.
It also improves consistency of appearance for contributors, because
while all(?) text editors will show hard line breaks in the same places
as each other, there is no telling where contributor X's text editor
might place a soft break when automatically wrapping a long line.
If anyone reading this is concerned that hard line breaks will decrease
the comprehensibility of "diffs", they are advised to try out the
`--word-diff` option to `git diff`.
=> Bring docs into line with Markdown style guide

chromium/background.js
cc @Hainish @gloomy-ghost It would be really great to see this in the next release.
TEST CASES
1. CSP Exists, Contains `upgrade-insecure-requests` directive
- https://www.w3.org/TR/upgrade-insecure-requests/
2. CSP Exists, Not Contains `upgrade-insecure-requests` directive
- https://www.theguardian.com/international
3. CSP Not Exists, With mixed content
- https://www.gsu.edu/about/
4. CSP Not Exists, Without mixed content
- https://www.mozilla.org/
Follow up: Should we modify the CORS headers as well??
Close #8506 Close cschanaj/https-everywhere/pull/13
=> Add upgrade-insecure-requests to responseHeaders in HTTP Nowhere Mode

utils/issue-format-bot/lib/issueedit.js
Apparently this snuck in when I PR'd this hotfix?
It was for debugging originally.
/cc @Hainish, this is making the bot not handle failures right
=> [Hotfix] Fix bot edit ignore date

test/rules/src/https_everywhere_checker/http_client.py
Travis failed to follow a non-trivial rewrite because the redirect location lack a trailing `/`. A testing PR is available at #14599. Close #14365. Close #14599 
P.S. This bug should not affect the extension itself.
cc @Hainish @jeremyn
=> Update https_everywhere_checker/http_client.py, Fix #14365

src/chrome/content/rules/JS.org.xml
Honestly, I don't really like this ruleset given the overwhelming amount of `exclusion` which cannot be tested automatically...
=> Remove duplicated test urls from JS.org.xml

src/chrome/content/rules/PCGamer.com.xml
this remove the `mixedcontent` platform from the ruleset. thanks.
Close #14516
=> Rename and Update PCGamer.com.xml, Fix #14516

src/chrome/content/rules/CDON.COM.xml, src/chrome/content/rules/cdon.se.xml
cdon.se subdomains are handled in [`cdon.se.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/cdon.se.xml).
=> [CDON] Remove cdon.se subdomains

src/chrome/content/rules/Hartwork-Project.xml
Somewhat related to #8265. binera.de has a dedicated certificate of its own by now and could change to serving its own content at some point.
=> rules: Hartwork-Project: Remove forward for binera.de

src/chrome/content/rules/University-of-Waterloo.xml
This PR:
- moves two subdomains from broken into rules (I believe they have now been fixed)
- adds mirror.csclub.uwaterloo.ca (official Canadian mirror for a lot of FOSS projects)
related previous PRs: #14126, #14441
=> Update University-of-Waterloo.xml yet again

src/chrome/content/rules/kantonalbanken.xml
Domain is already secured in [`Banque_Cantonale_du_Valais.xml`](https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/Banque_Cantonale_du_Valais.xml)
=> Remove bcvs.ch subdomains from kantonalbanken.xml

src/chrome/content/rules/Mozilla.xml
These domains now support HTTPS: https://symbols.mozilla.org, https://release.mozilla.org, https://view.e.mozilla.org, https://click.e.mozilla.org
These domains no longer exist: http://graphs.mozilla.org, http://sfx-images.mozilla.org
=> [Mozilla.org] Update working or non-existent hosts

src/chrome/content/rules/Trend_Micro.xml, src/chrome/content/rules/Zero_Day_Initiative.com.xml
The ZDI (https://zerodayinitiative.com) no longer redirects HTTPS to HTTP, and supports HSTS, but not preloaded yet. This PR updates the rulesets accordingly.
https://www.ssllabs.com/ssltest/analyze.html?d=zerodayinitiative.com
Also the ZDI is now operated by Trend Micro Security. HP sold it out 2 years ago.
=> [Zerodayinitiative.com] supports HTTPS completely

src/chrome/content/rules/Google.xml
#2747 mentions that https://www.google.cn and https://google.cn don't support HTTPS outside China. It seems this has been fixed. https://google.cn still redirects to http://www.google.cn, but no circular redirects at least.
* https://www.ssllabs.com/ssltest/analyze.html?d=google.cn&s=216.58.194.163
* https://www.ssllabs.com/ssltest/analyze.html?d=www.google.cn&s=74.125.135.94
Fixes #2747
Also deleted a comment about GoogleImages.xml. It was deleted in #12555.
=> [Google.xml] Google.cn no longer redirects to http

src/chrome/content/rules/Wikimedia.xml
https://blog.wikimedia.de/ probably no longer has mixed content. It uses HTTPS links to blog pages on its home page, e.g. https://blog.wikimedia.de/2018/03/01/neues-urheberrecht-fuer-bildung-eine-erleichterung-fuer-die-praxis/.
=> [Wikimedia.xml] Remove blog.wikimedia.de from exclusion

src/chrome/content/rules/ORF.at.xml
the rules already contain a redirect for appfeeds.orf.at, which is
requested from teletext.orf.at. If one naviates to
`http://teletext.orf.at`, HTTPS-Everywhere upgrades the API request from
`http://appfeeds.orf.at` to `https://appfeeds.orf.at`, which results in the
following CORS-error:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://appfeeds.orf.at/teletext/api/v2/mobile/channels/orf1/pages/100. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
redirecting teletext.orf.at as well fixes that.
~~**EDIT:** `test=FETCH` fails, because the rule contains redirects for other subdomains that are currently unavailable. I do not want to delete them, since I don't know why they are not available at this time (might be just the `/` …
=> fix orf.at rules for TEST=fetch; add rule for currently-broken teletext.orf.at

test/script.py
This pull request changes how `test/script.py` identifies the platform when setting `chromedriver_path` on a Linux system. There are two reasons for this change:
* The technical reason is that `platform.linux_distribution` [is deprecated](https://docs.python.org/3.6/library/platform.html#platform.linux_distribution) as of Python 3.5.
* The actual reason is that `platform.linux_distribution` [doesn't correctly identify Ubuntu](https://stackoverflow.com/a/33997262) if you have built Python 3.6 from source, because you are, for example, using Ubuntu 16.04. As the link mentions, the Ubuntu developers patch the `platform` module that Ubuntu provides so it works as expected on Ubuntu. With the `platform` module built from source, the HTTPS Everywhere Chromium test process looks for …
=> Modify the platform check in test/script.py

chromium/background-scripts/store.js
On Chrome Canary, the checkboxes in the HTTPS Everywhere popup are missing and this error shows up in the background page's console every time the popup loads: 
> `Error in event handler: TypeError: Error processing argument at index -1, conversion failure from undefined`
It looks like this is because `chrome.storage`'s methods no longer work unbound. The fix is to bind them to the `StorageArea ` when they get pulled out.
=> Fix settings on new versions of Chrome.

src/chrome/content/rules/AOL-mismatches.xml, src/chrome/content/rules/Moviefone.xml
there is a standalone ruleset for blogsmithmedia.com, however the domain itself does not seem to serve any content and HTTPS is not working properly. Maybe we should remove that as well?
=> Remove duplicates of blogsmithmedia.com

src/chrome/content/rules/Hatena.xml
I fixed replace pattern.
Currently, broken CSS loading. http://www.hatena.ne.jp/
* For example, from http://www.hatena.ne.jp/css/hatenaportal/portal2012.css?t=1487038420 redirect to...
* Before: https://www.hatena.ne.jp/hatenaportal/portal2012.css?t=1487038420 (404)
* After: https://www.hatena.ne.jp/css/hatenaportal/portal2012.css?t=1487038420
=> Fix ruleset for Hatena

chromium/background-scripts/background.js, chromium/pages/options/index.html, chromium/pages/options/style.css, chromium/pages/options/ux.js, src/chrome/locale/en/https-everywhere.dtd
This will allow advanced users to enable `mixedcontent` rulesets easily and globally, it should be particularly useful in `Block all unencrypted requests` mode where MCB is expected and resolved in #14600 
Basic testings were performed by visiting https://www.wwf.or.jp/ (which has a `mixedcontent` rules)
- With the option unchecked: `WWF.or.jp` shown up in `Experimental rules` and unchecked
- With the optoin checked: `WWF.or.jp` shown up in `Stable rules` and checked
Related: EFForg/https-everywhere/issues/9971, https://trac.torproject.org/projects/tor/ticket/21323
Re-open #15069
=> Add Option UI to Enable MCB Rulesets Globally

test/tor-browser.sh
When testing via Tor browser and then closing it normally, the following message appears:
```bash
++ openssl sha -sha256 pkg/https-everywhere-2018.2.26~pre-eff.xpi
Invalid command 'sha'; type "help" for a list.
+ shasum=
```
It does not occur on a keyboard interrupt with <kbd>CTRL</kbd>+<kbd>C</kbd>.
This PR fixes the issue.
=> Fix openssl sha256 command

docs/en_US/development.md
that seems to have been accidentally deleted at some point since
https://github.com/EFForg/https-docs/commit/236ea7c5f0404a2d0f4b7ac1cf614b555ae734d4
.
=> Restore a missing line break

chromium/pages/devtools/index.html, chromium/pages/devtools/ux.js, chromium/pages/options/index.html, chromium/pages/options/style.css, chromium/pages/options/ux.js, src/chrome/locale/en/https-everywhere.dtd
Adds "Show Devtools tab" to the extension options, defaulting to `true`.  Firefox itself lets users disable/hide devtools tabs out of the box, but Chromium does not.
Tested in Chromium 66 and Firefox 60b13 (Linux).
Rendered in Chromium 66:
Also see #13611, #13685.
/cc @Hainish
=> Add "Show Devtools tab" option to hide CDT tab

chromium/background-scripts/background.js
Closes #49.
Builds on https://github.com/EFForg/https-everywhere/pull/15092.
In Firefox, cross-origin resource sharing (CORS) requests that are approved for http urls are sometimes
blocked after being rewritten to https. Firefox has recently added a new option to webRequest.BlockingResponse, upgradeToSecure, which performs a simple http --> https rewrite. This branch tries to use that flag instead of a standard rewrite whenever (1) the rewrite is trivial and (2) the browser is Firefox 59+.
Can be tested on this website: http://shop.decatorevista.ro/
With the current version of the extension in Firefox, a few calls to maxcdn.bootstrapcdn.com will be blocked, breaking styles on the page. This branch allows them to be rewritten successfully. Turn on logging in the background page and look …
=> Use upgradeToSecure when possible

install-dev-dependencies.sh
The default when hitting enter is _not_ to continue.
=> install-dev-dependencies.sh: Fix default y/N prompt indication

utils/issue-format-bot/lib/helptext.js, utils/issue-format-bot/lib/issueedit.js, utils/issue-format-bot/lib/newissue.js, utils/issue-format-bot/test/helptext-test.js
Suggested by @noloader in https://github.com/EFForg/https-everywhere/issues/14654#issuecomment-366416388. I also made it so that most interactions with the bot include a note to contact me in case of trouble, but I worry this could get repetitive in case the bot comments multiple times. See for example strugee/https-everywhere-test#49.
/cc @Hainish
=> Improve issue bot wording

src/chrome/content/rules/Zhihu.xml
https://worldcup2014.zhihu.com no longer redirects to http, but it still has mixed content though.
=> [Zhihu.xml] worldcup2014 doesn't redirect to http now

chromium/background-scripts/background.js
* Rewrite access-control-allow-origin to avoid the HTTP protocol in
HTTP Nowhere mode
This change make CORS issues like #14275 less likely to happen in HTTP Nowhere mode
=> Fix some CORS issues in HTTP Nowhere mode

src/chrome/content/rules/Solus-Project.com.xml
The error that made the rule error was because of "bugs.solus-project.com" and that site does not exist anymore. This PR makes it default on and it updates the test sites to sites that exists now in 2018. I have been using the old rule for a long time and it does not cause any site breakage so it should be fine to make it default to on :+1:
=> Updates test sites for Solus-Project.com and makes it deafult to on

src/chrome/content/rules/trezor.io.xml
We probably had the domain disabled at the time of the check.  All the domains should be working now.
=> Re-enable trezor.io

src/chrome/content/rules/Stubhub.co.uk.xml
depends on https://github.com/EFForg/https-everywhere/pull/14269 due to duplicate host error.
=> [Stubhub.co.uk] Separate ruleset

src/chrome/content/rules/Stubhub.de.xml
depends on https://github.com/EFForg/https-everywhere/pull/14269 due to duplicate host error.
=> [Stubhub.de] Separate ruleset

src/chrome/content/rules/Bash.im.xml
Sublist3r also listed the `s.bash.im` domain name, but it does not seem to resolve to an IP address.
=> Add bash.im ruleset

src/chrome/content/rules/Mono-project.xml, src/chrome/content/rules/pronoun.is.xml
Two simple rulesets for simple websites.
=> Create ruleset: Mono project and pronoun.is

utils/trivialize-rules/explode-regexp.js
This fixes a bug in trivialize-rules script that affected "multiplication" of various repetitions like in `^http://(www\.)?(alliance)?bernstein\.com/` (it would miss some combinations of `www.` and `alliance.`).
cc @cschanaj
=> Fix explode-regexp

utils/merge-rulesets.py
@Hainish @bcyphers This will merge ruleset exclusion into a single pattern as implemented in #15448. The memory improvement measure is as follow
Before:
Initial usage: 41.1 MB
Maximum usage: 80.3 MB
After:
Initial usage: 40.9 MB
Maximum usage: 80.1 MB
Related #12232
=> Slightly reduce default.rulesets size and memory usage

utils/merge-rulesets.py
Before: 7390331 bytes
After: 6930115 bytes (93.77%) when uncompressed
=> A little more compact JSON representation in default.rulesets

install-dev-dependencies.sh
On my debian box, this requires sudo or fails with a permission error.  This patch just adds the sudo if needed.
=> Use sudo to link chromedriver

test/script.py
Correct me if I'm wrong, but these colors codes that we placed in `script.py` didn't seem to be used for anything.
=> Removed seemingly redundant colors in script.py

chromium/background-scripts/background.js, chromium/pages/options/index.html, chromium/pages/options/ux.js, src/chrome/locale/en/https-everywhere.dtd
This is legacy code left over from the initial stages of planning the move from XPCOM to WebExtensions.  No longer used or needed.
=> Remove 'import settings' ux from options page

src/chrome/content/rules/Bgm.tv.xml
I’m heavy user of this site: https://bgm.tv/user/franklinyu (see the GitHub link). The three domains are interchangeable.
In addition, I think it’s more appropriate to name it `Bangumi.xml`, because the official name is Bangumi. See [Chinese Wikipedia](https://zh.wikipedia.org/wiki/Bangumi_番组计划) for details (English Wikipedia page not available).
=> Add two other domains for Bangumi

chromium/background-scripts/background.js
On chromium browser, `upgradeToSecure` is not available, avoid the unnecessary trivial rewrites should improve performance.  Besides, since `ruleset.apply` might return `null` when the URL is excluded by a ruleset, the checking might be performed more than once in Firefox/Chromium. Move the check outside of the loop avoid unused variables and assignments.
=> Avoid unnecessary trivial rewrites in Chromium browsers

test/setup_travis.sh
It was used for xml linting but seems like it's no longer the case
=> Remove libxml dependencies

utils/trivialize-rules/explode-regexp.js, utils/trivialize-rules/package.json, utils/trivialize-rules/trivialize-rules.js
This PR modify `trivialize-rules.js` to detect _static_ `securecookie` to trivialize more rules. It also trivialize the `securecookie` tags if all the `securecookie` domain and `target` domain are strictly identical.  This will further trivializes about 100+ rulesets when ran against 8cfabe52e659fe0f0fb091f83e3b8004134d884f
cc @RReverser @Hainish @Bisaloo @J0WI
=> Detect static securecookies to trivialize more rules

src/chrome/content/rules/aastocks.com.xml
Video thumbnails and images are broken over HTTPS
=> Update aastocks.com.xml, add exclusion, fix #14275

src/chrome/content/rules/Pirata.cat.xml
https://github.com/EFForg/https-everywhere/issues/13290
=> Update and rename pirata.cat.xml to Pirata.cat.xml [#13290] [Audit default_off="missing certificate chain" rulesets.]

.build_exclusions
The 2017.10.30 release includes a test directory which is not used within the extension
=> Exclude test directory while generating package

chromium/background-scripts/background.js, chromium/pages/cancel/index.html, chromium/pages/cancel/ux.js, chromium/pages/debugging-rulesets/index.html, chromium/pages/devtools/index.html, chromium/pages/options/index.html, chromium/pages/options/style.css, chromium/pages/options/ux.js, chromium/pages/popup/index.html, chromium/pages/popup/style.css, chromium/pages/popup/ux.js, chromium/pages/send-message.js, chromium/pages/util.js, src/chrome/locale/en/https-everywhere.dtd
Add the ability to disable HTTPS Everywhere on a per-site basis.  Closes #16418, #10041
=> Disable per site

src/chrome/content/rules/spi-inc.org.xml
I’m not sure whether I should include the redirecting sites and/or HSTS (non-preload) sites. Also note that some sites only supports TLS 1.0.
=> Create ruleset: SPI Inc

src/chrome/content/rules/PHP.xml
https://museum.php.net and https://windows.php.net now send HSTS headers.
```
C:\Windows\System32>curl --head https://museum.php.net
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 13 Oct 2018 08:34:43 GMT
Content-Type: text/html
Connection: keep-alive
Strict-Transport-Security: max-age=63072000; includeSubdomains
C:\Windows\System32>curl --head https://windows.php.net
HTTP/1.1 200 OK
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Server: Microsoft-IIS/8.5
X-Powered-By: PHP/7.2.5
Strict-Transport-Security: max-age=15768000
Date: Sat, 13 Oct 2018 08:34:48 GMT
```
=> [PHP.xml] two subdomains now support HSTS

src/chrome/content/rules/Python.org.xml
* https://python.org and https://www.python.org are preloaded.
* redesign, vote domains are NX
* blog, legacy, buildbot, hg.es, lists.es all have good HTTPS support.
=> [Python.org.xml] Update rulesets

chromium/background-scripts/background.js, chromium/background-scripts/rules.js, chromium/background-scripts/store.js, chromium/pages/options/index.html, chromium/pages/options/style.css, chromium/pages/options/ux.js, chromium/pages/popup/ux.js, src/chrome/locale/en/https-everywhere.dtd
@Hainish This will introduce a simple UI in the option page for users to view and remove the user rules.
P.S. to my surprise, there is some constraint in the current implementation (in lookups & caching) which rendered this more complicated than I have expected... And it is not possible to allow custom user rules names, meaning there is only 1 custom rule for each domain... 
supersedes #16616 relates #14969
=> Add UI in option page to view and remove user rules

src/chrome/content/rules/Rettighedsalliancen.dk.xml
Rettighedsalliancen.dk is now available over HTTPS with no errors or mixed content
=> Enable Rettighedsalliancen.dk and simplify rule

install-dev-dependencies.sh, src/chrome/content/rules/Karlsruhe.de.xml
This PR is inspired by the moment when the script failed to work on Arch Linux.
Little enhancements were made:
- Comments specify which distro is the command related
- Output of `type` command doesn't appears  for user (either in success or fail)
- If any of install commands doesn't work (`apt`, `dnf`, ...), it displays an warning message
Thanks!
=> Add distro fallback on install-dev-dependencies.sh

chromium/pages/cancel/ux.js
When user clicks URL on interstitial, they get a statement
that seems more like a command, than an option.
Note: This is not the ideal solution, but provides a better user
indicator until we revisit the UI for un-encrypted requests.
=> Add question mark for disable prompt

chromium/background-scripts/background.js
This follows up on the work in PR #16924.
=> Early return for URLS that are already HTTPS

chromium/background-scripts/background.js, test/selenium/test_popup.py
STR:
1. Visit http://time.com/ using a build from b056c3d7f01bd6e6921f0a4b4a2173b60f11862a from #17010 
2. Visit https://bloomberg.com/
3. Notice that rulesets applied to http://time.com/ shows up when the URL is changed to https://bloomberg.com/ 
4. Expect rulesets from previous page are clear and only rulesets applied to current page are shown.
Issues 
02a9220 breaks browser test because #17010 contains a bugs. Step 3 can be repeated infinitely for different domains, as long as all the subsequent pages are HTTPS only. So this bug cannot be ignored.
1. For non-HTTPS pages, if `main_frame` is redirected by HTTPSE, no ruleset will be shown on the popup. Otherwise, rulesets for page's resources will be shown (if any). 
2. For HTTPS pages, no ruleset be shown unless the page serve …
=> Fix extension popup shows rulesets from previous pages

src/chrome/content/rules/Broadcasthe.net.xml
Drop no longer maintained secondary domain and reactivate ruleset.
=> Update Broadcasthe.net domains

src/chrome/content/rules/JSON-Schema.org.xml, src/chrome/content/rules/JSON-Schema.xml
I searched `site:*.json-schema.org` but didn't find any subdomain.
=> Create ruleset: JSON Schema

src/chrome/content/rules/IronRuby.net.xml
Note that http://ironpython.net/ is from the same organization https://github.com/IronLanguages, but none of the Iron Python domains support HTTPS. Should I put them in the same file, or just leave that domain alone?
=> Create ruleset: Iron Ruby

test/rules/src/https_everywhere_checker/check_rules.py
This is directly off of the work done in #11616, 
The only thing I added here was to disable the ruleset if all targets turn out to be problematic
=> Disable Rules Test Update

.travis.yml, chromium/package.json
node-webcrypto-ossl [v1.0.37+](https://github.com/PeculiarVentures/node-webcrypto-ossl/releases/tag/v1.0.37) support OpenSSL version used in NodeJS v10/v11
ref: https://github.com/EFForg/https-everywhere/pull/15254 https://github.com/EFForg/https-everywhere/issues/15253
=> Use latest stable node in travis

src/chrome/content/rules/Economist.xml
`www` 301 redirect to https, so I believe the exclusion is no longer necessary.
=> Re-activate and Update Economist.xml

chromium/background-scripts/background.js
This refers to #17192, where sites that don't exist get blocked by our EASE mode page.
The conclusive sentiment here on my part is that with or without EASE (BAUR) a site that doesn't exist (http or https), will pose little threat to our users. Since all major browsers provide a page explaining that the site does not exist.
=> Remove Network message for unknown hosts

chromium/background-scripts/background.js
I have only tested this on Chrome. Mixed content requests might still be blocked by Firefox's own MCB mechanism... 
close #17253 cc @Hainish @zoracon
=> Do not modify headers if EASE is disabled. fix #17253

test/selenium/shim.py, test/selenium/test_options.py
- Show counter has been failing lately for many PRs
- Suspected cause: deprecation warning
- Pushing fix for deprecation
Message
(Warnings.warn('use options instead of chrome_options', DeprecationWarning))
Edit: Checks out to not be the issue, will investigate further for a solution
Going to skip the test for now in Chrome. If not hashed out by Release time I will merge for the sake of people's PRs
=> Disable "Show Counter" test (temporarily) for Chrome

src/chrome/content/rules/Svenskakyrkan.se.xml
#9906 https://trac.torproject.org/projects/tor/ticket/9613 is 5 years ago, and the site redirects to HTTPS by default
=> Re-activate Svenskakyrkan.se.xml (Swedish Church)

src/chrome/content/rules/Trove.com.xml
Updating config due to new domain ownership
I have no control over the `socialreader.com` site, but the trove.com redirects in `src/chrome/content/rules//Social_Reader.com.xml` should go away.
=> Trove.com updates

chromium/pages/cancel/index.html, chromium/pages/cancel/style.css, chromium/pages/cancel/ux.js, src/chrome/locale/en/https-everywhere.dtd
When trying to visit a page that isn't available as HTTPS a user may be shown a cancel page where they can either cancel the insecure visit or choose to override the restriction. The link of the URL shown at the bottom of that page misleadingly goes to an internal extension URL. Instead, change the actionable item into a button with a clear label describing the action.
Notice the button at the bottom of the page
=> Change the open URL link to a button

chromium/pages/cancel/style.css
- Email tracking links get long and break layout, so cap overflow with an ellipsis
=> Adjust CSS for long http links

install-dev-dependencies.sh
Tested in https://github.com/EFForg/https-everywhere/issues/17206#issuecomment-466161962
Source: https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory
This was not updated since the switch to python3
=> Fix install-dev-dependencies.sh on Fedora

chromium/background-scripts/background.js
Added in a SSL code that occurs when HTTP Everywhere attempts to upgrade a HTTP request from a domain with this error.
Closes #17529
=> Add SSL internal error code to SSL misconfiguration list

src/chrome/content/rules/METEO.PL.xml
The ruleset name is all in capital letters because that is how the site name is spelled.
=> Add a METEO.PL ruleset

src/chrome/content/rules/BTCJam.com.xml
This company has now shut down and their main url is offline (btcjam.com) however they are still currently operating blog.btcjam.com so I have edited to account for this. I presume this will also close soon.
=>  Edited Btcjam.com.xml

src/chrome/content/rules/University-of-Waterloo.xml
The certificate is only valid for *.csclub.uwaterloo.ca, but these other subdomains rank higher in searches.
(For context, this is one of the most popular official Canadian mirrors for a bunch of linux distros and open source projects.)
=> redirect uwaterloo csclub mirrors

CONTRIBUTING.md
Provide information and a path for site admins and web developers who may want to figure out how to fix their malformed SSL configurations.
=> Add "How to Fix Site" to Documentation

src/chrome/content/rules/Pimienta.org.xml, src/chrome/content/rules/Poivron.org.xml, src/chrome/content/rules/Potager.org.xml, src/chrome/content/rules/SweetPepper.org.xml
@potager, could you fix the mismatch issues that occur when you are just redirecting to another domain?
In that case, we could bring back the wildcards. You may also want to consider [HSTS preloading](https://scotthelme.co.uk/hsts-preloading/).
=> Split Potager.org.xml into more manageable rulesets

src/chrome/content/rules/Trump.com.xml, src/chrome/content/rules/TrumpGolf.com.xml, src/chrome/content/rules/TrumpHotels.com.xml, src/chrome/content/rules/TrumpInternationalRealty.com.xml, src/chrome/content/rules/TrumpStore.com.xml, src/chrome/content/rules/TrumpWinery.com.xml
Sublist3r also shows the following subdomains, which do not resolve to IP addresses:
* `mail.trump.com`;
* `mail2.trump.com`;
* `mivsp2.trump.com`;
* `chi-operadb.trumphotels.com`;
* `ocis-app.trumphotels.com`;
* `njmls.trumpinternationalrealty.com`.
`virginia.trumpinternationalrealty.com` appears to have some weird redirect to `placester.com`, but still seems to be upgradeable.
=> Add Trump Organization rulesets

utils/zipfile_deterministic.py
Should fix #17618. ~~I'll test it later today.~~ Tested and it looks fine.
=> Update default timestamp for deterministic builds

test/validations/relaxng/schema.xml
=> Remove support for wildcard in the middle

src/chrome/content/rules/PyData.org.xml
Several previously problematic subdomains now work. Some font-related mixed content issues warnings will show up on `blaze` and `xarray` but nothing problematic.
=> [PyData.org] Update ruleset

test/rules/src/https_everywhere_checker/check_rules.py
Example of warning:
```
test/rules/src/https_everywhere_checker/check_rules.py:311: DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
config = SafeConfigParser()
```
=> Fix DeprecationWarning in HTTPS Everywhere Checker

chromium/background-scripts/store.js
At least on Chromium 73 when opening the extension options window an exception
"TypeError: Illegal invocation: Function must be called on an object of type StorageArea"
is thrown, which results in empty update channels page.
It looks like chrome.storage.local methods need to be called while bound to
the chrome.storage.local object.
According to
https://github.com/KeithHenry/chromeExtensionAsync/issues/10
https://github.com/wtetsu/mouse-dictionary/issues/16 this Chromium change
has been introduced probably around version 70 or 72.
Automatic ruleset updates might have been affected by this, too.
=> Fix Chromium local store exception

chromium/background-scripts/rules.js, chromium/test/rules_test.js
This replaces #17669 to drop support for middle wildcards in the runtime. hopefully #17711
=> Remove middle wildcard support in rules.js

.travis.yml
This PR makes unit tests run in the latest LTS Node.js release. In order to avoid pinning a older Node.js version every time there is a new version (#15254) and then manually switch to a newer version when `node-webcrypto-ossl` make a new release (#17071).
Personally, I don't think it is worth using the latest stable version of Node.js for unit tests. This is because stability should be preferred over the new features a newer version can bring. 
In the long term, we might want to investigate whether this dependency is really needed for our tests.
Ref: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
Related: #15254, #17071
=> Use the latest LTS Node.js release for unittests, fix #17829

chromium/pages/popup/index.html
Now applying patch to `master` branch.
Chose to use https://atlas.eff.org/index.html instead of https://atlas.eff.org/ because links to go back to "HTTPS Everywhere Atlas" main page from the Atlas itself go to the `index.html` file.  This is also a little safer in the event of a server misconfiguration or hack.
=>  Updated URL to new Atlas URL

chromium/pages/popup/ux.js
As a result of the UI redesign, #15532 is partially reverted. 
P.S. Ideally we should have a unittest on this when the UI stabilize.
=> Update chromium/pages/popup/ux.js, fix #17916

chromium/pages/popup/ux.js, src/chrome/locale/en/https-everywhere.dtd
this close #17891, related to #17918 
These duplicates in the messages.json need to be fixed to ensure proper translation of the extension. Some of them just "work" currently, because the display strings are hard-coded in JavaScript. 
https://github.com/EFForg/https-everywhere/blob/66c2e971c0582066d90d404294e215763eab6275/src/chrome/locale/en/https-everywhere.dtd#L10-L15
=> Properly change ON/OFF switch description, fix #17891

chromium/pages/popup/ux.js
Step to reproduce:
1. Visit https://hk.yahoo.com/ or any site with some experimental rulesets applicable
2. Observe the ruleset counter show wrong number: it shows the number of experimental rulesets instead of the number of all applicable rulesets. 
If possible, I hope this can be merged before #17944 since it disrupts the UX.
=> Fix counter show number of experimental rulesets

src/chrome/content/rules/ABC-Online.xml
there was a typo in the complicated rule for `abccommercial.com`
=> Fix typo causing abccommercial.com unprotected

chromium/background-scripts/rules.js
This should also be slightly faster (in real world performance, to much less degree than demonstrated in this example):
```js
let c = null
const a = performance.now()
for (let i = 0; i < 1e8; i++) {
c = Array()
}
const b = performance.now()
console.log(b - a)
// 2634.315000002971
```
```js
let c = null
const a = performance.now()
for (let i = 0; i < 1e8; i++) {
c = []
}
const b = performance.now()
console.log(b - a)
// 1824.0100000039092
```
=> Replace Array() with []

utils/trivialize-rules/package-lock.json, utils/trivialize-rules/package.json, utils/trivialize-rules/trivialize-targets.js
this supersedes #17842 and is ready for review and merging. thanks.
P.S. there is no need to rush for the major release in #17711 .
cc @pipboy96 @zoracon @Hainish
=> Add script to trivialize some left-wildcard targets

test/firefox.sh, test/firefox/test_profile_skeleton/extensions.json
standards.  Fixes test installation breaking in Firefox 67+.
=> Update profile skeleton `extensions.json` file to most recent Firefox

chromium/pages/popup/index.html
This change makes the popup scale better on [Firefox for Android](https://www.mozilla.org/firefox/mobile/).
Screenshots [before](https://user-images.githubusercontent.com/1102886/59396221-ff030480-8d87-11e9-9514-581ea059e03f.jpeg) and [after](https://user-images.githubusercontent.com/1102886/59396511-6cfbfb80-8d89-11e9-8823-ed3e74130b0a.jpeg).
=> Scale the popup window to device width

chromium/background-scripts/rules.js
In the past, we call safeToSecureCookie for every new cookie regardless we will ever secure the cookie or not. It is more sane to delay the call until we know it is necessary. The proposed change also reduce calls to potentiallyApplicableRulesets to avoid search in a huge (cached) Map object .
IMHO, the code logic is more complicated but I am not sure if it worth the trade off. Given the complexity of this change, I don't think it is necessary to merge it before the next release. 
P.S. This is also likely the last major change I will make before the next release. thanks!!
=> Do not call safeToSecureCookie until necessary

chromium/pages/cancel/index.html, chromium/pages/cancel/style.css, chromium/pages/options/index.html, chromium/pages/options/style.css, chromium/pages/options/ux.js, src/chrome/locale/en/https-everywhere.dtd
The options page in Firefox for Android looks weird, and opening it in a new tab looks much better.  We could do this with `"open_in_tab": true` in `manifest.json`, but opening the options page in a separate tab in desktop also looks a bit weird.  Thus the slightly hacky "Settings" link.
=> Making the options and cancel pages more mobile friendly

utils/android-push.sh
Killing `adb` server(aka daemon) prevents seeing groups of these messages
on `dmesg` every second:
```
[ 1460.763742] pcieport 0000:00:1c.4: restoring config space at offset 0x2c (was 0x0, writing 0x0)
[ 1460.763748] pcieport 0000:00:1c.4: restoring config space at offset 0x28 (was 0x0, writing 0x0)
[ 1460.763752] pcieport 0000:00:1c.4: restoring config space at offset 0x24 (was 0x1fff1, writing 0x1fff1)
[ 1460.763813] pcieport 0000:00:1c.4: PME# disabled
[ 1460.763920] xhci_hcd 0000:03:00.0: PME# disabled
[ 1460.763928] xhci_hcd 0000:03:00.0: enabling bus mastering
[ 1460.770239] xhci_hcd 0000:03:00.0: PME# enabled
[ 1460.770377] xhci_hcd 0000:03:00.0: PME# disabled
[ 1460.770383] xhci_hcd 0000:03:00.0: enabling bus mastering
[ 1460.884813] xhci_hcd 0000:03:00.0: PME# enabled
[ …
```
=> fixes #18103

utils/rewriter/package.json
This fixes a [ReDoS vulnerability found by Snyk](https://app.snyk.io/test/npm/readdirp/0.3.2).
=> Upgrade readdirp to 2.0.1 to Fix Vulnerability

src/chrome/content/rules/Da.gd.xml
The ruleset for da.gd was disabled in commit https://github.com/EFForg/https-everywhere/commit/9bf49cbeb4696cdea76df23f685da1d11031f693. This site works over IPv6 without issue.
=> Re-enable da.gd

src/chrome/content/rules/Acer.com.xml
Attack described in https://duo.com/assets/pdf/out-of-box-exploitation_oem-updaters.pdf. This won't be useful for the browser but it would be for [the thing we're building](https://git.yori.cc/https-everywhere-else/https-everywhere-rules) (using these rulesets outside the browser). Open for discussion, also on IRC.
=> Created Acer.com.xml for Acer Care Center Updates

.travis.yml
Since `trusty` reached its End of Standard Support in April 2019 and the docker image we use for testing is `bionic`, it seems more sane and consistent to use `bionic` for the travis ci distro.
https://wiki.ubuntu.com/Releases 
Note: Travis fails for PRs because Google Chrome Beta does not install properly. It seems that this error does not affect `bionic` in this very PR.
```
Installing Google Chrome beta
1.07s$ wget --no-verbose -O /tmp/$(basename $CHROME_SOURCE_URL) $CHROME_SOURCE_URL
2019-09-02 12:29:01 URL:https://dl.google.com/dl/linux/direct/google-chrome-beta_current_amd64.deb [64064808/64064808] -> "/tmp/google-chrome-beta_current_amd64.deb" [1]
dpkg-deb: error: archive '/tmp/google-chrome-beta_current_amd64.deb' has premature member 'control.tar.xz' before 'control.tar.gz', …
```
=> Upgrade travis ci distro from trusty to bionic

src/chrome/content/rules/acast.com.xml
High priority since current ruleset breaks bbc.co.uk (Alexa rank 109).
=> Update acast.com (fixes bbc.co.uk podcast playback)

src/chrome/content/rules/eti.hket.com.xml, test/rules/src/https_everywhere_checker/http_client.py
When Travis performs the `fetch` test, it will throw an `UnicodeDecodeError` error when the response header cannot be utf-8 decoded. This can be shown in the Travis log, see https://travis-ci.org/EFForg/https-everywhere/jobs/581484797#L344.
The proposed fix is to change the encoding's rule to `ignore` (just leave the character out of the Unicode result). See https://docs.python.org/3/howto/unicode.html#the-string-type
cc @zoracon @Hainish 
- #18385 
- issue link
=> Fix fetch test fails when response header cannot be utf-8 decoded

src/chrome/content/rules/Gegl.org.xml
- <https://gegl.org/>
- <https://www.gegl.org/>
=> gegl.org: expired certificate

src/chrome/content/rules/Open_Rights_Group.xml
The wildcard entry for openrightsgroup.org is effectively breaking the unsubscribe links in some of the mails sent via a third-party service.
(If it were safe, "preload" would have to the openrightsgroup.org Strict-Transport-Security header.)
=> remove the wildcard entry for openrightsgroup.org

src/chrome/content/rules/JAMF_Software.com.xml
jamfcloud.com is SaaS hosted by JAMF Software at _subdomain_.jamfcloud.com - all subdomains do listen on HTTPS, so the wildcard is desirable to rewrite everything here.
=> add *.jamfcloud.com rule to JAMF software ruleset

src/chrome/content/rules/Sumo_Logic.com.xml
- pr link
Description
HTTPSEverywhere rules for status.sumologic.com are outdated. It results in anyone using HTTPSEverywhere in Chrome to get confused when visiting http://status.sumologic.com.
Symptoms
What happens is that - you get "redirected" (HTTP 307, by local HTTPSEverywhere plugin) to https://sumologic.statuspage.io/, which is wrong.
=> Delete outdated rules from sumologic.com.

src/chrome/content/rules/179.ru.xml
There are a few domain names whose only purpose appears to be a redirect. For example, <http://wiki.179.ru/> redirects to <https://server.179.ru/wiki/>. For those domain names, HTTPS does not work; but non-root URLs like <http://wiki.179.ru/foo> simply give an error. I tried to express that using the exclusion.
=> Add 179.ru

src/chrome/content/rules/My-Aime.net.xml
Note: `my-aime.net` has HSTS for subdomains, but it isn't preloaded and it doesn't set secure cookies.
=> Add ruleset for my-aime.net

chromium/background-scripts/background.js, chromium/background-scripts/store.js, chromium/background-scripts/util.js
=> Normlise disabled site hostname and migrate stored list, fix #18451

utils/ruleset-whitelist.csv
This empty line was introduced by #18351.
=> Remove empty line at beginning of ruleset-whitelist.csv

chromium/package-lock.json, chromium/package.json
found 56 vulnerabilities (3 moderate, 52 high, 1 critical) in 2366 scanned packages
run `npm audit fix` to fix 6 of them.
50 vulnerabilities require semver-major dependency updates.
cc @zoracon @Hainish 
Is it possible to use a bot like https://github.com/marketplace/renovate to perform this kind of checking and submit PR automatically?
=> Run npm audit fix --force

chromium/background-scripts/background.js, chromium/background-scripts/ip_utils.js, chromium/manifest.json, chromium/test/ip_utils_test.js
=> Ignore loopback and private network addresses (such as 192.168.0.1)

utils/labeller/Dockerfile
Labeller is broken with current versions.
=> [Labeller Dockerfile] pin node version

src/chrome/content/rules/4chan.xml
Added a missing ruleset for the website. Quite recently, 4chan adopted the usage of boards.4channel.* in their service.
=> Add boards.4channel.org to ruleset

.travis.yml, chromium/package-lock.json, chromium/package.json
Unit tests pass with the latest LTS version of node, reverting #18601 and applying patches. This PR also supersede #18762
=>  Use the latest node LTS builds for unittests 

chromium/background-scripts/background.js
This bug will cause mixed content blocking issues if a `first_party_host` (which an user disabled HTTPSE in EASE mode) specifies a port and serves mixed content.
The `first_party_host` attribute in the `browserSession` object is used to disable HTTPSE rewrite on the third-party resources within the same tab in EASE mode. It is matched against the `disabledList` and `httpOnceList`. Since both `disabledList` and `httpOnceList` use normalised `uri.hostname` instead of `uri.host`, `first_party_host` should be configured to `uri.hostname` as well. Otherwise, third-party resources will be upgrade and cause MCB issues.
=> Fix bug causes MCB issues in EASE mode for some disabled sites

src/chrome/content/rules/FreeDesktop.xml
What is says on the tin :)
We use GitLab for pretty much all FreeDesktop.org projects now, so let's add a rule to always load it via https :+1:
=> Add gitlab subdomain to FreeDesktop.org ruleset

src/chrome/content/rules/Codeforces.com.xml
Previous PR which was rejected: https://github.com/EFForg/https-everywhere/pull/16661
codeforces.ru currently redirects to codeforces.com.
I'm not sure what to do about that rule-wise, so I've only considered the .com TLD in this PR.
=> Add codeforces.com

src/chrome/content/rules/City-Mail.xml, src/chrome/content/rules/EPEAT.xml, src/chrome/content/rules/MVG-mobil.de.xml, src/chrome/content/rules/OHeffernan.xml, src/chrome/content/rules/The-Republic.xml, src/chrome/content/rules/Whisper-Gifts.xml
The simplest subset of #12297 hosts in regex that are not in targets.
=> Fix rule hostname typos (#12297)

src/chrome/content/rules/FedEx.com.xml
Examples:
* http://www.fedex.com/kr/docs/
* http://www.fedex.com/kr/registration/
* http://www.fedex.com/kr/tools/commercialinvoice.html
Modern pages use `/ko-kr/` and it seems some older pages using `/kr/` are HTTP-only.
=> Ignore /kr/ pages in fedex.com

src/chrome/content/rules/Orion_Magazine.org.xml
Rule was for .com, which wasnt listed as a target.
.com is not functional; redirect to .org which is functional.
Related to https://github.com/EFForg/https-everywhere/issues/12297
=> Orion_Magazine.org.xml: Add .com target

chromium/pages/options/style.css
Related PR: #17896.
<details>
<summary><strong>Firefox</strong></summary>
</details>
<details>
<summary><strong>Chrome</strong></summary>
</details>
=> Fix options page appearance on Firefox when dark mode is on

chromium/background-scripts/background.js, chromium/background-scripts/rules.js
Closes https://github.com/EFForg/https-everywhere/issues/18983
=> Adding 'get_simple_rules_ending_with' message and functionality for Tor

chromium/pages/popup/ux.js
PR #18760 introduced a regression which breaks whitelisting and de-whitelisting for URLs contain a port number.
- #18760 
- fix #19029
=> Resolve a regression which breaks whitelisting features, fix #19029

test/rules/src/https_everywhere_checker/http_client.py
Reverts EFForg/https-everywhere#18964
Even though not preferred, these weaker ciphers are still supported within the browsers. 
@todo create a tool to crosscheck these among Tor (FF ESR), Chrome, and Firefox
Closes  #19034, however not sure with cipher suite triggered this error in particular
=> Revert "Update Cipher List for Pending Fetch Test"

src/chrome/content/rules/Client.foldingathome.org.xml
I've added client.foldingathome.org it's the control panel for the Foldingathome Client and it supports HTTPS, but it's default is sadly HTTP...
=> added client.foldingathome.org

utils/ruleset-whitelist-cleanup.sh
As per the documentation `sort(1)`
```
***  WARNING  ***  The locale specified by the environment affects sort
order.  Set LC_ALL=C to get the traditional sort order that uses native
byte values.
```
=> Use native bytes value as the default sort order

src/chrome/content/rules/E-rewards.com.xml
Related issues:  #17965 #12297 
- From https://github.com/EFForg/https-everywhere/pull/18938
=> E-rewards.com.xml: Add base domain used in rule

install-dev-dependencies.sh
The latest versions of the chromium-browser package now install by
default to /usr/lib/chromium-browser, not /usr/lib/chromium. By
updating the locations where /usr/lib/chromium is used to the new
path, the symlink for the chromedriver is properly created.
Further details can be found in issue #19174 
- Solves issue #19174
=> Updated chromedriver path to ensure correct symlink creation

src/chrome/content/rules/tekram.com.xml
Rule only targets the two domains that don't use redirect.
In the backend, tekram seems to use bigcommerce for everything,
which supports https and in the site it's being included as https.
It's strange that they set the hsts header with max-age=0, yet
backend consistently use https for everything.
Added all cookies as securecookies, while there are cookies
with the flag, some SESSION ones weren't.
=> Add tekram.com

src/chrome/content/rules/ebay.de.xml
This is a page for sellers on ebay - some links are still HTTP but HTTPS is available.
To see any content on this domain, you have to register on ebay.de, enable "Verkäufer-Cockpit Pro" on https://www.ebay.de/sh/landing, open "Mein ebay" at the top right, click on "Bestellungen" (orders), and select "Archiviert" (archived) on the left hand side. Adding a rule to HTTPS Everywhere upgrades this HTTP connection to HTTPS and does not break things.
=> Add k2b-bulk.ebay.de, fix ebay.de ruleset

.gitignore, test/validations/filename/run.py, test/validations/special/run.py, utils/merge-rulesets.py
Changing the `default.rulesets` file over by naming the extension.
This is because Opera will not accept this file unfortunately as is. I tried to find ways to make this work without having to create a new file. But coming up short on good ideas. If anyone would like to suggest a work around, I'd appreciate it.
My last idea is packaging the CRX file for Opera differently in the build process to include `.json`. But leaving this draft up for the time being until I make the final decision to change. Which would entail migrating over in small phases and letting stakeholders who use the hosted set of rulesets know that this file name is changing.
=> Mimetype rulesets change for Opera

src/chrome/content/rules/Fasthosts.xml
This reverts commit a9d02a014841be7da0e15ce6e8bd5ebbfb918e13
because it used invalid regex syntax.
=> Revert "[Fasthosts] Add coverage"

test/setup_travis.sh
- For an unknown reason, Travis is pulling one version below on stable
- This causes a mismatch in Chromedriver version to Chrome
- Statically update for now and update statically versioned Beta
- Also updating Geckodriver proactively
=> HOTFIX: Statically write versions for Chromedriver

src/chrome/content/rules/mkwrs.com.xml
mkwrs.com tracks the world record time trials for every game in the _Mario Kart_ video game series. This adds a rule-set to convert HTTP requests to HTTPS links.
=> Add rule for mkwrs.com

src/chrome/content/rules/Wikiscan.xml
Add rules to redirect http://(&#42;).wikiscan.org -> https://(&#42;).wikiscan.org
=> Add rules for Wikiscan.org

chromium/.eslintignore, chromium/pages/options/ux.js, utils/eslint/package-lock.json, utils/eslint/package.json
This PR upgrade the eslint version to support the ES2019 syntax.
Also note that #19531 addresses more than the eslint failure and should be merged before next release.
=> Bump eslint version to support ES2019 syntax, follow-up #19534

src/chrome/content/rules/Oregon-State-University.xml
* Re-enabled ruleset, as those certificate problems have been fixed
* Mixed-content has been fixed
* osulibrary.oregonstate.edu works and redirects to
library.oregonstate.edu
* web.engr.oregonstate.edu and ecampus.oregonstate.edu now work
This is part of a series of splits resulting from #19536 as asked
=> Re-enabled and extended OSU

src/chrome/content/rules/TU-Darmstadt.de.xml
add all subdomains from Sublist3r that return a HTTP200 status code when querying root on https
After I've not recieved much feedback on #19421 I've gone ahead and included all subdomains that return HTTP200 status codes when being queried over https (point 7 from the list in the linked issue).
Greetings Nmxcgeo
=> Expand tu-darmstadt.de

src/chrome/content/rules/AmazonAWS.com.xml
See #17912
<details>
<blockquote>
</blockquote>
Also, updating this file to only include v2 buckets
</details>
=> Remove S3 V1 References and Update to S3 V2 in AWS

src/chrome/content/rules/WikiFur.xml
Update WikiFur.com rules to redirect subdomains that don't start with two letter
==List of subdomains (all support https)==
wikifur.com
admin.wikifur.com
be.wikifur,com
be-tarask.wikifur.com
board.wikifur.com
by.wikifur.com
cs.wikifur.com
da.wikifur.com
de.wikifur.com
dk.wikifur.com
dumps.wikifur.com
en.wikifur.com
eo.wikifur.com
es.wikifur.com
et.wikifur.com
fr.wikifur.com
fursuit.wikifur.com
hu.wikifur.com
it.wikifur.com
ja.wikifur.com
ko.wikifur.com
nb.wikifur.com
nl.wikifur.com
no.wikifur.com
ny.wikifur.com
pl.wikifur.com
pt.wikifur.com
pool.wikifur.com
ru.wikifur.com
se.wikifur.com
stats.wikifur.com
sv.wikifur.com
tl.wikifur.com
uk.wikifur.com
www.wikifur.com
zh.wikifur.com
=> Update WikiFur.com rules

chromium/pages/cancel/index.html, chromium/pages/cancel/style.css, chromium/pages/cancel/ux.js, src/chrome/locale/en/https-everywhere.dtd
Closes #19385
Adds feature to copy unencrypted link from EASE warning page
=> Feature: EASE Copy Url

src/chrome/content/rules/Issuu_Aps.xml
See #17912
<details>
<blockquote>
</blockquote>
</details>
=> Remove S3 Refernces to Issu Aps Ruleset

src/chrome/content/rules/FeedBlitz.xml
Related #17912
<details>
<blockquote>
</blockquote>
</details>
=> Remove S3 Refernces to FeedBlitz

src/chrome/content/rules/SMF_for_Free.xml
Related #17912 
<details>
<blockquote>
</blockquote>
</details>
=> Remove S3 Reference from SMF for Free

src/chrome/content/rules/Scribd.com.xml
Related #17912 
<details>
<blockquote>
</blockquote>
</details>
=> Remove S3 References from Scribd

browser-dist/browser-dist.md, browser-dist/edge.sh, browser-dist/opera.sh, make.sh
- MIME Type restriction requires default.rulesets to be declared
- This is a better route than changing all downstream channels
- Process will entail signing the hash of the Opera CRX for assurance
Closes #19679
=> Modification: Opera CRX Creation

src/chrome/content/rules/frankfurt-university.de.xml
Add `frankfurt-university.de` to exclude `http://sea-01.cit.frankfurt-university.de:32224` because even the forwarding to insecure site sometimes fails (workaround)
=> add frankfurt-university.de.xml

install-dev-dependencies.sh
Ref: https://wiki.debian.org/Firefox#Iceweasel
=> Fix chromium-driver for Debian 10+; Use firefox-esr instead of iceweasel

src/chrome/content/rules/osufoundation.org.xml
* osufoundation.org now works, both with/without www prefix
This is part of a series of splits resulting from #19536 as asked
=> Re-enabled OSU Foundation

src/chrome/content/rules/KSH.xml
Using HTTPS for these paths causes a 404 error. HTTP works fine.
Examples:
* http://statinfo.ksh.hu/Statinfo/
* http://statinfo.ksh.hu/Statinfo/themeSelector.jsp?lang=hu&utm_source=kshhu&utm_medium=banner&utm_campaign=theme-teruleti-adatok
* http://statinfo.ksh.hu/Statinfo/QueryServlet?ha=TA2019_W
=> KSH: Add exclusion for /Statinfo/

src/chrome/content/rules/radio.garden.xml
Site does not support HTTPS and redirects to HTTP
Fixes #19927
=> Remove Radio.garden ruleset

src/chrome/content/rules/WordPress.xml
The wordpress.com site is already sending both secure and non-secure versions.
The non-secure version doesn't have a SameSite=None attribute, and securing it
would overwrite the secure cookie that has it.
Fixes #19954
=> Update WordPress.xml: don't secure wordpress_logged_in cookie

src/chrome/content/rules/DWheeler.xml
The www subdomain doesn't do https but the root does
and both have equivalent content on the same URL paths.
=> Update the rules for dwheeler.com

chromium/pages/options/index.html, chromium/pages/options/style.css, chromium/pages/options/ux.js
On Android, click "Add-ons" > "HTTPS Everywhere"  > "Settings", _a button to the setting page_ is shown. The setting page is shown only after an user clicks the button.
This PR restores the default behavior and shows the setting page without the needing to click the button.
=> Open option page in a single click on Android, follow up #19781

chromium/background-scripts/rules.js, chromium/background-scripts/update.js
This PR makes compiling `scope` into `RegExp` automatic. Pass the string literal version of the `scope` parameter everywhere, except for when constructing rulesets/ ~WASM calls~. 
- `getScope` expected a required string parameter, but get none. It is also called multiple time when passed to `addFromJson`
=> Fix invalid ruleset scope typings

chromium/background-scripts/rules.js
Property `state` is not defined in `Ruleset`
=> Fix access to undefined property `state` of type `Ruleset`

chromium/background-scripts/ip_utils.js
@pipboy96 would you kindly check if this is a bug?
`octet` is a `string` type, per typescript check
> the right-hard side of an arithmetic operation must be of type `any`, `number`, `bigint` or an `enum` type. 
`octetN` is not used otherwise.
=> Fix unexpected arithmetic operations on strings

chromium/manifest.json, make.sh
Fixes #16394
For Chrome: Change to "split"
For Firefox, remove key altogether since it [does not support](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/incognito) `split`. Defaults to `spanning` in Firefox. Where this original bug does not appear
=> Amend Incognito Key for Chrome and Firefox

chromium/background-scripts/background.js, chromium/background-scripts/modules/ssl_codes.js, chromium/manifest.json
In lieu of the lengthy `background.js` and [more massive PR](19737) that was created in a more optimistic manner, I decided to propose changes that help bring in the changes from that PR in more increments as I return to more core work throughout the summer.
=> Background JS Cleanup: Move SSL Codes

test/script.py
Update old `log_path` function for selenium Firefox driver to the new `service_log_path`. This suppresses the warning that is thrown during testing.
=> Update deprecated log function

test/script.py
Adds sleeper to Chrome extension load before grabbing URL
Fixes #(issue)
=> Hotfix: Patches Chrome Test Failure
